### ISSUE TITLE
Global workqueue failing with Data identifier not found

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10054]
**Impact of the bug**
Global Workqueue

**Describe the bug**
A week ago we had a few workflows stuck in `staging` status and reason was that some of the input blocks have been lost and invalidated. I forced that workflow to `staged` status, such that global workqueue could start creating the chunks of work and let the rest of the workflow to be processed.
It's been more than 10 days, and that workflow
pdmvserv_task_HIG-RunIIAutumn18DRPremix-02963__v1_T_200428_151736_1872

 is still stuck in `staged` status, which means global workqueue isn't able to process it. Indeed, the component crashes and raises an exception/traceback below.

**How to reproduce it**
Assign a backfill from this workflow in your VM.

**Expected behavior**
If DID block cannot be found, global workqueue should simply bypass that block (perhaps add it to the rejected list) and move on with the other blocks.

**Additional context and error message**
Traceback from global workqueue in vocms0740:
```
2020-11-06 00:03:36,811:INFO:WorkQueue:Splitting /pdmvserv_task_HIG-RunIIAutumn18DRPremix-02963__v1_T_200428_151736_1872/HIG-RunIIAutumn18DRPremix-02963_0 with policy Block params = {'ResubmitBlock': {'args': {}, 'name': 'ResubmitBlock'
}, 'MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Block'}}
2020-11-06 00:03:36,879:INFO:Rucio:Container: /Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW with container-based location at: set([u'T2_CH_CERN', u'T1_US_FNAL_Disk'])
2020-11-06 00:03:38,266:ERROR:WorkQueue:Exception splitting wqe pdmvserv_task_HIG-RunIIAutumn18DRPremix-02963__v1_T_200428_151736_1872 for pdmvserv_task_HIG-RunIIAutumn18DRPremix-02963__v1_T_200428_151736_1872: <@========== WMException 
Start ==========@>
Exception Class: WMRucioException
Message: Data identifier not found in Rucio: /GluGluHToCC_M-125_13TeV_powheg_MINLO_NNLOPS_pythia8/RunIIFall18GS-102X_upgrade2018_realistic_v11-v2/GEN-SIM#514cbacf-5749-4449-9203-008eae345979. Error: Data identifier not found.
Details: Data identifier 'cms:/GluGluHToCC_M-125_13TeV_powheg_MINLO_NNLOPS_pythia8/RunIIFall18GS-102X_upgrade2018_realistic_v11-v2/GEN-SIM#514cbacf-5749-4449-9203-008eae345979' not found
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py
        ClassName : None
        LineNumber : 796
        ErrorNr : 0

Traceback: 
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 793, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.23.6/lib/python2.7/site-packages/rucio/client/didclient.py", line 425, in get_did
    raise exc_cls(exc_msg)

<@---------- WMException End ----------@>
Traceback (most recent call last):
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1136, in processInboundWork
    continuous=continuous)
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1078, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 156, in __call__
    self.split()
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 35, in split
    for block in self.validBlocks(self.initialTask, dbs):
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 195, in validBlocks
    blockLocations = self.blockLocationRucioPhedex(block['block'])
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 275, in blockLocationRucioPhedex
    account=self.args['rucioAcct'])
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 1092, in getDataLockedAndAvailable
    if self.isContainer(kwargs['name']):
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 796, in isContainer
    raise WMRucioException(msg)
WMRucioException: <@========== WMException Start ==========@>
Exception Class: WMRucioException
Message: Data identifier not found in Rucio: /GluGluHToCC_M-125_13TeV_powheg_MINLO_NNLOPS_pythia8/RunIIFall18GS-102X_upgrade2018_realistic_v11-v2/GEN-SIM#514cbacf-5749-4449-9203-008eae345979. Error: Data identifier not found.
Details: Data identifier 'cms:/GluGluHToCC_M-125_13TeV_powheg_MINLO_NNLOPS_pythia8/RunIIFall18GS-102X_upgrade2018_realistic_v11-v2/GEN-SIM#514cbacf-5749-4449-9203-008eae345979' not found
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py
        ClassName : None
        LineNumber : 796
        ErrorNr : 0

Traceback: 
  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/cms/workqueue/1.4.2.pre8/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 793, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/data/srv/beHG2011h/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.23.6/lib/python2.7/site-packages/rucio/client/didclient.py", line 425, in get_did
    raise exc_cls(exc_msg)

<@---------- WMException End ----------@>
```

**Comment by nsmith-** [comment]
So eventually we should never have the case that the DID is not found, as that would indicate it was removed from PhEDEx before the sync. We will have to do some DBS-Rucio consistency checking to resolve those remaining cases where valid DIDs in DBS have no corresponding Rucio DID after turning off PhEDEx I think. Unlike in phedex, rucio maintains a catalog of DIDs even in the case that no replica remains (they are marked deleted). However there may be cases where the DID exists but all replicas are lost, in which case the work element should probably be skipped.

**Comment by amaltaro** [comment]
@nsmith-  Nick, do you think we should address this specific workflow (and any other that we spot until we have completely converged to Rucio) together with the DM team? Like, invalidating that block and all its files in DBS? Otherwise I see no way to let that workflow to run, unless we drop any blocks that return a DID not found from Rucio (but that would be a dangerous decision).

**Comment by nsmith-** [comment]
I agree that dropping blocks that are not found by Rucio at present is dangerous due to the possibility of incomplete sync. Can you send the block to be invalidated in DBS to the DM team?

**Comment by amaltaro** [comment]
Just updating this issue. I got in contact with the DM team and they took care of the problematic blocks.

Since then, I haven't seen this DID not found exception. Will keep it open for a little longer and close it if no issues are seen.

**Comment by amaltaro** [comment]
Just had a look at the workqueue logs (reqmgrInteraction*) for today, and it has such errors there, e.g.:
```
2020-12-16 22:10:35,727:ERROR:WorkQueue:Exception splitting wqe pdmvserv_task_BTV-RunIISummer19UL18NanoAOD-00034__v1_T_201207_174114_6515 for pdmvserv_task_BTV-RunIISummer19UL18NanoAOD-00034__v1_T_201207_174114_6515: <@========== WMExcept
ion Start ==========@>
Exception Class: WMRucioDIDNotFoundException
Message: Data identifier not found in Rucio: /W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v1/MINIAODSIM#aad1f8a0-7eec-4715-8acc-7fb6dd0d623c. Error: Data identifier not found.
Details: Data identifier 'cms:/W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v1/MINIAODSIM#aad1f8a0-7eec-4715-8acc-7fb6dd0d623c' not found
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /data/srv/beHG2012f/sw/slc7_amd64_gcc630/cms/workqueue/1.4.3.pre6/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py
        ClassName : None
        LineNumber : 803
        ErrorNr : 0

Traceback: 
  File "/data/srv/beHG2012f/sw/slc7_amd64_gcc630/cms/workqueue/1.4.3.pre6/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 800, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/data/srv/beHG2012f/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.23.11/lib/python2.7/site-packages/rucio/client/didclient.py", line 427, in get_did
    raise exc_cls(exc_msg)
```

@nsmith- Nick, would you have any clue of what happened to this DID?

**Comment by nsmith-** [comment]
I don't see any record of the block DID `/W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v1/MINIAODSIM#aad1f8a0-7eec-4715-8acc-7fb6dd0d623c` in rucio database. I'm not sure if our REST API logs go back far enough to determine if the request happened.

**Comment by amaltaro** [comment]
@nsmith- I wonder how we should proceed with this and any further non-existent DID that we catch in our service logs. It could be that:
1) data is VALID in DBS but does not exist in Rucio
2) data is INVALID/DELETE in DBS but does not exist in Rucio

For case 1), do we want to come up with a way to recreate that DID (usually a block) in Rucio?
For case 2), I guess we need to invalidate that DID in DBS, right?

I suppose the DM team will act on those? If so, how should we communicate such issues (email to the transfer-team egroup?)? Thanks

**Comment by amaltaro** [comment]
This issue has been fixed by https://github.com/dmwm/WMCore/pull/10342 and https://github.com/dmwm/WMCore/pull/10557
