### ISSUE TITLE
can't create database with WMInit.py anymore

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10197]
Hi @amaltaro  we have used since ever these instructions to create a new set of CRAB DB tables
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabRESTInterface#Install_Scratch_Update_the_Oracl
but now I tried (in order to move my private development DB from devdb11 to devdb19) and got

```
belforte@stefanovm2/srv> /data/user/WMCore/bin/wmcore-db-init --config /data/dbconfig.py --create --modules=Databases.TaskDB,Databases.FileMetaDataDB,Databases.FileTransfersDB
checking default database connection
DEBUG:root:Log file ready
default database connection tested
Traceback (most recent call last):
  File "/data/user/WMCore/bin/wmcore-db-init", line 156, in <module>
    create(cfgObject)
  File "/data/user/WMCore/bin/wmcore-db-init", line 131, in create
    wmInit.setSchema(modules, params = params)
  File "/data/srv/HG2101c-comp/sw.crab3/slc7_amd64_gcc630/cms/crabserver/v3.201217/lib/python2.7/site-packages/WMCore/WMInit.py", line 160, in setSchema
    myThread.transaction.begin()
AttributeError: '_MainThread' object has no attribute 'transaction'

```

looks it never reaches the point where any crab specific stuff is used.
Does this ring any bell ?

I am unsing rpms from http://cmsrep.cern.ch/cmssw/repos/comp.crab3/slc7_amd64_gcc630/latest/RPMS.json which weres built with 1.3.6.crab5
```
belforte@stefanovm2/srv> cat /data/srv/HG2101c-comp/sw.crab3/slc7_amd64_gcc630/cms/crabserver/v3.201217/lib/python2.7/site-packages/WMCore/__init__.py
#!/usr/bin/env python
"""
_WMCore_

Core libraries for Workload Management Packages

"""

__version__ = '1.3.6.crab5'
__all__ = []
belforte@stefanovm2/srv> 
```
Access to existing DB's work, but I do not like that we can't create a new one !

**Comment by belforte** [comment]
Sworry I was using an inconsistent version of wmcore-db-init. had checked out correct takg, but old version was still around.
