### ISSUE TITLE
pycurl_manager fails with TypeError in python3

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10333]
**Impact of the bug**
Every class that inherits from `WMCore.Services.Services` and uses pycurl to make a request.  

**Describe the bug**
While trying to run the micro services under python3 environment I got stuck with the following error: [4]

After a deeper look and running the whole long chain of calls through `pdb` I managed to pin the culprit. This is a type mismatch between the header we get from the call of `curl.perform()` in `pycurl_manager`, which is a `byte` [1], and the expression we use for splitting it, which is a hardcoded string [2]. We have two options to proceed here:
   * casting the header we are trying to parse to a `str`
   * or making the split `str` a `byte` 
I already tried the former and it seems to work [3], but it requires a change of the type of a header returned by a regular library (such as pycurl) and I would consider it risky because I am not sure if it is not to be expected as a byte somewhere else down the code. Even though in my case it did work.  

[1]
```
> /afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py(72)parse()
-> def parse(self, response):
(Pdb) l
 67  	        self.header = {}
 68  	        self.reason = ''
 69  	        self.fromcache = False
 70  	        self.parse(response)
 71  	
 72  ->	    def parse(self, response):
 73  	        """Parse response header and assign class member data"""
 74  	        startRegex = r"^HTTP/\d.\d \d{3}"
 75  	        continueRegex = r"^HTTP/\d.\d 100"  # Continue: client should continue its request
 76  	        replaceRegex = r"^HTTP/\d.\d"
 77  	
(Pdb) s
> /afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py(74)parse()
-> startRegex = r"^HTTP/\d.\d \d{3}"
(Pdb) response
b'HTTP/1.1 200 OK\r\nDate: Fri, 05 Mar 2021 21:12:25 GMT\r\nServer: CherryPy/17.4.0\r\nContent-Length: 18\r\nContent-Encoding: deflate\r\nX-Rest-Time: 22814.035 us\r\nX-Rest-Status: 100\r\nVary: Accept,Accept-Encoding\r\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\r\nCache-Control: max-age=3600\r\nContent-Type: application/json\r\nCMS-Server-Time: D=39530 t=1614978745314628\r\n\r\n'
```

[2]
```
> /afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py:
 78        for row in response.split('\r'):  
```

[3]
```
(Pdb) response=str(response)
(Pdb) s
> /afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py(79)parse()
-> row = row.replace('\n', '')
(Pdb) 
> /afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py(80)parse()
-> if not row:
...
```

[4]
```
2021-03-05 19:43:15,206:ERROR:MSRuleCleaner:execute(): ('Unknown exception while fetching requests from ReqMgr2. Error: %s', "a bytes-like object is required, not 'str'")
Traceback (most recent call last):
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/MicroService/Unified/MSRuleCleaner.py", line 207, in execute
    requestRecords.update(self.getRequestRecords(status))
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/MicroService/Unified/MSRuleCleaner.py", line 691, in getRequestRecords
    result = self.reqmgr2.getRequestByStatus([reqStatus], detail=True)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/ReqMgr/ReqMgr.py", line 131, in getRequestByStatus
    return self._getResult(callname, verb="GET")
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/ReqMgr/ReqMgr.py", line 50, in _getResult
    verb=verb, contentType=contentType)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Service.py", line 209, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Service.py", line 288, in getData
    contentType=contentType)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Requests.py", line 159, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Requests.py", line 177, in makeRequest_pycurl
    ckey=ckey, cert=cert, capath=capath)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 282, in request
    header = self.parse_header(hbuf.getvalue())
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 270, in parse_header
    return ResponseHeader(header)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 70, in __init__
    self.parse(response)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 78, in parse
    for row in response.split('\r'):
TypeError: a bytes-like object is required, not 'str'
```
 
**How to reproduce it**
Try to run anything which calls `WMCore.Services.pycurl_manager` under python3 environment.

**Expected behavior**
I expect the have a header and a parsing string of the same type (regardless `str` or `byte`) so that  any call to `pycurl_manager` should succeed.

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by todor-ivanov** [comment]
And digging deeper takes me to the reason why the header type and the parse string type are different. The buffer for the header is actually generated as `BytesIO` [1].

[1]
```
221  	        curl.setopt(pycurl.URL, encodeUnicodeToBytes(url))
222  	        if headers:
223  	            curl.setopt(pycurl.HTTPHEADER, \
224  	                [encodeUnicodeToBytes("%s: %s" % (k, v)) for k, v in viewitems(headers)])
225  	        bbuf = BytesIO()
226  ->	        hbuf = BytesIO()
227  	        curl.setopt(pycurl.WRITEFUNCTION, bbuf.write)
228  	        curl.setopt(pycurl.HEADERFUNCTION, hbuf.write)
229  	        if capath:
230  	            curl.setopt(pycurl.CAPATH, capath)
231  	            curl.setopt(pycurl.SSL_VERIFYPEER, True)
(Pdb) n
> /afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py(227)set_opts()
-> curl.setopt(pycurl.WRITEFUNCTION, bbuf.write)
(Pdb) type(bbuf)
<class '_io.BytesIO'>
```

**Comment by todor-ivanov** [comment]
Unfortunately simply casting the header from bytes to string doesn't work. The code still breaks few lines bellow: [1] Obviously the parsing is not going as expected.


[1]
```
2021-03-06 01:12:25,415:ERROR:MSRuleCleaner:execute(): ('Unknown exception while fetching requests from ReqMgr2. Error: %s', "'ResponseHeader' object has no attribute 'status'")
Traceback (most recent call last):
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/MicroService/Unified/MSRuleCleaner.py", line 207, in execute
    msg = "Unknown exception while fetching requests from ReqMgr2. Error: %s", str(err)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/MicroService/Unified/MSRuleCleaner.py", line 691, in getRequestRecords
    requests = {}
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/ReqMgr/ReqMgr.py", line 131, in getRequestByStatus
    return self._getResult(callname, verb="GET")
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/ReqMgr/ReqMgr.py", line 50, in _getResult
    verb=verb, contentType=contentType)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Service.py", line 209, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Service.py", line 288, in getData
    contentType=contentType)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Requests.py", line 159, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/Requests.py", line 177, in makeRequest_pycurl
    ckey=ckey, cert=cert, capath=capath)
  File "/afs/cern.ch/work/t/tivanov/private/WMCoreDev.d/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 283, in request
    if verbose:
AttributeError: 'ResponseHeader' object has no attribute 'status'

```

**Comment by todor-ivanov** [comment]
Here is some more detailed info about how the change I proposed is breaking so badly.

The function that is failing is: [1]. Due to the (wrong) casting all the spacial symbols are 'smeared' and double escaped, so the following steps fail all together - I took a real header from one of my pdb runs [2] and repeated them a single step at a time. The results are as follows:
   * The splitting of the header by Carriage Return is failing [3]
   * The replacement of all New Lines is failing [4]
   * The regular expression match is failing [5]
 
[1]
```
 72  ->	    def parse(self, response):
 73  	        response = str(response)
 74  	        """Parse response header and assign class member data"""
 75  	        startRegex = r"^HTTP/\d.\d \d{3}"
 76  	        continueRegex = r"^HTTP/\d.\d 100"  # Continue: client should continue its request
 77  	        replaceRegex = r"^HTTP/\d.\d"
(Pdb) 
 78  	
 79  	        for row in response.split('\r'):
 80  	            row = row.replace('\n', '')
 81  	            if not row:
 82  	                continue
 83  	            if re.search(startRegex, row):
 84  	                if re.search(continueRegex, row):
 85  	                    continue
 86  	                res = re.sub(replaceRegex, "", row).strip()
 87  	                status, reason = res.split(' ', 1)
 88  	                self.status = int(status)
(Pdb) 
 89  	                self.reason = reason
 90  	                continue
 91  	            try:
 92  	                key, val = row.split(':', 1)
 93  	                self.header[key.strip()] = val.strip()
 94  	            except:
 95  	                pass
```

[2]
```
In [2]: response
Out[2]: b'HTTP/1.1 200 OK\r\nDate: Sat, 06 Mar 2021 00:56:24 GMT\r\nServer: CherryPy/17.4.0\r\nContent-Length: 18\r\nContent-Encoding: deflate\r\nX-Rest-Time: 21893.024 us\r\nX-Rest-Status: 100\r\nVary: Accept,Accept-Encoding\r\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\r\nCache-Control: max-age=3600\r\nContent-Type: application/json\r\nCMS-Server-Time: D=37110 t=1614992184222564\r\n\r\n'

In [3]: response = str(response)

In [4]: response
Out[4]: 'b\'HTTP/1.1 200 OK\\r\\nDate: Sat, 06 Mar 2021 00:56:24 GMT\\r\\nServer: CherryPy/17.4.0\\r\\nContent-Length: 18\\r\\nContent-Encoding: deflate\\r\\nX-Rest-Time: 21893.024 us\\r\\nX-Rest-Status: 100\\r\\nVary: Accept,Accept-Encoding\\r\\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\\r\\nCache-Control: max-age=3600\\r\\nContent-Type: application/json\\r\\nCMS-Server-Time: D=37110 t=1614992184222564\\r\\n\\r\\n\''
```

[3]
```
In [7]: response.split('\r')
Out[7]: ['b\'HTTP/1.1 200 OK\\r\\nDate: Sat, 06 Mar 2021 00:56:24 GMT\\r\\nServer: CherryPy/17.4.0\\r\\nContent-Length: 18\\r\\nContent-Encoding: deflate\\r\\nX-Rest-Time: 21893.024 us\\r\\nX-Rest-Status: 100\\r\\nVary: Accept,Accept-Encoding\\r\\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\\r\\nCache-Control: max-age=3600\\r\\nContent-Type: application/json\\r\\nCMS-Server-Time: D=37110 t=1614992184222564\\r\\n\\r\\n\'']

In [8]: len(response.split('\r'))
Out[8]: 1

In [10]: row=response.split('\r')[0]

In [11]: row
Out[11]: 'b\'HTTP/1.1 200 OK\\r\\nDate: Sat, 06 Mar 2021 00:56:24 GMT\\r\\nServer: CherryPy/17.4.0\\r\\nContent-Length: 18\\r\\nContent-Encoding: deflate\\r\\nX-Rest-Time: 21893.024 us\\r\\nX-Rest-Status: 100\\r\\nVary: Accept,Accept-Encoding\\r\\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\\r\\nCache-Control: max-age=3600\\r\\nContent-Type: application/json\\r\\nCMS-Server-Time: D=37110 t=1614992184222564\\r\\n\\r\\n\''
```

[4]
```
In [12]: row = row.replace('\n', '')

In [13]: row
Out[13]: 'b\'HTTP/1.1 200 OK\\r\\nDate: Sat, 06 Mar 2021 00:56:24 GMT\\r\\nServer: CherryPy/17.4.0\\r\\nContent-Length: 18\\r\\nContent-Encoding: deflate\\r\\nX-Rest-Time: 21893.024 us\\r\\nX-Rest-Status: 100\\r\\nVary: Accept,Accept-Encoding\\r\\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\\r\\nCache-Control: max-age=3600\\r\\nContent-Type: application/json\\r\\nCMS-Server-Time: D=37110 t=1614992184222564\\r\\n\\r\\n\''
```


[5]
```
In [14]: startRegex = r"^HTTP/\d.\d \d{3}"

In [15]: if re.search(startRegex, row):
    ...:     print("match")
    ...: else:
    ...:     print("NOmatch")
    ...: 
NOmatch
```

**Comment by todor-ivanov** [comment]
Option number 2 which I proposed in my initial comment, is actually doing the job much better: [1]

[1]
```
In [17]: response
Out[17]: b'HTTP/1.1 200 OK\r\nDate: Sat, 06 Mar 2021 00:56:24 GMT\r\nServer: CherryPy/17.4.0\r\nContent-Length: 18\r\nContent-Encoding: deflate\r\nX-Rest-Time: 21893.024 us\r\nX-Rest-Status: 100\r\nVary: Accept,Accept-Encoding\r\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"\r\nCache-Control: max-age=3600\r\nContent-Type: application/json\r\nCMS-Server-Time: D=37110 t=1614992184222564\r\n\r\n'

In [18]: response.split(b'\r')
Out[18]: 
[b'HTTP/1.1 200 OK',
 b'\nDate: Sat, 06 Mar 2021 00:56:24 GMT',
 b'\nServer: CherryPy/17.4.0',
 b'\nContent-Length: 18',
 b'\nContent-Encoding: deflate',
 b'\nX-Rest-Time: 21893.024 us',
 b'\nX-Rest-Status: 100',
 b'\nVary: Accept,Accept-Encoding',
 b'\nEtag: "9c66ca948c2c34405e231689f5286bb9b0cc7c20"',
 b'\nCache-Control: max-age=3600',
 b'\nContent-Type: application/json',
 b'\nCMS-Server-Time: D=37110 t=1614992184222564',
 b'\n',
 b'\n']

In [19]: row=response.split(b'\r')[0]

In [20]: row
Out[20]: b'HTTP/1.1 200 OK'

In [22]: row = row.replace(b'\n', b'')

In [23]: row
Out[23]: b'HTTP/1.1 200 OK'

In [24]: startRegex = r"^HTTP/\d.\d \d{3}"

In [25]: if re.search(startRegex, row):
    ...:     print("match")
    ...: else:
    ...:     print("NOmatch")
    ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-7aa20f025131> in <module>
----> 1 if re.search(startRegex, row):
      2     print("match")
      3 else:
      4     print("NOmatch")
      5 

/usr/lib64/python3.6/re.py in search(pattern, string, flags)
    180     """Scan through string looking for a match to the pattern, returning
    181     a match object, or None if no match was found."""
--> 182     return _compile(pattern, flags).search(string)
    183 
    184 def sub(pattern, repl, string, count=0, flags=0):

TypeError: cannot use a string pattern on a bytes-like object

In [26]: startRegex = b"^HTTP/\d.\d \d{3}"

In [27]: if re.search(startRegex, row):
    ...:     print("match")
    ...: else:
    ...:     print("NOmatch")
    ...: 
match


```

**Comment by todor-ivanov** [comment]
And with the so proposed change put directly into the `pycurl_manager` module, here is the resultant header after parsing it [1]. Which is exactly what one would expect.


[1]
```
(Pdb) l
281  	        curl.perform()
282  	        if verbose:
283  	            print(verb, url, params, headers)
284  	        header = self.parse_header(hbuf.getvalue())
285  ->	        if header.status < 300:
286  	            if verb == 'HEAD':
287  	                data = ''
288  	            else:
289  	                data = self.parse_body(bbuf.getvalue(), decode)

(Pdb) header
<WMCore.Services.pycurl_manager.ResponseHeader object at 0x7fa0e069e748>

(Pdb) pprint(header.header)
{b'CMS-Server-Time': b'D=31131 t=1615065792052800',
 b'Cache-Control': b'max-age=3600',
 b'Content-Encoding': b'deflate',
 b'Content-Length': b'18',
 b'Content-Type': b'application/json',
 b'Date': b'Sat, 06 Mar 2021 21:23:12 GMT',
 b'Etag': b'"9c66ca948c2c34405e231689f5286bb9b0cc7c20"',
 b'Server': b'CherryPy/17.4.0',
 b'Vary': b'Accept,Accept-Encoding',
 b'X-Rest-Status': b'100',
 b'X-Rest-Time': b'18943.071 us'}
```

**Comment by todor-ivanov** [comment]
This thing does obviously not fit anywhere in the python3 migration plan. So no need for this to stay open.

**Comment by amaltaro** [comment]
Now that I managed to deploy `wmagentpy3` in my VM, I can confirm this `TypeError` exception that Todor reported a couple of months ago. It's probably one of the first things to be tackled once we have CI in python3.

Here's how to reproduce it, in a WMAgent PY3 box:
```
source /data/admin/wmagent/env.sh
$manage execute-agent wmagent-upload-config
```

which should raise this traceback:
```
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/bin/wmagent-upload-config", line 29, in <module>
    if not reqMgrAux.updateWMAgentConfig(wmConfig.Agent.hostName, DEFAULT_AGENT_CONFIG):
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 150, in updateWMAgentConfig
    resp = self["requests"].put("%s/%s" % (api, agentName), content)[0]['result']
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 138, in put
    return self.makeRequest(uri, data, 'PUT', incoming_headers,
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 161, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 178, in makeRequest_pycurl
    response, result = self.reqmgr.request(uri, data, headers, verb=verb,
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 284, in request
    header = self.parse_header(hbuf.getvalue())
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 271, in parse_header
    return ResponseHeader(header)
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 72, in __init__
    self.parse(response)
  File "/data/srv/wmagent/v1.4.9.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 80, in parse
    for row in response.split('\r'):
TypeError: a bytes-like object is required, not 'str'
```
