### ISSUE TITLE
MSOutput - unhandled exception in _getDatasetSize()

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10368]
**Impact of the bug**
MSOutput

**Describe the bug**
While trying to determine dataset size if the service for any reason fails to do so (e.g. fails to get DID info from Rucios etc.) we do not handle the exception [1] but just let it reach the upper level pipeline exception handler, while proper actions  should be taken at place. In result we pollute the logs with exceptions, which in many cases could be just predictable/expected behavior.   

[1]
https://github.com/dmwm/WMCore/blob/e45a4425c5437d194d0d02814b7011c752c33548/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L696

[2]
```
2021-03-23 01:14:48,521:ERROR:MSOutput: MSOutputProducer Pipeline Possibly broken read from ReqMgr2 API or other. Err: 'bytes'. Continue to the next document.
Traceback (most recent call last):
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 545, in msOutputProducer
    msPipeline.run(request)
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 140, in run
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 140, in <lambda>
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 72, in __call__
    return self.run(obj)
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 75, in run
    return self.func(obj, *self.args, **self.kwargs)
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 622, in docInfoUpdate
    bytesSize = self._getDatasetSize(dataItem['Dataset'])
  File "/data/srv/HG2103g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.6.pre9/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 695, in _getDatasetSize
    return didInfo["bytes"]
KeyError: 'bytes'
```

**How to reproduce it**
Just look at the MSOutput  logs

**Expected behavior**
In case the situation is expected, we should handle the exception at the place where it happens (even if we need to create a new class of exceptions), and propagate only the unexpected ones upstream.
 
**Additional context and error message**
N/A

**Comment by amaltaro** [comment]
For the record, I just spotted this problem in the MSOutput logs, and I believe it's actually a blocker to moving the workflow forward and eventually archiving it. Fresh logs are:
```
2021-06-15 10:43:19,828:INFO:MSOutput: Producing MongoDB record for workflow: pdmvserv_RVCMSSW_11_3_0_pre6H125GGgluonfusion_14__2026D76PU200_RECOonly_210419_202554_1748
2021-06-15 10:43:19,841:DEBUG:connectionpool: http://cms-rucio.cern.ch:80 "GET /dids/cms/%2FRelValH125GGgluonfusion_14%2FCMSSW_11_3_0_pre6-PU_113X_mcRun4_realistic_v6_2026D76PU200_RECOonly-v1%2FGEN-SIM-RECO?dynamic=True HTTP/1.1" 404 None
2021-06-15 10:43:19,842:ERROR:Rucio: Data identifier not found in Rucio: /RelValH125GGgluonfusion_14/CMSSW_11_3_0_pre6-PU_113X_mcRun4_realistic_v6_2026D76PU200_RECOonly-v1/GEN-SIM-RECO. Error: Data identifier not found.
Details: Data identifier 'cms:/RelValH125GGgluonfusion_14/CMSSW_11_3_0_pre6-PU_113X_mcRun4_realistic_v6_2026D76PU200_RECOonly-v1/GEN-SIM-RECO' not found
2021-06-15 10:43:19,842:ERROR:MSOutput: MSOutputProducer Pipeline Possibly broken read from ReqMgr2 API or other. Err: 'bytes'. Continue to the next document.
Traceback (most recent call last):
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 547, in msOutputProducer
    msPipeline.run(request)
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/Utils/Pipeline.py", line 140, in run
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/Utils/Pipeline.py", line 140, in <lambda>
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/Utils/Pipeline.py", line 72, in __call__
    return self.run(obj)
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/Utils/Pipeline.py", line 75, in run
    return self.func(obj, *self.args, **self.kwargs)
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 624, in docInfoUpdate
    bytesSize = self._getDatasetSize(dataItem['Dataset'])
  File "/data/srv/HG2106g/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.9.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 697, in _getDatasetSize
    return didInfo["bytes"]
KeyError: 'bytes'
```

Without giving too much thought, I see no reason to block this workflow because we failed to fetch its size in Rucio. It could actually well be that the workflow is getting announced, even though an output dataset didn't manage to be produced.

IMO, if a workflow is in one of the MSOutput expected statuses `['closed-out', 'announced']`, it's then ready to be archived.

PS.: The workflow above is stuck in the system for almost 2 months now, which means, it never gets archived and just contribute to the overall system load. 

Bumping the priority of this ticket.

**Comment by todor-ivanov** [comment]
Hi @amaltaro,

This is a strange behavior to me. Why do we not take any action at a point with a well known exception at [1], which is caught in [2] and an empty dict returned. But instead we try to fetch a non existing key from and empty dictionary and let (now a different  and confusing) Exception propagate to the top level general exception handler of the pipeline? This is in my opinion is:
   * Misleading - because of the Exception metamorphosis that is happening halfway down the road
   * It is a blocker, because at that  point it is definite the DID in question is missing from Rucio [3] (for an unknown reason), and the record about this workflow will never be created in MongoDB. This one is doomed to never move forward.  


[1]
https://github.com/dmwm/WMCore/blob/4d72c731ed444d9c84b8417d2c6a911fa2535b2c/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L696

[2]
https://github.com/dmwm/WMCore/blob/389f54600a739448d2809048a8e7fd20807fa70a/src/python/WMCore/Services/Rucio/Rucio.py#L828-L833

[3]
```
$ rucio get-metadata cms:/RelValH125GGgluonfusion_14/CMSSW_11_3_0_pre6-PU_113X_mcRun4_realistic_v6_2026D76PU200_RECOonly-v1/GEN-SIM-RECO
2021-06-15 22:03:04,529	ERROR	Data identifier not found.
Details: Data identifier 'cms:/RelValH125GGgluonfusion_14/CMSSW_11_3_0_pre6-PU_113X_mcRun4_realistic_v6_2026D76PU200_RECOonly-v1/GEN-SIM-RECO' not found

```

**Comment by amaltaro** [comment]
Todor, just to make sure I understood you. Are you saying that we should enclose the `_getDatasetSize` call in a try/except block and handle the `KeyError` properly, such that that workflow can move forward? If so, then we are on the same page and this is exactly what I meant in my comment above.

**Comment by amaltaro** [comment]
Or a variation of that, one could check if `didInfo` is an empty dictionary, which would - practically speaking - have the same result as in the comment above.

**Comment by todor-ivanov** [comment]
Hi @amaltaro, Thanks!
Indeed, we are on the same page here. Both ways would do in my opinion. How we decide to identify the error, either by the empty dictionary or by handling the already metamorphosed new `KeyError` exception, it doesn't matter to me. The discussion that we need to have is more on the type of action we decide to take in that situation. So I would suggest, in case we decide to block the workflow until a manual interaction takes place, then we should signal that to someone, instead of letting it stale in the queue until we find it by accident months later. In this case the `AlertManager` is not a bad choice. The other option should be to do some additional checks (if there are any possible) to see how bad the situation is before we let it pass through or alert. 
Of course it all depends also on the frequency at which we get those errors -  the more we have them the more automated action we'd need.

**Comment by amaltaro** [comment]
@haozturk Hasan, I think your input here would be quite important.
I assume that, if a workflow is in closed-out or announced, the Unified system has already verified the workflow completion, the output dataset stats, etc etc and things are good enough for the workflow announcement (including relvals?).

So, my question is, do you think we need any sort of alerts for such cases where one or more of the output datasets cannot be found in Rucio? My plan is to just bypass output datasets not inserted into Rucio (Copies=0), make a record in the log, and proceed with standard MSOutput data placement. If such cases are quite rare, we could extend it to also make an alert in the usual `dmwm` slack channel?

Please let us know what your thoughts are on this. Thanks

**Comment by haozturk** [comment]
@amaltaro 
> I assume that, if a workflow is in closed-out or announced, the Unified system has already verified the workflow completion, the output dataset stats, etc etc and things are good enough for the workflow announcement (including relvals?).

This is true

> So, my question is, do you think we need any sort of alerts for such cases where one or more of the output datasets cannot be found in Rucio? My plan is to just bypass output datasets not inserted into Rucio (Copies=0), make a record in the log, and proceed with standard MSOutput data placement. If such cases are quite rare, we could extend it to also make an alert in the usual dmwm slack channel?

I actually had hard time understanding the issue here. Do you mean an alert for cases where MSOutput fails to make an output data placement for a given dataset?

**Comment by amaltaro** [comment]
>I actually had hard time understanding the issue here. Do you mean an alert for cases where MSOutput fails to make an output data placement for a given dataset?

MSOutput runs in two modes:
* producing workflow entries, thus fetching information from Rucio and deciding how the data placement will be done (where this error happens)
* consuming workflow entries, based on the information produced in the thread above.

So, my question is, should we create any alerts for workflows going through the MSOutput service, and failing to find a given output dataset in Rucio? Imagine that a RelVal workflow has 3 datasets to be announced:
1) blah/GEN-SIM-RECO
2) blah/DQMIO
3) blah/AODSIM

supposing that the DQMIO merge job failed, meaning that no DQMIO dataset has been produced - thus making it unknown to Rucio - should we create a notification if the Rucio query `get the DQMIO container size` is empty (exception raised for "Data identifier not found")?

If it's still not clear, please ping me on slack.

**Comment by haozturk** [comment]
Thanks a lot for the explanation Alan, now it's clear. If a workflow is moved to `closed-out`, this means that satisfactory statistics have been produced for all outputs. Sometimes, we bypass some workflows if the output is partially produced and we record these cases in JIRA. But, I don't see any possibility to see a workflow in `closed-out` with its output completely missing from Rucio. So, if the output is completely missing from Rucio, yes, we should create an alert for it. I actually don't remember even one single case, so, I expect this alert should be very rare. I'd prefer email alerts if possible, it's easier to organize them. If not possible, Slack alert is also fine. 

Depending on the alerts that we take, I believe we can decide how to proceed in the future (Whether to suppress them or keep them)

**Comment by amaltaro** [comment]
That approach looks good to me.
Okay, I am going to make email alerts in case an output dataset cannot be found in Rucio, and let the usual workflow output data placement proceed with the rest of the datasets.

I believe we are going to get tens of emails once we upgrade CMSWEB services in the next Tuesday (likely with workflows that are months old in MSOutput...)

**Comment by haozturk** [comment]
Thanks Alan. Is one alert going to be generated for one missing output? Repetitive alerts really makes things harder to track.

**Comment by amaltaro** [comment]
It turns out the fix provided was incomplete! The service still tries to place that output dataset at one tape destination(!)

Fresh logs post CMSWEB upgrade report:
```
2021-08-03 09:55:12,446:INFO:MSOutput: Creating Rucio TAPE rule for container: /MinBias_TuneCP2_13TeV-pythia8/RunIISummer20UL18MiniAOD-FSUL18_pilot_106X_upgrade2018_realistic_v11_L1v1-v1/MINIAODSIM and RSE: T1_RU_JINR_Tape
2021-08-03 09:55:13,318:DEBUG:connectionpool: http://cms-rucio.cern.ch:80 "POST /rules/ HTTP/1.1" 201 None
2021-08-03 09:55:13,319:INFO:MSOutput: Creating Rucio TAPE rule for container: /MinBias_TuneCP2_13TeV-pythia8/RunIISummer20UL18MiniAODv2-FSUL18_pilot_106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM and RSE: T1_RU_JINR_Tape
2021-08-03 09:55:13,362:DEBUG:connectionpool: http://cms-rucio.cern.ch:80 "POST /rules/ HTTP/1.1" 404 None
2021-08-03 09:55:13,363:ERROR:Rucio: Exception creating rule replica for data: ['/MinBias_TuneCP2_13TeV-pythia8/RunIISummer20UL18MiniAODv2-FSUL18_pilot_106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM']. Error: Data identifier not found.
Details: Data identifier cms:/MinBias_TuneCP2_13TeV-pythia8/RunIISummer20UL18MiniAODv2-FSUL18_pilot_106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM is not valid.
2021-08-03 09:55:13,363:INFO:MSOutput: Tape requests partially successful for: pdmvserv_task_PPD-RunIISpring21UL18FSGSPremix-00002__v1_T_210504_144226_8134. Marking it as 'pending'
```

My bad, since I only test the producer thread. The consumer thread needs to be tested in a private VM pointing to Rucio Prod... reopening.
