### ISSUE TITLE
Microservices REST APIs returning a 500 Internal Server Error in 1.4.7.pre6

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10375]
**Impact of the bug**
MicroServices (reqmgr2ms)

**Describe the bug**
With the latest reorganization changes applied to the microservices packages, in this PR:
https://github.com/dmwm/WMCore/pull/10357

something went wrong and the services are not able to serve requests through the REST APIs, which returns a `500 Internal Server Error`.
 If we run the `status` command, microservices are reported as RUNNING though.

**How to reproduce it**
Deploy the latest WMCore pre-release `1.4.7.pre6` and call one of the MS APIs, e.g.: `/ms-transferor/data/info`

**Expected behavior**
MicroServices should be running without any issues, that includes the REST APIs.

**Additional context and error message**
I see this error in the MSTransferor log, when the service gets started:
```
ERROR initializing MicroService REST module.
Traceback (most recent call last):
  File "/data/srv/HG2104b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre6/lib/python2.7/site-packages/WMCore/MicroService/Service/Data.py", line 57, in __init__
    module = importlib.import_module('.'.join(arr[:-1]))
  File "/data/srv/HG2104b/sw/slc7_amd64_gcc630/external/python/2.7.13-comp2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named MSManager
[24/Mar/2021:15:30:06]  INFO: loading ui into /ms-transferor
```

and this is the server-side traceback when the REST API call is made:
```
[24/Mar/2021:15:30:06] ENGINE Bus STARTING
[24/Mar/2021:15:30:06] ENGINE Serving on http://0.0.0.0:8247
[24/Mar/2021:15:30:06] ENGINE Bus STARTED
[24/Mar/2021:15:31:14]  SERVER OTHER ERROR __builtins__.AttributeError 9359b4c9d9de6dda70ccf292f3d5d123 ('Data' object has no attribute 'mgr')
[24/Mar/2021:15:31:14]    Traceback (most recent call last):
[24/Mar/2021:15:31:14]      File "/data/srv/HG2104b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre6/lib/python2.7/site-packages/WMCore/REST/Server.py", line 726, in default
[24/Mar/2021:15:31:14]        return self._call(RESTArgs(list(args), kwargs))
[24/Mar/2021:15:31:14]      File "/data/srv/HG2104b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre6/lib/python2.7/site-packages/WMCore/REST/Server.py", line 807, in _call
[24/Mar/2021:15:31:14]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[24/Mar/2021:15:31:14]      File "/data/srv/HG2104b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre6/lib/python2.7/site-packages/WMCore/MicroService/Service/Data.py", line 90, in get
[24/Mar/2021:15:31:14]        'microservice': self.mgr.__class__.__name__}
[24/Mar/2021:15:31:14]    AttributeError: 'Data' object has no attribute 'mgr'
```

**Comment by amaltaro** [comment]
Bad bad job Alan! There are required configuration changes... I will update it soon with the correspondent PRs.

**Comment by amaltaro** [comment]
The PR description was updated with all the relevant deployment changes: https://github.com/dmwm/WMCore/pull/10357

Once those are merged, I will also close this issue.

**Comment by amaltaro** [comment]
Deployment changes have been tested, merged, and deployed to tesbed. Closing this issue.
