### ISSUE TITLE
improve reporting of Oracle connection failures

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10395]
with reference to
https://github.com/dmwm/WMCore/blob/77a1ae719757a1eef766f8fb0c9f29ce6fcd2275/src/python/WMCore/REST/Server.py#L1666
which CRABServer REST (at least) inherits from, as Kate pointed out after a problem storm last night:
```
 it would be great if at some point someone had changed it to push pure DB errors to the logs
instead of the nice but vague "DB is not available" msg.
It would make debugging issues much easier.
```

**Comment by amaltaro** [comment]
Stefano, this `DB is not available` error message is what gets reported in the service log? Or it's what gets reported to the client making a REST call?

On the same Oracle issues that popped up over the last days, this is the common error I've seen in our components:
```
(cx_Oracle.DatabaseError) ORA-12541: TNS:no listener
(Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by belforte** [comment]
thanks Alan. Your log surely is better than ours :-(
This is server side and traceback aside had no more info than client who gets the message in the last line
```
[30/Mar/2021:19:47:34]  SERVER REST ERROR WMCore.REST.Error.DatabaseUnavailable a8c7a10785c7c35b86c5930083d40100 (Database unavailable)
[30/Mar/2021:19:47:34]    Traceback (most recent call last):
[30/Mar/2021:19:47:34]      File "/data/srv/HG2102d/sw/slc7_amd64_gcc630/cms/crabserver/v3.210110-comp3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 723, in default
[30/Mar/2021:19:47:34]        return self._call(RESTArgs(list(args), kwargs))
[30/Mar/2021:19:47:34]      File "/data/srv/HG2102d/sw/slc7_amd64_gcc630/cms/crabserver/v3.210110-comp3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 800, in _call
[30/Mar/2021:19:47:34]        v(apiobj, request.method, api, param, safe)
[30/Mar/2021:19:47:34]      File "/data/srv/HG2102d/sw/slc7_amd64_gcc630/cms/crabserver/v3.210110-comp3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1975, in _dbenter
[30/Mar/2021:19:47:34]        raise DatabaseUnavailable()
[30/Mar/2021:19:47:34]    DatabaseUnavailable: DatabaseUnavailable a8c7a10785c7c35b86c5930083d40100 [HTTP 503, APP 401, MSG 'Database unavailable', INFO None, ERR None]

```

**Comment by belforte** [comment]
somehow Lassi did not bother to look at the details of failing to create a DC connection and just wrote:
https://github.com/dmwm/WMCore/blob/77a1ae719757a1eef766f8fb0c9f29ce6fcd2275/src/python/WMCore/REST/Server.py#L1318-L1319

**Comment by amaltaro** [comment]
Stefano, any chance you could print the whole content of `err` from this line:
https://github.com/dmwm/WMCore/blob/77a1ae719757a1eef766f8fb0c9f29ce6fcd2275/src/python/WMCore/REST/Server.py#L1972

I'm curious to know what is all the error information that gets returned from the `get` method.

**Comment by belforte** [comment]
I can add and e.g. try to start with a wrong password

reproducing failures is always a challenge

**Comment by belforte** [comment]
in this case they are both `None` and the server log has a sensible message:
```
[31/Mar/2021:15:08:12]    DatabaseError: ORA-01017: invalid username/password; logon denied
```

**Comment by belforte** [comment]
I got it wrong befreo, in this case `err` from that line is:
```
(DatabaseError(<cx_Oracle._Error object at 0x7f0147fd4fb8>,),
 'Traceback (most recent call last):\n  File "/data/repos/WMCore/src/python/WMCore/REST/Server.py", line 1481, in _connect\n    dbh = (self.idle and self.idle.pop()) or self._new(s, trace)\n  File "/data/repos/WMCore/src/python/WMCore/REST/Server.py", line 1526, in _new\n    ret.update({"connection": s["type"].connect(s["user"], s["password"], s["dsn"], threaded=True)})\nDatabaseError: ORA-01017: invalid username/password; logon denied\n')
```

**Comment by belforte** [comment]
`err` has to be `None` for Database unavailable exception to be raised:
https://github.com/dmwm/WMCore/blob/77a1ae719757a1eef766f8fb0c9f29ce6fcd2275/src/python/WMCore/REST/Server.py#L1972-L1979

so we are looking for a situation where the connection object in the pool failed to connect to oracle w/o reporting a reason. Maybe the code did not wait long enough to see the ORA-12541 which you have ?

**Comment by belforte** [comment]
see: https://github.com/dmwm/WMCore/issues/10395#issuecomment-811026888
the default wait_time seems to be 8 seconds

**Comment by belforte** [comment]
of course it is quite possible that there are situatons where an attempt to make a remote connection (even to Oracle) may simply hang forever.
If anything, what is quite odd is that a crabserver restart was needed, since threads in the connection pool are supposed to be checked periodically, discarded if found not working, and started again. Maybe some K8s effect

**Comment by amaltaro** [comment]
Thanks for these tests, Stefano.

From the error message you posted above, it seems to me we have all the required pieces to provide the correct error to the end user. It's a matter of properly parsing that `err` object and returning to the end user only what we want and consider useful.

Regarding the connection timeout, it isn't clear to me whether we can spot when that happens or not. If we can, then we could make a specific error message to be returned as well.

**Comment by belforte** [comment]
Alan, when `errr` has content, things which you describe happens already.

The problem here is that at times connection fails and `err` is `None` and in that case I do not know where to find more info.
I.e. when the `request.get` returns w/o reporting nor an error, nor a db handle. I am not sure where is the code that is activated in that case, since there has to be some reference to cx_oracle at some point, but it is not in this module.

I can try a different failure mode (wrong connection string ?) to see if I can reproduce the Database unavailble.

**Comment by belforte** [comment]
Nope. Wrong connection string immediately reports:
```
 DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified
```
I'd rather not ask Kate to break int2r now for this test :-(

**Comment by belforte** [comment]
But if you have a timeout in the other applications to compare with the 8sec in
https://github.com/dmwm/WMCore/blob/77a1ae719757a1eef766f8fb0c9f29ce6fcd2275/src/python/WMCore/REST/Server.py#L1241

**Comment by amaltaro** [comment]
Ok. So I understand the correct error already gets reported to the end user, the only exception is for those cases where the connection (waiting period) times out. Is that the correct summary?

In that case, I honestly don't see anything else that you could make to debug it further. Of course, if you put real effort on it, then you can do whatever you want to gather more information... but you won't get anything for free :)

It's a time out on the client side (CRABServer), which means, the client decided not to wait for the connection to be established anymore. I think it's a hopeless case to debug
