### ISSUE TITLE
Adopt a different method for updating jobs in JobUpdater

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10445]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Depending on the status of the schedd and amount of jobs in the system, running condor_qedit becomes a heavy action and it should be avoided if possible. Right now, when we need to update the priority for a workflow, we actually run condor_qedit matching a given WMAgent_SubTaskName, as far as I remember.

**Describe the solution you'd like**
Instead of running many condor_qedit for the very same workflow - passing a different task path every time - I think we could actually run a single call for each workflow, with the following format:
```
condor_qedit -const 'JobStatus=?=1 && (CMS_JobType =?= "Production" || CMS_JobType =?= "Processing")' JobPrio JOB_PRIO_VALUE
```

**Describe alternatives you've considered**
Not a critical development, so we could not make any changes as well.

**Additional context**
As one can see in this component log, a whole cycle updating 8 workflows too around 8 minutes, fairly slow in my opinion:
```
2021-04-13 18:23:48,012:140261058021120:INFO:JobUpdaterPoller:Found 8 workflows to update in workqueue
2021-04-13 18:24:44,926:140261058021120:ERROR:SimpleCondorPlugin:Failed to update JobPrio for WMAgent_SubTaskName=/cmsunified_task_TSG-Run3Winter21GS-00006__v1_T_210403_135412_3515/TSG-Run3Winter21GS-00006_0/TSG-Run3Winter21DRMiniAOD-00002_1MergeMINIAODSIMoutput
2021-04-13 18:24:44,926:140261058021120:ERROR:SimpleCondorPlugin:Unable to edit jobs matching constraint
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.4.5.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 485, in updateJobInformation
    schedd.edit(constraint, 'JobPrio', classad.Literal(newPriority))
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/external/condor/8.9.7-comp/lib/python2.7/site-packages/htcondor/_lock.py", line 75, in wrapper
    rv = func(*args, **kwargs)
RuntimeError: Unable to edit jobs matching constraint
2021-04-13 18:27:10,536:140261058021120:ERROR:SimpleCondorPlugin:Failed to update JobPrio for WMAgent_SubTaskName=/cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00054__v1_T_201206_222616_3749/TOP-RunIISummer20UL18wmLHEGEN-00054_0/TOP-RunIISummer20UL18RECO-00052_0MergeAODSIMoutput
2021-04-13 18:27:10,536:140261058021120:ERROR:SimpleCondorPlugin:Unable to edit jobs matching constraint
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.4.5.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 485, in updateJobInformation
    schedd.edit(constraint, 'JobPrio', classad.Literal(newPriority))
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/external/condor/8.9.7-comp/lib/python2.7/site-packages/htcondor/_lock.py", line 75, in wrapper
    rv = func(*args, **kwargs)
RuntimeError: Unable to edit jobs matching constraint
2021-04-13 18:28:14,551:140261058021120:ERROR:SimpleCondorPlugin:Failed to update JobPrio for WMAgent_SubTaskName=/cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00061__v1_T_201206_222729_9983/TOP-RunIISummer20UL18wmLHEGEN-00061_0/TOP-RunIISummer20UL18RECO-00059_0MergeAODSIMoutput
2021-04-13 18:28:14,551:140261058021120:ERROR:SimpleCondorPlugin:Unable to edit jobs matching constraint
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.4.5.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 485, in updateJobInformation
    schedd.edit(constraint, 'JobPrio', classad.Literal(newPriority))
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/external/condor/8.9.7-comp/lib/python2.7/site-packages/htcondor/_lock.py", line 75, in wrapper
    rv = func(*args, **kwargs)
RuntimeError: Unable to edit jobs matching constraint
2021-04-13 18:29:06,090:140261058021120:ERROR:SimpleCondorPlugin:Failed to update JobPrio for WMAgent_SubTaskName=/cmsunified_task_TOP-RunIISummer20UL18wmLHEGEN-00061__v1_T_201206_222729_9983/TOP-RunIISummer20UL18wmLHEGEN-00061_0/TOP-RunIISummer20UL18MiniAOD-00059_0MergeMINIAODSIMoutput
2021-04-13 18:29:06,091:140261058021120:ERROR:SimpleCondorPlugin:Unable to edit jobs matching constraint
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.4.5.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 485, in updateJobInformation
    schedd.edit(constraint, 'JobPrio', classad.Literal(newPriority))
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/external/condor/8.9.7-comp/lib/python2.7/site-packages/htcondor/_lock.py", line 75, in wrapper
    rv = func(*args, **kwargs)
RuntimeError: Unable to edit jobs matching constraint
2021-04-13 18:30:57,409:140261058021120:ERROR:SimpleCondorPlugin:Failed to update JobPrio for WMAgent_SubTaskName=/cmsunified_task_BTV-RunIISummer20UL16GENAPV-00028__v1_T_210127_101322_3364/BTV-RunIISummer20UL16GENAPV-00028_0/BTV-RunIISummer20UL16RECOAPV-00015_0MergeAODSIMoutput
2021-04-13 18:30:57,409:140261058021120:ERROR:SimpleCondorPlugin:Unable to edit jobs matching constraint
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.4.5.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 485, in updateJobInformation
    schedd.edit(constraint, 'JobPrio', classad.Literal(newPriority))
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/external/condor/8.9.7-comp/lib/python2.7/site-packages/htcondor/_lock.py", line 75, in wrapper
    rv = func(*args, **kwargs)
RuntimeError: Unable to edit jobs matching constraint
2021-04-13 18:31:47,324:140261058021120:ERROR:SimpleCondorPlugin:Failed to update JobPrio for WMAgent_SubTaskName=/cmsunified_task_BTV-RunIISummer20UL16GENAPV-00028__v1_T_210127_101322_3364/BTV-RunIISummer20UL16GENAPV-00028_0/BTV-RunIISummer20UL16MiniAODAPV-00015_0MergeMINIAODSIMoutput
2021-04-13 18:31:47,324:140261058021120:ERROR:SimpleCondorPlugin:Unable to edit jobs matching constraint
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.4.5.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 485, in updateJobInformation
    schedd.edit(constraint, 'JobPrio', classad.Literal(newPriority))
  File "/data/srv/wmagent/v1.4.5.patch1/sw/slc7_amd64_gcc630/external/condor/8.9.7-comp/lib/python2.7/site-packages/htcondor/_lock.py", line 75, in wrapper
    rv = func(*args, **kwargs)
RuntimeError: Unable to edit jobs matching constraint
2021-04-13 18:31:56,265:140261058021120:INFO:JobUpdaterPoller:Updating 61 workflows in WMBS.
2021-04-13 18:31:56,286:140261058021120:INFO:JobUpdaterPoller:Priorities were synchronized, wait until the next cycle
2021-04-13 18:31:56,286:140261058021120:INFO:BaseWorkerThread:JobUpdaterPoller took 491.051 secs to execute
```

**Comment by khurtado** [comment]
```Instead of running many condor_qedit for the very same workflow - passing a different task path every time - I think we could actually run a single call for each workflow, with the following format```

@amaltaro With this, do you mean just taking into account `WMAgent_RequestName` but not `WMAgent_SubTaskName` anymore?

**Comment by amaltaro** [comment]
Exactly! That way we would reduce the job priority update in condor from X SubTaskName to 1 RequestName, taking into account the Production/Processing jobs only.

**Comment by khurtado** [comment]
@amaltaro Sounds good, but how would this formula change in that case?

https://github.com/dmwm/WMCore/blob/c816d945cde7a32b62f6537e53ed17c42d3f7994/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L480

Do we consider `taskPriority=1` and leave `self.maxTaskPriority` as a constant in the equation? E.g:

```
newPriority = int(kwargs['requestPriority']) +  self.maxTaskPriority)
```

**Comment by amaltaro** [comment]
Ohh, only now I see we go through the BossAir API. I was even considering using this PyCondor API for that:
https://github.com/dmwm/WMCore/blob/c816d945cde7a32b62f6537e53ed17c42d3f7994/src/python/WMCore/Services/PyCondor/PyCondorAPI.py#L78

but keeping the current logic which looks up the submission plugin, creates an instance of it during runtime, and changes the priority is indeed the best approach here.

Regarding the formula, it depends on the job type (taskPriority), which has the lowest priority in the system (thus, multiplying factor equals 0), as defined here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/CreateWMBSBase.py#L504-L505
so we can likely simply keep the same formula, which will be equivalent to:
```
newPriority = int(kwargs['requestPriority'])
```

how to deal with those parameters and query constraints - keeping it consistent with the interface and other plugins - is something that is not clear to me yet.
