### ISSUE TITLE
MSTransferor fails to send alerts through Alertmanager

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10464]
**Impact of the bug**
MStransferor

**Describe the bug**
Following the lead from this Jira ticket [1] we figured out that in some cases MSTransferor fails to send alerts through the newly established mechanism with the AlertManager as a mediator for the alerts.   

Based on the trace provided in the Jira ticket [3] the MSTransferror is just trying to generate an alert for a big dataset (nothing unusual so far), but the url to the Alertmanager itself has been lost somewhere on the way. As mentioned also in this stackoverflow reply [2] this type of badly expressed error is generated by `pycurl` when the url is `None`. I hope this is lost somewhere up in the chain but not in the `@portForward` decorator.

Another critical question that needs to be answered is whether MSTransferor keeps creating input rules over and over for the same input data, similarly to a previously observed cases. 

**How to reproduce it**
To be investigated what exactly has triggered the bug.

**Expected behavior**

**Additional context and error message**
[1]
https://its.cern.ch/jira/browse/CMSCOMPPR-18772

[2]
https://stackoverflow.com/a/34402229

[3]
```
2021-04-21 06:14:09,570:ERROR:MSTransferor: Unknown exception while making Transfer Request for pdmvserv_task_TOP-RunIISummer20UL17MiniAODv2-00043__v1_T_210414_061607_9526     Error: unsetopt() is not supported for this option
Traceback (most recent call last):
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 208, in execute
    success, transfers = self.makeTransferRequest(wflow)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 628, in makeTransferRequest
    blocks, dataSize, nodes, idx)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 727, in makeTransferRucio
    self.notifyLargeData(aboveWarningThreshold, transferId, wflow.getName(), dataSize, dataIn)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 755, in notifyLargeData
    self.alertManagerApi.sendAlert(alertName, alertSeverity, alertSummary, alertDescription, self.alertServiceName)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/AlertManager/AlertManagerAPI.py", line 93, in sendAlert
    res = self.mgr.getdata(self.alertManagerUrl, params=params, headers=self.headers, verb='POST')
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 316, in getdata
    encode=encode, decode=decode, cookie=cookie)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 280, in request
    verbose, verb, doseq, encode, cainfo, cookie)
  File "/data/srv/HG2104e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.7.pre8/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 221, in set_opts
    curl.setopt(pycurl.URL, encodeUnicodeToBytes(url))
TypeError: unsetopt() is not supported for this option
```

**Comment by todor-ivanov** [comment]
The bad news is that the so mentioned Error is repeated every 10 min. If it is preceded  by any and what type of rule creation is still to be investigated.

**Comment by vkuznet** [comment]
Todor, I still can't understand the real issue here, but looking at traceback I can see that your codebase is stateful, e.g. it uses  `self.alertManagerUrl` member data. If you run multithreaded code, or pass object around its member data may be overwritten, lost, whatever. Without knowing default constructor of the class and how you initialize it, it is hard to say what is the value of url you trying to reach. My suggestion check the class itself and how it is initialized. Better, do not create class with url which makes it stateful. Instead make class that it will accept url and input data to send to. Then you can use stateless class instance and pass around url and JSON payload.

**Comment by todor-ivanov** [comment]
Hi @vkuznet ,
Thanks for the feedback. This:
> If you run multithreaded code, or pass object around its member data may be overwritten, lost, whatever

is kind of surprising to me. I was not aware it may happen for a uniquely defined value in the object. I may expect other kind of conditions that could lead to such member data loss regarding volatile data in the object, but this is a value set at the construction time and never attempted to be changed any more [1]. 

> Better, do not create class with url which makes it stateful. Instead make class that it will accept url and input data to send to

IIUC our case is more or less what you mean here. The `AlerManagerUrl` is supposed to be fetched from `msConfig` in our case. And indeed that is the cause of the error in the current case. The url is missing from the configuration: [2], because we somehow forgot that configuration change during the last deployment. Which leads me to my next question. What should that url be? :smile: 


[1]
https://github.com/dmwm/WMCore/blob/5da7f3c898bb39cdb7efb64070af182419501602/src/python/WMCore/Services/AlertManager/AlertManagerAPI.py#L22-L23

[2]
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/reqmgr2ms-transferor/config-transferor.py
