### ISSUE TITLE
Decouple Couchapp from the CouchDB spec

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10489]
**Impact of the new feature**
Most of the WMCore services

**Is your feature request related to a problem? Please describe.**
As we migrate to python3, a hard coupling dependency was spotted in the couchdb15 spec file:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/couchdb15.spec#L39

This is a problem for the other services depending on the CouchDB spec, because it will bring in some of the python2 libraries  as well. So, it's not a problem if we are building a service on python2, but it will be if we build a service on python3, since there would be a mix of python2 and python3 libraries in the path (including the python binary itself).

**Describe the solution you'd like**
The final implementation is yet to be found, however, the required solution is to stop shipping python-related libraries with the CouchDB spec file, such that it does not cause any side effects on our WMCore services.

This would work fine for WMAgent, by adding the cmscouchapp dependency to the WMAgent spec file (since the agent and couchdb run on the same node). However, it would be a problem for central services, since those would no longer have the CMSCouchapp library in the same node, making it not possible to deploy central couchapps.

**Describe alternatives you've considered**
Alternative 1:
* make sure that we migrate ALL the services depending on CouchDB to python3 "at the same time". Very hard to accomplish, but the cleanest!
Alternative 2:
* create a new spec file for couchdb, which would bring in the python3 CMSCouchapp library. We might have to create new deployment scripts as well

**Additional context**
Some information in: https://github.com/dmwm/WMCore/issues/10303

**Comment by amaltaro** [comment]
Just found out why we are not able to push couchapps from the WMAgent python3 environment:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/spidermonkey.spec#L5

this dependency is bringing in python2 and setuptools, which mess up with the agent environment and fail to init the agent with:
```
cmst1@vocms0262:/data/srv/wmagent/current $ $manage init-agent
Initialising Agent...
/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/external/python/2.7.13-comp2/bin/python
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/bin/wmagent-mod-config", line 14, in <module>
    standard_library.install_aliases()
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/external/py3-future/0.18.2/lib/python3.8/site-packages/future/standard_library/__init__.py", line 453, in install_aliases
    __import__(newmodname)
ImportError: No module named reprlib
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/bin/wmcore-db-init", line 19, in <module>
    from WMCore.Configuration import loadConfigurationFile
ImportError: No module named WMCore.Configuration
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/bin/wmagent-couchapp-init", line 10, in <module>
    standard_library.install_aliases()
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/external/py3-future/0.18.2/lib/python3.8/site-packages/future/standard_library/__init__.py", line 453, in install_aliases
    __import__(newmodname)
ImportError: No module named reprlib
```

**Comment by amaltaro** [comment]
And here is yet another spec bringing in python2 dependencies (python and setuptools):
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condor.spec#L10

I'm testing a few local changes for these two specs.

**Comment by amaltaro** [comment]
This issue has been resolved with: https://github.com/cms-sw/cmsdist/pull/6919

which provides a new spec file: `couchdb16.spec`, shipping the python3 version of CMSCouchapp (instead of python2). Closing.
