### ISSUE TITLE
[py2py3] Python3 list sort built-in takes no positional arguments

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10505]
**Impact of the bug**
WMCore in general

**Describe the bug**
Another popular issue while integrating python3 unit tests in our jenkins CI.
Python3 list `sort` built-in does not take any positional arguments, where many of our MySQL bind handling fails, see [1]

**How to reproduce it**
Run the DBSBufferFile unit test provided in the details

**Expected behavior**
List sorting functionality should remain intact and work in both python2 and python3 :-D

**Additional context and error message**
Documentation: https://docs.python.org/3.8/library/stdtypes.html#list.sort

[1]
```
======================================================================
ERROR: _testProperties_
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMComponent_t/DBS3Buffer_t/DBSBufferFile_t.py", line 41, in setUp
    locationAction.execute(siteName="se1.cern.ch")
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMComponent/DBS3Buffer/MySQL/DBSBufferFiles/AddLocation.py", line 23, in execute
    self.dbi.processData(self.sql, binds, conn = conn,
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Database/DBCore.py", line 172, in processData
    r = self.executebinds(s, b, connection=connection,
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Database/MySQLCore.py", line 126, in executebinds
    s, b = self.substitute(s, b)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Database/MySQLCore.py", line 77, in substitute
    bindVarNames.sort(stringLengthCompare)
TypeError: sort() takes no positional arguments
-------------------- >> begin captured logging << --------------------
root: DEBUG: Tables for WMComponent.DBS3Buffer created
--------------------- >> end captured logging << ---------------------
```

**Comment by amaltaro** [comment]
Instead of creating a new issue, let me reopen this one.
JobCreatorPoller ParentlessMergeBySize algorithm crashes when sorting its input files (dict objects). Traceback from Py3 WMAgent 1.5.2.pre1 is:
```
2021-08-08 23:38:42,204:140056173451008:INFO:JobCreatorPoller:Found end in iteration over subscription 296
2021-08-08 23:38:42,276:140056173451008:ERROR:JobCreatorPoller:Failed to execute JobCreator. Error: sort() takes no positional arguments
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 420, in algorithm
    self.pollSubscriptions()
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 555, in pollSubscriptions
    wmbsJobGroups = next(jobSplittingFunction)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 93, in runSplitter
    groups = jobFactory(**splitParams)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/JobSplitting/JobFactory.py", line 96, in __call__
    self.algorithm(*args, **kwargs)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/JobSplitting/ParentlessMergeBySize.py", line 210, in algorithm
    self.defineMergeJobs(groupedFiles[pnn])
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/JobSplitting/ParentlessMergeBySize.py", line 126, in defineMergeJobs
    mergeableFiles.sort(fileCompare)
TypeError: sort() takes no positional arguments
```

I will try getting a quick fix in for this one, just so I can resume testing the agent. However, we should scan WMCore code for other places where we can have the same exception and get those fixed as well.

**Comment by mapellidario** [comment]
(changing the assignees to better reflect who is working on this topic today)

**Comment by mapellidario** [comment]
Hello @amaltaro!

> However, we should scan WMCore code for other places where we can have the same exception and get those fixed as well.

I had a quick search with this regex `[.]sort[(].*[)]` (trying to use a simple and as generic as possible one) and there is only one instance in which we do not use the keyword arguments (that is not already covered by Eric in #10720 ):

https://github.com/dmwm/WMCore/blob/74bd93ca5ebd50c7b84e72223074ef7945dfce21/src/python/WMCore/REST/Server.py#L188-L191

Should I create a new issue or should we ask Eric's (our current sorting ninja) if he wants to have a look and add it to his PR?

FYI: @goughes

**Comment by amaltaro** [comment]
@mapellidario Dario, thanks for checking this. I guess I can create a PR request fixing it (this issue).

**Comment by amaltaro** [comment]
As discussed over slack, I hand this one back to you Dario @mapellidario ;)
