### ISSUE TITLE
[py2py3] Python3 does not have an 'exceptions' module

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10513]
**Impact of the bug**
WMCore in general

**Describe the bug**
Some of the python3 unit tests crash when importing `exceptions` module, see the full traceback in [1]

**How to reproduce it**
```
nosetests test/python/WMCore_t/WMSpec_t/Steps_t/Executors_t/LogArch_t.py
```

**Expected behavior**
Exception handling should be functional and consistent in python2 and python3.

**Additional context and error message**
[1]
```
======================================================================
ERROR: testUnitTestBackend (WMCore_t.WMSpec_t.Steps_t.Executors_t.LogArch_t.LogArchiveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/WMSpec_t/Steps_t/Executors_t/LogArch_t.py", line 119, in setUp
    taskMaker.processWorkload()
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMSpec/Makers/TaskMaker.py", line 127, in processWorkload
    sandboxCreator.makeSandbox(self.workdir, self.workload)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMRuntime/SandboxCreator.py", line 108, in makeSandbox
    fetcherInstances = list(map(getFetcher, fetcherNames))
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMSpec/Steps/StepFactory.py", line 196, in getFetcher
    return _FetcherFactory.loadObject(fetcherName)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMFactory.py", line 58, in loadObject
    module = __import__(module, globals(), locals(), [classname])
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 17, in <module>
    from WMCore.Services.DBS.DBSReader import DBSReader
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Services/DBS/DBSReader.py", line 9, in <module>
    from WMCore.Services.DBS.DBSErrors import DBSReaderError
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Services/DBS/DBSErrors.py", line 4, in <module>
    from WMCore.Services.DBS.ProdException import ProdException
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Services/DBS/ProdException.py", line 11, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
```

**Comment by mapellidario** [comment]
I remember having already encountered something like this. I can look for it, but if I am not mistaken simply removing the import and using directly `Exception`, which being a built-in should be readily available without any explicit import, should be enough. 

Otherwise, I think that the solution provided by [this answer in stackoverflow](https://stackoverflow.com/a/27030934) should work

**Comment by todor-ivanov** [comment]
grepping through the code I actually found few more imports of `exceptions` [1], but reading the code they seem to be just imported but never used... So I am fixing those too.



[1]
```
:WMCore$ grep -rin -E "(.*import.*exceptions|.*exceptions.*import)" --exclude=*~ --exclude=*.pyc src/python/ test/ |grep -i -v "from WMCore" |grep -v "import HTTPError" |grep -v "from dbs.exceptions" |grep -i exceptio
src/python/WMCore/Services/DBS/ProdException.py:11:import exceptions
src/python/WMCore/WMSpec/Makers/Handlers/MakeJob.py:14:import exceptions
src/python/WMCore/WMSpec/Makers/Handlers/MakeJobSlave.py:29:import exceptions
src/python/WMComponent/DBS3Buffer/Oracle/ListRunsWorkflow.py:11:import exceptions
```

**Comment by todor-ivanov** [comment]
Once I've passed beyond that error, I just hit another one... [1]. For which I have a vague memory about having it solved before, but for sure do not remember where and in what context.

FYI @amaltaro 


[1]
```
======================================================================
ERROR: testOnWorkerNodes (WMCore_t.WMSpec_t.Steps_t.Executors_t.LogArch_t.otherLogArchiveTexst)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/WMSpec_t/Steps_t/Executors_t/LogArch_t.py", line 288, in setUp
    taskMaker.processWorkload()
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMSpec/Makers/TaskMaker.py", line 127, in processWorkload
    sandboxCreator.makeSandbox(self.workdir, self.workload)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMRuntime/SandboxCreator.py", line 108, in makeSandbox
    fetcherInstances = list(map(getFetcher, fetcherNames))
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMSpec/Steps/StepFactory.py", line 196, in getFetcher
    return _FetcherFactory.loadObject(fetcherName)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMFactory.py", line 58, in loadObject
    module = __import__(module, globals(), locals(), [classname])
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 18, in <module>
    from WMCore.Services.Rucio.Rucio import Rucio
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Services/Rucio/Rucio.py", line 17, in <module>
    from rucio.client import Client
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.24.2.post1-comp/lib/python3.8/site-packages/rucio/client/__init__.py", line 20, in <module>
    from .client import Client  # noqa: F401
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.24.2.post1-comp/lib/python3.8/site-packages/rucio/client/client.py", line 30, in <module>
    from rucio.client.accountclient import AccountClient
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.24.2.post1-comp/lib/python3.8/site-packages/rucio/client/accountclient.py", line 39, in <module>
    from rucio.client.baseclient import BaseClient
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.24.2.post1-comp/lib/python3.8/site-packages/rucio/client/baseclient.py", line 66, in <module>
    from rucio.common.utils import build_url, get_tmp_dir, my_key_generator, parse_response, ssh_sign, setup_logger
  File "/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.24.2.post1-comp/lib/python3.8/site-packages/rucio/common/utils.py", line 107, in <module>
    imp.find_module(extra_module)
NameError: name 'imp' is not defined

----------------------------------------------------------------------

```

**Comment by todor-ivanov** [comment]
Thanks @mapellidario
