### ISSUE TITLE
[py2py3] Python3 pyexpat.xmlparser has no attribute returns_unicode

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10516]
**Impact of the bug**
WMCore

**Describe the bug**
Python3 unit tests complain about an attribute that does not exist in the `pyexpat.xmlparser` python3 library, full traceback in [1].

**How to reproduce it**
```
nosetests test/python/WMCore_t/Storage_t/TrivialFileCatalog_t.py
```

**Expected behavior**
Find a solution that works both in python2 and python3, consistently. If we have to drop that attribute and deal with byte strings, it should be fine as well. Best approach is yet to be defined.

**Additional context and error message**
[1]
```
======================================================================
ERROR: testMultipleRegexMatch (WMCore_t.Storage_t.TrivialFileCatalog_t.TrivialFileCatalogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Storage/TrivialFileCatalog.py", line 214, in readTFC
    node = xmlFileToNode(filename)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Algorithms/ParseXMLFile.py", line 64, in xmlFileToNode
    expat_parse(open(reportFile, 'r'),
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Algorithms/ParseXMLFile.py", line 79, in expat_parse
    parser.returns_unicode = False
AttributeError: 'pyexpat.xmlparser' object has no attribute 'returns_unicode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Storage_t/TrivialFileCatalog_t.py", line 161, in testMultipleRegexMatch
    tfc = readTFC(tfc_file)
  File "/home/dmwm/wmcore_unittest/WMCore/src/python/WMCore/Storage/TrivialFileCatalog.py", line 218, in readTFC
    raise RuntimeError(msg)
RuntimeError: Error reading TrivialFileCatalog: /home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Storage_t/T2_CH_CERNBOX_TrivialFileCatalog.xml
'pyexpat.xmlparser' object has no attribute 'returns_unicode'
```

**Comment by amaltaro** [comment]
It has been apparently fixed by Todor's PR: https://github.com/dmwm/WMCore/pull/10571

I ran these tests a couple of times in the python3 environment and they all pass, including in jenkins report. Closing it.
