### ISSUE TITLE
[py2py3] Oracle Python3 unit tests fail with ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10512]
**Impact of the bug**
WMAgent / unittests

**Describe the bug**
This issue happens with the unit tests, but it will very likely happen to the agent itself when it goes through its standard deployment.

If you have a Python3 WMCore setup with Oracle backend instead of MySQL, you will see many unit tests failing to connect to the database with that TNS error:
```
root: DEBUG: (cx_Oracle.DatabaseError) ORA-12541: TNS:no listener
```

full traceback can be found here [1].

**How to reproduce it**
```
nosetests test/python/WMCore_t/WMBS_t/Subscription_t.py
```

**Expected behavior**
Interactions with Oracle database should work either in python2 and python3.

**Additional context and error message**
BTW, I can properly connect to the database - from the same node/environment - via `sqlplus`.

[1]
```
======================================================================
ERROR: _testGetSubTypes_
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/amaltaro/wmagent/wmcore_unittest/WMCore/test/python/WMCore_t/WMBS_t/Subscription_t.py", line 36, in setUp
    self.testInit.setSchema(customModules=["WMCore.WMBS"],
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre3/lib/python3.8/site-packages/WMQuality/TestInit.py", line 199, in setSchema
    raise ex
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre3/lib/python3.8/site-packages/WMQuality/TestInit.py", line 196, in setSchema
    self.init.setSchema(modules, params = params)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre3/lib/python3.8/site-packages/WMCore/WMInit.py", line 160, in setSchema
    myThread.transaction.begin()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre3/lib/python3.8/site-packages/WMCore/Database/Transaction.py", line 32, in begin
    self.conn = self.dbi.connection()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre3/lib/python3.8/site-packages/WMCore/Database/DBCore.py", line 120, in connection
    return self.engine.connect()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2193, in connect
    return self._connection_cls(self, **kwargs)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2292, in raw_connection
    return self._wrap_pool_connect(
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/data/amaltaro/wmagent/unittestdeploy/wmagent/1.4.9.pre3/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-12541: TNS:no listener
(Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by amaltaro** [comment]
Rookie mistake! I made the wrong configuration change, that's why it was complaining about TNS. I have just fixed that and now I can run tests in python3 + oracle :-D

Closing
