### ISSUE TITLE
Requests stuck in staged state for weeks

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10510]
**Impact of the bug**
Requests stuck in staged state for weeks

**Describe the bug**
There are 10 requests stuck in `staged` state for weeks: https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?stuck_state=staged&stuck_min=21 It might be an indication for a bug in work-queue

**How to reproduce it**
Check the request logs

**Expected behavior**
They should not get stuck in this state for days

**Additional context and error message**
None

**Comment by amaltaro** [comment]
@haozturk Hasan, thanks for creating this ticket. I did not manage to get to it today, but will look into it first thing tomorrow morning.

**Comment by amaltaro** [comment]
@haozturk I randomly picked the first workflow:
pdmvserv_task_B2G-RunIISummer20UL18MiniAODv2-00472__v1_T_210327_075920_7924

and it's actually failing to be acquired in Global WorkQueue. The reason/traceback is provided in [1].

Translating that traceback, that block is known by DBS (and it has valid files):
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?block_name=/NMSSM_XtoHYto4b_MX_2400_MY_40_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM%237779de7a-4342-46a7-8c81-510a8653b6e6

while Rucio doesn't know anything about it:
```
amaltaro@lxplus7121:~ $ rucio list-dataset-replicas cms:/NMSSM_XtoHYto4b_MX_2400_MY_40_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM#7779de7a-4342-46a7-8c81-510a8653b6e6
2021-05-28 20:52:36,434	ERROR	Data identifier not found.
Details: Data identifier 'cms:/NMSSM_XtoHYto4b_MX_2400_MY_40_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM#7779de7a-4342-46a7-8c81-510a8653b6e6' not found
```

So, it's an inconsistency between DBS and Rucio, where either:
a) things were invalidated in Rucio but not in DBS
b) things were injected into DBS but never into Rucio
c) or maybe, this file was injected into PhEDEx back then(?)

[1]
```
2021-05-28 00:02:22,616:INFO:WorkQueue:Splitting /pdmvserv_task_B2G-RunIISummer20UL18MiniAODv2-00472__v1_T_210327_075920_7924/B2G-RunIISummer20UL18MiniAODv2-00472_0 with policy Block params = {'ResubmitBlock': {'args': {}, 'name': 'ResubmitBlock'}, 'MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Block'}}
2021-05-28 00:02:25,559:ERROR:Rucio:Data identifier not found in Rucio: /NMSSM_XtoHYto4b_MX_2400_MY_40_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM#7779de7a-4342-46a7-8c81-510a8653b6e6. Error: Data identifier not found.
Details: Data identifier 'cms:/NMSSM_XtoHYto4b_MX_2400_MY_40_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM#7779de7a-4342-46a7-8c81-510a8653b6e6' not found
2021-05-28 00:02:25,561:ERROR:WorkQueue:Exception splitting wqe pdmvserv_task_B2G-RunIISummer20UL18MiniAODv2-00472__v1_T_210327_075920_7924 for pdmvserv_task_B2G-RunIISummer20UL18MiniAODv2-00472__v1_T_210327_075920_7924: 'length'
Traceback (most recent call last):
  File "/data/srv/HG2105d/sw/slc7_amd64_gcc630/cms/workqueue/1.4.8.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1150, in processInboundWork
    continuous=continuous, rucioObj=rucioObj)
  File "/data/srv/HG2105d/sw/slc7_amd64_gcc630/cms/workqueue/1.4.8.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1092, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/data/srv/HG2105d/sw/slc7_amd64_gcc630/cms/workqueue/1.4.8.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 160, in __call__
    self.split()
  File "/data/srv/HG2105d/sw/slc7_amd64_gcc630/cms/workqueue/1.4.8.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 35, in split
    for block in self.validBlocks(self.initialTask, dbs):
  File "/data/srv/HG2105d/sw/slc7_amd64_gcc630/cms/workqueue/1.4.8.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 122, in validBlocks
    block = self._getBlockSummary(dbs, datasetPath, blockName)
  File "/data/srv/HG2105d/sw/slc7_amd64_gcc630/cms/workqueue/1.4.8.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 226, in _getBlockSummary
    if not blockRucio['length']:
KeyError: 'length'
```

**Comment by amaltaro** [comment]
Anyways, it should have been fixed by this PR: https://github.com/dmwm/WMCore/pull/10342
but I just noticed I made one mistake in line 226, sorry about that.

I'll get it fixed on Monday, but until it gets deployed to production, the best would be to follow up with the DM team and get those blocks invalidated in DBS as well (if no replicas are available in the system).

**Comment by flgomezc** [comment]
Hi @amaltaro @haozturk,
The dataset you mentioned has two records in rucio list-rules-history:

```
$ rucio list-rules-history cms:/NMSSM_XtoHYto4b_MX_2400_MY_40_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18RECO-106X_upgrade2018_realistic_v11_L1v1-v2/AODSIM#7779de7a-4342-46a7-8c81-510a8653b6e6
----------------------------------------
Rule insertion
Account : wma_prod
RSE expression : T2_CH_CERN
Time : 2021-01-29 16:23:18
----------------------------------------
Rule deletion
Account : wma_prod
RSE expression : T2_CH_CERN
Time : 2021-01-29 22:34:38

```
The rule existed just a few hours

**Comment by haozturk** [comment]
Hi @amaltaro all the requests are moved from staged, thanks a lot for the fix.
