### ISSUE TITLE
SetupCMSSWPSet bug when creating some T0 processes  

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10526]
**Impact of the bug**
Some (non merge or Repack) T0 processes fail with the current implementation of the createProcess method in [SetupCMSSWPset.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py)

**Describe the bug**
Arguments are not properly passed for certain scenarios during the creation of certain processed and fail

**How to reproduce it**
Submit e.g.: AlCaTestEnable process

**Expected behavior**
Process should be created properly

**Additional context and error message**
WMAgent fails when invoking the following script, due to lack of arguments for the function:
```
cmssw_wm_create_process.py --output_pkl PSet_out.pkl --funcname expressProcessing --funcargs process_funcArgs.json 
Failed to load process from Scenario AlCaTestEnable (<Configuration.DataProcessing.Impl.AlCaTestEnable.AlCaTestEnable object at 0x7f0303ba2750>).
Traceback (most recent call last):
  File "cmssw_wm_create_process.py", line 127, in <module>
    main()
  File "cmssw_wm_create_process.py", line 118, in main
    process=create_process(args, func_args)
  File "cmssw_wm_create_process.py", line 80, in create_process
    raise ex
TypeError: expressProcessing() takes exactly 2 arguments (1 given)
```

**Comment by khurtado** [comment]
@amaltaro @todor-ivanov This is the issue I talked to you about this morning. The PR linked to the issue should fix it, but we need to double check with the T0 team it really does, as it hasn't been tested yet (only interactively). This requires a fix in the script below first, that needs to be pushed on github and propagated in CVMFS before running the tests.

https://github.com/cms-sw/cmssw-wm-tools/blob/master/bin/cmssw_wm_create_process.py
