### ISSUE TITLE
Replace pep8 by pycodestyle in the CI setup and wmcore devtools packages

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10559]
**Impact of the new feature**
Specs and Jenkins CI

**Is your feature request related to a problem? Please describe.**
When running `pep8` checks from our python3 stack, it prints the following deprecation warning
```
/home/dmwm/unittestdeploy/wmagent/1.4.9.pre3-comp/sw/slc7_amd64_gcc630/external/py3-pep8/1.7.1/lib/python3.8/site-packages/pep8.py:2124: UserWarning: 

pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.

$ pip install pycodestyle
$ pycodestyle ...
```

**Describe the solution you'd like**
Replace the `pep8` package by `pycodestyle`, in our WMCore python3 stack. If it's also available for python2, then we should perform the same switch.

Once a new RPM is made available with this new library, we also need to update the Jenkins jobs. It should be `DMWM-WMCore-PR-pylint*` jobs.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by amaltaro** [comment]
Making it a high priority because the `pep8` checks are actually failing now, see this build log:
https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCore-PR-pylintpy3/lastBuild/console

which shows this crash:
```
*** Running Pylint on the changed files against the feature branch
Traceback (most recent call last):
  File "./pep8", line 16, in <module>
    from pkg_resources import load_entry_point
  File "/home/dmwm/unittestdeploy/wmagent/2.0.1/sw/slc7_amd64_gcc630/external/py3-setuptools/51.3.3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
```

Looking into `pep8` that we have inside our wmagent container, this is what I get:
```
[dmwm@3b5a9aec6813 WMCore]$ pep8 --version
/home/dmwm/unittestdeploy/wmagent/2.0.1/sw/slc7_amd64_gcc630/external/py3-pep8/1.7.1-comp/lib/python3.8/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
/home/dmwm/unittestdeploy/wmagent/2.0.1/sw/slc7_amd64_gcc630/external/py3-pep8/1.7.1-comp/lib/python3.8/site-packages/pep8.py:2123: UserWarning: 

pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.

$ pip install pycodestyle
$ pycodestyle ...

  warnings.warn(
1.7.1
```
