### ISSUE TITLE
[py2py3] WMAgent Py3 AgentStatusWatcher failing to calculate disk usage

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10634]
**Impact of the bug**
PY3 WMAgent

**Describe the bug**
Testing wmagentpy3 1.5.0.pre3 (plus some patches), we manage to run services + components, but there are exceptions being recorded in the AgentStatusWatcher logs, usual bytes vs text string issues. See traceback in [1]

**How to reproduce it**
See above

**Expected behavior**
This TypeError needs to be fixed - compatible for both python versions - and the AgentStatusWatcher component should be running without any issues.

**Additional context and error message**
[1]
```
2021-06-28 15:06:27,200:140063939860224:INFO:DrainStatusPoller:Agent not in drain mode. Resetting flags and skipping drain check...
2021-06-28 15:06:27,200:140063939860224:INFO:BaseWorkerThread:DrainStatusPoller took 0.048 secs to execute
2021-06-28 15:06:27,517:140063948252928:INFO:Grafana:Calling API: https://monit-grafana.cern.ch/api/datasources/proxy/9475/_msearch with query: ('{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["monit_prod_cmssst_*"]}\n'
 '{"size":500,"query":{"bool":{"filter":[{"range":{"metadata.timestamp":{"gte":"now-1d","lte":"now","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"metadata.type: '
 'ssbmetric AND metadata.type_prefix:raw AND metadata.path: '
 'sts15min"}}]}},"sort":{"metadata.timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"docvalue_fields":["metadata.timestamp"]}\n')
2021-06-28 15:06:27,571:140063956645632:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 139, in algorithm
    agentInfo = self.collectAgentInfo()
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 213, in collectAgentInfo
    agentInfo['disk_warning'] = listDiskUsageOverThreshold(self.config, updateDB=True)
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 404, in listDiskUsageOverThreshold
    diskUseList = diskUse()
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/Utils/Utilities.py", line 96, in diskUse
    output = df.communicate()[0].split("\n")
TypeError: a bytes-like object is required, not 'str'
2021-06-28 15:06:27,573:140063956645632:INFO:BaseWorkerThread:AgentStatusPoller took 0.822 secs to execute
```

**Comment by mapellidario** [comment]
Before opening a PR, try just to change in your env

```diff
- output = df.communicate()[0].split("\n")
+ output = df.communicate()[0].split(b"\n")
```

**Comment by amaltaro** [comment]
Thanks, Dario. I took a similar approach ;-)

After fixing the issue reported above, here is the next one:
```
2021-06-28 18:15:26,493:140074019202816:INFO:BaseWorkerThread:ResourceControlUpdater took 0.420 secs to execute
2021-06-28 18:15:26,852:140074027595520:INFO:AgentStatusPoller:Getting agent info ...
2021-06-28 18:15:27,489:140074027595520:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: argument should be integer or bytes-like object, not 'str'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 139, in algorithm
    agentInfo = self.collectAgentInfo()
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 229, in collectAgentInfo
    couchProc = numberCouchProcess()
  File "/data/srv/wmagent/v1.5.0.pre3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.0.pre3/lib/python3.8/site-packages/Utils/Utilities.py", line 111, in numberCouchProcess
    process = ps.communicate()[0].count('couchjs')
TypeError: argument should be integer or bytes-like object, not 'str'
2021-06-28 18:15:27,490:140074027595520:INFO:BaseWorkerThread:AgentStatusPoller took 0.638 secs to execute
```

working on it.

**Comment by amaltaro** [comment]
Oups, yet another error:
```
2021-06-28 18:40:20,806:140147165435648:INFO:AgentStatusPoller:Local WorkQueue data collected in: 0 secs
2021-06-28 18:40:20,829:140147165435648:ERROR:AgentStatusPoller:Failed to upload agent statistics to WMStats. Error: keys must be str, int, float, bool or None, not bytes
```
