### ISSUE TITLE
Python3 ReqMgr2 fails to set pickledarguments during assignment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10647]
**Impact of the bug**
ReqMgr2

**Describe the bug**
Note that this seem to be a rare case, since I managed to inject all the DMWM/Integration tests and a few old requests already. However, when I try to assign this workflow:
amaltaro_SC_ReDigi_Harvest_Agent136_Val_200814_105846_7752

it fails with a `400 Bad Request`. The logs extracted from ReqMgr2 testbed POD can be seen in [1]

**How to reproduce it**
Not sure, there must be something very peculiar about this one workflow(!)

**Expected behavior**
Python3 pickle requires data to be a bytes-like object, instead of python3 str. So we should encode the data we pass over to that pickle.loads call.

**Additional context and error message**
[1]
```
[30/Jun/2021:09:12:11]  Updating request "amaltaro_SC_ReDigi_Harvest_Agent136_Val_200814_105846_7752" with these user-provided args: {'SoftTimeout': 129600, 'UnmergedLFNBase': '/store/unmerged', 'TrustPUSitelists': True, 'GracePeriod': 30
0, 'SiteWhitelist': ['T1_US_FNAL', 'T2_CH_CERN'], 'MergedLFNBase': '/store/backfill/1', 'Team': 'testbed-vocms0193', 'ProcessingVersion': 21, 'TrustSitelists': False, 'ProcessingString': 'HG2107_Val_OLD_Alanv3', 'Dashboard': 'test', 'Site
Blacklist': [], 'Override': {'eos-lfn-prefix': 'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/TESTBED'}, 'AcquisitionEra': 'CMSSW_10_6_1', 'RequestStatus': 'assigned'}
Getting from Cache due to: CouchNotFoundError - reason: Object Not Found, data: {} result: None
[30/Jun/2021:09:12:11]  Assign request amaltaro_SC_ReDigi_Harvest_Agent136_Val_200814_105846_7752, input args: {'SoftTimeout': 129600, 'UnmergedLFNBase': '/store/unmerged', 'TrustPUSitelists': True, 'GracePeriod': 300, 'SiteWhitelist': ['
T1_US_FNAL', 'T2_CH_CERN'], 'MergedLFNBase': '/store/backfill/1', 'Team': 'testbed-vocms0193', 'ProcessingVersion': 21, 'TrustSitelists': False, 'ProcessingString': 'HG2107_Val_OLD_Alanv3', 'Dashboard': 'test', 'SiteBlacklist': [], 'Overr
ide': {'eos-lfn-prefix': 'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/TESTBED'}, 'AcquisitionEra': 'CMSSW_10_6_1', 'RequestStatus': 'assigned', 'HardTimeout': 129900} ...
[30/Jun/2021:09:12:11]  Error for request args {'SoftTimeout': 129600, 'UnmergedLFNBase': '/store/unmerged', 'TrustPUSitelists': True, 'GracePeriod': 300, 'SiteWhitelist': ['T1_US_FNAL', 'T2_CH_CERN'], 'MergedLFNBase': '/store/backfill/1'
, 'Team': 'testbed-vocms0193', 'ProcessingVersion': 21, 'TrustSitelists': False, 'ProcessingString': 'HG2107_Val_OLD_Alanv3', 'Dashboard': 'test', 'SiteBlacklist': [], 'Override': {'eos-lfn-prefix': 'root://eoscms.cern.ch//eos/cms/store/l
ogs/prod/recent/TESTBED'}, 'AcquisitionEra': 'CMSSW_10_6_1', 'RequestStatus': 'assigned', 'HardTimeout': 129900, 'EventStreams': 0, 'CustodialSites': [], 'NonCustodialSites': [], 'AutoApproveSubscriptionSites': [], 'CustodialSubType': 'Re
plica', 'NonCustodialSubType': 'Replica', 'CustodialGroup': 'DataOps', 'NonCustodialGroup': 'DataOps', 'SubscriptionPriority': 'Low', 'DeleteFromSource': False, 'MinMergeSize': 2147483648, 'MaxMergeSize': 4294967296, 'MaxWaitTime': 86400,
 'MaxMergeEvents': 100000000, 'AllowOpportunistic': False, 'BlockCloseMaxWaitTime': 66400, 'BlockCloseMaxFiles': 500, 'BlockCloseMaxEvents': 25000000, 'BlockCloseMaxSize': 5000000000000, 'ChainParentageMap': {}}: Traceback (most recent ca
ll last):
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/ReqMgr/Service/Request.py", line 436, in _handleAssignmentStateTransition
    workload.updateArguments(request_args)
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkload.py", line 1969, in updateArguments
    self.setLFNBase(kwargs["MergedLFNBase"], kwargs["UnmergedLFNBase"])
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkload.py", line 1154, in setLFNBase
    self.updateLFNsAndDatasets(runNumber=runNumber)
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkload.py", line 806, in updateLFNsAndDatasets
    task.updateLFNsAndDatasets(runNumber=runNumber)
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/WMTask.py", line 1783, in updateLFNsAndDatasets
    task.updateLFNsAndDatasets(runNumber=runNumber)
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/WMTask.py", line 1774, in updateLFNsAndDatasets
    self.updateDatasetName(datasetName)
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/WMTask.py", line 1801, in updateDatasetName
    cmsswHelper.setDatasetName(datasetName)
  File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/WMSpec/Steps/Templates/CMSSW.py", line 241, in setDatasetName
    args = pickle.loads(self.data.application.configuration.pickledarguments)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by amaltaro** [comment]
I think this is caused because we actually have the `pickledarguments` inside a pickle object, in the pickledarguments is another pickle object that has been written with `str` object.

This is the outcome of a python2 pickle.dumps:
```
In [10]: pickle.dumps(dd, protocol=0)
Out[10]: "(dp0\nS'datasetName'\np1\nS'alan'\np2\ns."
```

while, in python3 it looks like:
```
In [8]: pickle.dumps(dd, protocol=0)
Out[8]: b'(dp0\nVdatasetName\np1\nValan\np2\ns.'
```

and if we get the output of the python2 dumps, and try to load that in python3, the same failure is reproduced.

I'm still surprised that it happened to only one old workflow, out of ~10 that I successfully assigned.

**Comment by amaltaro** [comment]
I'm going to reopen this issue because now there is a failure during the job runtime when loading this pickledarguments.

Problem spotted with Py3 WMAgent 1.5.3.pre3, running a workflow created in 2020:
amaltaro_TaskChain_MC_April2020_Val_200421_090840_7165

traceback is:
```
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 740, in __call__
  File "/srv/job/PSetTweaks/WMTweak.py", line 391, in makeTaskTweak
    args = pickle.loads(stepSection.application.configuration.pickledarguments)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python3/3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python3/3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 118, in <module>
RuntimeError: Error invoking script for step WMTaskSpace.cmsRun1
withe Script module: SetupCMSSWPset
a bytes-like object is required, not 'str'Details:
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 740, in __call__
    makeTaskTweak(self.step.data, self.tweak)
  File "/srv/job/PSetTweaks/WMTweak.py", line 391, in makeTaskTweak
    args = pickle.loads(stepSection.application.configuration.pickledarguments)
```

which was overlooked when I created that PR fixing this issue.
