### ISSUE TITLE
ReqMgr2 StatusChangeTask thread attempting invalid status transition

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10646]
**Impact of the bug**
ReqMgr2 (one of its CherryPy threads)

**Describe the bug**
From the testbed logs [1], I see the StatusChangeTasks CherryPy thread sometimes attempt to perform invalid status transition, which returns a `400 Bad Request`, for `'InvalidStatus Transition: running-closed to running-open'`. We still need to investigate whether this is something new from the Python3 service (like an usual ordering that no longer happens) or if this issue is already present in production as well (thus, an old'ish bug).

It is not a critical problem, because in the next cycle of that thread, the workflow goes through the request status transition, but we should clear the logs from unneeded/known errors.

**How to reproduce it**
Not clear yet.

**Expected behavior**
ReqMgr2 should only perform valid status transition, thus avoiding such errors in our services.

**Additional context and error message**
[1]
```
2021-06-30 01:12:22,266:INFO:StatusChangeTasks:amaltaro_TaskChain_PUMCRecyc_HG2107_Val_210629_184629_8968 in staged moved to running-closed
2021-06-30 01:12:22,266:INFO:StatusChangeTasks:6 requests moved to new state from staged
2021-06-30 01:12:22,462:ERROR:CherryPyPeriodicTask:Periodic Thread ERROR http.client.HTTPException url=https://cmsweb-testbed.cern.ch:8443/reqmgr2/data/request, code=400, reason=Bad Request, headers={'Date': 'Tue, 29 Jun 2021 23:12:22 GMT', 'Server': 'CherryPy/17.4.0', 'Content-Type': 'text/html;charset=utf-8', 'X-Rest-Status': '1102', 'X-Error-Http': '400', 'X-Error-Id': 'f59ec82a79ee0096d22856942dbbe1ec', 'X-Error-Detail': "Invalid spec parameter value: InvalidStateTransition d4003f64c896534a89eacd8ac6910758 [HTTP 400, APP 1101, MSG 'InvalidStatus Transition: running-closed to running-open', INFO None, ERR None]", 'X-Rest-Time': '81663.370 us', 'Content-Length': '901', 'Vary': 'Accept-Encoding', 'CMS-Server-Time': 'D=89715 t=1625008342371463', 'Connection': 'close'}, result=b'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>400 Bad Request</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>400 Bad Request</h2>\n        <p>Invalid spec parameter value: InvalidStateTransition d4003f64c896534a89eacd8ac6910758 [HTTP 400, APP 1101, MSG \'InvalidStatus Transition: running-closed to running-open\', INFO None, ERR None]</p>\n        <pre id="traceback"></pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 17.4.0</a>\n      </span>\n    </div>\n    </body>\n</html>\n'
2021-06-30 01:12:22,463:ERROR:CherryPyPeriodicTask: Traceback (most recent call last):
2021-06-30 01:12:22,463:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/REST/CherryPyPeriodicTask.py", line 95, in run
2021-06-30 01:12:22,463:ERROR:CherryPyPeriodicTask:     self.taskFunc(self.config)
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py", line 124, in advanceStatus
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:     moveForwardStatus(reqmgrSvc, wfStatusDict, self.logger)
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py", line 73, in moveForwardStatus
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:     reqmgrSvc.updateRequestStatus(wf, nextStatus[j])
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/Services/ReqMgr/ReqMgr.py", line 196, in updateRequestStatus
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:     return self["requests"].put('request', status)[0]['result']
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 136, in put
2021-06-30 01:12:22,464:ERROR:CherryPyPeriodicTask:     return self.makeRequest(uri, data, 'PUT', incoming_headers,
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 159, in makeRequest
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:     result, response = self.makeRequest_pycurl(uri, data, verb, headers)
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 176, in makeRequest_pycurl
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:     response, result = self.reqmgr.request(uri, data, headers, verb=verb,
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/Utils/PortForward.py", line 67, in portMangle
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:     return callFunc(callObj, newUrl, *args, **kwargs)
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:   File "/data/srv/HG2107b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.5.0.pre5/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 306, in request
2021-06-30 01:12:22,465:ERROR:CherryPyPeriodicTask:     raise exc
```

**Comment by amaltaro** [comment]
Indeed it's a new issue, production logs are clean. Adding it to the python3 project as well.
Whoever works on this issue, I'd suggest to start from the tests (TDD).

I have added it to the Q3 board, but it would actually be great to get it sorted today. I might be able to get back to it, but I'm leaving it unassigned in case anyone else wants to take a pick.
