### ISSUE TITLE
Force-complete to completed transition fails

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10675]
**Impact of the bug**
Not sure which component is responsible from this transition. I know it's a WMCore service from previous examples, though

**Describe the bug**
I realized some workflows whose force-complete to completed transition fails. Thus the requests got stuck. Examples:
1. https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_PPD-RunIIFall17FSPrePremix-00006__v1_T_210625_125448_1923
2. https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIISummer20UL17MiniAODv2-00238__v1_T_210606_214915_2336

Here is a successful example from the past: https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIISummer20UL17wmLHEGEN-01248__v1_T_210324_145115_1446 

**How to reproduce it**
Check the requests before

**Expected behavior**
The responsible service should perform this transition. If there is anything fails, ops should be alerted.

**Additional context and error message**
None

**Comment by amaltaro** [comment]
@haozturk just to make sure I understand this issue.
Are you reporting that:
a) workflows `force-completed` are not automatically set to `completed` after a while?
b) or that you/unified fails to move workflows from `force-completed` to `completed` status?

**Comment by amaltaro** [comment]
Nevermind. Looking at the other issue where you provided this example:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_EXO-RunIIFall17wmLHEGS-03554__v1_T_210628_132241_8381

I see that it's been in `force-completed` for 5 days now. The agent working on this request is vocms0284, which looked fine to me. Anyhow, I have restarted all the components to see whether it improves. I'm investigating it now.

**Comment by haozturk** [comment]
@amaltaro  it's `a`. We can move workflows from `running-*` to `force-complete`, but it's not moved to `completed` automatically.

**Comment by amaltaro** [comment]
Looking into vocms0284 logs, I think this is the reason why workflows are not getting out of the `force-completed` status:
```
2021-07-26 12:11:50,586:140410422478592:INFO:WorkQueue:Deleting completed workflow WQ elements ...
2021-07-26 12:11:54,510:140410422478592:ERROR:WorkQueue:Error deleting WQ elements. Details: (52, 'Empty reply from server')
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1046, in performQueueCleanupActions
    res = self.deleteCompletedWFElements()
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 958, in deleteCompletedWFElements
    reqNames = self.backend.getWorkflows(includeInbox=True, includeSpecs=True)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueBackend.py", line 577, in getWorkflows
    [x['key'] for x in self.inbox.loadView('WorkQueue', 'elementsByWorkflow', {'group': True})['rows']])
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 546, in loadView
    (self.name, design, view), encodedOptions)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 123, in get
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 127, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 161, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 179, in makeRequest_pycurl
    ckey=ckey, cert=cert, capath=capath)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/srv/wmagent/v1.4.7.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch2/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 281, in request
    curl.perform()
error: (52, 'Empty reply from server')
2021-07-26 12:11:54,511:140410422478592:INFO:WorkQueue:Syncing and cancelling work ...
2021-07-26 12:11:54,745:140410422478592:ERROR:WorkQueue:Error syncing and canceling WQ elements. Details: (52, 'Empty reply from server')
```

WMAgent WorkQueueManager has to acknowledge the workqueue elements cancellation, which is - apparently - not working because it cannot retrieve data from global workqueue. Investigating it further....

**Comment by amaltaro** [comment]
Apparently the `'Empty reply from server'` error while querying workqueue was actually caused by a stale `workqueue_inbox` view compaction, as one can see from the huge view size in vocms0284:
```
cmst1@vocms0284:/data/srv/wmagent/current $ ls -lth install/couchdb/database/.workqueue_inbox_design/mrview/
total 17G
-rw-r--r--. 1 cmst1 zh 17G Jul 26 23:26 2f77345c5cf5065ec0f98a614222c8b2.view
-rw-r--r--. 1 cmst1 zh 11M Jul 26 23:26 2f77345c5cf5065ec0f98a614222c8b2.compact.view
```

I have stopped the agent and services, delete these 2 files listed above, started services and agent and waited ~5min for the workqueue_inbox views to be freshly recreated. Now they look like (actually it looks, it's meant to be a single view file!):
```
cmst1@vocms0284:/data/srv/wmagent/current $ ls -lth install/couchdb/database/.workqueue_inbox_design/mrview/
total 215M
-rw-r--r--. 1 cmst1 zh 215M Jul 27 06:29 2f77345c5cf5065ec0f98a614222c8b2.view
```

WorkQueueManager is happily running again, but the WorkQueueManagerCleaner thread is very slow (see https://github.com/dmwm/WMCore/issues/8477), so we have to wait for a few hours until it can complete its cycle and we can see whether things start moving to completed.

I'm watching these two requests that have been force completed:
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=cmsunified_task_EXO-RunIIFall17wmLHEGS-03554__v1_T_210628_132241_8381
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_PPD-RunIIFall17FSPrePremix-00006__v1_T_210625_125448_1923

which should move to completed as soon as vocms0284 is done with that WorkQueueManagerCleaner cycle. Watching...

**Comment by amaltaro** [comment]
It was indeed vocms0284 agent that was holding many WQE in a stale status, causing their relevant workflows to never go to `completed` status, even when all the elements were already done and/or force-completed.

I see a spike of around 500 workflows that went into `completed` status within the last 30min, global workqueue has shrinked as well, since the agent was now able to delete no-longer needed workqueue elements (~10k).

There is nothing else to be changed in the code or to be fixed in the WM infrastructure, so I'm closing this issue.
Hasan, please let us know if you have any other concerns or see any other workflows still stuck not moving to completed. Thanks
