### ISSUE TITLE
Runtime failure with CMSSW_12_0_0_pre5 (Python3?) workflows - edm_pset_pickler

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10716]
**Impact of the bug**
WMAgent

**Describe the bug**
The P&R team reported 100% failure rate with a batch of 12_0_0_pre5 RelVal workflows. Which reminded me yesterday's WMCore chat, when Kevin mentioned that this release is meant to be supporting Python3 only.

Traceback from one of the jobs can be seen here [1]. And a full job tarball for the workflow pdmvserv_RVCMSSW_12_0_0_pre5Upsilon1SToMuMu_14_210730_154150_8750 can be found at: https://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_10716/

**How to reproduce it**
Not yet known.

**Expected behavior**
Jobs shouldn't fail to run the PSet tweak.

Note that these workflows were executed by the RelVal agent, which contains this particular patch applied to support python3 workflows: https://github.com/dmwm/WMCore/pull/10479

**Additional context and error message**
[1]
```
2021-08-03 00:47:49,514:INFO:SetupCMSSWPset:Executing SetupCMSSWPSet...
2021-08-03 00:47:49,515:INFO:SetupCMSSWPset:Creating Scram environment with scram arch: slc7_amd64_gcc900 and CMSSW version: CMSSW_12_0_0_pre5
2021-08-03 00:47:53,016:INFO:SetupCMSSWPset:DEBUG: Now in the none scenario to load PSET
2021-08-03 00:47:53,016:INFO:SetupCMSSWPset:Working dir: /srv/job/WMTaskSpace/cmsRun1
2021-08-03 00:47:53,017:INFO:SetupCMSSWPset:ScramRun command args: edm_pset_pickler.py --input /srv/job/WMTaskSpace/cmsRun1/PSet.py --output_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl
2021-08-03 00:47:53,017:INFO:Scram:Creating a subprocess to run the PSet setup.
2021-08-03 00:47:53,017:INFO:Scram:Also recording SCRAM command-line related output.
2021-08-03 00:47:53,028:INFO:Scram:    Invoking command: edm_pset_pickler.py --input /srv/job/WMTaskSpace/cmsRun1/PSet.py --output_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl
2021-08-03 00:47:53,211:INFO:Scram:Subprocess stdout was:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_pickler.py", line 3, in <module>
    import FWCore.ParameterSet.Config as cms
ImportError: No module named FWCore.ParameterSet.Config

2021-08-03 00:47:53,212:INFO:Scram:Subprocess stderr was:
None
2021-08-03 00:47:53,212:ERROR:SetupCMSSWPset:Error running scram process. Error code: 5
2021-08-03 00:47:53,212:ERROR:SetupCMSSWPset:Error loading PSet:
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 712, in __call__
    self.loadPSet()
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 181, in loadPSet
    self.scramRun(cmd)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 117, in scramRun
    raise RuntimeError(msg)
RuntimeError: Error running scram process. Error code: 5

 Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 118, in <module>
RuntimeError: Error invoking script for step WMTaskSpace.cmsRun1
withe Script module: SetupCMSSWPset
Error running scram process. Error code: 5Details:
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 715, in __call__
    raise ex
```

**Comment by amaltaro** [comment]
@khurtado Kenyi, since you are the one who implemented all of this, can you help me debugging this issue and finding where the problem is? I'm contacting David L. now to buy us some time.

**Comment by amaltaro** [comment]
LogArchive jobs (containing that PSet) can be found at: https://eoscmsweb.cern.ch/eos/cms/store/logs/prod/recent/PRODUCTION/pdmvserv_RVCMSSW_12_0_0_pre5Upsilon1SToMuMu_14_210730_154150_8750/GenSimFull

**Comment by khurtado** [comment]
Changes from here:
https://github.com/cms-sw/cmssw-wm-tools/commit/dd8396181a6d483e53ce7a23235575c8a72ef463

fixed the issue. Stealing one job sandbox with the changes above, give instead:

```
NFO:root:RUNNING SCRAM SCRIPTS
INFO:root:Executing CMSSW. args: ['/bin/bash', u'/tmpscratch/users/khurtado/work/validation/T0v2/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', u'', u'slc7_amd64_gcc900', u'scramv1', u'CMSSW', u'CMSSW_12_0_0_pre5', u'FrameworkJobReport.xml', u'cmsRun', u'PSet.py', '', '', u'']
INFO:root:PSS: 278183; RSS: 280448; PCPU: 2.9; PMEM: 0.2
INFO:root:PSS: 535608; RSS: 537308; PCPU: 4.9; PMEM: 0.4
INFO:root:PSS: 990763; RSS: 993108; PCPU: 27.1; PMEM: 0.7
INFO:root:PSS: 1141298; RSS: 1143380; PCPU: 74.3; PMEM: 0.8
# more lines after cmssw finished executing
```

**Comment by amaltaro** [comment]
We got an extra confirmation from Hasan, saying that a workflow resubmission went through the system with no failures.
Thanks to David L for the fix, and Kenyi for the validation! Closing this issue.
