### ISSUE TITLE
[py2] Merge job failing to be tweaked due to unicode string

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10725]
**Impact of the bug**
WMAgent

**Describe the bug**
While testing some patches on top of Py2 WMAgent 1.5.1.pre6, I've seen 100% failure for the merge jobs - I was running a single slc6_amd64_gcc630 workflow.

From the `TypeError` exception, I believe we are actually passing a list of unicode strings with the input file names for the merge process, here is the traceback from WMStats [1]

**How to reproduce it**
Deploy a Py2 WMAgent, version 1.5.1.pre6 (plus a few patches resolving issues before reaching that code), and run one of our json test templates. 

**Expected behavior**
PSet should be properly created and tweaked, allowing the merge cmsRun to actually run.
In other words, we will have to encode those unicode strings to bytes, before we can pass it to the cmssw-sw-tools PSet tweak script.

**Additional context and error message**
[1]
```
2021-08-04 11:21:00,129:INFO:SetupCMSSWPset:Creating job level tweaks
2021-08-04 11:21:00,129:INFO:WMTweak:Adding 7 files to 'fileNames' attr
2021-08-04 11:21:00,129:INFO:WMTweak:Adding 0 files to 'secondaryFileNames' attr
2021-08-04 11:21:00,129:INFO:WMTweak:Setting 'maxEvents.input' attr to: -1
2021-08-04 11:21:00,130:INFO:SetupCMSSWPset:ScramRun command args: edm_pset_tweak.py --input_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --output_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --json /srv/job/WMTaskSpace/cmsRun1/PSetTweak.json
2021-08-04 11:21:00,130:INFO:Scram:Creating a subprocess to run the PSet setup.
2021-08-04 11:21:00,130:INFO:Scram:Also recording SCRAM command-line related output.
2021-08-04 11:21:00,133:INFO:Scram:    Invoking command: edm_pset_tweak.py --input_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --output_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --json /srv/job/WMTaskSpace/cmsRun1/PSetTweak.json
2021-08-04 11:21:00,894:INFO:Scram:Subprocess stdout was:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py", line 155, in <module>
    main()
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py", line 142, in main
    err_val = apply_tweak(process, tweak[0], tweak[1],args.skip_if_set)
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py", line 64, in apply_tweak
    value = eval('cms.{0}'.format('.'.join(value_split[1:])))
  File "<string>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_7/python/FWCore/ParameterSet/Types.py", line 23, in __call__
    param = globals()[self.name](*value,**params)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_7/python/FWCore/ParameterSet/Types.py", line 759, in __init__
    super(vstring,self).__init__(*arg,**args)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_7/python/FWCore/ParameterSet/Mixins.py", line 563, in __init__
    super(_ValidatingParameterListBase,self).__init__(*arg,**args)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_7/python/FWCore/ParameterSet/Mixins.py", line 513, in __init__
    ") added to "+str(type(self)))
TypeError: wrong types (<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>) added to <class 'FWCore.ParameterSet.Types.vstring'>

2021-08-04 11:21:00,895:INFO:Scram:Subprocess stderr was:
None
2021-08-04 11:21:00,895:ERROR:SetupCMSSWPset:Error running scram process. Error code: 5
...
 Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 118, in <module>
RuntimeError: Error invoking script for step WMTaskSpace.cmsRun1
withe Script module: SetupCMSSWPset
Error running scram process. Error code: 5Details:
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 739, in __call__
    self.applyPsetTweak(self.tweak, cleanupTweak=True)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 234, in applyPsetTweak
    self.scramRun(cmd)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 117, in scramRun
    raise RuntimeError(msg)
```

**Comment by amaltaro** [comment]
Given that this is happening with the Py2 WMAgent service, and we are trying to complete the commissioning of the Python3 based agent; I'm going to set this issue aside for a while and focus on other Python3 related issues.

**Comment by goughes** [comment]
I tested this on my central services VM and a py2 agent.

cmsweb tag: `HG2108h`
wmagent version: `v1.5.2.pre3`

I submitted two requests from `TC_LHE_PFN.json` and in each case the merge jobs were successful. This may take some additional investigation to determine if/how the error can be reproduced.

**Comment by amaltaro** [comment]
Given that this is a python2-related issue and WMCore no longer supports it, I am closing this out.
