### ISSUE TITLE
[py2py3] More runtime errors for Py3 agent on rhel7 OS

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10735]
**Impact of the bug**
Py3 WMAgent

**Describe the bug**
I'm going to try to report all the problems I happen to see while testing Py3 WMAgent during job runtime, on rhel7 setup (thus, using scramArch slc7_* and python 3.8.2).

First issue is also common to the rhel6 jobs and already reported in the other issue linked from this one. For completeness, here's the error message section [1].

Second issue is related to StepChain workflows - and likely the failure of the previous step(s) - when passing an object that is not json serializable, see [2].

A suspicious line - and possibly another problem - can be seen in the error block [2], which is:
```
2021-08-06 19:20:06,264:INFO:ExecuteMaster:StepName: cmsRun1, StepType: CMSSW, with result: 'logArch1'
``` 
the `cmsRun1` process should have an integer result(!). It's the first time I see that "Executor Task Change" code though, so perhaps it's expected...

**How to reproduce it**
Py3 WMAgent 1.5.2.pre1 + 10726, run an slc7_* StepChain workflow.

**Expected behavior**
This issue needs to address all the job runtime related errors seen while commissioning Py3 WMAgent and slc7_* workload.

**Additional context and error message**
Issue tightly coupled to its rhel6 equivalent: https://github.com/dmwm/WMCore/issues/10734

[1]
```
2021-08-06 19:20:06,053:INFO:CMSSW:Running PRE scripts
2021-08-06 19:20:06,099:ERROR:ExecuteMaster:Exception occured when executing step
2021-08-06 19:20:06,099:ERROR:ExecuteMaster:Exception is a bytes-like object is required, not 'str'
2021-08-06 19:20:06,100:ERROR:ExecuteMaster:Traceback:
2021-08-06 19:20:06,101:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 141, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 197, in execute
    scriptProcess.stdin.write("export LD_LIBRARY_PATH=$LD_LIBRARY_PATH\n")
TypeError: a bytes-like object is required, not 'str'

2021-08-06 19:20:06,101:CRITICAL:CMSSW:CMSDefaultHandler Diagnostic Handler invoked
```

[2]
```
2021-08-06 19:20:06,102:WARNING:Report:Exit code: 99109 has been already added to the job report
2021-08-06 19:20:06,103:INFO:CMSSW:Steps.Executors.CMSSW.post called
2021-08-06 19:20:06,103:INFO:ExecuteMaster:Post Executor Task Change: logArch1
2021-08-06 19:20:06,264:INFO:ExecuteMaster:StepName: cmsRun1, StepType: CMSSW, with result: 'logArch1'
2021-08-06 19:20:06,269:INFO:CMSSW:Steps.Executors.CMSSW.pre called
2021-08-06 19:20:06,357:INFO:CMSSW:Steps.Executors.CMSSW.execute called
2021-08-06 19:20:06,358:CRITICAL:CMSSW:Skipping this step due to a failure in a previous one.
2021-08-06 19:20:06,456:ERROR:ExecuteMaster:Exception occured when executing step
2021-08-06 19:20:06,456:ERROR:ExecuteMaster:Exception is Object of type bytes is not JSON serializable
2021-08-06 19:20:06,457:ERROR:ExecuteMaster:Traceback:
2021-08-06 19:20:06,463:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 141, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 111, in execute
    self._setStatus(99108, msg)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 57, in _setStatus
    self.setCondorChirpAttrDelayed('Chirp_WMCore_cmsRun_Exception_Message', returnMessage, compress=True)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executor.py", line 197, in setCondorChirpAttrDelayed
    args = [condor_chirp_bin, 'set_job_attr_delayed', key, json.dumps(value)]
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

2021-08-06 19:20:06,463:CRITICAL:CMSSW:CMSDefaultHandler Diagnostic Handler invoked
2021-08-06 19:20:06,464:WARNING:Report:Exit code: 99109 has been already added to the job report
2021-08-06 19:20:06,465:INFO:CMSSW:Steps.Executors.CMSSW.post called
2021-08-06 19:20:06,553:INFO:ExecuteMaster:StepName: cmsRun4, StepType: CMSSW, with result: 99109
2021-08-06 19:20:06,560:INFO:CMSSW:Steps.Executors.CMSSW.pre called
2021-08-06 19:20:06,674:INFO:CMSSW:Steps.Executors.CMSSW.execute called
2021-08-06 19:20:06,675:CRITICAL:CMSSW:Skipping this step due to a failure in a previous one.
2021-08-06 19:20:06,772:ERROR:ExecuteMaster:Exception occured when executing step
2021-08-06 19:20:06,773:ERROR:ExecuteMaster:Exception is Object of type bytes is not JSON serializable
2021-08-06 19:20:06,773:ERROR:ExecuteMaster:Traceback:
2021-08-06 19:20:06,774:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 141, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 111, in execute
    self._setStatus(99108, msg)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 57, in _setStatus
    self.setCondorChirpAttrDelayed('Chirp_WMCore_cmsRun_Exception_Message', returnMessage, compress=True)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executor.py", line 197, in setCondorChirpAttrDelayed
    args = [condor_chirp_bin, 'set_job_attr_delayed', key, json.dumps(value)]
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by amaltaro** [comment]
Here is another error once passed the condor chirp one:
```
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 118, in <module>
RuntimeError: Error invoking script for step WMTaskSpace.cmsRun4
withe Script module: SetupCMSSWPset
a bytes-like object is required, not 'str'Details:
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 752, in __call__
    self.handlePileup()
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 423, in handlePileup
    raise ex
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 420, in handlePileup
    json.dump(newPileupDict, f)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
```

**Comment by amaltaro** [comment]
And here we go with an error that makes merge jobs to fail:
```
2021-08-11 17:17:35,817:INFO:SetupCMSSWPset:Executing SetupCMSSWPSet...
2021-08-11 17:17:35,818:INFO:SetupCMSSWPset:Creating Scram environment with scram arch: slc7_amd64_gcc700 and CMSSW version: CMSSW_10_6_1
2021-08-11 17:17:37,979:INFO:SetupCMSSWPset:Setting up job scenario/process
2021-08-11 17:17:37,980:ERROR:SetupCMSSWPset:Error writing out process funcArgs json
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 138, in createProcess
    json.dump(funcArgs, f)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
2021-08-11 17:17:37,981:ERROR:SetupCMSSWPset:Error creating process for Config/DataProcessing:
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 688, in __call__
    self.createProcess(scenario, funcName, funcArgs)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 141, in createProcess
    raise ex
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 138, in createProcess
    json.dump(funcArgs, f)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not "str"
```
