### ISSUE TITLE
[py2py3] More runtime errors for Py3 agent on rhel6 OS

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10734]
**Impact of the bug**
Py3 WMAgent

**Describe the bug**
I'm going to try to report all the problems I happen to see while testing Py3 WMAgent during job runtime, on `rhel6` setup (thus, using scramArch slc6_* and python 3.6.4).

First issue to be reported happens during the SCRAM scripts, as shown in this wmagentJob.log [1]
 
**How to reproduce it**
Py3 WMAgent 1.5.2.pre1 + #10726, then run any of the slc6_* test json templates workflow.

**Expected behavior**
This issue needs to address all the job runtime related errors seen while commissioning Py3 WMAgent and slc6_* workload.

**Additional context and error message**
[1]
```
2021-08-06 19:26:40,264:INFO:CMSSW:Runing SCRAM
2021-08-06 19:26:41,923:INFO:CMSSW:Running PRE scripts
2021-08-06 19:26:41,932:ERROR:ExecuteMaster:Exception occured when executing step
2021-08-06 19:26:41,933:ERROR:ExecuteMaster:Exception is a bytes-like object is required, not 'str'
2021-08-06 19:26:41,933:ERROR:ExecuteMaster:Traceback:
2021-08-06 19:26:41,934:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 141, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 197, in execute
    scriptProcess.stdin.write("export LD_LIBRARY_PATH=$LD_LIBRARY_PATH\n")
TypeError: a bytes-like object is required, not 'str'

2021-08-06 19:26:41,935:CRITICAL:CMSSW:CMSDefaultHandler Diagnostic Handler invoked
2021-08-06 19:26:41,936:WARNING:Report:Exit code: 99109 has been already added to the job report
2021-08-06 19:26:41,936:INFO:CMSSW:Steps.Executors.CMSSW.post called
```

**Comment by amaltaro** [comment]
With the 1st commit provided in #10736, we managed to take only one small step. Next issue happens now with the actual execution of that command:
```
2021-08-07 08:09:27,717:INFO:CMSSW:Running PRE scripts
2021-08-07 08:09:27,720:INFO:CMSSW:    Invoking command:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python3/3.6.4/bin/python3 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset

2021-08-07 08:09:28,417:CRITICAL:CMSSW:Error running command
2021-08-07 08:09:28,417:CRITICAL:CMSSW:Error running command
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python3/3.6.4/bin/python3 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset

1
 b"2021-08-07 08:09:28,382:INFO:ScriptInvoke:Invoking scripts in current directory: /srv/job/WMTaskSpace/cmsRun1\n2021-08-07 08:09:28,388:INFO:Bootstrap:Job Index = 1148\nJob Instance = {'input_files': [{'lfn': 'MCFakeFile-amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071-DarkSUSY_14TeV_2023D17_GenSimHLBeamSpotFull14-0031b50ba950a6458506041ae7485674', 'size': 0, 'events': 10000, 'checksums': {}, 'runs': set(), 'merged': True, 'last_event': 0, 'first_event': 0, 'locations': set(), 'parents': set()}], 'id': 1148, 'jobgroup': 22, 'name': '45462b35-2ab9-400b-8348-03648e19e4f3-0', 'state': 'new', 'state_time': 1628320164, 'outcome': 'failure', 'retry_count': 0, 'location': None, 'mask': {'inclusivemask': True, 'FirstEvent': 1, 'LastEvent': 500, 'FirstLumi': 1, 'LastLumi': 5, 'FirstRun': 1, 'LastRun': 1, 'runAndLumis': {}, 'jobID': 1148}, 'task': '/amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071/DarkSUSY_14TeV_2023D17_GenSimHLBeamSpotFull14', 'fwjr': None, 'fwjr_path': None, 'workflow': 'amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071', 'owner': 'amaltaro', 'estimatedJobTime': 21600, 'estimatedMemoryUsage': 2000.0, 'estimatedDiskUsage': 4000000, 'cache_dir': '/data/srv/wmagent/v1.5.2.pre1/install/wmagentpy3/JobCreator/JobCache/amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071/DarkSUSY_14TeV_2023D17_GenSimHLBeamSpotFull14/JobCollection_22_0/job_1148', 'sandbox': '/data/srv/wmagent/v1.5.2.pre1/install/wmagentpy3/WorkQueueManager/cache/amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071/amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071-Sandbox.tar.bz2', 'jobType': 'Production', 'taskType': 'integration', 'spec': '/data/srv/wmagent/v1.5.2.pre1/install/wmagentpy3/WorkQueueManager/cache/amaltaro_TC_LHE_PFN_Aug2021_Val_210807_084927_9071/WMSandbox/WMWorkload.pkl', 'counter': 1, 'agentNumber': 0, 'agentName': 'vocms0192.cern.ch', 'ownerDN': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues', 'ownerGroup': 'unknown', 'ownerRole': 'unknown', 'numberOfCores': 8, 'allowOpportunistic': False}\n\n"
 b'Traceback (most recent call last):\n  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 99, in <module>\n  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 62, in boot\nValueError: level must be >= 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python3/3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python3/3.6.4/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 107, in <module>\nRuntimeError: Error booting script invoker for step WMTaskSpace.cmsRun1\nwithe Script module: SetupCMSSWPset\nlevel must be >= 0Details:\n  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 99, in <module>\n  File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 62, in boot\n\n'

2021-08-07 08:09:28,450:WARNING:Report:Exit code: 50513 has been already added to the job report
```
