### ISSUE TITLE
[py2py3] TypeError exception from DBS3 HTTPResponse parsing

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10745]
**Impact of the bug**
WMAgent (but issue is likely on the py3-dbs3-client)

**Describe the bug**
This bug only got exposed now because we seem to be failing to resolve a block/dataset in the WorkQueueManager. Full traceback can be found at [1]. Spotted in 1.5.2.pre1 BTW

As can be seen from the traceback, problem happens when creating the pileup config in the WorkQueueManager component, in a DBS3 call to `fileArray` API. However, if the request can be successfully served, I think we would not be seeing such errors.

**How to reproduce it**
I guess making a call through py3-dbs3-client that fails with an HTTPError.

**Expected behavior**
Fix that error:
```
TypeError: a bytes-like object is required, not 'str'
```
such that dbs3-client can properly respond to client requests, no matter what the http status will be.

**Additional context and error message**
[1]
```
2021-08-11 13:43:20,841:140687618520832:ERROR:WorkQueue:Failed to create subscription for amaltaro_SC_6Steps_Scratch_Aug2021_Val_210811_113054_8569 with block name None
Error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 355, in getWork
    match['Subscription'] = self._wmbsPreparation(match,
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 470, in _wmbsPreparation
    sub, match['NumOfFilesAdded'] = wmbsHelper.createSubscriptionAndAddFiles(block=dbsBlock)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 418, in createSubscriptionAndAddFiles
    raise ex
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 413, in createSubscriptionAndAddFiles
    self.createSubscription(self.topLevelTask, self.topLevelFileset)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 263, in createSubscription
    self._createSubscriptionsInWMBS(task, fileset, alternativeFilesetClose)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 281, in _createSubscriptionsInWMBS
    self.createSandbox()
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 213, in createSandbox
    sandboxCreator.makeSandbox(self.cachepath, self.wmSpec)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WMRuntime/SandboxCreator.py", line 138, in makeSandbox
    fetcher(task)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 209, in __call__
    self.createPileupConfigFile(helper)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 187, in createPileupConfigFile
    configDict = self._queryDbsAndGetPileupConfig(helper, dbsReader)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 63, in _queryDbsAndGetPileupConfig
    for fileInfo in dbsReader.getFileListByDataset(dataset=dataset, detail=True):
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre1/lib/python3.8/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 772, in getFileListByDataset
    fileList = self.dbs.listFileArray(dataset=dataset, validFileOnly=validFileOnly, detail=detail)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 1299, in listFileArray
    return self.__callServer("fileArray", data=kwargs, callmethod="POST")
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 200, in __callServer
    self.http_response = method_func(self.url, method, params, data, request_headers)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RestApi.py", line 40, in post
    return http_request(self._curl)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 61, in __call__
    raise HTTPError(effective_url, http_code, http_response.msg, http_response.raw_header, http_response.body)
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPResponse.py", line 67, in msg
    self.__parse_header()
  File "/data/srv/wmagent/v1.5.2.pre1/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPResponse.py", line 11, in __parse_header
    for header in self._response_header.getvalue().split('\r\n'):
TypeError: a bytes-like object is required, not 'str'
2021-08-11 13:43:20,895:140687618520832:INFO:WorkQueue:Injected 0 out of 1 units into WMBS
```

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, I'm not sure whether you (or Neil) have actually looked at the dbs3-client code that has been migrated to Python3. Even though it's been filled as a WMCore issue, it's actually a problem with the dbs3-client. So, I wonder if you would be able to investigate this issue in the coming days/weeks? Otherwise I might be able to have a quick look in the next week or two.

**Comment by amaltaro** [comment]
Just to add, this error can happen with any component and any service using py3-dbs3-client `3.16.2000`. The problem only occurs though when we actually have an HTTP error (http status < 200 or >= 300), as defined here:
https://github.com/dmwm/DBS/blob/master/PycurlClient/src/python/RestClient/RequestHandling/HTTPRequest.py#L61-L63

Example for DBS3Upload:
```
2021-08-17 10:20:22,383:140606158591744:INFO:DBSUploadPoller:About to insert block /b_bbar_4l_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16wmLHEGENAPV-myTask1_TaskChain_Prod_Aug2021_Val_Alanv13-v11/LHE#6952486e-d5de-4116-ae3c-125499e74e6
c
2021-08-17 10:20:22,385:140606158591744:INFO:DBSUploadPoller:About to insert block /b_bbar_4l_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16wmLHEGENAPV-myTask1_TaskChain_Prod_Aug2021_Val_Alanv13-v11/GEN#36c60b0f-eac9-4584-a7c9-679d017deec
f
2021-08-17 10:20:23,741:140606158591744:ERROR:DBSUploadPoller:Error trying to process block /b_bbar_4l_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16wmLHEGENAPV-myTask1_TaskChain_Prod_Aug2021_Val_Alanv13-v11/LHE#6952486e-d5de-4116-ae3c-125499e74e6c through DBS. Error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.5.2.pre2/lib/python3.8/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 85, in uploadWorker
    dbsApi.insertBulkBlock(blockDump=block)
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 345, in insertBulkBlock
    result =  self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/3.16.2000/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 200, in __callServer
    self.http_response = method_func(self.url, method, params, data, request_headers)
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RestApi.py", line 40, in post
    return http_request(self._curl)
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 61, in __call__
    raise HTTPError(effective_url, http_code, http_response.msg, http_response.raw_header, http_response.body)
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPResponse.py", line 67, in msg
    self.__parse_header()
  File "/data/srv/wmagent/v1.5.2.pre2/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl-client/3.16.2000/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPResponse.py", line 11, in __parse_header
    for header in self._response_header.getvalue().split('\r\n'):
TypeError: a bytes-like object is required, not 'str'
2021-08-17 10:20:23,921:140606158591744:ERROR:DBSUploadPoller:Error found in multiprocess during process of block /b_bbar_4l_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16wmLHEGENAPV-myTask1_TaskChain_Prod_Aug2021_Val_Alanv13-v11/LHE#6952486e-d5de-4116-ae3c-125499e74e6c
2021-08-17 10:20:23,922:140606158591744:ERROR:DBSUploadPoller:Error trying to process block /b_bbar_4l_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16wmLHEGENAPV-myTask1_TaskChain_Prod_Aug2021_Val_Alanv13-v11/LHE#6952486e-d5de-4116-ae3c-125499e74e6c through DBS. Error: a bytes-like object is required, not 'str'
```

**Comment by vkuznet** [comment]
Here is your fix: https://github.com/dmwm/DBS/pull/655

**Comment by amaltaro** [comment]
Waiting for required fixes on the new dbs3-client code (coming from the repository separation), which Yuyi is working on.

**Comment by amaltaro** [comment]
Setting it to the Waiting Q4 column.

Proper fix has been provided by the PR Valentin mentioned above, however there is a dbs3-client organizational change (server/client separation) and with that other issues popped up, which Yuyi is/will work on.

We could consider alternative options though, like:
* patch the dbs3-client spec itself
* apply the dbs3-client (actually dbs3-pycurl-client) on the agents
