### ISSUE TITLE
Replay fails using WMCore release 1.5.2.pre2

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/WMCore#10752]
**Impact of the bug**
Tier0 agent fails running a replay with SCRAMScriptFailure. The error message start as follows:
```
<@========== WMException Start ==========@>
Exception Class: PreScriptFailure
Message: Error running command
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/bin/python2 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 
```

**Describe the bug**
While Tier0 doesn't have issues during the deployment or initiating all the components, all the jobs are paused due SCRAMScriptFailure.

**How to reproduce it**
Logs, tarballs and sandbox for a Repack and Express jobs can be found here `/afs/cern.ch/user/c/cmst0/public/PausedJobs/WMCore/agent_1_5_2_pre2`

**Expected behavior**
Replay finished without issues

**Additional context and error message**
The last release stable (means that replay finished without issue) was using the following WMCore release and applying the patches:
`1.5.0.pre4 + PR 10344,10593,10255`
A previous replay using `1.5.1.pre6 + PR 10344, 10593, 10711, 10712` was tested but the component JobSubmitter failed with:
```
 File "/data/tier0/srv/wmagent/2.2.6/sw.jamadova/slc7_amd64_gcc630/cms/t0/2.2.6/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 529, in getJobParameters
    ad['My.WMAgent_RequestName'] = classad.quote(job['request_name'])
```

**Comment by amaltaro** [comment]
Thanks for making this GH issue, Jhonatan.
From the logs you provided, the actual problem is with this command:
```
2021-08-14 23:21:10,863:INFO:Scram:Also recording SCRAM command-line related output.
2021-08-14 23:21:10,867:INFO:Scram:    Invoking command: edm_pset_tweak.py --input_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --output_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --json /srv/job/WMTaskSpace/cmsRun1/PSetTweak.json
2021-08-14 23:21:11,509:INFO:Scram:Subprocess stdout was:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py", line 155, in <module>
    main()
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py", line 142, in main
    err_val = apply_tweak(process, tweak[0], tweak[1],args.skip_if_set)
  File "/cvmfs/cms.cern.ch/share/overrides/bin/edm_pset_tweak.py", line 64, in apply_tweak
    value = eval('cms.{0}'.format('.'.join(value_split[1:])))
  File "<string>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_2/python/FWCore/ParameterSet/Types.py", line 31, in __call__
    param = globals()[self.name](*value,**params)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_2/python/FWCore/ParameterSet/Types.py", line 1013, in __init__
    super(vstring,self).__init__(*arg,**args)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_2/python/FWCore/ParameterSet/Mixins.py", line 638, in __init__
    super(_ValidatingParameterListBase,self).__init__(*arg,**args)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_2/python/FWCore/ParameterSet/Mixins.py", line 581, in __init__
    ") added to "+str(type(self)))
TypeError: wrong types (<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>) added to <class 'FWCore.ParameterSet.Types.vstring'>
```

which I believe it to be the same as the one reported here: https://github.com/dmwm/WMCore/issues/10725

**Comment by amaltaro** [comment]
@jhonatanamado @germanfgv I wonder if this issue is still relevant? If not, can we close it?

**Comment by amaltaro** [comment]
Since we have been happily running T0 agent based on WMCore `1.5.2`, I'm going to close this issue. Please feel free to reopen if there is anything else missing.
