### ISSUE TITLE
Paused jobs from replay using WMCore agent 1.5.2 with error SetupCMSSWPset due issue in edm_pset_tweak.py

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#10807]
**Impact of the bug**
Tier0 agent using 1.5.2 fails workflows

**Describe the bug**
While testing WMCore agent 1.5.2, with the CMSSW CMSSW_11_3_4  and 12_0_0, the replay shows paused jobs with an error within SetupCMSSWPset.py when trying to execute  edm_pset_tweak.py

**How to reproduce it**
Replay using T0 release 3.0.0 based on 1.5.2 agent.

**Expected behavior**
No errors from edm_pset_tweak.py

**Additional context and error message**
Please take into account that Tier0 was able to deploy the replay using the 1.5.2 agent including the following PR #10801

**Comment by khurtado** [comment]
More details on the error after reproducing it interactively:

```
$ edm_pset_tweak.py --input_pkl PSet.pkl --output_pkl PSet_output.pkl --json PSetTweak.json --allow_failed_tweaks
We got here
Traceback (most recent call last):
  File "edm_pset_tweak.py", line 160, in <module>
    main()
  File "edm_pset_tweak.py", line 147, in main
    err_val = apply_tweak(process, tweak[0], tweak[1],args.skip_if_set, args.create_untracked_psets )
  File "edm_pset_tweak.py", line 82, in apply_tweak
    setattr(param,key_split[-1],value)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_4/python/FWCore/ParameterSet/Mixins.py", line 276, in __setattr__
    self.__addParameter(name, value)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_4/python/FWCore/ParameterSet/Mixins.py", line 244, in __addParameter
    self.__raiseBadSetAttr(name)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_4/python/FWCore/ParameterSet/Mixins.py", line 299, in __raiseBadSetAttr
    raise TypeError(name+" does not already exist, so it can only be set to a CMS python configuration type")
TypeError: fileName does not already exist, so it can only be set to a CMS python configuration type

$ echo $?
1
```

So, the problem is `--allow_failed_tweaks` isn't ignoring tweaks that fail, which we do want to happen sometimes like here (in this case, we want to ignore setting up `process.sqLite.xxx` variables in the PSet.

**Comment by khurtado** [comment]
This was fixed with the external commit below from David L.:

https://github.com/cms-sw/cmssw-wm-tools/commit/aa1626fb2d2fdbde6b3259e4b44828220883a809

and was verified to work by @germanfgv
