### ISSUE TITLE
CouchDB 3.x: AgentStatusWatcher fails to parse document source_seq attr

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11037]
**Impact of the bug**
WMAgent using CouchDB 3.x

**Describe the bug**
While testing a private build of WMAgent 1.5.7.patch2 + CouchDB 3.1, I noticed that AgentStatusWatcher fails with this error [1]

In addition to that exception, note that `CouchServer` is also reported as being down, but actually it's not.

**How to reproduce it**
None

**Expected behavior**
Needs further investigation, but that `source_seq` seems to be an integer followed by a uid hash, so we cannot cast it to integer.
Hopefully fixing this will also fix the "CouchServer is down"

**Additional context and error message**
[1]
```
2022-03-12 18:16:42,249:140419360032512:INFO:AgentStatusPoller:Getting agent info ...
2022-03-12 18:16:42,970:140419360032512:ERROR:CMSCouch:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.5.7.patch2-127c31293503ab5f4da2da887a06775a/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.7.patch2-127c31293503ab5f4da2da887a06775a/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 1249, in checkCouchServerStatus
    replicationFlag = self.checkReplicationStatus(activeStatus, dbInfo, source,
  File "/data/srv/wmagent/v1.5.7.patch2-127c31293503ab5f4da2da887a06775a/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.5.7.patch2-127c31293503ab5f4da2da887a06775a/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 1269, in checkReplicationStatus
    updateNum = int(activeStatus["source_seq"])
ValueError: invalid literal for int() with base 10: '664-g1AAAACheJzLYWBgYMpgTmEQTM4vTc5ISXIwNDLXMwBCwxyQVCJDUv3___-zMpiTGBgY83KBYuzmyaZmFmnG2PTgMSmPBUgyNACp_wgDtcAGphqmpZmbWWDTmgUA14Ao_w'

2022-03-12 18:16:43,025:140419360032512:INFO:AgentStatusPoller:CouchDB is running with 5 processes
2022-03-12 18:16:43,025:140419360032512:INFO:AgentStatusPoller:List of agent components down: ['TaskArchiver', 'CouchServer']
```

**Comment by amaltaro** [comment]
Moving it under the Waiting column because it can only go in once we migrate to CouchDB 3.x
