### ISSUE TITLE
WorkQueue fails to create subscription due to ORACLE unique constraint violation

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11108]
**Impact of the bug**
WorkQueue, WMBS 

**Describe the bug**
While checking the status of few workflows upon a P&R request, I've found plenty of Oracle errors: `ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated` at the two newly deployed CERN agents. The agent version deployed is **v2.0.2.patch1**.  This is  an error we do not observe neither in the FNAL agents (they are using MAriaDB anyway) nor at the agents currently on drain. 

Taking as an example a workflow that is been distributed amongst those all agents: 

[cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873](https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873) 

**agent url:** cmsgwms-submit4.fnal.gov,cmsgwms-submit5.fnal.gov,cmsgwms-submit6.fnal.gov,cmsgwms-submit7.fnal.gov,vocms0252.cern.ch,vocms0253.cern.ch,vocms0282.cern.ch,vocms0283.cern.ch 

We observe the following at `vocms0282 - v2.0.2.patch1`: [1], and no errors at all in both `vocms0252`. 

In addition to that I see quite low number of WMBS jobs created for those two new CERN agents. Something like 866 jobs for `vocms0282`  vs 43K jobs for `cmsgwms-submit7.fnal.gov`. And hence the low number of idle condor jobs for the two new CERN agents:

```
vocms0282: $ condor_q --totals
Total for query: 6187 jobs; 0 completed, 0 removed, 4224 idle, 1963 running, 0 held, 0 suspended 

vocms0283: $ condor_q --totals
Total for query: 30827 jobs; 0 completed, 0 removed, 3695 idle, 27132 running, 0 held, 0 suspended 
```

**How to reproduce it**

**Expected behavior**

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

[1]
```
2022-04-13 23:44:52,787:139862773548800:ERROR:WMBSHelper:Failed to create subscription. Error: (cx_Oracle.IntegrityError) ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated
[SQL: INSERT INTO dbsbuffer_dataset_subscription
             (id, dataset_id, site, custodial, auto_approve, move, priority, subscribed, phedex_group, delete_blocks, dataset_lifetime)
             SELECT dbsbuffer_dataset_sub_seq.nextval, :id, :site, :custodial, :auto_approve,
                    :move, :priority, 0, :phedex_group, :delete_blocks, :dataset_lifetime
             FROM DUAL
             WHERE NOT EXISTS
               ( SELECT *
                 FROM dbsbuffer_dataset_subscription
                 WHERE dataset_id = :id
                 AND site = :site
                 AND custodial = :custodial
                 AND auto_approve = :auto_approve
                 AND move = :move
                 AND priority = :priority
                 AND dataset_lifetime = :dataset_lifetime )
             ]
[parameters: {'id': 1, 'site': 'T2_US_Florida', 'custodial': False, 'auto_approve': 1, 'move': 0, 'priority': 'Low', 'phedex_group': 'DataOps', 'delete_blocks': None, 'dataset_lifetime': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.IntegrityError: ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 413, in createSubscriptionAndAddFiles
    self.createSubscription(self.topLevelTask, self.topLevelFileset)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 266, in createSubscription
    self._createDatasetSubscriptionsInDBSBuffer()
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 520, in _createDatasetSubscriptionsInDBSBuffer
    dbsDataset.addSubscription(subInfo[dataset])
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMComponent/DBS3Buffer/DBSBufferDataset.py", line 140, in addSubscription
    action.execute(self['id'], subscriptionInformation,
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMComponent/DBS3Buffer/MySQL/NewSubscription.py", line 66, in execute
    self.dbi.processData(self.sql, binds=binds, conn=conn, transaction=transaction)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/Database/DBCore.py", line 172, in processData
    r = self.executebinds(s, b, connection=connection,
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/Database/DBCore.py", line 64, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
    ret = self._execute_context(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (cx_Oracle.IntegrityError) ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated
[SQL: INSERT INTO dbsbuffer_dataset_subscription
             (id, dataset_id, site, custodial, auto_approve, move, priority, subscribed, phedex_group, delete_blocks, dataset_lifetime)
             SELECT dbsbuffer_dataset_sub_seq.nextval, :id, :site, :custodial, :auto_approve,
                    :move, :priority, 0, :phedex_group, :delete_blocks, :dataset_lifetime
             FROM DUAL
             WHERE NOT EXISTS
               ( SELECT *
                 FROM dbsbuffer_dataset_subscription
                 WHERE dataset_id = :id
                 AND site = :site
                 AND custodial = :custodial
                 AND auto_approve = :auto_approve
                 AND move = :move
                 AND priority = :priority
                 AND dataset_lifetime = :dataset_lifetime )
             ]
[parameters: {'id': 1, 'site': 'T2_US_Florida', 'custodial': False, 'auto_approve': 1, 'move': 0, 'priority': 'Low', 'phedex_group': 'DataOps', 'delete_blocks': None, 'dataset_lifetime': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)




2022-04-13 23:44:52,789:139862773548800:ERROR:WorkQueue:Failed to create subscription for cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873 with block name None
Error: (cx_Oracle.IntegrityError) ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated
[SQL: INSERT INTO dbsbuffer_dataset_subscription
             (id, dataset_id, site, custodial, auto_approve, move, priority, subscribed, phedex_group, delete_blocks, dataset_lifetime)
             SELECT dbsbuffer_dataset_sub_seq.nextval, :id, :site, :custodial, :auto_approve,
                    :move, :priority, 0, :phedex_group, :delete_blocks, :dataset_lifetime
             FROM DUAL
             WHERE NOT EXISTS
               ( SELECT *
                 FROM dbsbuffer_dataset_subscription
                 WHERE dataset_id = :id
                 AND site = :site
                 AND custodial = :custodial
                 AND auto_approve = :auto_approve
                 AND move = :move
                 AND priority = :priority
                 AND dataset_lifetime = :dataset_lifetime )
             ]
[parameters: {'id': 1, 'site': 'T2_US_Florida', 'custodial': False, 'auto_approve': 1, 'move': 0, 'priority': 'Low', 'phedex_group': 'DataOps', 'delete_blocks': None, 'dataset_lifetime': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.IntegrityError: ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 352, in getWork
    match['Subscription'] = self._wmbsPreparation(match,
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 453, in _wmbsPreparation
    sub, match['NumOfFilesAdded'] = wmbsHelper.createSubscriptionAndAddFiles(block=dbsBlock)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 418, in createSubscriptionAndAddFiles
    raise ex
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 413, in createSubscriptionAndAddFiles
    self.createSubscription(self.topLevelTask, self.topLevelFileset)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 266, in createSubscription
    self._createDatasetSubscriptionsInDBSBuffer()
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 520, in _createDatasetSubscriptionsInDBSBuffer
    dbsDataset.addSubscription(subInfo[dataset])
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMComponent/DBS3Buffer/DBSBufferDataset.py", line 140, in addSubscription
    action.execute(self['id'], subscriptionInformation,
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMComponent/DBS3Buffer/MySQL/NewSubscription.py", line 66, in execute
    self.dbi.processData(self.sql, binds=binds, conn=conn, transaction=transaction)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/Database/DBCore.py", line 172, in processData
    r = self.executebinds(s, b, connection=connection,
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMCore/Database/DBCore.py", line 64, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
    ret = self._execute_context(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3-comp/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (cx_Oracle.IntegrityError) ORA-00001: unique constraint (CMS_WMBS_PROD12.UQ_DBS_DAT_SUB) violated
[SQL: INSERT INTO dbsbuffer_dataset_subscription
             (id, dataset_id, site, custodial, auto_approve, move, priority, subscribed, phedex_group, delete_blocks, dataset_lifetime)
             SELECT dbsbuffer_dataset_sub_seq.nextval, :id, :site, :custodial, :auto_approve,
                    :move, :priority, 0, :phedex_group, :delete_blocks, :dataset_lifetime
             FROM DUAL
             WHERE NOT EXISTS
               ( SELECT *
                 FROM dbsbuffer_dataset_subscription
                 WHERE dataset_id = :id
                 AND site = :site
                 AND custodial = :custodial
                 AND auto_approve = :auto_approve
                 AND move = :move
                 AND priority = :priority
                 AND dataset_lifetime = :dataset_lifetime )
             ]
[parameters: {'id': 1, 'site': 'T2_US_Florida', 'custodial': False, 'auto_approve': 1, 'move': 0, 'priority': 'Low', 'phedex_group': 'DataOps', 'delete_blocks': None, 'dataset_lifetime': None}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

[2]
```
2022-04-11 10:24:24,733:140665460737792:INFO:WorkQueue:Running WMBS preparation for cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873 with ParentQueueId 84cadfd2061398ef871a19d9bb5d7466,
  with common location ['T2_US_Florida']
2022-04-11 10:24:24,744:140665460737792:INFO:Fileset:Fileset created: cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873-TSG-Run3Winter22GS-00002_0-27765ea9ee953e8b90915707e32347a3
2022-04-11 10:24:26,349:140665460737792:INFO:Rucio:WMCore Rucio initialization parameters: {'account': 'wmcore_transferor', 'rucio_host': None, 'auth_host': None, 'ca_cert': None, 'auth_type': None, 'creds': None, 'timeout': 600, 'user_agent': 'wmcore-client'}
2022-04-11 10:24:26,352:140665460737792:INFO:Rucio:Rucio client initialization parameters: {'host': 'http://cms-rucio.cern.ch', 'auth_host': 'https://cms-rucio-auth.cern.ch', 'auth_type': 'x509', 'account': 'wmcore_transferor', 'user_agent': 'wmcore-client/1.25.5', 'ca_cert': '/etc/grid-security/certificates/', 'creds': {'client_cert': '/data/certs/servicecert.pem', 'client_key': '/data/certs/servicekey.pem'}, 'timeout': 600, 'request_retries': 3}
2022-04-11 10:24:26,462:140665460737792:INFO:Rucio:Pileup container location for /MinBias_TuneCP5_13p6TeV-pythia8/Run3Winter22GS-122X_mcRun3_2021_realistic_v9-v1/GEN-SIM from single RSE locks at: ['T1_US_FNAL_Disk', 'T2_US_Florida', 'T1_ES_PIC_Disk']
2022-04-11 10:24:28,757:140665460737792:INFO:SandboxCreator:Created sandbox cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873-Sandbox.tar.bz2 with size 3197422
2022-04-11 10:24:28,776:140665460737792:INFO:Workflow:Workflow id 47920 created for cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873
2022-04-11 10:24:28,788:140665460737792:INFO:WMBSHelper:Top level subscription 67000 created for cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873
2022-04-11 10:24:28,793:140665460737792:INFO:Fileset:Fileset created: /cmsunified_task_TSG-Run3Winter22GS-00002__v1_T_220323_185605_8873/TSG-Run3Winter22GS-00002_0/unmerged-RAWSIMoutputGEN-SIM
```

[3]
```

```

**Comment by vkuznet** [comment]
@todor-ivanov I'm interested to know what kind of changes went into last WMAgent. This error is similar to what we observed with new DBS server which by itself is caused by parallel execution of HTTP requests. Therefore, if new WMAgent introduced parallel execution of internal components which hit DB with similar requests and underlying server should insert identical data than it can lead to ORA-00001 errors. From the posted errors I see that the issue with new subscription creation. My question is where this subscription is created, by whom, and is it possible that you have two or more running threads which request new subscription with similar data (like `site, custodial, auto_approve, move, priority and dataset_lifetime` parameters).

**Comment by todor-ivanov** [comment]
Hi @vkuznet I know you were talking about the same oracle error and race conditions in https://github.com/dmwm/WMCore/issues/11106 And initially I went exploring that path, but In this case I think the reason could be somewhere else. One change from the last month I find is related to how  the defaults for the `DBSBufferDataset`  instance are set: https://github.com/dmwm/WMCore/pull/11059/files 


Another thing I observe in the logs is that all those broken SQL queries are having somehow identical values (except for the `site` and `id`):

```
[SQL: INSERT INTO dbsbuffer_dataset_subscription
             (id, dataset_id, site, custodial, auto_approve, move, priority, subscribed, phedex_group, delete_blocks, dataset_lifetime)
             SELECT dbsbuffer_dataset_sub_seq.nextval, :id, :site, :custodial, :auto_approve,
                    :move, :priority, 0, :phedex_group, :delete_blocks, :dataset_lifetime
             FROM DUAL
             WHERE NOT EXISTS
               ( SELECT *
                 FROM dbsbuffer_dataset_subscription
                 WHERE dataset_id = :id
                 AND site = :site
                 AND custodial = :custodial
                 AND auto_approve = :auto_approve
                 AND move = :move
                 AND priority = :priority
                 AND dataset_lifetime = :dataset_lifetime )
             ]
[parameters: {'id': 661, 'site': 'T2_KR_KISTI', 'custodial': False, 'auto_approve': 1, 'move': 0, 'priority': 'Low', 'phedex_group': 'DataOps', 'delete_blocks': None, 'dataset_lifetime': None}]
```

**Comment by todor-ivanov** [comment]
Ok, We have looked in the issue and discussed several things with @vkuznet and here is a summary of our findings. Long story short:
We have a constraint for the `dbsbuffer_dataset_subscription` table defined in the database schema here: https://github.com/dmwm/WMCore/blob/8c6466ba373945d63aa909c80ed7664548c22549/src/python/WMComponent/DBS3Buffer/Oracle/Create.py#L54  which includes the following the following set of `unique` fields described in it :
```
dataset_id, site, custodial, auto_approve, move, priority
```
And we have a `WHERE NOT EXIST` clause protecting the new records for not hitting this constraint including the following set of query parameters:
```
dataset_id, site, custodial, auto_approve, move, priority, dataset_lifetime
```
As one can easily see `dataset_lifetime` is redundant here. The end result is the `WHERE NOT EXIST`  clause is not working at all. Here is the set of values passed as parameters to a real query:
```
[parameters: {'id': 661, 'site': 'T2_KR_KISTI', 'custodial': False, 'auto_approve': 1, 'move': 0, 'priority': 'Low', 'phedex_group': 'DataOps', 'delete_blocks': None, 'dataset_lifetime': None}]
```
And if one translates them manually into the following query: 
```
SQL> SELECT id, dataset_id, custodial, priority, auto_approve, dataset_lifetime  FROM dbsbuffer_dataset_subscription WHERE dataset_id = 661 AND site = 'T2_KR_KISTI' AND custodial = 0 AND auto_approve = 1  AND move = 0 AND priority = 'Low' AND dataset_lifetime = 0;

no rows selected
```
There are no results returned. While if one removes `dataset_lifetime`  from the query itself we get:
```
SQL> SELECT id, dataset_id, custodial, priority, auto_approve, dataset_lifetime  FROM dbsbuffer_dataset_subscription WHERE dataset_id = 661 AND site = 'T2_KR_KISTI' AND custodial = 0 AND auto_approve = 1  AND move = 0 AND priority = 'Low';

	ID DATASET_ID  CUSTODIAL PRIORITY   AUTO_APPROVE DATASET_LIFETIME
---------- ---------- ---------- ---------- ------------ ----------------
      9313	  661	       0 Low		       1
```

Which is the expected behavior.  

But there is more on that. Even though the extra parameter is present in the query it shouldn't be a problem if the actual records in the database reflect correctly the datatype defined in the database shema, meaning if the value of a real subscription record was having `dataset_lifetime` as 0. But as it is noticeable in the result from the query above the `dataset_lifetime` in the actual record in the database is `NULL` or empty. Even though it is defined in the schema as `int` with default `0`, so one would expect it to be entered as `0` with a new fresh record as well (even if the value in python is `None`). For this I am not sure (and I'd avoid speculating here, but just need to mention it) we should search for how those are treated in the middle layer which sits between the python code values and the actually translated query parameters, etc. In our case this should be `sqlalchemy`.  Another possible apporoach would be to implement strict data type checks on our end and to properly translate everything to the expected data type values as defined in the schema... but this would involve more effort.

This whole construction was  added  with the following [PR](https://github.com/dmwm/WMCore/pull/10950) and the `dataset_lifetime` was basically included upon a request from T0 Team. This so far is something we do not use in production workflows. So I feel safe about creating a fix by just removing  the `dataset_lifetime` from the innermost query. In the worst case scenario that would result in overwriting of records regarding subscriptions having all the rest of the fields equal but the `dataset_lifetime`. Which, firstly, is hard to happen in my opinion. Secondly, we do not use the field at all, so the end result would be expected behavior in respect to the production workflows. And third but not last, we shouldn't have a unique constrain having one set of parameters and having a query protecting us from hitting the constraint having a different set of parameters. We may consider fixing that properly through the database scheme and also (as mentioned above) even including strict data type checks in the python code. For that we should create and track the effort in a different GH issue, which should be properly tested and get in the regular release.

**Comment by todor-ivanov** [comment]
Ok, the genie  is out of the bottle now. 
Even though I have created the patch for this issue, I applied the change directly into all CERN agents: `vocms0282`, `vocms0283` and the relval one `vocms0258`. The logs are clean now, and we have skyrocketed in WMBS jobs created at CERN for the last 30 min. Please see the image attached [1].

The agents are ramping up steadily in condor jobs: 
```
vocms0282:
Total for query: 30907 jobs; 0 completed, 0 removed, 25167 idle, 5740 running, 0 held, 0 suspended

vocms0283:
Total for query: 12881 jobs; 0 completed, 2 removed, 10641 idle, 2238 running, 0 held, 0 suspended 
``` 

I expect to see this reflected in real pressure in the global pool in a matter of few hours. 

FYI: @haozturk  @vkuznet  @klannon  @amaltaro 

[1]

![Screenshot at 2022-04-22 16-53-43](https://user-images.githubusercontent.com/8182807/164729023-15f413ba-2667-4768-9c95-b719750735e3.png)
