### ISSUE TITLE
Flaw in the isEmptyResults logic for MS/Common tools

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11147]
**Impact of the bug**
Microservices

**Describe the bug**
Data is returned as a JSON object by pycurl_manager module, which means this check for empty results:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Tools/Common.py#L49

is missing one - or probably two extra checks - for json empty objects like 'null' and '[]'.

**How to reproduce it**
Query DBS with `from WMCore.Services.pycurl_manager import getdata` for an invalid input data

**Expected behavior**
We should not consider a 200 status code with output `'[]'` (JSON object) as failure in:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Tools/Common.py#L49

So we need to either add a couple of other possible results in that list in the `if` statement. Or add a logic of json.load and check (likely in a try/except block).
 
**Additional context and error message**
Error message from MSTransferor logs:
```
2022-05-17 12:13:00,261:INFO:Common: Executing 13 requests against DBS 'blockparents' API
Failure in findBlockParents for block /NoBPTX/Run2018D-12Nov2019_UL2018-v1/MINIAOD#be382968-82b7-4e65-b73f-57aa0b83d0e4. Error: 'this_block_name'
2022-05-17 12:13:00,461:ERROR:MSManager: MS daemon error: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSManager.py", line 41, in daemon
    func(reqStatus)
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSManager.py", line 179, in transferor
    res = self.msTransferor.execute(reqStatus)
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSTransferor/MSTransferor.py", line 193, in execute
    reqResults = self.reqInfo(reqSlice)
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSTransferor/RequestInfo.py", line 69, in __call__
    self.unified(workflows)
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSTransferor/RequestInfo.py", line 151, in unified
    self.setParentChildBlocks(workflows, parentageMap)
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSTransferor/RequestInfo.py", line 506, in setParentChildBlocks
    wflow.setChildToParentBlocks(parentageMap[wflow.getInputDataset()])
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.0.3.pre7/lib/python3.8/site-packages/WMCore/MicroService/MSTransferor/DataStructs/Workflow.py", line 321, in setChildToParentBlocks
    for child, parents in viewitems(blocksDict):
  File "/data/srv/HG2205e/sw/slc7_amd64_gcc630/external/py3-future/0.18.2-comp/lib/python3.8/site-packages/future/utils/__init__.py", line 277, in viewitems
    func = obj.items
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by todor-ivanov** [comment]
Thanks @amaltaro for finding this bug. Where did you spot the issue for the first time. Maybe a short excerpt of few log messages or exceptions may be useful to have here.

**Comment by amaltaro** [comment]
This is actually a confusing logic. We consider empty results as failure, but I think we should only evaluate it to failed if it has a code >= 300 (or 400) AND it has an `error` key in the output, as provided by the underlying http library:
https://github.com/dmwm/WMCore/blob/b298768bfd3d46c2ffb424a02d854036a510c493/src/python/WMCore/Services/pycurl_manager.py#L510

**Comment by amaltaro** [comment]
@vkuznet thanks for your comment. I think we reached the same conclusion and my proposal in the PR is actually replacing the empty check by an http request status check.
