### ISSUE TITLE
CouchDB 3.x: JobUpdater fail to authenticate to localhost workqueue

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11203]
**Impact of the bug**
WMAgent

**Describe the bug**
It looks like the scenario where a workflow gets a priority update and that has to propagate to the agents and jobs wasn't actually tested when working on this issue: https://github.com/dmwm/WMCore/issues/11044

Todor mentioned problems with the JobUpdater component in the new agents (2.0.4 series), and it turns out the component is not able to write to the local CouchDB instance of the workqueue (to update the local workqueue elements). Here is a snippet of the ComponentLog [1]

**How to reproduce it**
Have a workflow running and update its priority in ReqMgr2

**Expected behavior**
The agent should not have authorization issues and JobUpdater should be able to complete the workflow priority update task.

**Additional context and error message**
Similar to https://github.com/dmwm/WMCore/issues/11044

[1]
```
2022-06-29 20:19:21,626:140042221348608:INFO:JobUpdaterPoller:Updating workqueue elements priority for request: cmsunified_task_BPH-RunIISummer20UL16GEN-00129__v1_T_220316_105623_1257
2022-06-29 20:19:21,680:140042221348608:ERROR:JobUpdaterPoller:Caught unexpected exception in JobUpdater: url=http://localhost:5984/workqueue/cmsunified_task_BPH-RunIISummer20UL16GEN-00129__v1_T_220316_105623_1257/spec, code=401, reason=U
nauthorized, headers={'Cache-Control': 'must-revalidate', 'Content-Length': '78', 'Content-Type': 'application/json', 'Date': 'Wed, 29 Jun 2022 18:19:20 GMT', 'Server': 'CouchDB/3.1.2 (Erlang OTP/22)', 'X-Couch-Request-ID': '82f6a2a4f4', 
'X-CouchDB-Body-Time': '0'}, result=b'{"error":"unauthorized","reason":"You are not authorized to access this db."}\n'
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.4.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.4.patch1/lib/python3.8/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 84, in algorithm
    self.synchronizeJobPriority()
  File "/data/srv/wmagent/v2.0.4.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.4.patch1/lib/python3.8/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 151, in synchronizeJobPriority
    self.workqueue.updatePriority(workflow, priorityCache[workflow])
  File "/data/srv/wmagent/v2.0.4.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.4.patch1/lib/python3.8/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 242, in updatePriority
    wmspec.load(self.db['host'] + "/%s/%s/spec" % (self.db.name, wf))
```

**Comment by amaltaro** [comment]
After further debugging, I found that it actually manages to update the workqueue elements, but it's failing to update the spec file that is kept in the workqueue database, e.g.:
AMR url: http://localhost:5984/workqueue/WF_NAME/spec

The reason for that is that when saving the spec in couch, the url has already been sanitized and we no longer have the couch credentials, not in the url neither in the additional HTTP headers that we usually define for modules inhering from the Requests/Service super class. See code in:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Persistency.py#L84
