### ISSUE TITLE
MSUnmerged fails to connect to MongoDB - [Errno 111] Connection refused

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11213]
**Impact of the bug**
MSUnmerged

**Describe the bug**
Imran noticed that MSUnmerged was crashing after today's testbed upgrade and it turns out the same issue is hitting us in production as well. A short version of the error message is (hostnames skipped on purpose):
```
pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()", Timeout: 30s, Topology Description: <TopologyDescription id: 62cc0f85150690ab863cec6e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDes
cription
```

and the traceback can be found at [1].
 
**How to reproduce it**
Unknown

**Expected behavior**
We need to check whether the mongodb cluster is fully operation, and for that I have just contacted Panos via mattermost.

In addition to that, I think we need two developments on the WMCore side:
1) create an alert for MongoDB connection problems (I'd suggest to use the Prometheus API we already have in our stack).
2) make sure credentials don't show up in the logs

**Additional context and error message**
[1]
```
[11/Jul/2022:13:55:15]  ERROR: terminating due to error: Traceback (most recent call last):
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/REST/Main.py", line 435, in start_daemon
    self.run()
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/REST/Main.py", line 496, in run
    self.install_application()
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/REST/Main.py", line 276, in install_application
    obj = getattr(module, class_name)(self, view, path)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/MicroService/Service/RestApiHub.py", line 35, in __init__
    self._add({"status": Data(app, self, config, mount),
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/Utils/Patterns.py", line 13, in __call__
    super(Singleton, cls).__call__(*args, **kwargs)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/MicroService/Service/Data.py", line 58, in __init__
    self.mgr = getattr(module, cname)(config)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/MicroService/MSManager.py", line 146, in __init__
    self.msUnmerged = MSUnmerged(self.msConfig, logger=self.logger)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/MicroService/MSUnmerged/MSUnmerged.py", line 128, in __init__
    mongoClt = MongoDB(**msUnmergedDBConfig)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/Database/MongoDB.py", line 60, in __init__
    raise ex
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.0.pre5/lib/python3.8/site-packages/WMCore/Database/MongoDB.py", line 55, in __init__
    self.client.server_info()
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1662, in server_info
    return self.admin.command("buildinfo",
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/database.py", line 594, in command
    with self.__client._socket_for_reads(
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1177, in _socket_for_reads
    server = self._select_server(read_preference, session)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1137, in _select_server
    server = topology.select_server(server_selector)
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/topology.py", line 242, in select_server
    servers = self.select_servers(
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/topology.py", line 200, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/data/srv/HG2207h/sw/slc7_amd64_gcc630/external/py3-pymongo/4.0.1/lib/python3.8/site-packages/pymongo/topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
```

**Comment by Panos512** [comment]
Thanks Alan! Alerts should indeed be implemetned. We have monitoring in place, with a MongoDB Prometheus exporter enabled http://mongodb-m7wwpbnzgide-node-0.cern.ch:30000/rules 

I believe we just never push those alerts in the central system so that we get notifications. I'll look into it with Imran and update the ticket.

**Comment by amaltaro** [comment]
@Panos512 Hi Panos, sorry for not following this up. I just wanted to check whether there is anything that we need to do from the WMCore side. Have you deployed these alerts that you mentioned above?

**Comment by Panos512** [comment]
Hi @amaltaro yes everything should be in place. @mrceyhun has enabled the alerts and has also created a slack channel where the alerts are propagated. I can add you to the channel if you want.

**Comment by amaltaro** [comment]
@Panos512 if it's a new channel in the CMS Monitoring slack organization, could you please share it such that I can ask a few of the WMCore team to join it? Yes, you can also add me to email alerts please. With that, I think we can close this issue out.

**Comment by Panos512** [comment]
@amaltaro yes it's a channel in the CMS Monitoring, it's called `alerts-mongodb-k8s-cluster` I can't find a way to generate a link to it :) I think @mrceyhun should be able to add you to the mail list.

**Comment by amaltaro** [comment]
@Panos512 no worries, I just searched and joined it. Do you know what the other mongodb channel is? Perhaps it's for running mongodb within the CMSWEB setup?

**Comment by Panos512** [comment]
Perfect, thanks @amaltaro . I would guess that yes, the other channel is for the VM based MongoDB service but I'm not 100% sure.

**Comment by amaltaro** [comment]
Thanks @Panos512 . I am in favor of closing this issue out then. Feel free to reopen it if there is anything missing.
