### ISSUE TITLE
Broken workflow status transition to assigned

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11269]
**Impact of the bug**
Reqmgr2

**Describe the bug**
During the [HG2209](https://github.com/dmwm/WMCore/issues/11225) validation we have faced a problem with moving workflows' status from `assignment-approved` to `assigned`. Here [1] is the error we face. This has been found while working with ACDC workflows. The general workflow transition seems to be somehow working because we  do see workflows passing to `running-open`. All the conditions under which the bug reveals itself are currently investigated. So far the clues we have point to the following [PR](https://github.com/dmwm/WMCore/pull/11181/files). 

This bug needs to be resolved before we deploy the new release in production.   

**How to reproduce it**
Submit a workflow with central services version WMCore v.2.1.2.pre3 and try to create  and move an ACDC workflow from `assignment-approved` to  `assigned`.

**Expected behavior**
The workflow status transition to proceed with no errors. 

**Additional context and error message**
[1]
```
[04/Sep/2022:09:10:45] reqmgr2-7689bd755d-p52m8 188.185.14.143 "GET /reqmgr2/data/request?name=spiga_ReReco_339_TB_CMS_Marconi_220731_175607_3091 HTTP/1.1" 200 OK [data: 3936 in 1925 out 26215 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0192.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v002" ]
[04/Sep/2022:09:10:45]  Updating request "tivanov_ACDC_TaskChain_LumiMask_multiRun_HG2209_Val_220904_091028_2526" with these user-provided args: {'RequestStatus': 'assigned', 'RequestPriority': 200000, 'Team': 'testbed-vocms0192', 'SiteWhitelist': ['T1_US_FNAL', 'T2_CH_CERN'], 'SiteBlacklist': '', 'AcquisitionEra': {'HLTD': 'CMSSW_7_2_0', 'RECODreHLT': 'CMSSW_7_2_0'}, 'ProcessingString': {'HLTD': 'HLTD_TaskChain_LumiMask_multiRun_HG2209_Val_Todor_v1', 'RECODreHLT': 'RECODreHLT_TaskChain_LumiMask_multiRun_HG2209_Val_Todor_v1'}, 'ProcessingVersion': 11, 'Dashboard': 'integration', 'MergedLFNBase': '/store/mc', 'TrustSitelists': 'False', 'UnmergedLFNBase': '/store/unmerged', 'MinMergeSize': 2147483648, 'MaxMergeSize': 4294967296, 'MaxMergeEvents': 100000, 'BlockCloseMaxWaitTime': 72000, 'BlockCloseMaxFiles': 500, 'BlockCloseMaxEvents': 250000000, 'BlockCloseMaxSize': 5000000000000, 'SoftTimeout': 129600, 'GracePeriod': 1000, 'TrustPUSitelists': 'False', 'CustodialSites': '', 'CustodialSubType': '', 'NonCustodialSites': '', 'NonCustodialSubType': '', 'Override': {'eos-lfn-prefix': 'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/TESTBED'}, 'AutoApproveSubscriptionSites': '', 'SubscriptionPriority': 'Low'}
[04/Sep/2022:09:10:46]  Error: Traceback (most recent call last):
  File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/ReqMgr/Service/Request.py", line 188, in validate
    self._validateRequestBase(param, safe, validate_request_update_args, requestName)
  File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/ReqMgr/Service/Request.py", line 100, in _validateRequestBase
    workload, r_args = valFunc(args, self.config, self.reqmgr_db_service, param)
  File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/ReqMgr/Utils/Validation.py", line 60, in validate_request_update_args
    workload.validateArgumentForAssignment(request_args)
  File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkload.py", line 1945, in validateArgumentForAssignment
    validateArgumentsUpdate(schema, argumentDefinition)
  File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkloadTools.py", line 292, in validateArgumentsUpdate
    validateUnknownArgs(arguments, argumentDefinition)
  File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkloadTools.py", line 323, in validateUnknownArgs
    raise WMSpecFactoryException(msg)
WMCore.WMSpec.WMSpecErrors.WMSpecFactoryException: <@========== WMException Start ==========@>
Exception Class: WMSpecFactoryException
Message: There are unknown/unsupported arguments in your request spec: ['AutoApproveSubscriptionSites', 'NonCustodialSubType', 'CustodialSubType']
        ClassName : None
        ModuleName : WMCore.WMSpec.WMWorkloadTools
        MethodName : validateUnknownArgs
        ClassInstance : None
        FileName : /data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/WMSpec/WMWorkloadTools.py
        LineNumber : 323
        ErrorNr : 0

Traceback: 

<@---------- WMException End ----------@>

[04/Sep/2022:09:10:46]  SERVER REST ERROR WMCore.ReqMgr.DataStructs.RequestError.InvalidSpecParameterValue 53d67b1934bc2cd41f720c7b170dc0e9 (Invalid spec parameter value: There are unknown/unsupported arguments in your request spec: ['AutoApproveSubscriptionSites', 'NonCustodialSubType', 'CustodialSubType'])
[04/Sep/2022:09:10:46]    Traceback (most recent call last):
[04/Sep/2022:09:10:46]      File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/REST/Server.py", line 728, in default
[04/Sep/2022:09:10:46]        return self._call(RESTArgs(list(args), kwargs))
[04/Sep/2022:09:10:46]      File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/REST/Server.py", line 805, in _call
[04/Sep/2022:09:10:46]        v(apiobj, request.method, api, param, safe)
[04/Sep/2022:09:10:46]      File "/data/srv/HG2209c/sw/slc7_amd64_gcc630/cms/reqmgr2/2.1.2.pre3/lib/python3.8/site-packages/WMCore/ReqMgr/Service/Request.py", line 223, in validate
[04/Sep/2022:09:10:46]        raise InvalidSpecParameterValue(msg) from None
[04/Sep/2022:09:10:46]    WMCore.ReqMgr.DataStructs.RequestError.InvalidSpecParameterValue: InvalidSpecParameterValue 53d67b1934bc2cd41f720c7b170dc0e9 [HTTP 400, APP 1102, MSG "Invalid spec parameter value: There are unknown/unsupported arguments in your request spec: ['AutoApproveSubscriptionSites', 'NonCustodialSubType', 'CustodialSubType']", INFO None, ERR None]

```

**Comment by todor-ivanov** [comment]
On a first glance it seems the problem comes from the removal of some Phedex related  request parameters from `StdBase` here: https://github.com/dmwm/WMCore/pull/11181/files#diff-5a3ac3cd52b6d14d69977560f1fcfe410d45a16f5f683facb1c2ba1fa0a20ef3L1137-L1144

Here follows the full set:
```
AutoApproveSubscriptionSites
CustodialSubType
NonCustodialSubType
CustodialGroup
NonCustodialGroup
```

But if I look deeper those parameters are  not present in the original request. Neither in the `.json` template [1], nor in the request as it was created in Reqmgr2 from the very beginning [2], nor in the ACDC request (the  `Resubmission`) [3]. But hey are actually only present in the REST call which is sent during the request status transition [4], which makes it break the validation check immedately.   



[1]
https://github.com/dmwm/WMCore/blob/master/test/data/ReqMgr/requests/DMWM/ReReco_RunBlockWhite.json

[2]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_RunBlockWhite_HG2209_Val_220901_112836_6904

[3]
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ACDC_ReReco_RunBlockWhite_HG2209_Val_220904_091356_2976

[4]
```
[04/Sep/2022:09:04:09]  Updating request "tivanov_ACDC_TC_6Tasks_Scratch_HG2209_Val_220904_090248_4309" with these user-provided args: {'RequestStatus': 'assigned', 'RequestPriority': 600000
, 'Team': 'testbed-vocms0192', 'SiteWhitelist': ['T1_US_FNAL', 'T2_CH_CERN'], 'SiteBlacklist': '', 'AcquisitionEra': 'DMWM_Test', 'ProcessingString': 'TC_6Tasks_Scratch_HG2209_Val_Todor_v1',
 'ProcessingVersion': 11, 'Dashboard': 'integration', 'MergedLFNBase': '/store/backfill/1', 'TrustSitelists': 'False', 'UnmergedLFNBase': '/store/unmerged', 'MinMergeSize': 2147483648, 'MaxM
ergeSize': 4294967296, 'MaxMergeEvents': 100000000, 'BlockCloseMaxWaitTime': 66400, 'BlockCloseMaxFiles': 500, 'BlockCloseMaxEvents': 25000000, 'BlockCloseMaxSize': 5000000000000, 'SoftTimeo
ut': 129600, 'GracePeriod': 300, 'TrustPUSitelists': 'False', 'CustodialSites': '', 'CustodialSubType': '', 'NonCustodialSites': '', 'NonCustodialSubType': '', 'Override': {'eos-lfn-prefix':
 'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/TESTBED'}, 'AutoApproveSubscriptionSites': '', 'SubscriptionPriority': 'Low'}
```

**Comment by todor-ivanov** [comment]
It seems this [1] is the chain how we add those parameters in the request dictionary, only for the web based calls for status transition  to `assigned`. (It was a wrong initial guess this bug is related to ACDC workflows only. It affects everything  we try to assign through the Reqmgr web based interface). 

[1]
* Here we build the web page with the table with proposed  values for the call for status update from `assignment-approved` to `assigned` : https://github.com/dmwm/WMCore/blob/dc3c46837ab8364907d75299dd136e586d9ad29c/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L470
 
* Here is the actual list of proposed values for constructing the table  with values  itself: https://github.com/dmwm/WMCore/blob/dc3c46837ab8364907d75299dd136e586d9ad29c/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L291-L304


So removing them from this table is a must, but I also find few more checks related to those request parameters which  are now obsolete with the change introduced with https://github.com/dmwm/WMCore/pull/11181:

Here:
https://github.com/dmwm/WMCore/blob/dc3c46837ab8364907d75299dd136e586d9ad29c/src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py#L120-L129 
 * notice only the parameters from the previously mentioned list above.

And one docstring to be updated  here:
https://github.com/dmwm/WMCore/blob/dc3c46837ab8364907d75299dd136e586d9ad29c/src/python/WMCore/WMSpec/WMTask.py#L1055-L1056

**Comment by todor-ivanov** [comment]
Testbed was patched with the so provided changes from #11270 and now I am capable to move workflows to status `assigned` safely [1].

[1]
```
[05/Sep/2022:18:47:45]  Updating request "tivanov_ACDC_ReReco_RunBlockWhite_HG2209_Val_220904_091356_2976" with these user-provided args: 
{'RequestStatus': 'assigned', 
 'RequestPriority': 190000,
 'Team': 'testbed-vocms0192',
 'SiteWhitelist': ['T1_US_FNAL', 'T2_CH_CERN'], 'SiteBlacklist': '',
 'AcquisitionEra': 'Run2016H',
 'ProcessingString': 'ReReco_RunBlockWhite_HG2209_Val_Todor_v1',
 'ProcessingVersion': 11,
 'Dashboard': 'integration',
 'MergedLFNBase': '/store/backfill/1',
 'TrustSitelists': 'False',
 'UnmergedLFNBase': '/store/unmerged',
 'MinMergeSize': 2147483648,
 'MaxMergeSize': 4294967296,
 'MaxMergeEvents': 100000000,
 'BlockCloseMaxWaitTime': 66400,
 'BlockCloseMaxFiles': 500,
 'BlockCloseMaxEvents': 25000000,
 'BlockCloseMaxSize': 5000000000000,
 'SoftTimeout': 129600,
 'GracePeriod': 300,
 'TrustPUSitelists': 'False',
 'CustodialSites': '',
 'NonCustodialSites': '',
 'Override': {'eos-lfn-prefix': 'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/TESTBED'},
 'SubscriptionPriority': 'Low'}


[05/Sep/2022:18:47:45]  Assign request tivanov_ACDC_ReReco_RunBlockWhite_HG2209_Val_220904_091356_2976, input args: 
{'RequestStatus': 'assigned',
 'RequestPriority': 190000,
 'Team': 'testbed-vocms0192',
 'SiteWhitelist': ['T1_US_FNAL', 'T2_CH_CERN'],
 'SiteBlacklist': [],
 'AcquisitionEra': 'Run2016H',
 'ProcessingString': 'ReReco_RunBlockWhite_HG2209_Val_Todor_v1',
 'ProcessingVersion': 11,
 'Dashboard': 'integration',
 'MergedLFNBase': '/store/backfill/1',
 'TrustSitelists': False,
 'UnmergedLFNBase': '/store/unmerged',
 'MinMergeSize': 2147483648,
 'MaxMergeSize': 4294967296,
 'MaxMergeEvents': 100000000,
 'BlockCloseMaxWaitTime': 66400,
 'BlockCloseMaxFiles': 500,
 'BlockCloseMaxEvents': 25000000,
 'BlockCloseMaxSize': 5000000000000,
 'SoftTimeout': 129600,
 'GracePeriod': 300,
 'TrustPUSitelists': False,
 'CustodialSites': [],
 'NonCustodialSites': [],
 'Override': {'eos-lfn-prefix': 'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent/TESTBED'},
 'SubscriptionPriority': 'Low',
 'HardTimeout': 129900} ...
```

**Comment by amaltaro** [comment]
@todor-ivanov thank you for investigating it. Do I understand it correctly that it only affects workflow assignment via ReqMgr2 Web UI?

**Comment by todor-ivanov** [comment]
hi @amaltaro 

> Do I understand it correctly that it only affects workflow assignment via ReqMgr2 Web UI

Yes, so far this is what my findings point to. Only the Web UI and no other ReqMgr2 interfaces are affected.
