### ISSUE TITLE
Agents stuck with "bash: fork: retry: No child processes"

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11289]
**Impact of the bug**
WMAgent

**Describe the bug**
The whole system becomes not functional, no data reported to wmstats, we are not able to renew the user proxy for job submission/execution, and even terminal commands are not functional. It might be what is called as "fork bomb".

I am not able to do anything, open the component log, kill process, list processes, etc. Here is the terminal output [1]

It's worth mentioning that this is a new issue (comparing WMAgent 2.1.2 vs 2.0.4), so it's likely something that one of the python 3rd-party libraries update brought in. 

**How to reproduce it**
No clue

**Expected behavior**
Well, what I can say is that it should not happen. If this is a limit of processes per user, then we might have to update the kernel limits.
One good deliverable for this ticket is to review all the kernel limits (ulimit) in all the FNAL and CERN nodes and set it to a consistent and more stable/robust values.
 
**Additional context and error message**
[1]
```
amaltaro@vocms0267:~ $ cmst1
cmst1@vocms0267:/afs/cern.ch/user/a/amaltaro $ agentenv 
cmst1@vocms0267:/data/srv/wmagent/current $ ps aux | grep python
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: Resource temporarily unavailable
```

**Comment by amaltaro** [comment]
The CMS@Home agent is completely down now, here is a ticket that Ivan created today:
https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3238446

@todor-ivanov from your description in mattermost, I understand that this is exactly the same issue that you resolved in the RelVal agent yesterday. Could you please have a look at vocms0267?

**Comment by todor-ivanov** [comment]
Thanks @amaltaro  I'll take care of this

**Comment by todor-ivanov** [comment]
Hi @amaltaro In this case I just had to restart the agent. The issue itself has been gone at the time I logged in. I did check the resource limits though, and  for this agent they are the default ones:

```
max user processes              (-u) 4096
```

**Comment by todor-ivanov** [comment]
On the other hand, even though I am not quite sure it is 100% related, but still worth mentioning here. We've started to notice `AgentStatusWatcher` failing on few agents with the following error:
```
2022-09-19 06:53:36,426:139722706917120:INFO:BaseWorkerThread:AgentStatusPoller took 0.003 secs to execute
2022-09-19 06:53:36,536:139722706917120:ERROR:LogDB:LogDBBackend delete API failed, error=(58, 'could not load PEM client certificate, OpenSSL error error:02001018:system library:fopen:Too many open files, (no key found, wrong pass phrase, or wrong file format?)')
2022-09-19 06:58:36,963:139722706917120:ERROR:LogDB:LogDBBackend delete API failed, error=(58, 'could not load PEM client certificate, OpenSSL error error:02001018:system library:fopen:Too many open files, (no key found, wrong pass phrase, or wrong file format?)')
2022-09-19 06:58:36,964:139722706917120:INFO:AgentStatusPoller:Getting agent info ...
2022-09-19 06:58:36,967:139722706917120:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2.patch1/lib/python3.8/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 136, in algorithm
    agentInfo = self.collectAgentInfo()
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2.patch1/lib/python3.8/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 201, in collectAgentInfo
    agentInfo = self.wmagentDB.getComponentStatus(self.config)
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2.patch1/lib/python3.8/site-packages/WMComponent/AnalyticsDataCollector/DataCollectAPI.py", line 260, in getComponentStatus
    if not daemon.isAlive():
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2.patch1/lib/python3.8/site-packages/WMCore/Agent/Daemon/Details.py", line 84, in isAlive
    dummyse, dummyso, rc = run('ps -p %s' % self['ProcessID'])
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2.patch1/lib/python3.8/site-packages/WMCore/Agent/Daemon/Details.py", line 27, in run
    proc = subprocess.Popen(
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/subprocess.py", line 804, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/data/srv/wmagent/v2.1.2.patch1/sw/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/subprocess.py", line 1468, in _get_handles
    p2cread, p2cwrite = os.pipe()
OSError: [Errno 24] Too many open files

```

**Comment by amaltaro** [comment]
@todor-ivanov did you manage to come up with a set of tweaks that we need to perform?
We keep getting failures with the agents, now it's submit5 and submit6, can you please update this ticket today with what are the tweaks that need to be performed?

We also need to contact the FNAL and CERN team to persist such changes under the puppet manifest.

**Comment by amaltaro** [comment]
I am not sure, but it could be related to this issue in the `stomp.py` library (FYI @mrceyhun ):
https://github.com/jasonrbriggs/stomp.py/issues/323

Now checking components on submit5, we have the following PID for AgentStatusWatcher:
```
[cmsdataops@cmsgwms-submit5 current]$ $manage status
Component:AgentStatusWatcher Running:3909028
```

and here is the total number of sockets opened by this PID:
```
[cmsdataops@cmsgwms-submit5 current]$ ls -la /proc/3909028/fd  | wc -l
1026
```

thus exceeding the soft limit for file descriptors in this node:
```
[cmsdataops@cmsgwms-submit5 current]$ ulimit -aS
open files                      (-n) 1024
```

**Comment by todor-ivanov** [comment]
This morning I noticed the issue at vocms0252 this morning. So far there is only one parameter that needs to be tuned in order to mitigate the effect for the time being: 

`ulimit -u 60177`  or alternatively (for permanently preserving the change) adding the following line:

```
cmst1          soft    nproc     60177
``` 

to `/etc/security/limits.d/20-nproc.conf``

BTW the number is not exactly random, but rather taken from the default values for a Debian 10 system. 

We will have to debug this one to the bottom. Last night I did notice the number of `ESTABLISHED` TCP session at those machines was quite stable, but on the other hand I also noticed many sessions restarting and the numbers were quite volatile in that regard. This indeed may be a clue pointing to the same bug @amaltaro is mentioning above.

I am contacting the VOC to apply the temporary fix. That would by us a little bit more time.

**Comment by todor-ivanov** [comment]
And here is the Jira ticket to the VOC: 
https://its.cern.ch/jira/browse/CMSVOC-395

**Comment by amaltaro** [comment]
> I am contacting the VOC to apply the temporary fix. That would buy us some more time.

@todor-ivanov if we increase the soft limit to that value, don't we have to bump the hard limit as well?

Please make the same request to the FNAL team (HyunWoo?), such that we get this change applied to all our schedds.

**Comment by todor-ivanov** [comment]
Hi @amaltaro 

> @todor-ivanov if we increase the soft limit to that value, don't we have to bump the hard limit as well (to at least the same value)?

I have tested it with a regular user and it worked, meaning the the soft value should already be in the possible range, but you are right, we'd better use: [1] instead, which should set both - `soft` && `hard` limits accordingly.


BTW, just to make a clarification here. This is not a global limit that will be permanently associated  with all processes originating from the user. These are limits which are set at the login session through the PAM module. What it means is it would just give us the chance to properly log into the machine and start rebooting agents when we find components stuck. This was previously impossible. We still need to find what is causing all this. 
 
[1]
```
cmst1          -    nproc     60177
```

**Comment by amaltaro** [comment]
Thanks Todor.
@todor-ivanov then please provide specific instructions to the VoC to avoid any possible miscommunications and/or mistakes.

Also provide the foreman hostgroup for the CERN nodes (in the JIRA ticket), which is:
```
* Puppet environment: production (but can be applied in qa as well)
* Foreman hostgroup: vocms/production/schedd
```

**Comment by todor-ivanov** [comment]
> please provide specific instructions to the VoC

DONE

**Comment by amaltaro** [comment]
I updated the JIRA ticket as well. I see there are already different limits defined for the CERN schedds under /etc/security/limits.conf. I have seen a few agents failing with this "too many open files", but I don't know if those changes are new or if they have always been there. If the latter, then we might have to re-evaluate how to properly workaround this issue before Germano and HyunWoo perform further changes to the template.

**Comment by amaltaro** [comment]
Ceyhun provided a fix for the CMSMonitoring library. I have applied it to the RelVal agent (vocms0258), please see this for further details:
https://github.com/dmwm/CMSMonitoring/pull/167

Late today we can see whether this fix works well or not.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro  @mrceyhun !

**Comment by amaltaro** [comment]
Ceyhun's patch of the StompAMQ7 module resolved this issue. I applied the patch above to all the production agents and restarted AgentStatusWatcher.

Once a new CMSMonitoring package is made available in PyPi, we can update the requirements here in the WMCore, update cmsdist, and release a WMAgent 2.1.2.patch2 with the fix in place.

**Comment by amaltaro** [comment]
Ok, even though this has been automatically closed with that PR, we still need to get back to Germano (VoC) and complete those kernel settings on the CERN agents.

@todor-ivanov was this file created by you (maybe on all nodes):
/etc/security/limits.d/20-nproc.conf ?

It has a setting that will override /etc/security/limits.conf. 

I would like to keep both CERN and FNAL nodes consistent with these parameters. For FNAL, these are the changes applied to all the schedds:
```
cmsdataops soft nofile 46080
cmsdataops hard nofile 65536
cmsdataops soft nproc 16384
cmsdataops hard nproc 65536
```

so we need to have the same on the CERN side (replacing cmsdataops by cmst1 though). It does not matter if it goes to limits.conf or another file in the limits.d directory.

Todor, since you are almost on the same timezone as the VoC, can you please make sure it happens on Monday? Please check a few nodes to make sure we don't have redundant information and that it actually gets correctly applied.
