### ISSUE TITLE
ErrorHandler trying to update null document in CouchDB

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11340]
**Impact of the bug**
WMAgent

**Describe the bug**
Overnight we have had many alarms for submit5 and vocms0252, where ErrorHandler gets automatically restarted.
Looking into vocms0252 logs, I see this error occurring over and over [1], eventually one of those exceptions is not expected and the component gets terminated (waiting to be restarted by a cronjob).

**How to reproduce it**
Not yet clear

**Expected behavior**
ErrorHandler should be able to successfully upload documents to CouchDB. If the document it's trying to update does not exist, we should investigate why is that. Another option would be to create a document if it does not exist.

**Additional context and error message**
[1]
```
2022-10-12 12:45:09,780:140652455094016:INFO:ErrorHandlerPoller:About to process 500 failures
2022-10-12 12:45:09,780:140652455094016:INFO:ErrorHandlerPoller:Processing retries for 500 failed jobs of type jobfailed
2022-10-12 12:45:09,999:140652455094016:ERROR:ChangeState:Error updating job in couch: CouchInternalServerError - reason: Internal Server Error, data: None result: b'{"error":"render_error","reason":"function raised error: (new TypeError(
\\"doc is null\\", \\"updates.jobSummaryState\\", 2)) \\nstacktrace: (null,[object Object])@updates.jobSummaryState:2\\nrunUpdate(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [do
c, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1052\\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./sha
re/server/main.js:1143\\n(\\"_design/WMStatsAgent\\",[object Array],[object Array])@./share/server/main.js:1621\\n()@./share/server/main.js:1667\\n()@./share/server/main.js:1688\\n@./share/server/main.js:1\\n"}\n'
2022-10-12 12:45:10,001:140652455094016:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 131, in makeRequest
    result, status, reason, cached = JSONRequests.makeRequest(
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 173, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 190, in makeRequest_pycurl
    response, result = self.reqmgr.request(uri, data, headers, verb=verb,
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 351, in request
    raise exc
http.client.HTTPException: url=http://localhost:5984/wmagent_summary/_design/WMStatsAgent/_update/jobSummaryState/38c5d5c3-f196-40e6-8030-0b888db1e9dd?newstate=jobfailed&timestamp=1665571509, code=500, reason=Internal Server Error, header
s={'Cache-Control': 'must-revalidate', 'Content-Length': '741', 'Content-Type': 'application/json', 'Date': 'Wed, 12 Oct 2022 10:45:09 GMT', 'Server': 'CouchDB/3.2.2 (Erlang OTP/22)', 'X-Couch-Request-ID': 'b8e99d7813', 'X-CouchDB-Body-Ti
me': '0'}, result=b'{"error":"render_error","reason":"function raised error: (new TypeError(\\"doc is null\\", \\"updates.jobSummaryState\\", 2)) \\nstacktrace: (null,[object Object])@updates.jobSummaryState:2\\nrunUpdate(function (doc, r
eq) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1052\\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = 
parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1143\\n(\\"_design/WMStatsAgent\\",[object Array],[object Array])@./share/server/main.js:1621\\n()@./share/server/main.js:1667\\
n()@./share/server/main.js:1688\\n@./share/server/main.js:1\\n"}\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 178, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 304, in recordInCouch
    self.jsumdatabase.makeRequest(uri=updateUri, type="PUT", decode=False)
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 135, in makeRequest
    self.checkForCouchError(getattr(e, "status", None),
  File "/data/srv/wmagent/v2.1.2/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.1.2/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 171, in checkForCouchError
    raise CouchInternalServerError(reason, data, result)
WMCore.Database.CMSCouch.CouchInternalServerError: CouchInternalServerError - reason: Internal Server Error, data: None result: b'{"error":"render_error","reason":"function raised error: (new TypeError(\\"doc is null\\", \\"updates.jobSummaryState\\", 2)) \\nstacktrace: (null,[object Object])@updates.jobSummaryState:2\\nrunUpdate(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1052\\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1143\\n(\\"_design/WMStatsAgent\\",[object Array],[object Array])@./share/server/main.js:1621\\n()@./share/server/main.js:1667\\n()@./share/server/main.js:1688\\n@./share/server/main.js:1\\n"}\n'
```

**Comment by amaltaro** [comment]
Apparently it was a transient problem, which went away at 1pm CERN time (on vocms0252).
Regarding FNAL submit5, ErrorHandler was crashing as well, but apparently because it could not upload documents to central CouchDB (acdcserver db).

I am going to keep an eye on this for the coming days, but please let me know if you spot any issues with ErrorHandler component. @khurtado @todor-ivanov

**Comment by amaltaro** [comment]
It's been 13 days since the last update and this problem has not re-occurred, so I am closing this out.
In case ErrorHandler hits the same issue in the near future, we should reopen it and properly investigate and address this issue.
