### ISSUE TITLE
Missing AlertManagerAPI for MSOutput instance

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11350]
**Impact of the bug**
MSOutput

**Describe the bug**
While working with https://github.com/dmwm/WMCore/pull/11280 and https://github.com/dmwm/WMCore/pull/11020 I found that we were living with a bug in MSOuput for quite long now. Every time the service tries to use Alert Manager to send an alert it actually fires an exception [1] and does not manage to send any error or whatsoever. This is coming from this line here: https://github.com/dmwm/WMCore/blob/e0c39d56b70dc5a6b4c3ac3d996bde68b5bb12fb/src/python/WMCore/MicroService/MSOutput/MSOutput.py#L780 (and actually also from few more similar to this one) 

It seems there is no `self.alertManagerAPI` object inside the `MSOutput` instance. I am not yet quite sure if it needs to be created by `MSOutput` itself or inherited from `MSCore` but it definitely does not end up in the service instance with the current implementation.
 
**How to reproduce it**
Try to send an alert through AlertManager with the current MSOutput object. (could be done even in standalone and interactive mode).

**Expected behavior**
To have the relevant object present in the service instance and to be used properly for sending alerts.

**Additional context and error message**

[1]
```
2022-10-25 08:21:41,534:ERROR:MSOutput: 'MSOutput' object has no attribute 'alertManagerAPI'
Traceback (most recent call last):
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 57
3, in msOutputProducer
    msPipeline.run(request)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 140, in run
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 140, in <lambda>
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 72, in __call__
    return self.run(obj)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 75, in run
    return self.func(obj, *self.args, **self.kwargs)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 66
4, in docInfoUpdate
    if not self.canDatasetGoToDisk(dataItem, msOutDoc['IsRelVal']):
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 78
0, in canDatasetGoToDisk
    self.alertManagerAPI.sendAlert(alertName, alertSeverity, alertSummary, alertDescription, self.alertServiceName)
AttributeError: 'MSOutput' object has no attribute 'alertManagerAPI'

```

**Comment by amaltaro** [comment]
@todor-ivanov can you please check whether the instance you are running actually has the `alertManagerUrl` configuration attribute?
That object should have been created here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSCore/MSCore.py#L51-L52
and inherited by the MSOutput code.

**Comment by amaltaro** [comment]
@todor-ivanov I just found out that we are hitting this bug in production! Here is a snippet of the log file:
```
2022-10-30 08:34:44,600:CRITICAL:MSOutput: Dataset: /MinBias_Hydjet_Drum5F_5p02TeV/Run3Winter22PbPbNoMixDIGI-122X_mcRun3_2021_realistic_HI_v10-v3/GEN-SIM-DIGI-RAW-HLTDEBUG contains a datatier: GEN-SIM-DIGI-RAW-HLTDEBUG not yet inserted in
to Unified configuration. Please add it ASAP. Letting it pass for now...
2022-10-30 08:34:44,600:ERROR:MSOutput: 'MSOutput' object has no attribute 'alertManagerAPI'
Traceback (most recent call last):
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 573, in msOutputProducer
    msPipeline.run(request)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 140, in run
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 140, in <lambda>
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 72, in __call__
    return self.run(obj)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/Utils/Pipeline.py", line 75, in run
    return self.func(obj, *self.args, **self.kwargs)
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 664, in docInfoUpdate
    if not self.canDatasetGoToDisk(dataItem, msOutDoc['IsRelVal']):
  File "/data/srv/HG2210b/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.3.pre1/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 780, in canDatasetGoToDisk
    self.alertManagerAPI.sendAlert(alertName, alertSeverity, alertSummary, alertDescription, self.alertServiceName)
AttributeError: 'MSOutput' object has no attribute 'alertManagerAPI'
```

from the traceback, I have the impression that whenever this exception is hit, the whole Producer cycle gets stopped.

This likely explains why we have accumulated 12k requests sitting in `announced` status and not moving forward in MSRuleCleaner.

**Comment by todor-ivanov** [comment]
hi @amaltaro I am moving this on top of my priority list .... we will have to create a patch for this though.

**Comment by amaltaro** [comment]
It looks like there are a couple of problems with this service.
1. the service was getting restarted over and over (cherrypy signal 9). I suspect its memory footprint was exceeding the limit defined in the yaml file (750MB). I edited the service with `kubectl edit deploy ms-output -n dmwm` requesting 750MiB and setting a limit to 1500MiB. It seems to be better now!
2. After some debugging, I confirm that `self.alertManagerAPI` is properly created by MSCore, but when it's going to be used by MSOutput object, it fails to find that attribute. I still can't explain it though!

In order to get things moving forward, I connected to the POD and made the following service configuration change:
```
data.sendNotification = False  # SEND_NOTIFICATION
```

such that we don't try to access that inexistent alertManagerAPI attribute. After a service restart, I see that the Producer process actually completed the whole cycle and managed to create the expected documents (see the huge backlog):
```
2022-11-02 20:23:27,663:INFO:MSOutput: MSOutputProducer: Total 10531 requests processed from the streamer. 
```

On what concerns the memory utilization plots, we can refer to this link:
https://monit-grafana.cern.ch/d/M2U6T6uGk/kube-eagle-k8s-metrics?orgId=11&from=1667406731576&to=1667417531577&viewPanel=215

TODO: verify which changes are required to be done upstream (WMCore changes? CMSKubernetes changes?)

**Comment by vkuznet** [comment]
Can someone provide where this error happens, is it on WMAgent? According to posted output the release is 1.1.3.pre1 and if I look at github https://github.com/dmwm/WMCore/tree/1.1.3.pre1/src/python/WMCore I do not see any MicroService in WMCore area. May be I'm missing something but it seems to me it is old code which was patched and as such it may lack of MSCore class which defines `self.alertManagerAPI` member data. If you'll post the node then we can look at the release area to identify what is inherited (which will be based on PYTHONPATH at run time).

**Comment by amaltaro** [comment]
Fix for this issue has been provided in the PR linked above.

Nonetheless, I thought it strange that we were still not archiving any workflows. It turns out that now that MSOutput managed to create ~11k transfer documents, MSRuleCleaner memory footprint became much bigger and the service was getting restarted - within the container - as well.

I did the same temporary trick and increased the container memory requirements with `kubectl edit deploy ms-rulecleaner -n dmwm`, boosting the previous limit of 750MiB to 1500MiB. Things are looking good so far and I already see ~400 workflows archived in the last 20min or so. Once the backlog is over, the resource increase is probably no longer needed.

**Comment by todor-ivanov** [comment]
hi @vkuznet 

> Can someone provide where this error happens, is it on WMAgent?

This is central services. The `1.1.3.pre1` release is the microservice release. It goes one major version behind the central services but it is still properly linked to the proper WMCore tag: https://github.com/amaltaro/cmsdist/blob/6a92ab867a63dbe7c9f23e3d3e31e615059cacbc/reqmgr2ms.spec#L1-L6
