### ISSUE TITLE
MSUnmerged failing to connect to RucioConMon due to a change in the endpoint URL

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11388]
**Impact of the bug**
MSUnmereged

**Describe the bug**
We found  out that  MSUnmerged is failing to fetch RSE statistics from Rucio Consitency Montior [1]. Our service is trying to contact the following URl:

https://cmsweb.cern.ch/rucioconmon/WM/stats

While this one works:

https://cmsweb.cern.ch/rucioconmon/unmerged/stats

Same for the file lists per RSE API:

https://cmsweb.cern.ch/rucioconmon/WM/files?rse=T2_DE_DESY&format=json  vs. https://cmsweb.cern.ch/rucioconmon/unmerged/files?rse=T2_DE_DESY&format=json

Obviously, at some moment, the endpoint prefix has changed from:
*  from: https://cmsweb.cern.ch/rucioconmon/unmerged/stats
* to:  https://cmsweb.cern.ch/rucioconmon/WM 
and the change has not been reflected in our code/configuration.

**How to reproduce it**
Just try to contact the old Url

**Expected behavior**
The Url for a service in production not to change without a notice.

**Additional context and error message**
[1]
```
2022-12-09 01:59:19,359:ERROR:MSUnmerged: Unknown exception while trying to fetch statistics from Rucio Consistency Monitor. Error: url=https://cmsweb.cern.ch:8443/rucioconmon//WM/stats, code=404, reason=Not Found, headers={'Date': 'Fri, 09 Dec 2022 00:59:19 GMT', 'Server': 'Apache', 'Content-Type': 'application/json', 'Content-Length': '135', 'X-WebPie-Request-Id': 'UHk.331', 'CMS-Server-Time': 'D=18447 t=1670547559340442'}, result=b'{"message": "The resource could not be found.<br /><br />\\nInvalid path //WM/stats\\n\\n", "code": "404 Not Found", "title": "Not Found"}'
Traceback (most recent call last):
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSUnmerged/MSUnmerged.py", line 216, in execute
    self.rseConsStats = self.rucioConMon.getRSEStats()
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/RucioConMon/RucioConMon.py", line 104, in getRSEStats
    rseStats = self._getResult(uri, callname='stats')
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/RucioConMon/RucioConMon.py", line 76, in _getResult
    with self.refreshCache(cachedApi, apiUrl) as istream:
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/Service.py", line 218, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType, binary=binary)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/Service.py", line 362, in getData
    raise he
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/Service.py", line 318, in getData
    data, dummyStatus, dummyReason, from_cache = self["requests"].makeRequest(uri=url,
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 173, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 190, in makeRequest_pycurl
    response, result = self.reqmgr.request(uri, data, headers, verb=verb,
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/Utils/PortForward.py", line 67, in portMangle
    return callFunc(callObj, newUrl, *args, **kwargs)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 341, in request
    raise exc
http.client.HTTPException: url=https://cmsweb.cern.ch:8443/rucioconmon//WM/stats, code=404, reason=Not Found, headers={'Date': 'Fri, 09 Dec 2022 00:59:19 GMT', 'Server': 'Apache', 'Content-Type': 'application/json', 'Content-Length': '135', 'X-WebPie-Request-Id': 'UHk.331', 'CMS-Server-Time': 'D=18447 t=1670547559340442'}, result=b'{"message": "The resource could not be found.<br /><br />\\nInvalid path //WM/stats\\n\\n", "code": "404 Not Found", "title": "Not Found"}'
```

**Comment by amaltaro** [comment]
As discussed over Slack, we need to:
* find out whether the uri API really changed?
* if so, when was that? and where was that announced?
* if there is any functionality/format change to the request and response object

Lastly, it might give us a clue that we should have an alert for these basic initial data that we collect before proceeding with the removal logic. Especially because the interval of MSUnmerged is pretty large (8h?). I think this can be done as an extra ticket for the future though.

**Comment by todor-ivanov** [comment]
That's a good idea @amaltaro 
I'd say we may think of creating a general mechanism to upload all types of exceptions from our logs to `monit` in addition to the alerts we create.
