### ISSUE TITLE
Broken production depoyment and startup for Services using MongoDBAs A Service

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11439]
**Impact of the bug**
MSRulecleaner, MSOutput, MSUnmerged

**Describe the bug**
Not a bug on our side but we need to track this in our project as well.

During today's  deployment of WMCore v2.1.6  in production, we did experience some issues with all services using MongoDB As A Service (either directly or through the `MSOutput` REST interface). The services were failing to startup with the following error: [2]. The reason is not on our side but rather on the CMSWEB cluster providing the MongoDB instance for us. Here [[1]](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3350736) in this SNOW ticket are the details related to the broken MongoDB instance, provided by the CMSWeb Team to CERN IT in order to tackle the problem. 

The issue is not related to the deployment itself. It has started on Monday and it simply went unnoticed until today.  Both `MSUnmerged` and `MSOutput` do require a direct connection to the database, so they do fail with the error mentioned above, and were filling the logs with the above exceptions on every polling cycle since Monday `[09/Jan/2023:12:10:57] `, but were not  failing the service itself. That's why they went unnoticed until today's deployment. 

On the other hand `MSRulecleaner` does not require a direct database connection, but it uses the `MSOutput`'s REST interface to reach to the data it needs. It still fails on the very first workflow (again in every polling cycle) with [3]. 

The problem was  also difficult to debug even during service startup today, because the output of `run.sh` with the pod's startup is not preserved anywhere. We had to figure out through old logs, from previous, days what the problem was. 

Currently the services are  stopped. And we are waiting for resolution on the issue with the MongoDB As A Service cluster. Upon that the actions required from us is to redeploy the three services.    

The problem is not present in the `preprod` environment - the test MongoDBAsAService cluster at `mongodb-cms-test.cern.ch` s working properly. 

P.S. Because the service behaves differently when losing the database at runtime vs. startup time, we may consider creating two types of alarms:
* based on the logs from the service - meaning to cover service errors of the type during runtime
* based on the presence of the service - meaning to cover service  startup errors and preserve output from `run.sh` 
(the `liveness` probe for the pods did not catch the broken service startup, I suspect, because `run.sh`  script somewhere forks a background continuous tail process:
```
_reqmgr+      11  0.0  0.0   5928  3524 ?        S    12:32   0:00 /bin/bash /data/run.sh
_reqmgr+      67  0.0  0.0   4324   576 ?        S    12:32   0:00  \_ tail -f /etc/hosts
```   

**How to reproduce it**
Try to connect to a broken MongoDBAs a Service instance with any of the services above.

**Expected behavior**
To properly alarm about broken  service runs /polling cycles due to broken database connection.

**Additional context and error message**

[1]
https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3350736

[2]

```
[10/Jan/2023:00:51:57] ms-output-574645cc45-jdgtk 127.0.0.1 "GET /ms-output/data/status HTTP/1.1" 200 OK [data: 300 in 246 out 865 us ] [auth: OK "" "" ] [ref: "" "Go-http-client/1.1" ]
2023-01-10 00:51:57,883:ERROR:MSOutput: MSOutputConsumer: Unknown exception while running Consumer thread. Error: mongodb-m7wwpbnzgide-node-0.cern.ch:32001: [Errno 111] Connection refused,mongodb-m7wwpbnzgide-node-0.cern.ch:32002: [Errno 111] Connection refused,mongodb-m7wwpbnzgide-node-0.cern.ch:32003: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6391c82406623b47ce13e5d4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-m7wwpbnzgide-node-0.cern.ch', 32001) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-m7wwpbnzgide-node-0.cern.ch:32001: [Errno 111] Connection refused')>, <ServerDescription ('mongodb-m7wwpbnzgide-node-0.cern.ch', 32002) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-m7wwpbnzgide-node-0.cern.ch:32002: [Errno 111] Connection refused')>, <ServerDescription ('mongodb-m7wwpbnzgide-node-0.cern.ch', 32003) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-m7wwpbnzgide-node-0.cern.ch:32003: [Errno 111] Connection refused')>]>
Traceback (most recent call last):
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 283, in _executeConsumer
    total_num_requests = self.msOutputConsumer()
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 526, in msOutputConsumer
    for docOut in self.getDocsFromMongo(mQueryDict, dbColl, self.msConfig['limitRequestsPerCycle']):
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSOutput/MSOutput.py", line 931, in getDocsFromMongo
    for mongoDoc in dbColl.find(mQueryDict):
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/external/py3-pymongo/4.2.0/lib/python3.8/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongodb-m7wwpbnzgide-node-0.cern.ch:32001: [Errno 111] Connection refused,mongodb-m7wwpbnzgide-node-0.cern.ch:32002: [Errno 111] Connection refused,mongodb-m7wwpbnzgide-node-0.cern.ch:32003: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6391c82406623b47ce13e5d4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-m7wwpbnzgide-node-0.cern.ch', 32001) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-m7wwpbnzgide-node-0.cern.ch:32001: [Errno 111] Connection refused')>, <ServerDescription ('mongodb-m7wwpbnzgide-node-0.cern.ch', 32002) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-m7wwpbnzgide-node-0.cern.ch:32002: [Errno 111] Connection refused')>, <ServerDescription ('mongodb-m7wwpbnzgide-node-0.cern.ch', 32003) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb-m7wwpbnzgide-node-0.cern.ch:32003: [Errno 111] Connection refused')>]>
2023-01-10 00:51:57,884:INFO:MSManager: Total outputConsumer execution time: 30 secs

```

[3]
```
[09/Jan/2023:16:00:10] ms-rulecleaner-658c5d67d8-src5n 127.0.0.1 "GET /ms-rulecleaner/data/status HTTP/1.1" 200 OK [data: 305 in 306 out 1483 us ] [auth: OK "" "" ] [ref: "" "Go-http-client/1.1" ]
2023-01-09 16:00:24,561:ERROR:MSRuleCleaner: General exception while fetching TransferInfo from MSOutput for cmsunified_task_SMP-RunIISummer20UL16wmLHEGENAPV-00467__v1_T_220914_200134_906. Error: url=https://cmsweb.cern.ch:8443/ms-output/data/info?request=cmsunified_task_SMP-RunIISummer20UL16wmLHEGENAPV-00467__v1_T_220914_200134_906, code=500, reason=Internal Server Error, headers={'Date': 'Mon, 09 Jan 2023 15:00:24 GMT', 'Server': 'Apache', 'Set-Cookie': 'cms-auth=5c6c3ce006d168a543e689d6d8eaaaf4cab9086b0d5be89ef06b84a9b590a15430d0b2c6661e3266;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Content-Length': '742', 'X-Rest-Status': '400', 'X-Error-Http': '500', 'X-Error-Id': '6077fcb5143aed42e12f002537fa6d0a', 'X-Error-Detail': 'Server error', 'X-Rest-Time': '30269808.054 us', 'CMS-Server-Time': 'D=30298678 t=1673276394250013', 'Connection': 'close'}, result=b'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>Server error</p>\n        <pre id="traceback"></pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.dev">CherryPy 18.8.0</a>\n      </span>\n    </div>\n    </body>\n</html>\n'
Traceback (most recent call last):
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 624, in getMSOutputTransferInfo
    res = self.curlMgr.getdata(url, params=params, headers=headers, ckey=ckey(), cert=cert())
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 351, in getdata
    _, data = self.request(url=url, params=params, headers=headers, verb=verb,
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/Utils/PortForward.py", line 67, in portMangle
    return callFunc(callObj, newUrl, *args, **kwargs)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 341, in request
    raise exc
http.client.HTTPException: url=https://cmsweb.cern.ch:8443/ms-output/data/info?request=cmsunified_task_SMP-RunIISummer20UL16wmLHEGENAPV-00467__v1_T_220914_200134_906, code=500, reason=Internal Server Error, headers={'Date': 'Mon, 09 Jan 2023 15:00:24 GMT', 'Server': 'Apache', 'Set-Cookie': 'cms-auth=5c6c3ce006d168a543e689d6d8eaaaf4cab9086b0d5be89ef06b84a9b590a15430d0b2c6661e3266;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Content-Length': '742', 'X-Rest-Status': '400', 'X-Error-Http': '500', 'X-Error-Id': '6077fcb5143aed42e12f002537fa6d0a', 'X-Error-Detail': 'Server error', 'X-Rest-Time': '30269808.054 us', 'CMS-Server-Time': 'D=30298678 t=1673276394250013', 'Connection': 'close'}, result=b'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>Server error</p>\n        <pre id="traceback"></pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.dev">CherryPy 18.8.0</a>\n      </span>\n    </div>\n    </body>\n</html>\n'
2023-01-09 16:00:24,562:ERROR:MSRuleCleaner: Unknown exception while running MSRuleCleaner thread Error: local variable 'transferInfo' referenced before assignment
Traceback (most recent call last):
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 222, in execute
    totalNumRequests, cleanNumRequests, normalArchivedNumRequests, forceArchivedNumRequests = self._execute(requestRecords)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 263, in _execute
    self._dispatchWflow(wflow)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 296, in _dispatchWflow
    self.getMSOutputTransferInfo(wflow)
  File "/data/srv/HG2212d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/1.1.5rc7/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 632, in getMSOutputTransferInfo
    if transferInfo is None:
UnboundLocalError: local variable 'transferInfo' referenced before assignment
2023-01-09 16:00:24,563:INFO:MSManager: Total ruleCleaner execution time: 39 secs

```

**Comment by todor-ivanov** [comment]
I am not sure if that is related, but since yesterday we  started receiving the following alarm: 
I did check and we are not the one to define that alarm. it comes from monit.


FYI @amaltaro 

```
  {
    "annotations": {
      "description": "There is no data from ReqMgr2 CPU, please that service is running.",
      "summary": "cmsweb ReqMgr2-globalR CPU rate"
    },
    "endsAt": "2023-01-13T10:27:05.169Z",
    "fingerprint": "4792be2b2308bb55",
    "receivers": [
      {
        "name": "dmwm"
      }
    ],
    "startsAt": "2023-01-12T11:24:03.000Z",
    "status": {
      "inhibitedBy": [],
      "silencedBy": [],
      "state": "active"
    },
    "updatedAt": "2023-01-13T10:22:05.169Z",
    "generatorURL": "https://monit-grafana.cern.ch/d/cmsweb_reqmgr/reqmgr2?tab=alert&viewPanel=2&orgId=11",
    "labels": {
      "alert": "grafana",
      "alertname": "cmsweb ReqMgr2-globalR CPU rate",
      "metric": "NoData",
      "service": "reqmgr2",
      "severity": "high",
      "tag": "cmsweb"
    }
  }
```

**Comment by todor-ivanov** [comment]
And now we have the services back up and running. The issue with the MongoDB instance was figurred out to be a misbehaving of the livenes  probe of the MongoDBAsAService cluster. 

 I am closing the issue, here.

**Comment by todor-ivanov** [comment]
I forgot to mention. We have also changed  the log names for Micro services, which also added a little bit of confusion this time.
E.g.:
from:
`ms-rulecleaner-20230112-ms-rulecleaner-658c5d67d8-src5n.log`
to 
`
reqmgr2ms-20230113-ms-rulecleaner-84df77fdd4-scn8x.log
`

**Comment by amaltaro** [comment]
@todor-ivanov concerning the logs that you mentioned above. Where have the changes being made? I might be wrong, but I expect changes to be required for both the service configuration and for CMSKubernetes yaml files as well. Please provide any commit/PRs with the changes mentioned above.

**Comment by amaltaro** [comment]
In addition to the comment above, could you please clarify what the actual problem was with MongoDB? Did we have to change the current setup? Is there any action items for the near future (regardless whether it is on us or not)? Even though I was involved in this debugging, I didn't follow all the discussions very closely, so I would appreciate if you can share this in a few sentences with the team.

**Comment by todor-ivanov** [comment]
Hi @amaltaro 
> Where have the changes being made?

I am not sure, there have been any change dedicated to log renaming itself. To me the change comes from the fact that  we renamed the pods when splitting the micro services in their own package each.  

And the log name is simply created here: 
https://github.com/dmwm/CMSKubernetes/blob/d1780db3ef0873a734461a254086a55d83cc5c8b/kubernetes/cmsweb/services/reqmgr2ms-output.yaml#L15

**Comment by todor-ivanov** [comment]
> could you please clarify what the actual problem was with MongoDB? 

For some unknown reason, the `liveness` probe for those pods serving the MongoDB As A Service instance were failing to connect, while internally the service (`Mongod`) was running ok. The problem has been triggered most probably because  all pods were served by a single node - `node-0` initially. And then the traffic has been redirected through `NodePort` to it IIUC.  So `node-0` (possibly) has an alias pointing to it so only this node has been attempted to be contacted directly. 
When Ricardo looked at the cluster, he found the pods were served all by `node-1` . Several attempts were made to rebuild the cluster such that `node-0` is forced to serve them again, but the livenes probe continued to fail, which was causing a continuous restart of the service. So at some point it was switched of by @muhammadimranfarooqi and then the service got stable. I hope I am not forwarding any wrong information, @arooshap  and @muhammadimranfarooqi  may correct me if I am wrong here.   All is followed in this SNOW ticket: https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3350736


> Did we have to change the current setup? 

No at the end we were left with the same setup that we were having in production so far.
 
> Is there any action items for the near future (regardless whether it is on us or not)?

Well yes. We must do few things:
* Recreate the setup that we have in the test cluster and get rid of the LoadBalancer.
* Distributing all pods on multiple notes/hosts (but still using one pod per replicaset), such that similar failures are avoided in the future. 
* Eventually, revisit/get rid of any aliases for the entry point. 

The place  to track all those items should be the dedicated Jira ticket [1], as before. And this time CERNIT people are also offering their help and advises in order to make this happen.

[1]
https://its.cern.ch/jira/browse/CMSKUBERNETES-175

**Comment by amaltaro** [comment]
Todor, thank you for this summary!

> Well yes. We must do few things:
>     Recreate the setup that we have in the test cluster and get rid of the LoadBalancer.
>     Distributing all pods on multiple notes/hosts (but still using one pod per replicaset), such that similar failures are avoided in the future.
>     Eventually, revisit/get rid of any aliases for the entry point.

I think Panos is back from vacation. Can you please update that JIRA ticket to ensure that people know what is left to be done on this front? Of course, always keeping in mind that any action on the production MongoDBAaS needs to be properly communicated and discussed with us. Thanks

**Comment by arooshap** [comment]
Hi @amaltaro and @todor-ivanov, I am working with Panos working to fix some issues with MongoDB. I faced some issues while creating a new testbed cluster for MongoDB. Somehow, the instructions for the mongoDB cluster setup are not enough. I will update the documentation as soon as I figure out these caveats. On the same side, I also created a new cluster for production MongoDB with the same setup that we have in the `dev` cluster.

The creation of the clusters is complete, however, there are some issues that I want to fix before making them available for use.


Thank you.

**Comment by arooshap** [comment]
@amaltaro, sorry for the double ping, but we are working on fixing the issues. And we will communicate ith you if we want to make any changes. Thanks.

**Comment by todor-ivanov** [comment]
Thanks @arooshap 
Let us know once/if our interaction is needed. One place I am sure we will need to do some changes on our side is once - once we get rid of the LB we should start  connecting  to the fully described replicaset as we do for testbed/prepropduction services. This means we will have to reconfigure the MS* services/pods  running in production which are using MongoDB. So in case you are ready to go in that  direction please let us know in advance. 
Thanks once  again.

**Comment by arooshap** [comment]
Hi @todor-ivanov, I have updates for you on the following ticket [CMSKubernetes-175](https://its.cern.ch/jira/browse/CMSKUBERNETES-175). Thanks.
