### ISSUE TITLE
ACDC failures due to missing policy args

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11508]
**Impact of the bug**
GlobalWorkQueue  

**Describe the bug**
While going through the Global WorkQueue logs I've stumbled on the following exception [1]. 
What I can say from a first glance it is happening only for ACDC workflows which are relying on default policy parameters:

```
INFO:reqmgrInteraction:Splitting /haozturk_ACDC0_Run2022D_BTagMu_10Dec2022_221221_171345_19/DataProcessingMergeDQMoutputEndOfRunDQMHarvestMerged with policy name ResubmitBlock and policy par
ams {'name': 'ResubmitBlock', 'args': {}}
```

Which are set here: https://github.com/dmwm/WMCore/blob/d89fc9ddee0e405e09f1deaa4fdeb895bf445947/src/python/WMCore/WorkQueue/WorkQueue.py#L1063

These types of ACDCs end up referring to `ResubmitBlock`: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py 

**NOTE:** Even though in the TraceBack the error stems from `File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 160, in __call__
    self.split()`,  the `ResubmitBlock` policy redefines the default `self.split()` method from   https://github.com/dmwm/WMCore/blob/d89fc9ddee0e405e09f1deaa4fdeb895bf445947/src/python/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py#L48 

with with its own:

https://github.com/dmwm/WMCore/blob/d89fc9ddee0e405e09f1deaa4fdeb895bf445947/src/python/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py#L50

for which no key `NumberOfRuns` is set. But how we end up referring to this key in the policy object is still a mystery to me.   
 
In addition, those workflows are constantly retried and are filling the GWQ logs.  
 
**How to reproduce it**
I have not yet figured out the full set of ACDC parameter that trigger such behavior. 

**Expected behavior**
To properly map all possible ACDC parameters to the given policy. 

**Additional context and error message**
[1]
```
INFO:reqmgrInteraction:Splitting /haozturk_ACDC0_Run2022D_BTagMu_10Dec2022_221221_171345_19/DataProcessingMergeDQMoutputEndOfRunDQMHarvestMerged with policy name ResubmitBlock and policy params {'name': 'ResubmitBlock', 'args': {}}
ERROR:reqmgrInteraction:Exception splitting wqe haozturk_ACDC0_Run2022D_BTagMu_10Dec2022_221221_171345_19 for haozturk_ACDC0_Run2022D_BTagMu_10Dec2022_221221_171345_19: 'NumberOfRuns'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1133, in processInboundWork
    work, rejectedWork, badWork = self._splitWork(inbound['WMSpec'], data=inbound['Inputs'],
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1073, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 160, in __call__
    self.split()
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py", line 70, in split
    Jobs=ceil(float(block[self.args['SliceType']]) /
KeyError: 'NumberOfRuns'
ERROR:reqmgrInteraction:Unknown error processing haozturk_ACDC0_Run2022D_BTagMu_10Dec2022_221221_171345_19
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 108, in queueNewRequests
    units = queue.queueWork(workLoadUrl, request=reqName, team=team)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 646, in queueWork
    work = self.processInboundWork(inbound, throw=True)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1133, in processInboundWork
    work, rejectedWork, badWork = self._splitWork(inbound['WMSpec'], data=inbound['Inputs'],
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1073, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 160, in __call__
    self.split()
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py", line 70, in split
    Jobs=ceil(float(block[self.args['SliceType']]) /
KeyError: 'NumberOfRuns'

```

**Comment by amaltaro** [comment]
This is not a bug! ACDC for harvesting jobs is not supported and it has already been communicated to the P&R team many times.

I am going to lower the priority of this issue and define a deliverable as: validate Resubmission workflow parameters such that it fails to create the workflow when it is meant to recover a LogCollect, or Cleanup or Harvesting task type. Providing a meaningful error message back to the client, of course.

**Comment by amaltaro** [comment]
@todor-ivanov please don't work on this issue in this quarter. We can schedule it for the coming quarters.
Please also ask the P&R team to abort this ACDC workflow, if they want to recover the harvesting job, the recommended way to do so is creating a DQMHarvest workflow (which at some point was part of the Unified machinery).

**Comment by todor-ivanov** [comment]
Thanks @amaltaro will communicate this with P&R

**Comment by amaltaro** [comment]
I am just cleaning up the assignees and status such that it correctly reflects what is in progress or not. Next time, please feel free to do so yourself.

**Comment by amaltaro** [comment]
I am setting this as a P&R stakeholder request and marking it as high priority, given that it takes person power from multiple groups to figure out what is happening.

**Comment by amaltaro** [comment]
Related to this issue: https://github.com/dmwm/WMCore/issues/11458

However, the best approach here is to really have a brand new workflow that will aggregate all of the relevant DQM/DQMIO at the same storage, otherwise we end up with incomplete statistics in the harvesting outcome.

Said that, I am very much in favor of detecting ACDC creation for DQMHarvest and fail it right away, in ReqMgr2. Such that the end user gets a clear message saying that this is not supported.

**Comment by amaltaro** [comment]
I still see such workflows polluting the logs
```
2024-06-10 00:00:18,721:ERROR:WorkQueue:Exception splitting wqe fuyan_ACDC1_Run2022E_ZeroBias_30May2023v2_240222_163718_5019 for fuyan_ACDC1_Run2022E_ZeroBias_30May2023v2_240222_163718_5019: 'NumberOfRuns'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1138, in processInboundWork
    work, rejectedWork, badWork = self._splitWork(inbound['WMSpec'], data=inbound['Inputs'],
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1078, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 167, in __call__
    self.split()
  File "/usr/local/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py", line 70, in split
    Jobs=ceil(float(block[self.args['SliceType']]) /
KeyError: 'NumberOfRuns'
```

So, we need to:
* add this case to the validation of ACDC workflows
* fail the workflow creation if it's targetting a DQMHarvest task
* finally, give a meaningful error message to the client.

This has to happen next quarter, because it will definitely not stop unless we implement it on the server side.

**Comment by amaltaro** [comment]
FYI.: I updated the expected behavior description above. In short, ACDC/recovery workflows for harvesting jobs is not supported and we should fail it whenever someone is creating such request in ReqMgr2.

**Comment by anpicci** [comment]
@amaltaro @todor-ivanov I am reclassifying this issue as dev, to take into consideration for Q2/2025
