### ISSUE TITLE
Perform pre-production validation of MSPileup

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11525]
**Impact of the new feature**
MSPileup

**Is your feature request related to a problem? Please describe.**
Now that we have all the pieces in place, we need to run a final battery of more realistic tests to ensure that MSPileup behaves.

**Describe the solution you'd like**
Perform realistic integration tests for MSPileup, including:
* create pileup
* update pileup
* delete pileup
* activate/disable pileup
* validate all the 5 tasks from MSPileupTasks
* validate MSTransferor using data location from MSPileup
* validate MSRuleCleaner no longer doing anything with secondaries

If required, final configuration changes and bug fixes need to be delivered with this issue.

**Describe alternatives you've considered**
None

**Additional context**
Depends on: https://github.com/dmwm/WMCore/issues/11427 and https://github.com/dmwm/WMCore/issues/11428

**Comment by amaltaro** [comment]
So far, 4 problems have been spotted.

1. apparently, the cmsweb dev clusters certificate cannot query Rucio, even though it does retrieve a token:
```
2023-03-29 20:24:48,074:INFO:PycurlRucio: Requesting a token to Rucio for account: wmcore_transferor, against url: https://cms-rucio-auth-int.cern.ch
2023-03-29 20:24:48,110:INFO:PycurlRucio: Retrieved Rucio token valid until: Wed, 29 Mar 2023 21:24:48 UTC
2023-03-29 20:24:48,114:INFO:PycurlRucio: Executing 5 requests against Rucio for the container size
2023-03-29 20:24:48,124:ERROR:PycurlRucio: getPileupContainerSizesRucio function did not return a valid response for container: /RelValMinBias_14TeV/CMSSW_10_6_1-106X_mcRun3_2021_realistic_v1_rsb-v1/GEN-SIM. Error: {'ExceptionClass': 'CannotAuthenticate', 'ExceptionMessage': 'Cannot authenticate with given credentials'}
```

2. even without resolving the pileup size, we still update the pileup document (have to check if it's updated with None size, breaking schema):
```
2023-03-29 20:24:48,169:INFO:MSPileupData: Pileup object /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM successfully updated
```

3. wrong logging syntax:
```
2023-03-29 20:24:48,351:INFO:MSPileupTasks: monitoring task {uuid}, processed without update for {pname}
```

4. mix of operands type when evaluating free space (likely because there is no quota defined in the Integration server!):
```
2023-03-29 20:24:48,434:ERROR:MSPileupTasks: MSPileup active task ffbf3b98-2179-4738-9c8c-dba0f5766b5b pileup /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM, failed with error unsupported operand type(s) for -: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 481, in runTask
    activeTask(doc, spec)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 426, in activeTask
    if rec['bytes_remaining'] - pileupSize > marginSpace:
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

For 4. above, I think the only thing we can do is to actually ask the Rucio team to create quotas in the Integration server (IF that is really the problem here).

Rucio client in verbose mode is tough to read, because debug logger propagates to all the underlying libraries. So I will simply update services_config to keep it non-verbose.

**Comment by amaltaro** [comment]
These errors have all been understood and fixed in the PR linked above, the only exception so far is the authentication issue with Rucio. 
Token is correctly retrieved for the wmcore_transferor account, using the credentials avaialble for MSPileup (CMSWEB Robot certificate *CN=852819*), but it fails when contacting the Rucio server (not the auth).

I checked the credentials available in Rucio Int with the API below, and the certificate above is properly mapped:
```
>>> pprint(list(client.list_identities("wmcore_transferor")))
```

so I am puzzled as of why it fails. 
@vkuznet if you have a chance tomorrow, could you please try to find out the reason while I proceed with MSTransferor validation?

**Comment by vkuznet** [comment]
Alan, I think it is issue with rucio servers. Here is a proof:
1. I logged in into reqmgr2 pod
2. I setup the following
```
rcert=/etc/robots/robotcert.pem
rckey=/etc/robots/robotkey.pem
aurl=https://cms-rucio-auth-int.cern.ch/auth/x509
account=wmcore_transferor
opt="-s -L -k --key $rckey --cert $rcert"
```
3. then, I query rucio auth server
```
# successful call
curl $opt -v -H "X-Rucio-Account: $account" $aurl
...
< X-Rucio-Auth-Token: wmcore_transferor-xxx
```
and, then if I tried again the sam curl command it returns
```
* error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
```
I think @ericvaandering should check rucio int instance since it seems to me that it has failed node somewhere as two identical curl calls has different results.

**Comment by amaltaro** [comment]
Thank you for promptly looking into this, @ericvaandering. From the #cms-rucio MM channel, I see that the Integration cluster is in the process of being recreated. Could you please announce (either here or in MM) once the Integration server is back up and running?

**Comment by amaltaro** [comment]
Based on WMCore `2.2.0rc6` and with Rucio Int enabled now, I just spotted another traceback in the code when fetching inactive pileup objects. Here is the traceback that needs debugging and fix:
```
2023-04-03 18:27:21,512:INFO:MSPileupData: Getting pileup with spec: {'active': False}, projection: None
2023-04-03 18:27:21,514:ERROR:MSManager: MS daemon error: '_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 51, in daemonOpt
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 210, in pileupTasks
    self.msPileupTasks.executeCycle()
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTaskManager.py", line 65, in executeCycle
    self.mgr.cleanupTask(self.cleanupDaysThreshold)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 91, in cleanupTask
    spec = {'_id': doc['_id']}
KeyError: '_id'
```

I am going to reopen this issue.

**Comment by vkuznet** [comment]
The issue may be as simple as the returned doc is empty dictionary. We should check that doc indeed has some keys and `_id` jkey is present in it. Do you want me to prepare PR for that?

**Comment by vkuznet** [comment]
ahh, the actual issue is here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/MSPileup/MSPileupData.py#L227

**Comment by amaltaro** [comment]
>  change query to use pileupName instead of _id in MSPileupTasks.py

@vkuznet Valentin, thanks for the prompt feedback. I guess I'd be inclined to not strip anything and run the cleanup logic based on `pileupName` (which in the end is equal to `_id`). Can you provide a PR? I can then test it in testbed.

**Comment by vkuznet** [comment]
Here it is: https://github.com/dmwm/WMCore/pull/11529

**Comment by amaltaro** [comment]
Todor mentioned a problem fetching pileup data while running the integration tests. Looking into the service (ms-pileup) logs, I see this exception:
```
2023-04-08 00:00:31,860:INFO:MSManager: Total pileup execution time: 0.00 secs
2023-04-08 00:00:37,831:INFO:MSPileupData: Getting pileup with spec: {'active': True}, projection: {'expectedRSEs': 1, 'pileupName': 1}
ERROR, json.dumps failed to serialize {'_id': ObjectId('643018aab9669baa516fedb9'), 'pileupName': '/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM', 'expectedRSEs': ['T1_US_FNAL_Disk', 'T2_CH_CERN']}, type <class 'dict'>
Exception: Object of type ObjectId is not JSON serializable
[08/Apr/2023:00:00:37]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 0a2f07fdc12dd49c9aa7ead3a6c52fad (Execution error)
[08/Apr/2023:00:00:37]    Traceback (most recent call last):
[08/Apr/2023:00:00:37]      File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Format.py", line 253, in stream_chunked
[08/Apr/2023:00:00:37]        chunk = comma + json.dumps(obj) + "\n"
[08/Apr/2023:00:00:37]      File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
[08/Apr/2023:00:00:37]        return _default_encoder.encode(obj)
[08/Apr/2023:00:00:37]      File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
[08/Apr/2023:00:00:37]        chunks = self.iterencode(o, _one_shot=True)
[08/Apr/2023:00:00:37]      File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
[08/Apr/2023:00:00:37]        return _iterencode(o, 0)
[08/Apr/2023:00:00:37]      File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
[08/Apr/2023:00:00:37]        raise TypeError(f'Object of type {o.__class__.__name__} '
[08/Apr/2023:00:00:37]    TypeError: Object of type ObjectId is not JSON serializable
[08/Apr/2023:00:00:37] ms-pileup-bc767ff99-p2zwj 137.138.33.58 "POST /ms-pileup/data/pileup HTTP/1.1" 500 Internal Server Error [data: 4731 in 745 out 7009 us ]
```

which I believe to be coming from the MongoDB `ObjectId` data type.

A fix has been proposed in: https://github.com/dmwm/WMCore/pull/11539
Reopening this issue.

**Comment by amaltaro** [comment]
Based on MSPileup 2.2.0.1 + #11553 , I changed my dev service settings such as:
* enabled Rucio Prod instead of Rucio Int
* updated the disk expression configuration by removing the "cms_type=int"
* ensure dryRun was set to True

then I injected the 75 unique pileup configuration provided in #11543 and here is the outcome for active=true datasets:
https://amaltaro.web.cern.ch/amaltaro/forWMCore/PR_11543/reqmgr2ms-20230417-ms-pileup-tasks-6cf955c766-pwdrj.log

for a cleaner version of it, one can look at:
https://amaltaro.web.cern.ch/amaltaro/forWMCore/PR_11543/reqmgr2ms-20230417-ms-pileup-tasks-6cf955c766-pwdrj.log.clean
where:
* a total of 2 rules would have been deleted (probably locking dataset in an RSE that it should not. I did not double check it though)
* a total of 56 rules would have been created (pileup is not replicated as it should - as it is configured in the campaigns)

@haozturk could you please have a look at these logs and if possible, update the pileup configurations, as we discussed on Friday? FYI @vkuznet 

NOTE that if we inject pileup configurations with `active=false`, the service will delete ALL the rules that it finds under wmcore_transferor (it not in dry-run mode). In other words, if we decide to inject active=false pileup, then we need to ensure that the service remains in dryRun=false.
