### ISSUE TITLE
Cannot quote None type in SimpleCondorPlugin - CMS_CampaignName

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11759]
**Impact of the bug**
WMAgent

**Describe the bug**
While running a WMAgent release candidate validation, based on `2.2.4rc8`, I see that JobSubmitter crashed when trying to cast a NoneType classad:
```
Python argument types in
    classad.classad.quote(NoneType)
did not match C++ signature:
    quote(std::string input)
```

This implementation has been recently done to provide the feature requested in this ticket:
https://github.com/dmwm/WMCore/issues/10914

**How to reproduce it**
```
>>> import classad
>>> classad.classad.quote(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    classad.classad.quote(NoneType)
did not match C++ signature:
    quote(std::string input)
```

**Expected behavior**
If the value is of None type, we should set it to the `undefined` condor classad.

**Additional context and error message**
Full traceback is:
```
2023-09-29 22:37:59,960:140059245987584:ERROR:BossAirAPI:Unhandled exception while submitting jobs to plugin: SimpleCondorPlugin
Python argument types in
    classad.classad.quote(NoneType)
did not match C++ signature:
    quote(std::string input)
2023-09-29 22:38:00,085:140059245987584:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobSubmitter.JobSubmitterPoller.JobSubmitterPoller object at 0x7f6222d5e970> <@========== WMException Start ==========@>
Exception Class: BossAirException
Message: Unhandled exception while submitting jobs to plugin: SimpleCondorPlugin
Python argument types in
    classad.classad.quote(NoneType)
did not match C++ signature:
    quote(std::string input)
        ClassName : None
        ModuleName : WMCore.BossAir.BossAirAPI
        MethodName : submit
        ClassInstance : None
        FileName : /data/srv/wmagent/v2.2.4rc8/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.2.4rc8/lib/python3.8/site-packages/WMCore/BossAir/BossAirAPI.py
        LineNumber : 396
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v2.2.4rc8/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.2.4rc8/lib/python3.8/site-packages/WMCore/BossAir/BossAirAPI.py", line 382, in submit
    localSuccess, localFailure = pluginInst.submit(jobs=jobsToSubmit,

  File "/data/srv/wmagent/v2.2.4rc8/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.2.4rc8/lib/python3.8/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 162, in submit
    (sub, jobParams) = self.createSubmitRequest(jobsReady)

  File "/data/srv/wmagent/v2.2.4rc8/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.2.4rc8/lib/python3.8/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 684, in createSubmitRequest
    jobParameters = self.getJobParameters(jobList)

  File "/data/srv/wmagent/v2.2.4rc8/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.2.4rc8/lib/python3.8/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 544, in getJobParameters
    ad['My.CMS_CampaignName'] = classad.quote(job['campaignName'])
```

**Comment by khurtado** [comment]
@amaltaro Thank you, I suppose this got switched at some point and I did not notice, when I resolving the Merge conflicts with the physics type PR
