### ISSUE TITLE
Agent v2.3.0 trying to resolve input data for ACDC workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11877]
**Impact of the bug**
WMAgent

**Describe the bug**
After observing depletion of jobs in the system for the last 12h/24h, I started looking into the component logs for a couple of agents. I noticed some sporadic HTCondor related errors in vocms0281; but vocms0282 has a more scary exception [1], caused by an attempt to look up for ACDC input data (which is actually reference to data in the ACDC server) in Rucio, which of course returns a DIDNotFound error.

**How to reproduce it**
Not sure, but this is definitely a regression

**Expected behavior**
WorkQueueManager should not try to resolve the location of input data for ACDC workflows through Rucio, given that that input data comes from an ACDC collection, e.g:
```
/acdc/cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_
240123_014605_3460/:wangz_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240111_162540_2272:DataProcessing/0/373
```

this behavior needs to be fixed and Rucio cannot be used in such cases.

**Additional context and error message**
[1]
```
2024-01-25 03:05:12,012:139760401794816:INFO:WorkQueue:Splitting /cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240123_014605_3460/DataProcessing with policy name ResubmitBlock and policy params {'name': 'ResubmitBlock', 'args': {}}
2024-01-25 03:05:12,269:139760401794816:INFO:StartPolicyInterface:Fetching Rucio locks for account: wmcore_transferor and dataset: /acdc/cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240123_014605_3460/:wangz_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240111_162540_2272:DataProcessing/0/373
2024-01-25 03:05:15,293:139760401794816:ERROR:WorkQueue:Exception splitting wqe a0caf38833a7073868fd4c24fa349e32 for cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240123_014605_3460: <@========== WMException Start ==========@>
Exception Class: WMRucioDIDNotFoundException
Message: Data identifier not found in Rucio: /acdc/cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240123_014605_3460/:wangz_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240111_162540_2272:DataProcessing/0/373. Error: Data identifier not found.
Details: Data identifier 'cms:/acdc/cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240123_014605_3460/:wangz_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240111_162540_2272:DataProcessing/0/373' not found
        ClassName : None
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py
        LineNumber : 773
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 770, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.29.10/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)

<@---------- WMException End ----------@>
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 770, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.29.10/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)
rucio.common.exception.DataIdentifierNotFound: Data identifier not found.
Details: Data identifier 'cms:/acdc/cmsunified_ACDC0_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240123_014605_3460/:wangz_r-0-Run2017C_Charmonium_UL2017_MiniAODv2_BParking_240111_162540_2272:DataProcessing/0/373' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1138, in processInboundWork
    work, rejectedWork, badWork = self._splitWork(inbound['WMSpec'], data=inbound['Inputs'],
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1078, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 168, in __call__
    self.split()
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py", line 64, in split
    self.newQueueElement(Inputs={block['Name']: block['Sites']},
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 142, in newQueueElement
    locations = self.getDatasetLocations(data, account=self.rucioAcct)
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 273, in getDatasetLocations
    locations = self.rucio.getDataLockedAndAvailable(name=datasetPath,
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 1084, in getDataLockedAndAvailable
    if self.isContainer(kwargs['name']):
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 773, in isContainer
    raise WMRucioDIDNotFoundException(msg)
2024-01-25 03:05:15,348:139760401794816:INFO:WorkQueueManagerWorkPoller:Splitting finished
2024-01-25 03:05:15,348:139760401794816:INFO:BaseWorkerThread:WorkQueueManagerWorkPoller took 3.601 secs to execute
```

**Comment by amaltaro** [comment]
And the submit4 node is having the same issue at the moment:
```
2024-01-25 08:08:56,382:140437777262336:INFO:WorkQueue:Retrieved 1 elements for splitting with continuous flag: False
2024-01-25 08:08:56,397:140437777262336:INFO:WorkQueue:Splitting /cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240123_015705_4680/DataProcessing with policy name ResubmitBlock and 
policy params {'name': 'ResubmitBlock', 'args': {}}
2024-01-25 08:08:57,806:140437777262336:INFO:StartPolicyInterface:Fetching Rucio locks for account: wmcore_transferor and dataset: /acdc/cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParkin
g_240123_015705_4680/:wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476:DataProcessing/0/176
2024-01-25 08:08:58,040:140437777262336:ERROR:WorkQueue:Exception splitting wqe 94eef158f2fee7623ff74055f679260e for cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240123_015705_4680
: <@========== WMException Start ==========@>
Exception Class: WMRucioDIDNotFoundException
Message: Data identifier not found in Rucio: /acdc/cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240123_015705_4680/:wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111
_165116_2476:DataProcessing/0/176. Error: Data identifier not found.
Details: Data identifier 'cms:/acdc/cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240123_015705_4680/:wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476:Da
taProcessing/0/176' not found
        ClassName : None
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py
        LineNumber : 773
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 770, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/external/py3-rucio-clients/1.29.10/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)

<@---------- WMException End ----------@>
...
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1138, in processInboundWork
    work, rejectedWork, badWork = self._splitWork(inbound['WMSpec'], data=inbound['Inputs'],
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1078, in _splitWork
    units, rejectedWork, badWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 168, in __call__
    self.split()
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/ResubmitBlock.py", line 64, in split
    self.newQueueElement(Inputs={block['Name']: block['Sites']},
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 142, in newQueueElement
    locations = self.getDatasetLocations(data, account=self.rucioAcct)
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 273, in getDatasetLocations
    locations = self.rucio.getDataLockedAndAvailable(name=datasetPath,
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 1084, in getDataLockedAndAvailable
    if self.isContainer(kwargs['name']):
  File "/data/srv/wmagent/v2.3.0/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.3.0/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 773, in isContainer
    raise WMRucioDIDNotFoundException(msg)
```

If we look at the input document used for this work splitting, we see that the ACDC input actually has a legit location set to "T2_FI_HIP":
```
$ curl $user:$pass@localhost:5984/workqueue_inbox/94eef158f2fee7623ff74055f679260e | jq
{
  "_id": "94eef158f2fee7623ff74055f679260e",
  "_rev": "2-d79ea73c17401dbb68cf69533cbbc792",
  "timestamp": 1705977673.4819334,
  "updatetime": 1705978099.8032176,
  "thunker_encoded_json": true,
  "type": "WMCore.WorkQueue.DataStructs.WorkQueueElement.WorkQueueElement",
  "WMCore.WorkQueue.DataStructs.WorkQueueElement.WorkQueueElement": {
    "Inputs": {
      "/acdc/cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240123_015705_4680/:wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476:DataProcessing/0/176": [
        "T2_FI_HIP"
      ]
    },
...
```

so I fail to see why the code enters in this `if not sites` clause in this line:
https://github.com/dmwm/WMCore/blob/0d0e383/src/python/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py#L140

**Comment by amaltaro** [comment]
If we look at the ACDC collection at this link:
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476%22&include_docs=true&reduce=false

and filter documents matching:
```
"fileset_name":"/wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476/DataProcessing"
```

we can actually see that some files have been reported with this location: `"locations":["T1_US_FNAL_MSS"]`.

**This is the first problem**, in no situation we should start working on a file that is only available on Tape - unless it is supposed to use AAA to access the data, and even in that situation we would consider the block as being available in the workflow SiteWhitelist. So NO, it shouldn't ever happen.

Now zooming in into one example input file (reported at FNAL_MSS), e.g.:
```
"files":{"/store/data/Run2017E/SinglePhoton/AOD/09Aug2019_UL2017-v1/50000/D87D636A-35CA-EC4E-B55D-BB575237D687.root"
```
then resolving the file to block relationship (in DAS or DBS):
```
/SinglePhoton/Run2017E-09Aug2019_UL2017-v1/AOD#10db06b1-fed0-44e9-985e-7c95ebeffa25
```
and lastly checking the block location, it does tell that the block is available at FNAL_Tape, HIP and Bari.

So, the **golden question** is, why this/those files are reported as being available on at `['T1_US_FNAL_MSS']`? The agents should never do that, this is not an expected scenario. 

To answer this question, we need to go down one further layer of recoveries, where:
```
cmsunified_ACDC0_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240123_015705_4680
    worked on --> 
    "InitialTaskPath": "/wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476/DataProcessing",
        and wangz_r-0-Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_240111_165116_2476
            worked on --> 
            "InitialTaskPath": "/pdmvserv_Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_231108_233223_2058/DataProcessing",
            "CollectionName": "pdmvserv_Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_231108_233223_2058_9e175a80-b0a1-11ee-8fbc-fa163e203803",
```

NOTE that the last collection is actually different, it corresponds to a specialized ACDC where the collection documents are handcrafted by Unified / P&R team. Let us have a look at that collection in the ACDC server:
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_231108_233223_2058_9e175a80-b0a1-11ee-8fbc-fa163e203803%22&include_docs=true&reduce=false

then we match documents against the `InitialTaskPath` defined in the workflow, thus documents under the following `fileset_name`:
```
"/pdmvserv_Run2017E_SinglePhoton_UL2017_MiniAODv2_BParking_231108_233223_2058/DataProcessing"
```

and with that we can confirm that documents were initially (Unified) created in the system with a wrong/unsupported location:
```
"locations":["T1_US_FNAL_MSS"]
```

which injects an unsupported scenario into WM, causing it to crash.

I am reaching out to the P&R team to investigate and correct this in their recovery system (which should likely depend on wmcore_transferor rules instead of a current snapshot of the locations).

**Comment by amaltaro** [comment]
As discussed over Mattermost, the P&R team is using a script that fetches location from DBS. DBS only provides the origin location and cannot be used for data location.

Qier said that they will change the script and instead assign any given Disk site (perhaps T2_CH_CERN) as file location, relying then on AAA for running the workflow and reading input data remotely.
