### ISSUE TITLE
Incorrect parsing and handling of MSPileup GET parameters

### ISSUE THREAD

**Issue by d-ylee** [dmwm/WMCore#11882]
**Impact of the bug**
MSPileup

**Describe the bug**
Passing a single filter into the `/pileup` GET parameters to create a MongoDB projection as per the MSPileup API returns nothing, while passing in an empty string to the filter parameter causes an HTTP 500 Error.

**How to reproduce it**
Doing a GET request from command line or browser to fetch an MSPileup Document with the filter query parameter: https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs
does not return anything.

Additionally,
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs&filters=
causes an HTTP 500 error

**Expected behavior**
What is expected is to have a response that represents the MongoDB projection provided by the `filter` parameter.
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs&filters=pileupName

**Additional context and error message**
[1] Logs for the request:
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs

```
2024-01-31 21:45:18,586:INFO:MSPileupData: Getting pileup with spec: {'pileupName': '/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM'}, projection: {'c': 1, 'u': 1, 'r': 1, 'e': 1, 'n': 1, 't': 1, 'R': 1, 'S': 1, 'E': 1, 's': 1}
```

[2] Trying to pass a comma separated list:
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs,pileupName

```
2024-01-31 21:46:36,814:INFO:MSPileupData: Getting pileup with spec: {'pileupName': '/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM'}, projection: {'c': 1, 'u': 1, 'r': 1, 'e': 1, 'n': 1, 't': 1, 'R': 1, 'S': 1, 'E': 1, 's': 1, ',': 1, 'p': 1, 'i': 1, 'l': 1, 'N': 1, 'a': 1, 'm': 1}
```

[3] With brackets: https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=[currentRSEs,pileupName]

```
2024-01-31 21:47:29,140:INFO:MSPileupData: Getting pileup with spec: {'pileupName': '/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM'}, projection: {'[': 1, 'c': 1, 'u': 1, 'r': 1, 'e': 1, 'n': 1, 't': 1, 'R': 1, 'S': 1, 'E': 1, 's': 1, ',': 1, 'p': 1, 'i': 1, 'l': 1, 'N': 1, 'a': 1, 'm': 1, ']': 1}
```

[4] Trying to force a list by providing an empty filter --> HTTP 500 error:
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs&filters=

```
[31/Jan/2024:21:49:32]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 7eb99d895cecf06c15739ce91ebb0d60 (Execution error)
[31/Jan/2024:21:49:32]    Traceback (most recent call last):
[31/Jan/2024:21:49:32]      File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Format.py", line 307, in stream_chunked
[31/Jan/2024:21:49:32]        for obj in stream:
[31/Jan/2024:21:49:32]      File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/Service/Data.py", line 146, in get
[31/Jan/2024:21:49:32]        raise cherrypy.HTTPError(status=500, message=msg) from None
[31/Jan/2024:21:49:32]    cherrypy._cperror.HTTPError: (500, 'Unable to GET request, error=Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/Service/Data.py", line 139, in get\n    for doc in self.mgr.get(**kwds):\n  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 391, in get\n    return self.msPileup.getPileup(**kwds)\n  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileup.py", line 64, in getPileup\n    results = self.dataMgr.getPileup(spec, projection)\n  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupData.py", line 246, in getPileup\n    for doc in self.dbColl.find(spec, projection):\n  File "/usr/local/lib/python3.8/site-packages/pymongo/cursor.py", line 1248, in next\n    if len(self.__data) or self._refresh():\n  File "/usr/local/lib/python3.8/site-packages/pymongo/cursor.py", line 1165, in _refresh\n    self.__send_message(q)\n  File "/usr/local/lib/python3.8/site-packages/pymongo/cursor.py", line 1052, in __send_message\n    response = client._run_operation(\n  File "/usr/local/lib/python3.8/site-packages/pymongo/_csot.py", line 105, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1302, in _run_operation\n    return self._retryable_read(\n  File "/usr/local/lib/python3.8/site-packages/pymongo/_csot.py", line 105, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1420, in _retryable_read\n    return func(session, server, sock_info, read_pref)\n  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1298, in _cmd\n    return server.run_operation(\n  File "/usr/local/lib/python3.8/site-packages/pymongo/server.py", line 134, in run_operation\n    _check_command_response(first, sock_info.max_wire_version)\n  File "/usr/local/lib/python3.8/site-packages/pymongo/helpers.py", line 181, in _check_command_response\n    raise OperationFailure(errmsg, code, response, max_wire_version)\npymongo.errors.OperationFailure: FieldPath cannot be constructed with empty string, full error: {\'ok\': 0.0, \'errmsg\': \'FieldPath cannot be constructed with empty string\', \'code\': 40352, \'codeName\': \'Location40352\', \'$clusterTime\': {\'clusterTime\': Timestamp(1706737772, 1), \'signature\': {\'hash\': b\'\\xd8\\xfa\\x99\\x94Z3\\xbf\\xd6\\x9cI\\x18~\\x86\\xb6`\\xa9\\xeb\\x8c\\x10\\x95\', \'keyId\': 7309182508338249730}}, \'operationTime\': Timestamp(1706737772, 1)}\n')
[31/Jan/2024:21:49:32] ms-pileup-6d66f4865d-gh2dr 131.225.72.201 "GET /ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs&filters= HTTP/1.1" 500 Internal Server Error [data: 4883 in 745 out 73567 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=delee/CN=857801/CN=Dennis Lee" "" ] [ref: "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0" ]
```

Basically for cases [1-3] case, if `filter=` is only provided once in the parameters, the server is parsing each character, including special characters (`[` and `,`), in the filter (ie currentRSEs) and sending that as a projection to MongoDB.

In case [4] when trying to force a list of filters (HTTP 500 error), the issue is that the empty string '' is passed into the filter, which is not possible with MongoDB.

The following requests work:
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=currentRSEs&filters=pileupName

https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM&filters=

**Comment by d-ylee** [comment]
Is there code reuse here:
https://github.com/dmwm/WMCore/blob/1e059313b9e465e08c307047d3ad64c2707f548d/src/python/WMCore/MicroService/MSCore/MSManager.py#L390-L391
https://github.com/dmwm/WMCore/blob/1e059313b9e465e08c307047d3ad64c2707f548d/src/python/WMCore/MicroService/MSCore/MSManager.py#L407-L408

These two functions:
https://github.com/dmwm/WMCore/blob/1e059313b9e465e08c307047d3ad64c2707f548d/src/python/WMCore/MicroService/MSPileup/MSPileup.py#L49C1-L93

**Comment by amaltaro** [comment]
Added this issue to the Q1 board and properly labelled it.

**Comment by vkuznet** [comment]
I fear that you addressing a wrong issue here. The main problem lies in ambiguity of how to parse arguments in HTTP request for entire WMCore web framework. The issue is that is undefined. In other words how user should pass multiple values to the HTTP server, should it be `key=val1,val2` or `key=val1&key=val2` or `key=[val1,val2]`, etc. The MSPileup is just sub-system which is based on WMCore web framework and therefore resolution within MSPileup is not optimal since it will only address this specific service and leave the issue unsolved from all other services.Since there is no clear definition in HTTP standard, e.g. see this [thread](https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request), it should be defined in a web framework, and in WMCore case the framework should deal with this and pass in uniform way the arguments to services. For instance it can be done as decorator for WMCore, and then any API which needs to support multiple arguments should use such decorator. The logic of decorator will then handle multiple supported variations of passing arguments and yield common structure, like `{key: [val1, val2], ...}`. In GoLang all parameters (single or multiple) are represented as list of values, even if a list contains a single value. This provides uniform representation and allow to use common code patterns to parse it.

**Comment by amaltaro** [comment]
Valentin, that is a fair argument. From what I can see, WMCore HTTP server is expecting multiple key/value pairs, e.g.:
https://cmsweb-testbed.cern.ch/reqmgr2/data/request?status=staging&status=acquired&detail=false
or similar for ms-pileup:
https://cmsweb-prod.cern.ch/ms-pileup/data/pileup?query=pileupName&filters=currentRSEs&filters=pileupName&filters=containerFraction&filters=ruleIds

As we can see, ReqMgr2 deals properly with such GET requests, while MSPileup does not as it has a broken parsing of the query string. Said that, I don't think Dennis needs to chase and/or try to refactor anything WMCore wide. This is somehow a legacy stack at this moment and we have not identified a general problem core problem. Given the discussions of refactoring, new generation and whatnot, that would not be a great investment IMO. 

@d-ylee Dennis, once you follow up on the few comments along the code, please request another review.
