### ISSUE TITLE
ModuleNotFoundError: No module named 'WMCore.BossAir' error when build CRAB TaskWorker with WMCore==2.3.1rc3

### ISSUE THREAD

**Issue by novicecpp** [dmwm/WMCore#11912]
**Impact of the bug**
CRAB jobs running on the grid.

**Describe the bug**
`ModuleNotFoundError: No module named 'WMCore.BossAir'` in the CRAB jobs running on the grid.

This is due to importing `BossAir` in [WMRuntime/Bootstrap.py](https://github.com/dmwm/WMCore/blob/52ae759608a65bdaa61e5ad77e10c1f7f5cab9c5/src/python/WMCore/WMRuntime/Bootstrap.py#L28) was introduced in https://github.com/dmwm/WMCore/pull/11812, but [setup_dependencies.py for crabtaskworker](https://github.com/dmwm/WMCore/blob/52ae759608a65bdaa61e5ad77e10c1f7f5cab9c5/setup_dependencies.py#L222-L226) does not include `WMCore.BossAir` directory.

Currently, we use `2.1.8` and found this error when tried to bump version to `2.3.1rc3`.

**How to reproduce it**
Build TaskWorker with the latest WMCore (via our [Jenkins job](https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_BuildOnRelease/159/rebuild/parameterized)) and submit the CRAB task. All jobs will fail because module not found.

**Expected behavior**
Jobs should not have `ModuleNotFoundError: No module named 'WMCore.BossAir'` error.

**Additional context and error message**

CRAB issue tracker: https://github.com/dmwm/CRABServer/issues/8110
Error logs:
```
==== FAILURE WHEN LOADING WMCORE AT Sun Dec 17 23:24:40 2023 UTC ====
Traceback (most recent call last):
  File "CMSRunAnalysis.py", line 585, in <module>
    from WMCore.WMRuntime.Bootstrap import setupLogging
  File "<frozen zipimport>", line 259, in load_module
  File "/srv/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 28, in <module>
    from WMCore.BossAir.Plugins.BasePlugin import BasePlugin
ModuleNotFoundError: No module named 'WMCore.BossAir'
```

I am not sure what the proper way is to fix this, but adding a `BossAir` directory like [this](https://github.com/novicecpp/WMCore/commit/019d150afd867ae9b26171ecc2209e7dd16009ba) fixes the issue (or should I put it in the `wmc-runtime` instead?).

**Comment by novicecpp** [comment]
Hi @todor-ivanov @amaltaro, could you please have a look?
This is the blocker for deploying new CRAB images [with supporting jobs run on EL9](https://github.com/dmwm/WMCore/pull/11897).

**Comment by todor-ivanov** [comment]
Hi @novicecpp 
> adding a BossAir directory like [this](https://github.com/novicecpp/WMCore/commit/019d150afd867ae9b26171ecc2209e7dd16009ba) fixes the issue (or should I put it in the wmc-runtime instead?).

I think the solution you suggest is the proper one indeed. This, unfortunately, introduces yet another module dependency for `CRABTaskWorker`. But it is needed or properly resolving the `OS` to `scramArch` map at runtime.  

Since this change would affect only you, please feel free to make the PR for adding this line and we will review and merge it.

FYI: @amaltaro
