### ISSUE TITLE
Wrong usage of scopes in Rucio wrapper and MSPileupTasks

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11937]
**Impact of the bug**
Failure to properly place requests to Rucio server.

**Describe the bug**
During integration tests with newly available MSPileupTasks I found several issues with Rucio APIs due to wrong scope mismatch. When I scan codebase I see missing scope parameter in both Rucio wrapper code and MSPileupTasks.

**How to reproduce it**
Deploy new MSPileup codebase to testX cluster and request partial pileup data placement.

**Expected behavior**
Follow integration tests logic

**Additional context and error message**
This is part of #11920 issue.

**Comment by amaltaro** [comment]
@vkuznet can you please clarify what the "several issues with Rucio APIs" are? Please provide either tracebacks or snippet of code

**Comment by vkuznet** [comment]
Here are some exception I saw in a log:
```
2024-03-19 13:52:47,145:ERROR:MSManager: MS daemon error: <@========== WMException Start ==========@>
Exception Class: WMRucioDIDNotFoundException
Message: Data identifier not found in Rucio: /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1
-v1/GEN-SIM-V1. Error: Data identifier not found.
Details: Data identifier 'cms:/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V1'
 not found
        ClassName : None
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py
        LineNumber : 788
        ErrorNr : 0

Traceback:
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 785, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/usr/local/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)
<@---------- WMException End ----------@>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 785, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)
  File "/usr/local/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)
rucio.common.exception.DataIdentifierNotFound: Data identifier not found.
Details: Data identifier 'cms:/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V1' not found

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 51, in daemonOpt
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 210, in pileupTasks
    self.msPileupTasks.executeCycle()
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTaskManager.py", line 73, in executeCycle
    self.mgr.partialPileupTask()
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 210, in partialPileupTask
    customBlocks = self.getPileupBlocks(doc, previousFraction, fraction)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 121, in getPileupBlocks
    return self.getDecreasingBlocks(doc, fraction)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 164, in getDecreasingBlocks
    customBlocks = self.rucioClient.getBlocksInContainer(cname)
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 172, in getBlocksInContainer
    if not self.isContainer(container):
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 788, in isContainer
    raise WMRucioDIDNotFoundException(msg)
```
and similar ones related to missing scope parameter in `isContainer` rucio wrapper API calls. Please note that `isContainer` called from multiple places and I fixed them all in my PR #11938

**Comment by vkuznet** [comment]
And, now I see new Rucio error:
```
2024-03-20 12:38:17,714:ERROR:Rucio: Exception attaching dids: [] to: /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V2. Error: Provided object does not match schema.
Details: Problem validating attachment : [] is too short

Failed validating 'minItems' in schema['properties']['dids']:
    {'description': 'Array of Data Identifiers(DIDs)',
     'items': {'additionalProperties': False,
               'description': 'Data Identifier(DID)',
               'properties': {'adler32': {'description': 'adler32',
                                          'pattern': '^[a-fA-F\\d]{8}$',
                                          'type': 'string'},
                              'bytes': {'description': 'Size in bytes',
                                        'type': 'integer'},
                              'md5': {'description': 'md5',
                                      'pattern': '^[a-fA-F\\d]{32}$',
                                      'type': 'string'},
                              'meta': {'additionalProperties': True,
                                       'description': 'Data '
                                                      'Identifier(DID) '
                                                      'metadata',
                                       'properties': {'guid': {'description': 'Universally '
                                                                              'Unique '
                                                                              'Identifier '
                                                                              '(UUID)',
                                                               'pattern': '^(\\{){0,1}[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12}(\\}){0,1}$',
                                                               'type': 'string'}},
                                       'type': 'object'},
                              'name': {'description': 'Data Identifier '
                                                      'name',
                                       'pattern': '^/[a-zA-Z0-9\\-_]{1,99}/[a-zA-Z0-9\\.\\-_]{1,199}/[A-Z0-9\\-]{1,50}$|^/[a-zA-Z0-9\\-_]{1,99}/[a-zA-Z0-9\\.\\-_]{1,199}/[A-Z0-9\\-]{1,50}#[a-zA-Z0-9\\.\\-_]{1,100}$|^\\/store\\/[A-Za-z0-9][A-Za-z0-9\\.\\-\\_\\/]{1,493}$',
                                       'type': 'string'},
                              'pfn': {'description': 'Physical File Name',
                                      'type': 'string'},
                              'rules': {'description': 'Array of '
                                                       'replication rules',
                                        'items': {'additionalProperties': False,
                                                  'description': 'Replication '
                                                                 'rule',
                                                  'properties': {'account': {'description': 'Account '
                                                                                            'name',
                                                                             'pattern': '^[a-z0-9-_]{1,25}$',
                                                                             'type': 'string'},
                                                                 'activity': {'description': 'Activity '
                                                                                             'name',
                                                                              'enum': ['Data '
                                                                                       'Brokering',
                                                                                       'Data '
                                                                                       'Consolidation',
                                                                                       'Data '
                                                                                       'rebalancing',
                                                                                       'Debug',
                                                                                       'Express',
                                                                                       'Functional '
                                                                                       'Test',
                                                                                       'Group '
                                                                                       'Subscriptions',
                                                                                       'Production '
                                                                                       'Input',
                                                                                       'Production '
                                                                                       'Output',
                                                                                       'Analysis '
                                                                                       'Input',
                                                                                       'Analysis '
                                                                                       'Output',
                                                                                       'Staging',
                                                                                       'T0 '
                                                                                       'Export',
                                                                                       'T0 '
                                                                                       'Tape',
                                                                                       'Upload/Download '
                                                                                       '(Job)',
                                                                                       'Upload/Download '
                                                                                       '(User)',
                                                                                       'User '
                                                                                       'AutoApprove',
                                                                                       'User '
                                                                                       'Subscriptions',
                                                                                       'Data '
                                                                                       'Challenge'],
                                                                              'type': 'string'},
                                                                 'ask_approval': {'description': 'Rule '
                                                                                                 'approval '
                                                                                                 'request',
                                                                                  'type': ['boolean',
                                                                                           'null']},
                                                                 'asynchronous': {'description': 'Asynchronous '
                                                                                                 'rule '
                                                                                                 'creation',
                                                                                  'type': ['boolean',
                                                                                           'null']},
                                                                 'comment': {'description': 'Rule '
                                                                                            'comment',
                                                                             'maxLength': 250,
                                                                             'type': ['string',
                                                                                      'null']},
                                                                 'copies': {'description': 'Number '
                                                                                           'of '
                                                                                           'replica '
                                                                                           'copies',
                                                                            'type': 'integer'},
                                                                 'delay_injection': {'description': 'Time '
                                                                                                    '(in '
                                                                                                    'seconds) '
                                                                                                    'to '
                                                                                                    'wait '
                                                                                                    'before '
                                                                                                    'starting '
                                                                                                    'applying '
                                                                                                    'the '
                                                                                                    'rule. '
                                                                                                    'Implies '
                                                                                                    'asynchronous '
                                                                                                    'rule '
                                                                                                    'creation.',
                                                                                     'type': ['integer',
                                                                                              'null']},
                                                                 'dids': {'type': 'array'},
                                                                 'grouping': {'description': 'Rule '
                                                                                             'grouping',
                                                                              'enum': ['DATASET',
                                                                                       'NONE',
                                                                                       'ALL',
                                                                                       None],
                                                                              'type': ['string',
                                                                                       'null']},
                                                                 'ignore_availability': {'description': 'Rule '
                                                                                                        'ignore '
                                                                                                        'availability '
                                                                                                        'status',
                                                                                         'type': 'boolean'},
                                                                 'lifetime': {'description': 'Rule '
                                                                                             'lifetime',
                                                                              'type': ['number',
                                                                                       'null']},
                                                                 'locked': {'description': 'Rule '
                                                                                           'locked '
                                                                                           'status',
                                                                            'type': ['boolean',
                                                                                     'null']},
                                                                 'meta': {'description': 'Rule '
                                                                                         'wfms '
                                                                                         'metadata',
                                                                          'maxLength': 3999,
                                                                          'type': ['string',
                                                                                   'null']},
                                                                 'notify': {'description': 'Rule '
                                                                                           'notification '
                                                                                           'setting',
                                                                            'enum': ['Y',
                                                                                     'C',
                                                                                     'N',
                                                                                     'P',
                                                                                     None],
                                                                            'type': ['string',
                                                                                     'null']},
                                                                 'priority': {'description': 'Priority '
                                                                                             'of '
                                                                                             'the '
                                                                                             'transfers',
                                                                              'type': 'integer'},
                                                                 'purge_replicas': {'description': 'Rule '
                                                                                                   'purge '
                                                                                                   'replica '
                                                                                                   'status',
                                                                                    'type': 'boolean'},
                                                                 'rse_expression': {'description': 'RSE '
                                                                                                   'expression',
                                                                                    'type': 'string'},
                                                                 'source_replica_expression': {'description': 'RSE '
                                                                                                              'expression',
                                                                                               'type': ['string',
                                                                                                        'null']},
                                                                 'split_container': {'description': 'Rule '
                                                                                                    'split '
                                                                                                    'container '
                                                                                                    'mode',
                                                                                     'type': ['boolean',
                                                                                              'null']},
                                                                 'subscription_id': {'description': 'Rule '
                                                                                                    'Subscription '
                                                                                                    'id',
                                                                                     'type': ['string',
                                                                                              'null']},
                                                                 'weight': {'description': 'Rule '
                                                                                           'weight',
                                                                            'type': ['string',
                                                                                     'null']}},
                                                  'required': ['dids',
                                                               'copies',
                                                               'rse_expression'],
                                                  'type': 'object'},
                                        'maxItems': 1000,
                                        'minItems': 1,
                                        'type': 'array'},
                              'scope': {'description': 'Scope name',
                                        'pattern': '\\w',
                                        'type': 'string'},
                              'state': {'description': 'Replica state',
                                        'enum': ['AVAILABLE',
                                                 'UNAVAILABLE',
                                                 'COPYING',
                                                 'BEING_DELETED',
                                                 'BAD',
                                                 'SOURCE',
                                                 'A',
                                                 'U',
                                                 'C',
                                                 'B',
                                                 'D',
                                                 'S'],
                                        'type': 'string'},
                              'type': {'description': 'DID type',
                                       'enum': ['DATASET',
                                                'CONTAINER',
                                                'FILE',
                                                'F'],
                                       'type': 'string'}},
               'required': ['scope', 'name'],
               'type': 'object'},
     'maxItems': 30000,
     'minItems': 1,
     'type': 'array'}

On instance['dids']:
    []
2024-03-20 12:38:17,763:WARNING:Rucio: Resolving duplicate rules and separating every DID in a new rule...
2024-03-20 12:38:17,807:WARNING:Rucio: Found duplicate rule for account: wmcore_pileup, rseExp: T1_US_FNAL_Disk
dids: [{'scope': 'group.wmcore', 'name': '/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V2'}]
2024-03-20 12:38:17,819:INFO:MSPileupTasks: Rule ids: ['f795b21cbb9b4da8b482afa9a0626f8d'] created for custom pileup: /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V2 for RSE: T1_US_FNAL_Disk
2024-03-20 12:38:17,859:WARNING:Rucio: Resolving duplicate rules and separating every DID in a new rule...
2024-03-20 12:38:17,966:WARNING:Rucio: Found duplicate rule for account: wmcore_pileup, rseExp: T2_CH_CERN
dids: [{'scope': 'group.wmcore', 'name': '/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V2'}]
2024-03-20 12:38:17,981:INFO:MSPileupTasks: Rule ids: ['0e68e51c47f2462dae0e086641f9d162'] created for custom pileup: /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V2 for RSE: T2_CH_CERN
```
I do not know how to interpret it but it does not affect MSPIleupTasks logic and I got proper transition record.

**Comment by vkuznet** [comment]
And, now I got a new rucio exception, most likely due to the failed custom container placement and error I posted before. This time I increase fraction from 0.3 to 0.75 and got this:
```
2024-03-20 12:48:18,267:INFO:MSPileupData: Getting pileup with spec: {'active': True}, projection: None
2024-03-20 12:48:18,268:INFO:MSPileupTasks: Running the monitoring task on 1 pileup objects
2024-03-20 12:48:18,290:INFO:MSPileupTasks: monitoring task 42d3e094-3e7f-4fc2-a4af-a210b966f439, container /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V2 under the rule ID f795b21cbb9b4da8b482afa9a0626f8d targeting RSEs ['T1_US_FNAL_Disk'] in rucio account wmcore_pileup is completely available
2024-03-20 12:48:18,290:INFO:MSPileupTasks: monitoring task 42d3e094-3e7f-4fc2-a4af-a210b966f439, container /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext
        ClassInstance : None
        FileName : /usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py
        LineNumber : 788
        ErrorNr : 0

Traceback:
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 785, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/usr/local/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)

<@---------- WMException End ----------@>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 785, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)
  File "/usr/local/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)
rucio.common.exception.DataIdentifierNotFound: Data identifier not found.
Details: Data identifier 'group.wmcore:/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V3' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 51, in daemonOpt
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 210, in pileupTasks
    self.msPileupTasks.executeCycle()
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTaskManager.py", line 73, in executeCycle
    self.mgr.partialPileupTask()
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 210, in partialPileupTask
    customBlocks = self.getPileupBlocks(doc, previousFraction, fraction)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 120, in getPileupBlocks
    return self.getIncreasingBlocks(doc, fraction)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSPileup/MSPileupTasks.py", line 139, in getIncreasingBlocks
    customBlocks = self.rucioClient.getBlocksInContainer(cname, scope=self.customRucioScope)
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 172, in getBlocksInContainer
    if not self.isContainer(container, scope=scope):
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 788, in isContainer
    raise WMRucioDIDNotFoundException(msg)
WMCore.Services.Rucio.Rucio.WMRucioDIDNotFoundException: <@========== WMException Start ==========@>
Exception Class: WMRucioDIDNotFoundException
Message: Data identifier not found in Rucio: /MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V3. Error: Data identifier not found.
Details: Data identifier 'group.wmcore:/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM-V3' not found
        ClassName : None
        ModuleName : WMCore.Services.Rucio.Rucio
        MethodName : isContainer
        ClassInstance : None
        FileName : /usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py
        LineNumber : 788
        ErrorNr : 0

Traceback:
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 785, in isContainer
    response = self.cli.get_did(scope=scope, name=didName)

  File "/usr/local/lib/python3.8/site-packages/rucio/client/didclient.py", line 424, in get_did
    raise exc_cls(exc_msg)

<@---------- WMException End ----------@>
```

**Comment by vkuznet** [comment]
Here is current summary of tests:
- I setup code on test10
- I used the following curl commands in my tests:
```
# delete document
scurl -X DELETE -H "Content-type: application/json" -d@./pileup-delete.json https://cmsweb-test10.cern.ch/ms-pileup/data/pileup

# inject data
scurl -X POST -H "Content-type: application/json" -d@./pileup.json https://cmsweb-test10.cern.ch/ms-pileup/data/pileup
# where pileup.json has this form
{
  "pileupName": "/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM",
  "pileupType": "classic",
  "expectedRSEs": [
    "T1_US_FNAL_Disk",
    "T2_CH_CERN"
  ],
  "currentRSEs": [
    "T1_US_FNAL_Disk",
    "T2_CH_CERN"
  ],
  "fullReplicas": 1,
  "campaigns": [
    "Apr2023_Val"
  ],
  "containerFraction": 1.0,
  "replicationGrouping": "ALL",
  "active": true,
  "pileupSize": 1233099715874,
  "ruleIds": [
    "55e5a21aecb5445c8aa40581a7bf18d2",
    "67a3fa7252f54507ba1c45f271beb754"
  ],
  "customName": ""
}

# change fraction
scurl -X PUT -H "Content-type: application/json" -d@./pileup-fraction.json https://cmsweb-test10.cern.ch/ms-pileup/data/pileup
# where pileup-fraction.json has this content:
{
  "pileupName": "/MinBias_TuneCP5_14TeV-pythia8/PhaseIITDRSpring19GS-106X_upgrade2023_realistic_v2_ext1-v1/GEN-SIM",
  "containerFraction": 0.75
}
```
And, I made few tests:
- inject new document
- change fraction to 0.5, SUCCESS in transition record
- change fraction to 0.3, SUCCESS in transition record, but I got in a log rucio complain shown here https://github.com/dmwm/WMCore/issues/11937#issuecomment-2009483420
- change fraction to 0.75, FAIL with this error https://github.com/dmwm/WMCore/issues/11937#issuecomment-2009493027

I think we need to understand Rucio did issues before moving further.

**Comment by dynamic-entropy** [comment]
In the second case, https://github.com/dmwm/WMCore/issues/11937#issuecomment-2009493027, it seems to be querying for a did that was perhaps never registered.
