### ISSUE TITLE
Condor is not able to access runtime scripts from WMAgent container

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11946]
**Impact of the bug**
WMAgent

**Fixed by:** https://github.com/dmwm/CMSKubernetes/pull/1460

**Describe the bug**
In short, when running jobs from a container-based WMAgent, there is an inconsistent path for the runtime WMAgent code which crashes grid jobs right away. 

The jobs are not even reaching the grid.  They fail directly into the agent with the following error: [1]. The most important line is: 
```
                <a n="Message"><s>Error from slot1_5@glidein_8_165834852@cmsgli-118187-0-cmswn6018.fnal.gov: SHADOW at 2001:1458:d00:39::100:49 failed to send file(s) to &lt;[2620:6a:0:8421:f0:0:190:77]:41669&gt;: |Error: reading from file /usr/local/lib/python3.8/site-packages/WMCore/WMRuntime/Unpacker.py: (errno 2) No such file or directory; STARTER failed to receive file(s) from &lt;[2001:1458:d00:39::100:49]:4080&gt;</s></a>
```
Htcondor puts the job on hold immediately, and what we see is basically only the condor error logs and nothing related to the WMagent  jobs. 

Here is all that is preserved in the job archive:
```
cmst1@vocms0290:Job_1 $ ll
total 20
-rw-r--r--. 1 cmst1 zh 8145 Mar 18 16:58 condor.3958.0.log
-rw-r--r--. 1 cmst1 zh 2732 Mar 18 16:53 job.pkl
-rw-r--r--. 1 cmst1 zh 4514 Mar 18 16:59 Report.0.pkl
``` 

One is for sure, the origin of the problem is not hidden behind the difference in the job working directory path set inside the container and the host:
```
/data/dockerMount/srv/wmagent/2.3.0/ vs. /data/srv/wmagent/2.3.0/
``` 
Because this  one  is already resolved with a symbolic link created at  the host: 
```
cmst1@vocms0290:Job_1 $ ls -la /data/srv/wmagent
lrwxrwxrwx. 1 cmst1 zh 29 Mar 18 15:31 /data/srv/wmagent -> /data/dockerMount/srv/wmagent
```  

The `Unpacker` script itself lives in the regular path for all WMcore modules (including Runtime), which is: [`WMCore/src/python/WMCore/`](https://github.com/dmwm/WMCore/tree/master/src/python/WMCore), and it ends up in the container's `$WMA_DEPLOY_DIR` itself which in our case is: 
```
(WMAgent-2.3.0) [cmst1@vocms0290:current]$ echo $WMA_DEPLOY_DIR
/usr/local
```

And this is also quite visible from the error message itslef. The Unpacker script is searched for at: 
```
/usr/local/lib/python3.8/site-packages/WMCore/WMRuntime/Unpacker.py
```
Which is inside the container and not part of the host mount point. This is a location completely invisible for HTCondor.

**NOTE:** 
For the purpose of this investigation, I also ran this same test in a virtual environment, which lacks the extra encapsulation coming from the Docker container, so HTCondor and the Agent runtime environment should see all the host files without the extra bind mount complications, but the error still exists:

```

    <a n="HoldReason"><s>Transfer input files failure at access point vocms0290 while sending files to the execution point. Details: reading from file /data/WMAgent.venv3/srv/WMCore/WMCore/WMRuntime/Unpacker.py: (errno 2) No such file or directory</s></a>
```

This makes me think here may be involved a wrongly set environment variable at the agent during the deployment  which should be referring to the correct path at runtime. `WMCORE_ROOT` is one that comes to mind, which is set with the [`WMCore/deploy/env.sh`](https://github.com/dmwm/WMCore/blob/master/deploy/env.sh)  script and is a major dependence at the manage script:   [CMSKubernetes/.../bin/manage#L14-L22](https://github.com/dmwm/CMSKubernetes/blob/192b3037b26d05d29ea668da80f93ce48303d013/docker/pypi/wmagent/bin/manage#L14-L22) 

```
# NOTE: The folowing environment variables, which are referenced from inside the WMCore code,
#       are exported by sourcing the $WMA_ENV_FILE at runtime, but not from the Dockerfile at build time
#
#       * $WMAGENTPY3_VERSION
#       * $WMAGENTPY3_ROOT
#       * $WMCORE_ROOT
#       * install
#       * config
#       * X509_*
```

It is located here:

```
(WMAgent-2.3.0) [cmst1@vocms0290:current]$ echo $WMA_ENV_FILE
/usr/local/deploy/env.sh
```

And its contents (after all the tweaks done at deployment time):

```
(WMAgent-2.3.0) [cmst1@vocms0290:current]$ cat /usr/local/deploy/env.sh 
cd $WMA_ROOT_DIR/srv/wmagent/current

# exporting the variables to the enviroment
export WMAGENT_SECRETS_LOCATION=$WMA_ROOT_DIR/admin/wmagent/WMAgent.secrets
export X509_HOST_CERT=$WMA_ROOT_DIR/certs/servicecert.pem
export X509_HOST_KEY=$WMA_ROOT_DIR/certs/servicekey.pem
export X509_USER_CERT=$WMA_ROOT_DIR/certs/servicecert.pem
export X509_USER_KEY=$WMA_ROOT_DIR/certs/servicekey.pem
export X509_USER_PROXY=$WMA_ROOT_DIR/certs/myproxy.pem
export install=$WMA_INSTALL_DIR
export config=$WMA_CONFIG_DIR
export manage=$WMA_MANAGE_DIR/manage
export RUCIO_HOME=$WMA_CONFIG_DIR

alias condorq='condor_q -format "%i." ClusterID -format "%s " ProcId -format " %i " JobStatus  -format " %d " ServerTime-EnteredCurrentStatus -format "%s" UserLog -format " %s\n" DESIRED_Sites'
alias condor_overview='python ~/condor_overview.py'
export WMA_BUILD_ID=$(cat $WMA_ROOT_DIR/.dockerBuildId)
export WMCORE_ROOT=$WMA_DEPLOY_DIR
export WMAGENTPY3_ROOT=$WMA_INSTALL_DIR
export WMAGENTPY3_VERSION=$WMA_TAG
export CRYPTOGRAPHY_ALLOW_OPENSSL_102=true
export YUI_ROOT=/usr/local/yui/
export PATH=$WMA_INSTALL_DIR/bin${PATH:+:$PATH}
export PATH=$WMA_DEPLOY_DIR/bin${PATH:+:$PATH}

```

And the real location to which this variable points to  (and $WMAGENTPY3_ROOT as well): 
```
(WMAgent-2.3.0) [cmst1@vocms0290:current]$ echo $WMCORE_ROOT
/usr/local
(WMAgent-2.3.0) [cmst1@vocms0290:current]$ echo $WMAGENTPY3_ROOT
/data/srv/wmagent/2.3.0/install
```
So the former one is pointing inside the container, while the later points to the mount point visible also at the host. So one solution would be to copy the `Unpacker` script at the destination visible from the host during the agent initialization time, [here](https://github.com/dmwm/CMSKubernetes/blob/192b3037b26d05d29ea668da80f93ce48303d013/docker/pypi/wmagent/init.sh#L99):
```
deploy_to_host(){
    # This function does all the needed Docker image to Host modifications at Runtime
    # DONE: Here to execute all local config and manage/copy opertaions from the image deploy area of the container to the host
```
But to be honest  this solution I'd consider a last resort.

**How to reproduce it**
Build a WMAgent  docker container and run it.
Upon that  send a set a workflows targeting the relevant WMAgent. 

**Expected behavior**
Condor to be able to create the sandbox for the Job regardless of the fact if it runs inside or outside the container. 

**Additional context and error message**

[1]
https://cmsweb-testbed.cern.ch/wmstatsserver/data/jobdetail/tivanov_ReReco_RunBlockWhite_WMAgentDockerTest_v2_240318_144614_1700

```
Errors:

    NoJobReport
        NoJobReport (Exit Code: 99303)

            Could not find jobReport

            ========== condor.3958.0.err ==========

            ========== condor.3958.0.out ==========

            ========== condor.3958.0.log ==========
            Adding end of condor.3958.0.log to error message:

                <a n="EnteredCurrentStatus"><i>1710777519</i></a>
                <a n="ExtDESIRED_Sites"><s>T1_US_FNAL,T2_CH_CERN</s></a>
                <a n="WMAgent_JobID"><i>1</i></a>
                <a n="JobStartDate"><i>1710777519</i></a>
                <a n="JobStatus"><i>2</i></a>
                <a n="TriggerEventTypeName"><s>ULOG_SHADOW_EXCEPTION</s></a>
                <a n="EventTime"><s>2024-03-18T16:58:47.670</s></a>
                <a n="Cluster"><i>3958</i></a>
                <a n="MachineAttrGLIDEIN_CMSSite0"><s>T1_US_FNAL</s></a>
                <a n="Proc"><i>0</i></a>
                <a n="MyType"><s>JobAdInformationEvent</s></a>
                <a n="ReceivedBytes"><r>2.663137000000000E+06</r></a>
                <a n="EventTypeNumber"><i>28</i></a>
                <a n="Subproc"><i>0</i></a>
                <a n="SentBytes"><r>0.0</r></a>
                <a n="Message"><s>Error from slot1_5@glidein_8_165834852@cmsgli-118187-0-cmswn6018.fnal.gov: SHADOW at 2001:1458:d00:39::100:49 failed to send file(s) to &lt;[2620:6a:0:8421:f0:0:190:77]:41669&gt;: |Error: reading from file /usr/local/lib/python3.8/site-packages/WMCore/WMRuntime/Unpacker.py: (errno 2) No such file or directory; STARTER failed to receive file(s) from &lt;[2001:1458:d00:39::100:49]:4080&gt;</s></a>
                <a n="DESIRED_Sites"><s>T1_US_FNAL,T2_CH_CERN</s></a>
            </c>
            <c>
                <a n="HoldReasonCode"><i>13</i></a>
                <a n="HoldReason"><s>Transfer input files failure at access point vocms0290 while sending files to the execution point. Details: reading from file /usr/local/lib/python3.8/site-packages/WMCore/WMRuntime/Unpacker.py: (errno 2) No such file or directory</s></a>
                <a n="HoldReasonSubCode"><i>2</i></a>
                <a n="Subproc"><i>0</i></a>
                <a n="EventTypeNumber"><i>12</i></a>
                <a n="MyType"><s>JobHeldEvent</s></a>
                <a n="Proc"><i>0</i></a>
                <a n="Cluster"><i>3958</i></a>
                <a n="EventTime"><s>2024-03-18T16:58:48.122</s></a>
            </c>
            <c>
                <a n="EnteredCurrentStatus"><i>1710777528</i></a>
                <a n="ExtDESIRED_Sites"><s>T1_US_FNAL,T2_CH_CERN</s></a>
                <a n="QDate"><i>1710777198</i></a>
                <a n="TriggerEventTypeNumber"><i>12</i></a>
                <a n="DESIRED_Sites"><s>T1_US_FNAL,T2_CH_CERN</s></a>
                <a n="JobStartDate"><i>1710777519</i></a>
                <a n="JobStatus"><i>5</i></a>
                <a n="TriggerEventTypeName"><s>ULOG_JOB_HELD</s></a>
                <a n="EventTime"><s>2024-03-18T16:58:48.122</s></a>
                <a n="Cluster"><i>3958</i></a>
                <a n="MachineAttrGLIDEIN_CMSSite0"><s>T1_US_FNAL</s></a>
                <a n="Proc"><i>0</i></a>
                <a n="EventTypeNumber"><i>28</i></a>
                <a n="Subproc"><i>0</i></a>
                <a n="MyType"><s>JobAdInformationEvent</s></a>
                <a n="HoldReasonSubCode"><i>2</i></a>
                <a n="HoldReasonCode"><i>13</i></a>
                <a n="HoldReason"><s>Transfer input files failure at access point vocms0290 while sending files to the execution point. Details: reading from file /usr/local/lib/python3.8/site-packages/WMCore/WMRuntime/Unpacker.py: (errno 2) No such file or directory</s></a>
                <a n="WMAgent_JobID"><i>1</i></a>
            </c>

```

**Comment by todor-ivanov** [comment]
Hi @amaltaro  I actually did something more than just updating the issue's description. I've also put there all the information I have collected during the investigation I was already doing last week. You may  take a look for more details.

**Comment by todor-ivanov** [comment]
And here is the fix for this: 
https://github.com/dmwm/CMSKubernetes/pull/1460/files

**Comment by todor-ivanov** [comment]
And with those changes we just made one step further to the final goal but we did not achieve it in full:
Here is the next  condor error we have stumbled on: [1] . from which the most important part is: 
```
Error: reading from file /usr/local/etc/submit.sh: (errno 2) No such file or directory;
```


[1]
```
Could not find jobReport

========== condor.3961.0.err ==========

========== condor.3961.0.out ==========

========== condor.3961.0.log ==========
Adding end of condor.3961.0.log to error message:

    <a n="EnteredCurrentStatus"><i>1712000144</i></a>
    <a n="ExtDESIRED_Sites"><s>T1_US_FNAL</s></a>
    <a n="WMAgent_JobID"><i>11</i></a>
    <a n="JobStartDate"><i>1712000144</i></a>
    <a n="JobStatus"><i>2</i></a>
    <a n="TriggerEventTypeName"><s>ULOG_SHADOW_EXCEPTION</s></a>
    <a n="EventTime"><s>2024-04-01T21:35:57.701</s></a>
    <a n="Cluster"><i>3961</i></a>
    <a n="MachineAttrGLIDEIN_CMSSite0"><s>T1_US_FNAL</s></a>
    <a n="Proc"><i>0</i></a>
    <a n="MyType"><s>JobAdInformationEvent</s></a>
    <a n="ReceivedBytes"><r>2.674767000000000E+06</r></a>
    <a n="EventTypeNumber"><i>28</i></a>
    <a n="Subproc"><i>0</i></a>
    <a n="SentBytes"><r>0.0</r></a>
    <a n="Message"><s>Error from slot1_8@glidein_8_228200112@cmsgli-179625-0-cmswn3003.fnal.gov: SHADOW at 2001:1458:d00:39::100:49 failed to send file(s) to &lt;[2620:6a:0:8421:f0:0:190:18]:42129&gt;: |Error: reading from file /usr/local/etc/submit.sh: (errno 2) No such file or directory; STARTER failed to receive file(s) from &lt;[2001:1458:d00:39::100:49]:4080&gt;</s></a>
    <a n="DESIRED_Sites"><s>T1_US_FNAL</s></a>
</c>
<c>
    <a n="HoldReasonCode"><i>13</i></a>
    <a n="HoldReason"><s>Transfer input files failure at access point vocms0290 while sending files to the execution point. Details: reading from file /usr/local/etc/submit.sh: (errno 2) No such file or directory</s></a>
    <a n="HoldReasonSubCode"><i>2</i></a>
    <a n="Subproc"><i>0</i></a>
    <a n="EventTypeNumber"><i>12</i></a>
    <a n="MyType"><s>JobHeldEvent</s></a>
    <a n="Proc"><i>0</i></a>
    <a n="Cluster"><i>3961</i></a>
    <a n="EventTime"><s>2024-04-01T21:36:07.986</s></a>
</c>
<c>
    <a n="EnteredCurrentStatus"><i>1712000167</i></a>
    <a n="ExtDESIRED_Sites"><s>T1_US_FNAL</s></a>
    <a n="QDate"><i>1711982430</i></a>
    <a n="TriggerEventTypeNumber"><i>12</i></a>
    <a n="DESIRED_Sites"><s>T1_US_FNAL</s></a>
    <a n="JobStartDate"><i>1712000144</i></a>
    <a n="JobStatus"><i>5</i></a>
    <a n="TriggerEventTypeName"><s>ULOG_JOB_HELD</s></a>
    <a n="EventTime"><s>2024-04-01T21:36:07.986</s></a>
    <a n="Cluster"><i>3961</i></a>
    <a n="MachineAttrGLIDEIN_CMSSite0"><s>T1_US_FNAL</s></a>
    <a n="Proc"><i>0</i></a>
    <a n="EventTypeNumber"><i>28</i></a>
    <a n="Subproc"><i>0</i></a>
    <a n="MyType"><s>JobAdInformationEvent</s></a>
    <a n="HoldReasonSubCode"><i>2</i></a>
    <a n="HoldReasonCode"><i>13</i></a>
    <a n="HoldReason"><s>Transfer input files failure at access point vocms0290 while sending files to the execution point. Details: reading from file /usr/local/etc/submit.sh: (errno 2) No such file or directory</s></a>
    <a n="WMAgent_JobID"><i>11</i></a>
</c>

```

**Comment by todor-ivanov** [comment]
One more painful step further with this commit: [CMSKubernetes#1460/commits: Change config.JobSubmitter.submitScript location
 ](https://github.com/dmwm/CMSKubernetes/pull/1460/commits/6fceb0fd511c3d8aecc9b56462dccb50258ab5f1) Its purpose is to copy also the `submit.py` script together with the rest of the environment and to tweak the wmagent config in such a way that it would be placed in a location reachable by HTCondor

**Comment by todor-ivanov** [comment]
Unfortunately the small but significant success from few minutes ago leads to yet another stone to stumble on: 

The workflow submitted was: [SC_MultiPU_WMAgentDockerTest_v7_240418_124104_3709](https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_SC_MultiPU_WMAgentDockerTest_v7_240418_124104_3709)

The jobs again reached to condor and tried to run. But here are the errors observed this time: [SC_MultiPU_WMAgentDockerTest_v7_240418_124104_3709/JobDetails](https://cmsweb-testbed.cern.ch/wmstatsserver/data/jobdetail/tivanov_SC_MultiPU_WMAgentDockerTest_v7_240418_124104_3709)



```
Could not find jobReport

========== condor.8218.0.err ==========
Adding end of condor.8218.0.err to error message:

GWMS_SINGULARITY_BIND_GPU_LIBS=1
CVMFS_REPOS_LIST=
APPTAINER_BIND=/etc/grid-security,/etc/hosts,/etc/localtime,/cvmfs
OMP_THREAD_LIMIT=4
GWMS_SINGULARITY_LIB_VERSION=2
GLITE_LOCATION=/usr
GLIDEIN_PROVIDES=singularity/unprivileged
GLIDEIN_LOCAL_TMP_DIR=/tmp/glide_cmsplt02_4JPANo
_CONDOR_JOB_IWD=/srv
SITE_NAME=CERN-PROD
TF_LOOP_PARALLEL_ITERATIONS=4
SRM_PATH=/opt/d-cache/srm
GWMS_SINGULARITY_OUTSIDE_PWD=/pool/condor/dir_3830787/glide_JEQAVM/execute/dir_12139
GWMS_SINGULARITY_IMAGE_RESTRICTIONS=cvmfs
CONDOR_PROCD_ADDRESS=/pool/condor/dir_3830787/glide_JEQAVM/log/procd_address
_=/usr/bin/printenv
DEBUG (/srv/.gwms-user-job-wrapper.sh) GWMS singularity wrapper, final setup.
DEBUG (/srv/.gwms-user-job-wrapper.sh) current directory at execution (/srv): total 5820
drwx------. 5 cmsplt02 zh    4096 Apr 19 21:20 .
drwxr-xr-x. 1 cmsplt02 zh      40 Apr 19 21:20 ..
-rw-r--r--. 1 cmsplt02 zh   14462 Apr 19 21:20 .LOG_.gwms-user-job-wrapper.sh.21.txt
drwx------. 2 cmsplt02 zh       6 Apr 19 21:20 .apptainer
-rwx------. 1 cmsplt02 zh      48 Apr 19 21:20 .chirp.config
drwxr-xr-x. 5 cmsplt02 zh      56 Apr 19 21:20 .gwms.d
drwxr-xr-x. 2 cmsplt02 zh      40 Apr 19 21:20 .gwms_aux
-rw-r--r--. 1 cmsplt02 zh    9645 Apr 19 21:20 .job.ad
-rw-r--r--. 1 cmsplt02 zh   17503 Apr 19 21:20 .machine.ad
-rw-r--r--. 1 cmsplt02 zh   12018 Apr 19 21:20 JobPackage.pkl
-rw-r--r--. 1 cmsplt02 zh    4938 Apr 19 21:20 Unpacker.py
-rw-r--r--. 1 cmsplt02 zh   19302 Apr 19 21:20 _condor_stderr
-rw-r--r--. 1 cmsplt02 zh     121 Apr 19 21:20 _condor_stdout
-rwxr-xr-x. 1 cmsplt02 zh    7502 Apr 19 21:20 condor_exec.exe
-rw-------. 1 cmsplt02 zh   17544 Apr 19 21:20 myproxy.pem
-rw-r--r--. 1 cmsplt02 zh 5828100 Apr 19 21:20 tivanov_SC_MultiPU_WMAgentDockerTest_v7_240418_124104_3709-Sandbox.tar.bz2
DEBUG (/srv/.gwms-user-job-wrapper.sh) GWMS singularity wrapper, job exec: /srv/condor_exec.exe tivanov_SC_MultiPU_WMAgentDockerTest_v7_240418_124104_3709-Sandbox.tar.bz2 1 0
DEBUG (/srv/.gwms-user-job-wrapper.sh) GWMS singularity wrapper, messages after this line are from the actual job ##################
Traceback (most recent call last):
  File "Startup.py", line 18, in <module>
    from Utils.Timers import CodeTimer
  File "/srv/job/Utils/Timers.py", line 86
    self.logger.info(f"{self.label} took {runtime} seconds to complete")
                                                                      ^
SyntaxError: invalid syntax
+ cp 'WMTaskSpace/Report*.pkl' ../
cp: cannot stat 'WMTaskSpace/Report*.pkl': No such file or directory
+ ls -l WMTaskSpace
ls: cannot access WMTaskSpace: No such file or directory
+ ls -l 'WMTaskSpace/*'
ls: cannot access WMTaskSpace/*: No such file or directory
+ set +x

```

**Comment by khurtado** [comment]
The "syntax error" in line 86 is suspicious. I remember getting those when python2 was used rather than python3 for some tests.

**Comment by todor-ivanov** [comment]
Thanks @khurtado! that's  a good hint.

I wonder if it could be related to the problems with the singularity container. I do not think we use python2 anywhere any more. There were some issues with the ITB pool last 24 hours. Maybe I should try to resubmit in the GlobalPool. If we observe the same errors there we could attribute it for sure the job runtime configuration.

**Comment by khurtado** [comment]
@todor-ivanov One explanation could be that `submit.sh` is getting executed rather than `submit_py3.sh`

**Comment by todor-ivanov** [comment]
hmm.... good point....

**Comment by todor-ivanov** [comment]
Thank you @khurtado it was a supper useful remark of yours !!!

And, 
* Here is the commit to fix that silly mistake of mine: [#CMSKubernetes/1460/commits:Fixing wrong submitScript](https://github.com/dmwm/CMSKubernetes/pull/1460/commits/8f741b51bdf27171562ea8df9f72b94bd885acfb)
* Here are 3 other workflows for us to monitor for the outcome: 
    * [SC_MultiPU_WMAgentDockerTest_v8_240419_214153_2257 ](https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_SC_MultiPU_WMAgentDockerTest_v8_240419_214153_2257)
    * [ReReco_Run2022C_LumiMask_WMAgentDockerTest_v8_240419_214144_7576](https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_Run2022C_LumiMask_WMAgentDockerTest_v8_240419_214144_7576)
    *  [ReReco_RunBlockWhite_WMAgentDockerTest_v8_240419_214137_806](https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=tivanov_ReReco_RunBlockWhite_WMAgentDockerTest_v8_240419_214137_806)

**Comment by todor-ivanov** [comment]
I can already see the workflows completing. I've sent the same set of workflows to both: the GlobalPool (through vocms0290)  and to ITB (through vocms0260) . They behave absolutely the same (not that we would expect anything else). 

The suggestion that @khurtado  was the fix to the last Error. Thank you Kenyi, that was really right on the spot.  

I am merging the CMSKuberenetes changes and finally closing this issue now.
