### ISSUE TITLE
testCMSSWVersions test broken in python 3.9

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#12115]
**Impact of the bug**
Running the following unit tests breaks due to a python 3.9 threading issue:

[testCMSSWVersions](https://cmssdt.cern.ch/dmwm-jenkins/view/WMCore%20Docker/job/WMCore-Unittest-Baseline-khurtado2/48/testReport/junit/WMCore_t.ReqMgr_t.Service_t.Auxiliary_t/AuxiliaryTest/testCMSSWVersions/)

**Describe the bug**
When running the testCMSSWVersions unit test, we get an error outside our code, related to python 3.9:

```
 File "/usr/lib64/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.9/unittest/case.py", line 588, in run
    self._callSetUp()
  File "/usr/lib64/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/cmsbld/WMCore/test/python/WMCore_t/ReqMgr_t/Service_t/Auxiliary_t.py", line 30, in setUp
    RESTBaseUnitTestWithDBBackend.setUp(self)
  File "/home/cmsbld/WMCore/src/python/WMQuality/REST/RESTBaseUnitTestWithDBBackend.py", line 61, in setUp
    CherrypyTestInit.start(self.server)
  File "/home/cmsbld/WMCore/src/python/WMQuality/CherrypyTestInit.py", line 11, in start
    server.start(blocking=False)
  File "/home/cmsbld/WMCore/src/python/WMQuality/REST/ServerSetup.py", line 55, in start
    cherrypy.engine.start()
  File "/usr/local/lib/python3.9/site-packages/cherrypy/process/wspbus.py", line 278, in start
    self.exit()
  File "/usr/local/lib/python3.9/site-packages/cherrypy/process/wspbus.py", line 310, in exit
    os._exit(EX_SOFTWARE)
  File "/home/cmsbld/WMCore/setup_test.py", line 109, in trapExit
    raise SystemExit("os._exit() was called in a child thread. " + \
```

**How to reproduce it**
Run unit test above

**Expected behavior**
We should not get a raised error from os._exit()

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by d-ylee** [comment]
Additional context/traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib64/python3.9/threading.py", line 894, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

cherrypy.error: ERROR: [28/Jan/2025:15:28:26] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/local/lib/python3.9/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: RuntimeError('threads can only be started once')
```
