### ISSUE TITLE
wm_workers handling on error messages

### ISSUE THREAD

**Issue by samircury** [dmwm/WMCore#3612]
I got a component crashing with a "too big" error message, maybe the treating should be improved, either truncating the message or allowing bigger messages in the schema? (2nd won't solve all cases though)

Error looks like :

{{{

012-04-18 16:21:44,660:INFO:Harness:>>>Terminating worker threads
2012-04-18 16:21:44,667:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller instance at 0x437ab48> (DatabaseError) ORA-12899: value too large for column "CMS_T0AST_REPLAY2"."WM_WORKERS"."ERROR_MESSAGE" (actual: 2226, maximum: 1000)
 'UPDATE wm_workers \n              SET last_error = :last_error,  \n                  state = :state, error_message = :error_message \n              WHERE component_id = (SELECT id FROM wm_components WHERE name = :component_name)\n                   AND name = :worker_name' {'last_error': 1334758904, 'state': 'Error', 'worker_name': 'RetryManagerPoller', 'error_message': 'Error in worker algorithm (1):\nBacktrace:\n  <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller instance at 0x437ab48> RetryManagerException\nMessage: Exception while checking for cooloff timeout for job 1\n\'ConfigSection\' object has no attribute \'PauseCount\'\n\tModuleName : WMComponent.RetryManager.RetryManagerPoller\n\tMethodName : selectRetryAlgo\n\tClassInstance : None\n\tFileName : /data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/RetryManagerPoller.py\n\tClassName : None\n\tLineNumber : 219\n\tErrorNr : 0\n\nTraceback: \nTraceback (most recent call last):\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 210, in selectRetryAlgo\n    if self.plugin.isReady(job = job, jobType = jobType):\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/PlugIns/PauseAlgo.py", line 27, in isReady\n    pauseCount = self.config.RetryManager.PauseCount\nAttributeError: \'ConfigSection\' object has no attribute \'PauseCount\'\n\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 160, in __call__\n    self.algorithm(parameters)\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 110, in algorithm\n    self.doRetries()\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 237, in doRetries\n    self.processRetries(jobs, \'submit\')\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 156, in processRetries\n    propList = self.selectRetryAlgo(jobList, jobType)\n  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 219, in selectRetryAlgo\n    raise RetryManagerException(msg)\n', 'component_name': 'RetryManager'}
Backtrace:
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 188, in __call__
    myThread.getName(), msg)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMCore/Agent/HeartbeatAPI.py", line 64, in updateWorkerError
    transaction = self.existingTransaction())
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMCore/Agent/Database/MySQL/UpdateWorkerError.py", line 31, in execute
    transaction = transaction)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 179, in processData
    returnCursor = returnCursor)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/cms/wmcore/0.8.37/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 65, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp5/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 824, in execute
    return Connection.executors[c](self, object, multiparams, params)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp5/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 888, in _execute_text
    return self.__execute_context(context)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp5/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 896, in __execute_context
    self._cursor_execute(context.cursor, context.statement, context.parameters[0], context=context)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp5/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 950, in _cursor_execute
    self._handle_dbapi_exception(e, statement, parameters, cursor, context)
  File "/data/srv/wmagent/1.9.1/sw.pre/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp5/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 931, in _handle_dbapi_exception
    raise exc.DBAPIError.instance(statement, parameters, e, connection_invalidated=is_disconnect)

2012-04-18 16:21:44,667:INFO:BaseWorkerThread:Worker thread <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller instance at 0x437ab48> terminated

}}}

**Comment by amaltaro** [comment]
@ticoann @hufnagel can we close this one (3 years without any news)?
