### ISSUE TITLE
Analyticscolllector is missing some vals from the configuration

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4198]
```
======================================================================
ERROR: Tests the components, as in sees if they load.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jenkins/workspace/WMCore-UnitTests-try/jobSlice/8/label/wmcore-unit-test-slaves/code/test/python/WMComponent_t/AnalyticsDataCollector_t/AnalyticsDataCollector_t.py", line 110, in testAnalyticsPoller
    analytics = AnalyticsPoller(config)
  File "/jenkins/install/lib/python2.6/site-packages/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py", line 34, in __init__
    self.agentInfo['agent_url'] = ("%s:%s" % (config.Agent.hostName, config.WMBSService.Webtools.port))
AttributeError: 'Configuration' object has no attribute 'WMBSService'
```

seangchan, can you take a look at this and un-blacklist the tests?

**Comment by amaltaro** [comment]
@ticoann should we also close this one?

**Comment by ticoann** [comment]
I will fix this.
