### ISSUE TITLE
TestInitCouchApp can blow up in tearDown

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/WMCore#4263]
```
Traceback (most recent call last):
  File "/jenkins/deploy/0.9.28/sw/slc5_amd64_gcc461/external/python/2.6.8-comp/lib/python2.6/unittest.py", line 289, in run
    self.tearDown()
  File "/jenkins/workspace/WMCore-UnitTests-try/jobSlice/6/label/wmcore-unit-test-slaves/code/test/python/WMComponent_t/TaskArchiver_t/TaskArchiver_t.py", line 107, in tearDown
    self.testInit.tearDownCouch()
  File "/jenkins/install/lib/python2.6/site-packages/WMQuality/TestInitCouchApp.py", line 113, in tearDownCouch
    couch.drop()
  File "/jenkins/install/lib/python2.6/site-packages/WMQuality/TestInitCouchApp.py", line 53, in drop
    self.couchServer.deleteDatabase(self.dbName)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 786, in deleteDatabase
    return self.delete("/%s" % dbname)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 133, in delete
    encode, decode, contentType)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 108, in makeRequest
    getattr(e, "reason", None), data)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 125, in checkForCouchError
    raise CouchNotFoundError(reason, data, result)
CouchNotFoundError: CouchNotFoundError - reason: Object Not Found, data: {} result: None
```

```
Traceback (most recent call last):
  File "/jenkins/deploy/0.9.28/sw/slc5_amd64_gcc461/external/python/2.6.8-comp/lib/python2.6/unittest.py", line 289, in run
    self.tearDown()
  File "/jenkins/workspace/WMCore-UnitTests-try/jobSlice/8/label/wmcore-unit-test-slaves/code/test/python/WMCore_t/WorkQueue_t/WorkQueue_t.py", line 195, in tearDown
    WorkQueueTestCase.tearDown(self)
  File "/jenkins/workspace/WMCore-UnitTests-try/jobSlice/8/label/wmcore-unit-test-slaves/code/test/python/WMCore_t/WorkQueue_t/WorkQueueTestCase.py", line 61, in tearDown
    self.testInit.tearDownCouch()
  File "/jenkins/install/lib/python2.6/site-packages/WMQuality/TestInitCouchApp.py", line 113, in tearDownCouch
    couch.drop()
  File "/jenkins/install/lib/python2.6/site-packages/WMQuality/TestInitCouchApp.py", line 53, in drop
    self.couchServer.deleteDatabase(self.dbName)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 786, in deleteDatabase
    return self.delete("/%s" % dbname)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 133, in delete
    encode, decode, contentType)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 108, in makeRequest
    getattr(e, "reason", None), data)
  File "/jenkins/install/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 125, in checkForCouchError
    raise CouchNotFoundError(reason, data, result)
CouchNotFoundError: CouchNotFoundError - reason: Object Not Found, data: {} result: None
```

**Comment by amaltaro** [comment]
@ericvaandering another Jenkins stuff

**Comment by ericvaandering** [comment]
Maybe just unit tests. Let me label it and see about it later.
