### ISSUE TITLE
Oracle deadlock in JobStatusLite

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5213]
Creating this issue so we do not lose track of it.

Here is part the traceback got back from the JobStatusLite logs

```
2014-07-09 11:29:16,067:ERROR:StatusPoller:Unhandled error in statusPoller(DatabaseError) ORA-00060: deadlock detected while waiting for resource
 'UPDATE wmbs_job\n          SET location = COALESCE((SELECT id FROM wmbs_location WHERE cms_name = :location), location)\n          WHERE id = :jobID' [{'location': 'T2_ES_IFCA', '
jobID': 1586437}, {'location': 'T2_ES_IFCA', 'jobID': 1586439}, {'location': 'T2_ES_IFCA', 'jobID': 1587964}, {'location': 'T2_ES_IFCA', 'jobID': 1587965}, {'location': 'T2_ES_IFCA'
, 'jobID': 1588495}, {'location': 'T2_ES_IFCA', 'jobID': 1589503}, {'location': 'T2_ES_IFCA', 'jobID': 1616563}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616564}, {'location': 'T2_ES
_IFCA', 'jobID': 1616565}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616566}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616567}, {'location': 'T2_IT_Pisa', 'jobID': 1616918}, {'location
': 'T2_US_Nebraska', 'jobID': 1618186}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1618817}]
Traceback (most recent call last):
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/StatusPoller.py", line 65, in algorithm
    self.checkStatus()
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/StatusPoller.py", line 91, in checkStatus
    runningJobs = self.bossAir.track()
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/BossAirAPI.py", line 564, in track
    self._updateJobs(jobs = jobsToChange)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/BossAirAPI.py", line 307, in _updateJobs
    self.stateMachine.recordLocationChange(jobsWithLocation)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/JobStateMachine/ChangeState.py", line 538, in recordLocationChange
    transaction = self.existingTransaction())
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/WMBS/MySQL/Jobs/UpdateLocation.py", line 34, in execute
    transaction = transaction)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 167, in processData
    returnCursor=returnCursor))
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 114, in executemanybinds
    result = connection.execute(s, b)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 824, in execute
    return Connection.executors[c](self, object, multiparams, params)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 888, in _execute_text
    return self.__execute_context(context)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 894, in __execute_context
    self._cursor_executemany(context.cursor, context.statement, context.parameters, context=context)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 960, in _cursor_executemany
    self._handle_dbapi_exception(e, statement, parameters, cursor, context)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 931, in _handle_dbapi_excepti
on
    raise exc.DBAPIError.instance(statement, parameters, e, connection_invalidated=is_disconnect)
DatabaseError: (DatabaseError) ORA-00060: deadlock detected while waiting for resource
 'UPDATE wmbs_job\n          SET location = COALESCE((SELECT id FROM wmbs_location WHERE cms_name = :location), location)\n          WHERE id = :jobID' [{'location': 'T2_ES_IFCA', '
jobID': 1586437}, {'location': 'T2_ES_IFCA', 'jobID': 1586439}, {'location': 'T2_ES_IFCA', 'jobID': 1587964}, {'location': 'T2_ES_IFCA', 'jobID': 1587965}, {'location': 'T2_ES_IFCA'
, 'jobID': 1588495}, {'location': 'T2_ES_IFCA', 'jobID': 1589503}, {'location': 'T2_ES_IFCA', 'jobID': 1616563}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616564}, {'location': 'T2_ES_IFCA', 'jobID': 1616565}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616566}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616567}, {'location': 'T2_IT_Pisa', 'jobID': 1616918}, {'location': 'T2_US_Nebraska', 'jobID': 1618186}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1618817}]
2014-07-09 11:29:16,223:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMCore.BossAir.StatusPoller.StatusPoller instance at 0x1272ab8> StatusPollerException
Message: Unhandled error in statusPoller(DatabaseError) ORA-00060: deadlock detected while waiting for resource
 'UPDATE wmbs_job\n          SET location = COALESCE((SELECT id FROM wmbs_location WHERE cms_name = :location), location)\n          WHERE id = :jobID' [{'location': 'T2_ES_IFCA', 'jobID': 1586437}, {'location': 'T2_ES_IFCA', 'jobID': 1586439}, {'location': 'T2_ES_IFCA', 'jobID': 1587964}, {'location': 'T2_ES_IFCA', 'jobID': 1587965}, {'location': 'T2_ES_IFCA', 'jobID': 1588495}, {'location': 'T2_ES_IFCA', 'jobID': 1589503}, {'location': 'T2_ES_IFCA', 'jobID': 1616563}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616564}, {'location': 'T2_ES_IFCA', 'jobID': 1616565}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616566}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1616567}, {'location': 'T2_IT_Pisa', 'jobID': 1616918}, {'location': 'T2_US_Nebraska', 'jobID': 1618186}, {'location': 'T2_FR_CCIN2P3', 'jobID': 1618817}]
        ModuleName : WMCore.BossAir.StatusPoller
        MethodName : algorithm
        ClassInstance : None
        FileName : /data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/StatusPoller.py
        ClassName : None
        LineNumber : 78
        ErrorNr : 0
Traceback: 
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/StatusPoller.py", line 65, in algorithm
    self.checkStatus()

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/StatusPoller.py", line 91, in checkStatus
    runningJobs = self.bossAir.track()

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/BossAirAPI.py", line 564, in track
    self._updateJobs(jobs = jobsToChange)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/BossAirAPI.py", line 307, in _updateJobs
    self.stateMachine.recordLocationChange(jobsWithLocation)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/JobStateMachine/ChangeState.py", line 538, in recordLocationChange
    transaction = self.existingTransaction())

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/WMBS/MySQL/Jobs/UpdateLocation.py", line 34, in execute
    transaction = transaction)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 167, in processData
    returnCursor=returnCursor))

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/Database/DBCore.py", line 114, in executemanybinds
    result = connection.execute(s, b)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 824, in execute
    return Connection.executors[c](self, object, multiparams, params)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 888, in _execute_text
    return self.__execute_context(context)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 894, in __execute_context
    self._cursor_executemany(context.cursor, context.statement, context.parameters, context=context)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 960, in _cursor_executemany
    self._handle_dbapi_exception(e, statement, parameters, cursor, context)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/external/py2-sqlalchemy/0.5.2-comp7/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 931, in _handle_dbapi_exception
    raise exc.DBAPIError.instance(statement, parameters, e, connection_invalidated=is_disconnect)

  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 163, in __call__
    self.algorithm(parameters)
  File "/data/srv/wmagent/v0.9.91/sw/slc5_amd64_gcc461/cms/wmagent/0.9.91/lib/python2.6/site-packages/WMCore/BossAir/StatusPoller.py", line 78, in algorithm
```

**Comment by amaltaro** [comment]
@yuyiguo thanks for setting up cmssrv113 to deadlock debug mode. Just a reminder:
 - cmssrv113 has MariaDB and is ready to log deadlocks
 - vocms235 has Oracle but the NOLB has vanished in the last deployment (a couple of months ago, sorry)
 - vocms0304 has Oracle and was setup to NOLB

I've just managed to replicate the/a deadlock in vocms0304, JobStatusLite component is dead at the moment and I'll wait for you to look at it. I'm sending you more details in a private mail.

**Comment by yuyiguo** [comment]
Oracle deadlock was reproduced and trace file showed that the problem was caused by missing indexes on foreign keys. So I have added below indexes. 
 `CREATE INDEX CMS_WMBS_PROD9.IDX_BL_RUNJOB_WMBS ON CMS_WMBS_PROD9.BL_RUNJOB(WMBS_ID);`
`CREATE INDEX CMS_WMBS_PROD9.IDX_BL_RUNJOB_WMBS ON CMS_WMBS_PROD9.BL_RUNJOB(WMBS_ID);`
`CREATE INDEX CMS_WMBS_PROD9.IDX_BL_RUNJOB_STATUS ON CMS_WMBS_PROD9.BL_RUNJOB(SCHED_STATUS);`
`CREATE INDEX CMS_WMBS_PROD9.IDX_BL_RUNJOB_USERS ON CMS_WMBS_PROD9.BL_RUNJOB(USER_ID);`

Alan will test the change by reproduce the deadlock.

CREATE INDEX CMS_WMBS_PROD9.IDX_BL_RUNJOB_LOCATION ON CMS_WMBS_PROD9.BL_RUNJOB(LOCATION);

**Comment by amaltaro** [comment]
I haven't seen this happening again in Oracle. Since we have mostly used CERN agents for the last half year, I haven't seen this in MySQL as well. I actually don't remember if we managed to fix anything on the mysql backend.
