### ISSUE TITLE
Where is TotalEventCPU in Report.pkl (JobAccountant)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5642]
I have no time to look at it, so just throwing this error message that I have just seen in vocms053 for the JobAccountant component.
```
2015-02-26 21:10:34,900:INFO:AccountantWorker:Handling /data/srv/wmagent/v1.0.0.patch4/install/wmagent/JobCreator/JobCache/fabozzi_RVCMSSW_7_4_0_pre8RunHI2011__RelVal_hi2011_150225_173436_9069/RECOHID11/RECOHID11MergeALCARECOStreamTkAlMinBiasHI/JobCollection_38166_0/job_296904/Report.0.pkl
2015-02-26 21:10:35,000:ERROR:ChangeState:Error updating job in couch: 'TotalEventCPU'
2015-02-26 21:10:35,001:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.0.patch4/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch4/lib/python2.6/site-packages/WMCore/JobStateMachine/ChangeState.py", line 156, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.0.0.patch4/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch4/lib/python2.6/site-packages/WMCore/JobStateMachine/ChangeState.py", line 319, in recordInCouch
    updateSummaryDB(self.statsumdatabase, job)
  File "/data/srv/wmagent/v1.0.0.patch4/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch4/lib/python2.6/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 157, in updateSummaryDB
    sum_doc = fwjr_parser(document)
  File "/data/srv/wmagent/v1.0.0.patch4/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.0.patch4/lib/python2.6/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 84, in fwjr_parser
    pdict['totalEventCPU'] += float(perf['cpu']['TotalEventCPU'])
KeyError: 'TotalEventCPU'
```

Just in case, I kept the Report.pkl file in:
/afs/cern.ch/user/c/cmst1/public/forAlan/Report.0.pkl

**Comment by amaltaro** [comment]
Fixed by @hufnagel in the last couple of months.
