### ISSUE TITLE
WMTask unit test fails

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5653]
-bash-4.1$ python WMTask_t.py 
.......F......
======================================================================
FAIL: testJobSplittingArgs (__main__.WMTaskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "WMTask_t.py", line 179, in testJobSplittingArgs
    "Error: Wrong number of algo parameters.")
AssertionError: Error: Wrong number of algo parameters.

----------------------------------------------------------------------

**Comment by ericvaandering** [comment]
Possibly related: -bash-4.1$ python WMWorkload_t.py 
..........F.......FFF.....
======================================================================
FAIL: testListJobSplittingParametersByTask (__main__.WMWorkloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "WMWorkload_t.py", line 1183, in testListJobSplittingParametersByTask
    "Error: Wrong splitting parameters: %s" % results["/TestWorkload/ProcessingTask"])
AssertionError: Error: Wrong splitting parameters: {'trustSitelists': False, 'type': 'Processing', 'files_per_job': 2, 'algorithm': 'FileBased'}

======================================================================
FAIL: testUpdatingMergeParameters (__main__.WMWorkloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "WMWorkload_t.py", line 422, in testUpdatingMergeParameters
    "Error: Wrong number of params for proc task.")
AssertionError: Error: Wrong number of params for proc task.

======================================================================
FAIL: testUpdatingSplitParameters (__main__.WMWorkloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "WMWorkload_t.py", line 962, in testUpdatingSplitParameters
    "Error: Wrong number of params for proc task.")
AssertionError: Error: Wrong number of params for proc task.

======================================================================
FAIL: testUpdatingSubSplitParameters (__main__.WMWorkloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "WMWorkload_t.py", line 1103, in testUpdatingSubSplitParameters
    "Error: Wrong number of params for proc task.")
AssertionError: Error: Wrong number of params for proc task.

----------------------------------------------------------------------

**Comment by ericvaandering** [comment]
Working on master now. Closing.
