### ISSUE TITLE
Child queue is deleted when workflow is still open

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5735]
2015-03-29 17:03:03,462 INFO     WorkQueueReqMgrInterface: Contacting Request manager for more work

2015-03-29 17:03:03,980 WARNING  WorkQueueReqMgrInterface: no team or more than one team are assigined: amaltaro_MonteCarlo_TEST_ALAN_Move2Disk_v2_150329_161559_6055

2015-03-29 17:03:03,980 INFO     WorkQueueReqMgrInterface: Checking Request Manager for open requests and closing old ones

2015-03-29 17:03:06,114 ERROR    WorkQueueReqMgrInterface: Error caught during RequestManager split

Traceback (most recent call last):

  File "/data/srv/HG1504a-comp/sw.pre.sryu/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre7/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 40, in **call**

```
extraWork = self.addNewElementsToOpenRequests(queue)
```

  File "/data/srv/HG1504a-comp/sw.pre.sryu/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre7/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 296, in addNewElementsToOpenRequests

```
queue.closeWork()
```

  File "/data/srv/HG1504a-comp/sw.pre.sryu/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre7/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueue.py", line 772, in closeWork

```
lastUpdate = float(max(childrenElements, key = lambda x: x.timestamp).timestamp)
```

ValueError: max() arg is an empty sequence

**Comment by hufnagel** [comment]
@ticoann , shouldn't this have been closed when #5736 was merged ?

**Comment by ticoann** [comment]
Hi Dirk, That was temp fix. I want to check  how this happen if happens again and maybe recover it if possible.

**Comment by amaltaro** [comment]
Since it didn't happen since Mar 2015, shall we close it now? @ticoann
