### ISSUE TITLE
JobAccountant cannot find TotalEventCPU in fwjr

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5739]
Recording this error here to investigate in the next days. I've seen this error quite often in the agents, usually it happens to taskchain multicore jobs, but this case is a data taskchain
```
2015-03-30 21:45:48,050:INFO:AccountantWorker:Handling /data/srv/wmagent/v1.0.5.pre9/install/wmagent/JobCreator/JobCache/amaltaro_700_pre11_RunTau2012A_HG1504d_Ag105_150330_141000_8004/HLTD/RECODreHLT/Job
Collection_243_0/job_3934/Report.0.pkl
2015-03-30 21:45:49,188:ERROR:ChangeState:Error updating job in couch: 'TotalEventCPU'
2015-03-30 21:45:49,203:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.5.pre9/sw.pre.sryu/slc6_amd64_gcc481/cms/wmagent/1.0.5.pre9/lib/python2.6/site-packages/WMCore/JobStateMachine/ChangeState.py", line 156, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.0.5.pre9/sw.pre.sryu/slc6_amd64_gcc481/cms/wmagent/1.0.5.pre9/lib/python2.6/site-packages/WMCore/JobStateMachine/ChangeState.py", line 319, in recordInCouch
    updateSummaryDB(self.statsumdatabase, job)
  File "/data/srv/wmagent/v1.0.5.pre9/sw.pre.sryu/slc6_amd64_gcc481/cms/wmagent/1.0.5.pre9/lib/python2.6/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 157, in updateSummaryDB
    sum_doc = fwjr_parser(document)
  File "/data/srv/wmagent/v1.0.5.pre9/sw.pre.sryu/slc6_amd64_gcc481/cms/wmagent/1.0.5.pre9/lib/python2.6/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 84, in fwjr_parser
    pdict['totalEventCPU'] += float(perf['cpu']['TotalEventCPU'])
KeyError: 'TotalEventCPU'
``` 
I saved this pkl file in current of vocms009.
Feel free to assign this one to me.

**Comment by amaltaro** [comment]
Interestingly, I investigated that pickled file and it goes through that method without any problems (and TotalEventCPU is there)
```
>>> from WMCore.JobStateMachine import SummaryDB
>>> SummaryDB.fwjr_parser(wmbsJob)
{'tasks': {'/amaltaro_700_pre11_RunTau2012A_HG1504d_Ag105_150330_141000_8004/HLTD/RECODreHLT': {'sites': {'T2_CH_CERN': {'inputEvents': 426, 'cmsRunCPUPerformance': {'totalJobTime': 15198.700000000001, 'totalJobCPU': 3826.96, 'totalEventCPU': 3737.8600000000001}, 'wrappedTotalJobTime': 17737, 'dataset': {}}}}}, '_id': 'amaltaro_700_pre11_RunTau2012A_HG1504d_Ag105_150330_141000_8004'}
```
unless I got the wrong report pickle file...

**Comment by amaltaro** [comment]
@ticoann also high prio, I think this affects the final stats in the end (reqmgr_cache)

**Comment by hufnagel** [comment]
Yes, this is fixed by my change. Its an error but a passable one, agent still works, we "just" don't update job stats in couch.

**Comment by hufnagel** [comment]
We can probably close this...

**Comment by hufnagel** [comment]
@amaltaro , this is fixed, right ? If I don't hear feedback I'll close it...

**Comment by amaltaro** [comment]
Thanks Dirk! Indeed #5893  fixes this issue. Closing it
