### ISSUE TITLE
WMDataMining fail to retrieve some data from McM (in testbed)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5746]
Hey folks, while scanning the reqmgr2 logs in cmsweb-testbed, I noticed this error is being raised every 15min
```
[01/Apr/2015:02:27:24]  INFO: Active Requests: Getting job information from https://cmsweb-testbed.cern.ch/couchdb/wmstats and https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache. Please wait.
[01/Apr/2015:02:27:29]  INFO: Active Requests: Total 2115 requests retrieved

[01/Apr/2015:02:27:39] vocms0133.cern.ch 127.0.0.1 "GET /reqmgr2/data/about HTTP/1.1" 200 OK [data: 338 in 780 out 636656 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
[01/Apr/2015:02:27:42]  ERROR: <type 'exceptions.ValueError'> getting history from McM for PREP ID task_SUS-Fall13wmLHE-00011. Unknown error.
[01/Apr/2015:02:27:43]  ERROR: <type 'exceptions.ValueError'> getting history from McM for PREP ID REDIGITEST-0001. Unknown error.
[01/Apr/2015:02:27:43]  Periodic Thread ERROR __builtins__.KeyError 'request_status'
[01/Apr/2015:02:27:43]   Traceback (most recent call last):
[01/Apr/2015:02:27:43]     File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/CherryPyPeriodicTask.py", line 74, in run
[01/Apr/2015:02:27:43]       self.taskFunc(self.config)
[01/Apr/2015:02:27:43]     File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/WMDataMining.py", line 30, in gatherActiveDataStats
[01/Apr/2015:02:27:43]       archived = False, log = cherrypy.log)
[01/Apr/2015:02:27:43]     File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre9/lib/python2.6/site-packages/WMCore/WMDataMining/Utils.py", line 229, in gatherWMDataMiningStats
[01/Apr/2015:02:27:43]       for status in requests[wf]['request_status']:
[01/Apr/2015:02:27:43]   KeyError: 'request_status'
```
I know 0 about this service, but it seems it fails to retrieve wf information from McM (based on the prepID) and then it fails to find that key.

BTW, I just found this one as well
```
[30/Mar/2015:02:30:22]  INFO: Active Requests: Total 2071 requests retrieved

[30/Mar/2015:02:30:34]  Periodic Thread ERROR __builtins__.KeyError 'inputdataset'
[30/Mar/2015:02:30:34]   Traceback (most recent call last):
[30/Mar/2015:02:30:34]     File "/data/srv/beHG1504c/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre7/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/CherryPyPeriodicTask.py", line 74, in run
[30/Mar/2015:02:30:34]       self.taskFunc(self.config)
[30/Mar/2015:02:30:34]     File "/data/srv/beHG1504c/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre7/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/WMDataMining.py", line 30, in gatherActiveDat
aStats
[30/Mar/2015:02:30:34]       archived = False, log = cherrypy.log)
[30/Mar/2015:02:30:34]     File "/data/srv/beHG1504c/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre7/lib/python2.6/site-packages/WMCore/WMDataMining/Utils.py", line 137, in gatherWMDataMiningStats
[30/Mar/2015:02:30:34]       inputdataset = requests[wf]['inputdataset']
[30/Mar/2015:02:30:34]   KeyError: 'inputdataset'
```

**Comment by ericvaandering** [comment]
Thanks Alan. Let me look into this. It looks like I didn’t manage to trap every exception that could be thrown.

Eric

> On Apr 1, 2015, at 10:19, Alan Malta Rodrigues <notifications@github.com> wrote:
> 
> Hey folks, while scanning the reqmgr2 logs in cmsweb-testbed, I noticed this error is being raised every 15min
> 
> [01/Apr/2015:02:27:24]  INFO: Active Requests: Getting job information from https://cmsweb-testbed.cern.ch/couchdb/wmstats and https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache. Please wait.
> [01/Apr/2015:02:27:29]  INFO: Active Requests: Total 2115 requests retrieved
> 
> [01/Apr/2015:02:27:39] vocms0133.cern.ch 127.0.0.1 "GET /reqmgr2/data/about HTTP/1.1" 200 OK [data: 338 in 780 out 636656 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
> [01/Apr/2015:02:27:42]  ERROR: <type 'exceptions.ValueError'> getting history from McM for PREP ID task_SUS-Fall13wmLHE-00011. Unknown error.
> [01/Apr/2015:02:27:43]  ERROR: <type 'exceptions.ValueError'> getting history from McM for PREP ID REDIGITEST-0001. Unknown error.
> [01/Apr/2015:02:27:43]  Periodic Thread ERROR __builtins__.KeyError 'request_status'
> [01/Apr/2015:02:27:43]   Traceback (most recent call last):
> [01/Apr/2015:02:27:43]     File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/CherryPyPeriodicTask.py", line 74, in run
> [01/Apr/2015:02:27:43]       self.taskFunc(self.config)
> [01/Apr/2015:02:27:43]     File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/WMDataMining.py", line 30, in gatherActiveDataStats
> [01/Apr/2015:02:27:43]       archived = False, log = cherrypy.log)
> [01/Apr/2015:02:27:43]     File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre9/lib/python2.6/site-packages/WMCore/WMDataMining/Utils.py", line 229, in gatherWMDataMiningStats
> [01/Apr/2015:02:27:43]       for status in requests[wf]['request_status']:
> [01/Apr/2015:02:27:43]   KeyError: 'request_status'
> I know 0 about this service, but it seems it fails to retrieve wf information from McM (based on the prepID) and then it fails to find that key.
> 
> BTW, I just found this one as well
> 
> [30/Mar/2015:02:30:22]  INFO: Active Requests: Total 2071 requests retrieved
> 
> [30/Mar/2015:02:30:34]  Periodic Thread ERROR __builtins__.KeyError 'inputdataset'
> [30/Mar/2015:02:30:34]   Traceback (most recent call last):
> [30/Mar/2015:02:30:34]     File "/data/srv/beHG1504c/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre7/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/CherryPyPeriodicTask.py", line 74, in run
> [30/Mar/2015:02:30:34]       self.taskFunc(self.config)
> [30/Mar/2015:02:30:34]     File "/data/srv/beHG1504c/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre7/lib/python2.6/site-packages/WMCore/ReqMgr/CherryPyThreads/WMDataMining.py", line 30, in gatherActiveDat
> aStats
> [30/Mar/2015:02:30:34]       archived = False, log = cherrypy.log)
> [30/Mar/2015:02:30:34]     File "/data/srv/beHG1504c/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.5.pre7/lib/python2.6/site-packages/WMCore/WMDataMining/Utils.py", line 137, in gatherWMDataMiningStats
> [30/Mar/2015:02:30:34]       inputdataset = requests[wf]['inputdataset']
> [30/Mar/2015:02:30:34]   KeyError: 'inputdataset'
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/WMCore/issues/5746>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by ericvaandering** [comment]
We think this is due to RegMgr2 missing some data. I've protected the code against it and then @ticoann  can see which workflow(s) have a problem.

**Comment by ericvaandering** [comment]
BTW, nothing to do with McM, but it's good to see those errors are now being caught.
