### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'addFile'

### ISSUE THREAD

**Issue by juztas** [dmwm/WMCore#5762]
This is critical for CRAB3 right now... 
```
2015-04-09 00:55:13,967:ERROR:Handler:Problem handling 150408_225428:gdyckes_crab_QCD_Pt_30to80_bcToE_Tune4C_13TeV_pythia8_Phys14DR-PU20bx25_PHYS14_25_V1-v1 because of 'NoneType' object has no attribute 'addFile'
 failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 74, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/TaskWorker/Actions/Splitter.py", line 42, in execute
    factory = jobfactory(**splitparam)
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/WMCore/JobSplitting/JobFactory.py", line 90, in __call__
    self.algorithm(*args, **kwargs)
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/WMCore/JobSplitting/LumiBased.py", line 378, in algorithm
    self.lumiChecker.fixInputFiles()
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/WMCore/JobSplitting/LumiBased.py", line 129, in fixInputFiles
    self.lumiJobs[(run, lumi)].addFile(file_)
AttributeError: 'NoneType' object has no attribute 'addFile'
```

**Comment by PerilousApricot** [comment]
What is sending None down to self.splitLumiFiles? https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/LumiBased.py#L127

That dict is populated with:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/LumiBased.py#L289

but I don't see how f can be none since that block is in a loop iterating over f['runs']

**Comment by juztas** [comment]
good catch @PerilousApricot . I have identified where the issue is and this is CRAB3 problem. False alarm ;) Will create CRAB3 ticket

**Comment by PerilousApricot** [comment]
:v:

**Comment by PerilousApricot** [comment]
dmwm/CRABServer#4747
