### ISSUE TITLE
WQ trying to abort workflows in aborted-archived

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5809]
Hi Seangchan,

I can see LOTS of error messages in the central WQ logs (both for testbed and production) where it tries to move 'aborted-archived' workflows to 'aborted'. Here is the traceback

```
2015-04-19 02:05:09,362 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb-testbed.cern.ch/-7235943892105166720_PUT_request does not exist and the service at https://cmsweb-testbed.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 403 because Forbidden
 with result: {"exception": 403, "message": "Failed to change status: Cannot change status from aborted-archived to aborted.  Allowed values are []", "type": "HTTPError"}

2015-04-19 02:05:09,362 ERROR    WorkQueueReqMgrInterface: Error talking to ReqMgr about request "amaltaro_ReDigi_cmsRun3_Agent105_CDB16_forceComplete_150416_123020_8567": Traceback (most recent call last):
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 177, in report
    self.reportElement(ele)
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 289, in reportElement
    self.reportRequestStatus(element['RequestName'], element['Status'])
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 245, in reportRequestStatus
    self.reqMgr.reportRequestStatus(request, self._workQueueToReqMgrStatus(status))
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/Services/RequestManager/RequestManager.py", line 141, in reportRequestStatus
    return self._getResult(callname, args = args, verb = "PUT")
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/Services/RequestManager/RequestManager.py", line 56, in _getResult
    verb = verb, contentType = contentType)
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/Services/Service.py", line 212, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/beHG1504d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.5.pre9/lib/python2.6/site-packages/WMCore/Services/Service.py", line 319, in getData
    raise he
HTTPException
```

The reason seems to be coming from the fact that these workflows still have elements in the workqueue_inbox (and the spec file doc) and then it goes through the report() method for WQ.

I made a possible fix here https://github.com/amaltaro/WMCore/commit/74140efa27a7173317807022bb0ab28b7549c220 , but it's not tested yet. I'm not sure that would fix the problem, what do you think?

**Comment by amaltaro** [comment]
Actually, I noticed it can be simplified by: https://github.com/amaltaro/WMCore/commit/a4c71ea69de769f89b3abecef9edef208a3b3425
We basically have to skip reportElement() and append this element to uptodate_elements, which will then do the job here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L64

**Comment by ticoann** [comment]
Thanks Alan, I think your patch would work. I was just wondering how it happens in (trying to abort request when request is already archived.) Since we can always clean up manually, I will hold on to your patch a while.

**Comment by amaltaro** [comment]
Being verbose :-) I think the reason is the following, the workflow given in the error message above still has a document in the workqueue_inbox with "Status":"Canceled":
https://cmsweb-testbed.cern.ch/couchdb/workqueue_inbox/_design/WorkQueue/_rewrite/element/amaltaro_ReDigi_cmsRun3_Agent105_CDB16_forceComplete_150416_123020_8567

Since the request status is "aborted-archived", it will fall into this line (which returns [])
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L190

then here it maps to "aborted"
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L255

The REAL reason is that the cleanup is not cleaning up ALL docs :-) With this patch it would call again (and hopefully it would clean up all couch docs)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L66 

Cleaning it manually is too risky IMO (and we get new requests in this situation in a daily basis, basically)

**Comment by ticoann** [comment]
Thanks Alan, I wasn't saying we should manually clean up. :smile:  I was just saying since we have the other means to do this, it is not critical to fix to add now. I was just want to know how this happen first. 

Cancelled request periodically  cleaned up by this call.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L826

It seemed it is Cancelled but not be able to clean up, right?
https://cmsweb-testbed.cern.ch/couchdb/workqueue_inbox/_design/WorkQueue/_rewrite/element/amaltaro_ReDigi_cmsRun3_Agent105_CDB16_forceComplete_150416_123020_8567

**Comment by amaltaro** [comment]
@ticoann certainly a good bug to be closed by the next upgrade

**Comment by amaltaro** [comment]
Should be fixed now. But still it tries to abort workflows in 'aborted-completed' now, since this aborted-completed is a transient state, this issue happens only for a couple of global WQ cycles. Nothing urgent, we can fix it for the next cycle.

Just in case, here is the traceback
```
2015-06-03 14:45:03,619 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb-testbed.cern.ch/2203756717081705903_PUT_request does not exist and the service 
at https://cmsweb-testbed.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 403 because Forbidden
 with result: {"exception": 403, "message": "Failed to change status: Cannot change status from aborted-completed to aborted.  Allowed values are ['aborted-archived']", "type": "HTTPError"}

2015-06-03 14:45:04,410 ERROR    WorkQueueReqMgrInterface: Error talking to ReqMgr about request "amaltaro_MonteCarlo_Ext_HG1506d_Validation_ChangeState_150603_130558_4845": Traceback (most recent call la
st):
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 190, in report
    self.reportElement(ele)
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 303, in reportElement
    self.reportRequestStatus(element['RequestName'], element['Status'])
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 258, in reportRequestStatus
    self.reqMgr.reportRequestStatus(request, self._workQueueToReqMgrStatus(status))
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/Services/RequestManager/RequestManager.py", line 141, in reportRequestStatus
    return self._getResult(callname, args = args, verb = "PUT")
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/Services/RequestManager/RequestManager.py", line 56, in _getResult
    verb = verb, contentType = contentType)
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/Services/Service.py", line 212, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/beHG1506d/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.7.pre10/lib/python2.6/site-packages/WMCore/Services/Service.py", line 319, in getData
    raise he
HTTPException
```

**Comment by amaltaro** [comment]
Just saw this transient issue again in testbed HG1509h, pasting the traceback here so we have fresh logs :) I'll take care of it in the next week, hopefully
```
015-08-26 21:05:01,947 INFO     WorkQueueReqMgrInterface: Checking Request Manager for open requests and closing old ones
2015-08-26 21:05:13,273 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb-testbed.cern.ch/5454720924062130026_PUT_request does not exist and the service at https://cmsweb-testbed.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 403 because Forbidden
 with result: {"exception": 403, "message": "Failed to change status: Cannot change status from aborted-completed to aborted.  Allowed values are ['aborted-archived']", "type": "HTTPError"}

2015-08-26 21:05:13,800 ERROR    WorkQueueReqMgrInterface: Error talking to ReqMgr about request "amaltaro_MonteCarlo_Ext_HG1509h_Validation_v1_150826_201811_5359": Traceback (most recent call last):
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 185, in report
    self.reportElement(ele)
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 303, in reportElement
    self.reportRequestStatus(element['RequestName'], element['Status'])
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 261, in reportRequestStatus
    self.reqMgr2.updateRequestStatus(request, reqmgrStatus)
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/Services/ReqMgr/ReqMgr.py", line 160, in updateRequestStatus
    return self["requests"].put('request', status)[0]['result']
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 125, in put
    encode, decode, contentType)
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 145, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/beHG1509h/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre8/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 275, in makeRequest_httplib
    raise e
HTTPException
```

**Comment by amaltaro** [comment]
@ticoann this is a good candidate to get fixed by Wednesday

**Comment by ticoann** [comment]
I will take care of this, Alan. Thanks,

**Comment by ticoann** [comment]
@amaltaro, Alan, Is this still a problem. It should be fixed with reqmgr2/reqmgr compatibility issue.

**Comment by amaltaro** [comment]
I don't think it;s related to reqmgr? compatibility, but instead to state of workqueue elements.
It seems to still be there, I found this entry from Oct 29 (testbed)
```
2015-10-29 11:26:11,287 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb.cern.ch/-4588980864849362209_PUT_request does not exist and the service at http
s://cmsweb.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 403 because Forbidden
 with result: {"exception": 403, "message": "Failed to change status: Cannot change status from aborted-archived to aborted.  Allowed values are []", "type": "HTTPError"}

2015-10-29 11:26:11,488 ERROR    WorkQueueReqMgrInterface: Error talking to ReqMgr about request "pdmvserv_EXO-RunIISpring15DR74-03378_00438_v0__151006_070321_2345": Traceback (most recent call last):
  File "/data/srv/beHG1510f/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.10.pre6/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 191, in report
    self.reportElement(ele)
  File "/data/srv/beHG1510f/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.10.pre6/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 319, in reportElement
    self.reportRequestStatus(element['RequestName'], element['Status'])
  File "/data/srv/beHG1510f/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.10.pre6/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 273, in reportRequestStatus
    raise ex
HTTPException
```

**Comment by ticoann** [comment]
You are right, I will get this one right this time.

**Comment by ticoann** [comment]
This might be fixed with the new updated state transition. We will monitor whether this happens again.

**Comment by ticoann** [comment]
I don't see any errors any more, but it might be due to they didn't abort  the workflow.
@amaltaro, Alan do you want to leave this open for a while?

**Comment by amaltaro** [comment]
No, it's fixed LoL
We can reopen if it shows up again ;)
