### ISSUE TITLE
pycurl call gives following error

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5846]
#5846 need to applied to test

Traceback (most recent call last):
  File "/Users/sryu/WorkArea2/WMCore/test/python/WMCore_t/Services_t/ReqMgr_t/ReqMgr_t.py", line 62, in setUp
    RESTBaseUnitTestWithDBBackend.setUp(self)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMQuality/REST/RESTBaseUnitTestWithDBBackend.py", line 53, in setUp
    self.testInit.setupCouch(dbName, couchApp)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMQuality/TestInitCouchApp.py", line 98, in setupCouch
    self.couch.create(dropExistingDb=self.dropExistingDb)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMQuality/TestInitCouchApp.py", line 49, in create
    self.couchServer.createDatabase(self.dbName)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Database/CMSCouch.py", line 876, in createDatabase
    self.put("/%s" % urllib.quote_plus(dbname))
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Services/Requests.py", line 130, in put
    encode, decode, contentType)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Database/CMSCouch.py", line 113, in makeRequest
    encode, decode,contentType)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Services/Requests.py", line 147, in makeRequest
    encoder, decoder, contentType)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Services/Requests.py", line 172, in makeRequest_pycurl
    verb=verb, ckey=ckey, cert=cert, capath=capath, decode=decoder)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 149, in request
    ckey, cert, capath, verbose, verb, doseq, cainfo)
  File "/Users/sryu/WorkArea2/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 91, in set_opts
    curl.setopt(pycurl.POSTFIELDS, params)
TypeError: invalid arguments to setopt

**Comment by vkuznet** [comment]
Seangchan, I don't get this error. But I also found that in order to run this test I was need to ```cp test/data/ReqMgr/requests/DMWM/ReReco.json test/data/ReqMgr/requests/``` file and then adjust ```test/python/WMCore_t/Services_t/ReqMgr_t/ReqMgr_t.py``` at line 100 (test fails with RequestPriority value which I changed from 1000 to 10000, but I think it is due to ReReco.json which had 10000 value. So, please post your version of pycurl and environment you run this test.

**Comment by ticoann** [comment]
Sorry Valentin, unittest is fixed now.  (But pycurl error still 
https://github.com/dmwm/WMCore/pull/5850
I am using pycurl-7.19.0. It seems production is pycurl-7.19.3. I will update and run again.

**Comment by vkuznet** [comment]
Seangchan, I updated my tree and now I can run unit test without tweaking. So here is my output (everything is fine):
```
Ran 1 test in 13.117s

OK
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cherrypy/process/wspbus.py:206: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STOPPED state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.
  "main thread exits." % self.state, RuntimeWarning)
INFO:cherrypy.error:[30/Apr/2015:11:34:25] ENGINE Bus STOPPING
INFO:cherrypy.error:[30/Apr/2015:11:34:25] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 9988)) already shut down
INFO:cherrypy.error:[30/Apr/2015:11:34:25] ENGINE No thread running for None.
INFO:cherrypy.error:[30/Apr/2015:11:34:25] ENGINE Bus STOPPED
INFO:cherrypy.error:[30/Apr/2015:11:34:25] ENGINE Bus EXITING
INFO:cherrypy.error:[30/Apr/2015:11:34:25] ENGINE Bus EXITED
vkair(11:34:25) WMCore git:master> python
Python 2.7.9 (default, Dec 13 2014, 15:13:49)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'libcurl/7.42.0 OpenSSL/1.0.2a zlib/1.2.5 libidn/1.29'
>>>
```

**Comment by ticoann** [comment]
Hi Valentin, after I upgrade to pycurl-7.19.3. The unittest ran fine. I am not sure why it failed to connect in production Agent. I am closing the issues and I will test in agent environment. Sorry for the false alarm.
