### ISSUE TITLE
Review AlertProcessor component

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5857]
We just got a message from CERN IT complaining that one of our agents (vocms055 - testbed) were sending too many mails to wmagentalerts@gmail.com, which slows down delivery of messages to gmail and impacts people at CERN.

Looking at the component log, it seems it retries this operation each 5 secs.

For now I have commented out a few lines in the config.py (fromAddr, smtpServer and toAddr). That should stop it.

Then we investigate how to improve it in the near future.

[1]
2015-05-04 06:38:04,487:WARNING:EmailSink:Server disconnected, reconnecting ...
2015-05-04 06:38:09,491:ERROR:Processor:Sending alerts failed (soft) on Connection unexpectedly closed, reason: EmailSink
Traceback (most recent call last):

   File "/data/srv/wmagent/v1.0.5.patch1/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.5.patch1/lib/python2.6/site-packages/WMCore/Alerts/ZMQ/Processor.py", line 88, in handleSoft
    target.send(alertBuffer)

   File "/data/srv/wmagent/v1.0.5.patch1/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.5.patch1/lib/python2.6/site-packages/WMCore/Alerts/ZMQ/Sinks/EmailSink.py", line 50, in send
    self.smtp.sendmail(self.fromAddr, self.toAddr, msg)

   File "/data/srv/wmagent/v1.0.5.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/smtplib.py", line 697, in sendmail
    self.rset()

   File "/data/srv/wmagent/v1.0.5.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/smtplib.py", line 438, in rset
    return self.docmd("rset")

   File "/data/srv/wmagent/v1.0.5.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/smtplib.py", line 363, in docmd
    return self.getreply()

   File "/data/srv/wmagent/v1.0.5.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/smtplib.py", line 340, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")

 SMTPServerDisconnected: Connection unexpectedly closed

2015-05-04 06:38:09,607:WARNING:EmailSink:Server disconnected, reconnecting ...

**Comment by amaltaro** [comment]
BTW, who owns this account wmagentalerts@gmail.com?

**Comment by ticoann** [comment]
Probabley Zdenek
