### ISSUE TITLE
Investigate the silent outage of ReqMgr

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5975]
We've seen ReqMgr silently (no logs AT ALL) dying in private VMs and cmsweb-testbed for the last 2 or 3 months. It never hit the cmsweb production cluster before today, when we had the service down in 2 different backends.

We should hunt this issue down for the next cmsweb cycle (and it's going to be very hard :-D)

**Comment by amaltaro** [comment]
Just got back this traceback for this reqmgr crash (from my VM running 1.0.8.pre2)
```
INFO:cherrypy.access:[23/Jun/2015:15:07:38] alan-cloud1.cern.ch 127.0.0.1 "GET /reqmgr/ HTTP/1.1" 200 OK [data: - in 1631 out 438 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
ERROR:cherrypy.error:Create request failed, reason: Traceback (most recent call last):
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrRESTModel.py", line 480, in putRequest
    self.workloadDBName, self.wmstatWriteURL)
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrWebTools.py", line 468, in makeRequest
    request = buildWorkloadAndCheckIn(webApi, reqSchema, couchUrl, couchDB, wmstatUrl)
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrWebTools.py", line 367, in buildWorkloadAndCheckIn
    schema = reqSchema)
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/RequestManager/RequestMaker/Registry.py", line 81, in buildWorkloadForRequest
    globals(), locals(), [factoryName])
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/WMSpec/StdSpecs/ReDigi.py", line 10, in <module>
    from WMCore.WMSpec.StdSpecs.DataProcessing import DataProcessing
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/WMSpec/StdSpecs/DataProcessing.py", line 9, in <module>
    from WMCore.WMSpec.StdSpecs.StdBase import StdBase
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 12, in <module>
    from WMCore.Services.Dashboard.DashboardReporter import DashboardReporter
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/Services/Dashboard/DashboardReporter.py", line 13, in <module>
    from WMCore.Services.Dashboard.DashboardAPI import apmonSend, apmonFree
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/Services/Dashboard/DashboardAPI.py", line 7, in <module>
    from WMCore.Services.Dashboard import apmon
  File "/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/Services/Dashboard/apmon.py", line 48, in <module>
    import xdrlib
EOFError: EOF read where object expected

/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrRESTModel.py:491: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  if hasattr(ex, "message"):
/data/srv/HG1507a/sw.pre.sryu/slc6_amd64_gcc481/cms/reqmgr/1.0.8.pre2/lib/python2.6/site-packages/WMCore/HTTPFrontEnd/RequestManager/ReqMgrRESTModel.py:492: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  if hasattr(ex.message, '__call__'):
INFO:cherrypy.access:[23/Jun/2015:15:08:00] alan-cloud1.cern.ch 128.142.143.162 "PUT /reqmgr/reqMgr/request HTTP/1.1" 400 Bad Request [data: - in 107 out 10573 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues" "" ] [ref: "" "" ]
ERROR:root:Missing componentDir and General section in config
ERROR:root:Going to trust you to know what you're doing.
CherryPy Checker:
The Application mounted at '/reqmgr/closeout' has an empty config.
```

**Comment by amaltaro** [comment]
And it's a segmentation fault, here is the strace I just got (1.0.8.pre5 now)
```
amaltaro@alan-cloud1:/data/srv/current $ sudo strace -p 8606
Process 8606 attached - interrupt to quit
select(0, NULL, NULL, NULL, {0, 34326}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 100000}) = 0 (Timeout)
...
select(0, NULL, NULL, NULL, {0, 100000}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 100000} <unfinished ...>
+++ killed by SIGSEGV (core dumped) +++
```

**Comment by ticoann** [comment]
We are not going to do this instead move reqmgr2 as soon as possible.
