### ISSUE TITLE
Can we drop DBS2 client from the RPMs?

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#6182]
When trying to replicate a unit test, I get this: 

```
-bash-4.1$ nosetests Dataset_t.py:DatasetTestCase.testDataDirectiveFromQueue
E
======================================================================
ERROR: Test data directive from queue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/storage/local/data1/ewv/wmcore_unittest/WMCore/test/python/WMCore_t/WorkQueue_t/Policy_t/Start_t/Dataset_t.py", line 158, in testDataDirectiveFromQueue
    dbs = {inputDataset.dbsurl : MockDBSReader(inputDataset.dbsurl)}
  File "/storage/local/data1/ewv/unittestdeploy/wmagent/1.0.8.pre7/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.8.pre7/lib/python2.6/site-packages/WMQuality/Emulators/DBSClient/DBSReader.py", line 34, in __init__
    self.dbs = _MockDBSApi(args)
  File "/storage/local/data1/ewv/unittestdeploy/wmagent/1.0.8.pre7/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.8.pre7/lib/python2.6/site-packages/WMQuality/Emulators/DBSClient/DBSReader.py", line 12, in __init__
    DbsApi(args)
  File "/storage/local/data1/ewv/unittestdeploy/wmagent/1.0.8.pre7/sw.pre/slc6_amd64_gcc481/cms/dbs-client/DBS_2_1_9-comp8/lib/DBSAPI/dbsApi.py", line 82, in __init__
    self._server = DbsHttpService(self.url(), self.version(), Args)
  File "/storage/local/data1/ewv/unittestdeploy/wmagent/1.0.8.pre7/sw.pre/slc6_amd64_gcc481/cms/dbs-client/DBS_2_1_9-comp8/lib/DBSAPI/dbsHttpService.py", line 119, in __init__
    raise DbsConnectionError(args="Could not locate the host " + self.Host, code=400)
DbsConnectionError: Could not locate the host cmsdbsprod.cern.ch
```

Jenkins fails differently, of course, since it runs the DBS2 emulator, but I don't see any reason we continue to depend on the DBS2 client API

**Comment by amaltaro** [comment]
See #5856 I'm planning to remove this dependency for quite some time too :-(

**Comment by ticoann** [comment]
I think we removed most of the dependencies (Except the unittest). But Of course, I think we need to run the test first. After new WMAgent deployment next week. I will removed all DBS2 code and remove dependency from all the rpms. (wq, wmagent, etc)

**Comment by ericvaandering** [comment]
So it turns out we don't actually call that API anymore, at least in the test I was running. I had some old version of the code I was running.

Removing the RPM dependency shouldn't change much. At most it would change the form of the error since there is no DBS to talk to anymore.

Removing all the DBS code may be more risky. May be interesting to see what happens, though. :-)

**Comment by alexanderrichards** [comment]
as mentioned in #5856 Is the following sufficient, If so the I can submit the PR against the cms-sw repo

https://github.com/alexanderrichards/cmsdist/pull/1/files

**Comment by ticoann** [comment]
Updated for HG1603
https://github.com/cms-sw/cmsdist/pull/2110
