### ISSUE TITLE
WorkQueue eventually failing to change request status

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6262]
Issue was reported in this elog:
https://cms-logbook.cern.ch/elog/Workflow+processing/21645

the problem is that couchdb has one workflow status (completed) while reqmgr oracle db has a different one (this case running-open, but we saw some even in assigned).

And this is the GQ logs where it clearly failed talking to ReqMgr and the same call was not retried later on (nor any rollback operation) [1].

Actually, it seems it was retried again in the next day, see this log+timestamp [2]. Where it failed talking to ReqMgr again, though I don't see any state transition (in couch doc) around that timestamp...

Last but not least, this wf was moved to running-closed in couch at this timestamp
cmst1@vocms0304:/data/srv/wmagent/current $ date -d @1442394515
Wed Sep 16 11:08:35 CEST 2015

if I'm not wrong couch logs use different timezone, but even so the timestamp does not perfectly match the workqueue logs..

to debug. 

[1]
```
2015-09-16 13:25:01,632 INFO     WorkQueueReqMgrInterface: Contacting Request manager for more work
2015-09-16 13:25:03,076 INFO     WorkQueueReqMgrInterface: Checking Request Manager for open requests and closing old ones
2015-09-16 13:25:31,428 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb.cern.ch/15744094587142094_GET_request?name=pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977 does not exist and the service at https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977 is unavailable - it returned 500 because Internal Server Error
 with result: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>Server error</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>


2015-09-16 13:25:31,429 ERROR    WorkQueueReqMgrInterface: Error talking to ReqMgr about request "pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977": Traceback (most recent call last):
  File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre9/lib/python2.6/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 157, in report
    request = self.reqMgr2.getRequestByNames(ele['RequestName'])[ele['RequestName']]
  File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/ReqMgr/ReqMgr.py", line 101, in getRequestByNames
    return self._getResult(callname, verb = "GET")
  File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/ReqMgr/ReqMgr.py", line 46, in _getResult
    verb = verb, contentType = contentType)
  File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Service.py", line 212, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/workqueue/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Service.py", line 319, in getData
    raise he
HTTPException

2015-09-16 13:25:32,387 INFO     WorkQueue: Canceling work for workflow(s): set(['jbadillo_task_SMP-RunIIWinter15wmLHE-00007__v1_T_150601_113253_5226'])
```

[2]
```
2015-09-17 05:25:09,861 INFO     WorkQueueReqMgrInterface: Checking Request Manager for open requests and closing old ones
... 
and the same error as above
```

**Comment by amaltaro** [comment]
And this is the matching log in ReqMgr2 logs, at the exact moment that the running-closed transition failed:
```
[16/Sep/2015:13:25:31] vocms0136.cern.ch 128.142.209.42 "GET /reqmgr2/data/request?name=pdmvserv_SMP-RunIISummer15GS-00016_00067_v0__150908_001921_8222 HTTP/1.1" 200 OK [data: 3930 in 2740 out 9710 us ] 
[auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0308.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[16/Sep/2015:13:25:31]  SERVER OTHER ERROR __builtins__.TypeError 81dca400fc480811cd165dcd9d4809ff ('member_descriptor' object is not callable)
[16/Sep/2015:13:25:31]    Traceback (most recent call last):
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[16/Sep/2015:13:25:31]        return self._call(RESTArgs(list(args), kwargs))
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/REST/Server.py", line 772, in _call
[16/Sep/2015:13:25:31]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/ReqMgr/Service/Request.py", line 278, in get
[16/Sep/2015:13:25:31]        request_info.append(self.reqmgr_db_service.getRequestByNames(name))
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 150, in getRequestByN
ames
[16/Sep/2015:13:25:31]        data = self._getRequestByNames(requestNames, detail = detail)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 82, in _getRequestByN
ames
[16/Sep/2015:13:25:31]        result = self.couchDB.allDocs(options, requestNames)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 532, in allDocs
[16/Sep/2015:13:25:31]        {'keys':keys})
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 117, in post
[16/Sep/2015:13:25:31]        encode, decode, contentType)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 113, in makeRequest
[16/Sep/2015:13:25:31]        encode, decode,contentType)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 145, in makeRequest
[16/Sep/2015:13:25:31]        encoder, decoder, contentType)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/reqmgr2/1.0.9.pre9/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 246, in makeRequest_httplib
[16/Sep/2015:13:25:31]        body = encoded_data, headers = headers)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/py2-httplib2/0.7.1-comp9/lib/python2.6/site-packages/httplib2/__init__.py", line 1436, in request
[16/Sep/2015:13:25:31]        (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/py2-httplib2/0.7.1-comp9/lib/python2.6/site-packages/httplib2/__init__.py", line 1188, in _request
[16/Sep/2015:13:25:31]        (response, content) = self._conn_request(conn, request_uri, method, body, headers)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/py2-httplib2/0.7.1-comp9/lib/python2.6/site-packages/httplib2/__init__.py", line 1171, in _conn_request
[16/Sep/2015:13:25:31]        content = response.read()
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 522, in read
[16/Sep/2015:13:25:31]        return self._read_chunked(amt)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 555, in _read_chunked
[16/Sep/2015:13:25:31]        line = self.fp.readline()
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/socket.py", line 427, in readline
[16/Sep/2015:13:25:31]        data = recv(1)
[16/Sep/2015:13:25:31]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/ssl.py", line 224, in recv
[16/Sep/2015:13:25:31]        return socket.recv(self, buflen, flags)
[16/Sep/2015:13:25:31]    TypeError: 'member_descriptor' object is not callable
[16/Sep/2015:13:25:31] vocms0136.cern.ch 188.184.64.223 "GET /reqmgr2/data/request?name=pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977 HTTP/1.1" 500 Internal Server Error [data: 3893 in 723 out 31922 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
```

**Comment by amaltaro** [comment]
Finally (I hope :D), reqmgr logs also complaining to fetch this workflow spec file from time to time
```
 [data: - in 112710 out 924315 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mohapatr/CN=659205/CN=Ajit Kumar Mohapatra" "" ] [ref: "" "" ]
ERROR:root:Could not check workload for pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977, reason: (404, 'Cannot find workload https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977/spec')
INFO:cherrypy.access:[16/Sep/2015:08:23:41] vocms0163.cern.ch 188.184.135.24 "GET /reqmgr/view/showWorkload?requestName=pdmvserv_EXO-RunIISpring15DR74-01822_00364_v0__150915_143313_2977 HTTP/1.1" 404 Not Found [data: - in 831 out 1125112 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=pdmvserv/cmsdev04.cern.ch" "" ] [ref: "" "" ]
```

**Comment by amaltaro** [comment]
It seems this issue got fixed with your PR, Seangchan. Closing.
