### ISSUE TITLE
Missing siteDB attribute in DBS3Reader

### ISSUE THREAD

**Issue by mmascher** [dmwm/WMCore#6466]
I got this when validating the WMCore master branch with CRAB3:

```
Traceback (most recent call last):
  File "/afs/cern.ch/user/m/mmascher/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 105, in execute
    locationsMap = self.dbs.listFileBlockLocation(list(blocks), dbsOnly=True)
  File "/afs/cern.ch/user/m/mmascher/repos/WMCore/src/python/WMCore/Services/DBS/DBS3Reader.py", line 586, in listFileBlockLocation
    blockInfo[0]['origin_site_name'] = self.siteDB.checkAndConvertSENameToPNN(blockInfo[0]['origin_site_name'])
AttributeError: DBS3Reader instance has no attribute 'siteDB'
```

pull request coming soon

**Comment by amaltaro** [comment]
Fixed by #6515
