### ISSUE TITLE
gcc481 and python2.7 ?

### ISSUE THREAD

**Issue by juztas** [dmwm/WMCore#6506]
In production, there are a lot of scram failures, but seems to be not site specific issue. Checking errors on wmstats, it shows gcc481 and python2.7.6. Was python2.7.6 ever built for gcc481? 
```
 Adding last ten lines of SCRAM error log:
Log for recording SCRAM command-line output
-------------------------------------------
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_14347/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 20, in 
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_14347/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 23, in 
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_14347/job/WMCore.zip/WMCore/WMRuntime/TaskSpace.py", line 16, in 
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_14347/job/WMCore.zip/WMCore/WMSpec/WMWorkload.py", line 11, in 
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_14347/job/WMCore.zip/WMCore/WMSpec/Persistency.py", line 16, in 
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/urllib2.py", line 94, in 
    import httplib
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/httplib.py", line 79, in 
    import mimetools
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/mimetools.py", line 6, in 
    import tempfile
ImportError: No module named tempfile
```

**Comment by ericvaandering** [comment]
I don’t believe so. We should be using 493 and 2.7

Eric

**Comment by hufnagel** [comment]
Hm, could this be a python version that is pulled in via a CMSSW dependency ? Do you have more of the log ? What was it trying to do here ?

**Comment by juztas** [comment]
This task in prod: pdmvserv_EGM-RunIISummer15GS-00010_00200_v0__160111_201702_1997
and check 60515 exit code. 
```
INFO:root:create(/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMTaskSpace/cmsRun1)
INFO:root:create(/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMTaskSpace/stageOut1)
INFO:root:create(/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMTaskSpace/logArch1)
INFO:root:In Watchdog.setupMonitors
INFO:root:Set Watchdog interval to 300
INFO:root:Initializing monitor DashboardMonitor
INFO:root:In DashboardMonitor.initMonitor
INFO:root:About to set destination to cms-wmagent-job.cern.ch:8884
INFO:root:Initializing monitor PerformanceMonitor
INFO:root:MonitorThread: JobStarted
INFO:root:About to send UDP package to dashboard: {'StatusDestination': 'T2_US_Caltech', 'StatusEnterTime': '2016-01-13 21:08:49', 'MessageType': 'JobStatus', 'jobId': '0d664b54-ba0a-11e5-ba77-001e67abf518-119_0', 'StatusValue': 'running
', 'MessageTS': '2016-01-13 21:08:49', 'StatusValueReason': 'Job started execution in the WN', 'taskId': u'wmagent_pdmvserv_EGM-RunIISummer15GS-00010_00200_v0__160111_201702_1997', 'NCores': 1}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:About to send UDP package to dashboard: {'SyncCE': 'T2_US_Caltech', 'MessageType': 'jobRuntime-jobStart', 'jobId': '0d664b54-ba0a-11e5-ba77-001e67abf518-119_0', 'MessageTS': '2016-01-13 21:08:49', 'taskId': u'wmagent_pdmvserv_EGM-RunIISummer15GS-00010_00200_v0__160111_201702_1997', 'GridName': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues/CN=16766342/CN=1608177312/CN=539771399/CN=1077960285/CN=1668555357\n', 'WNHostName': 'compute-7-11.tier2', 'ExeStart': 'cmsRun1'}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:About to send UDP package to dashboard: {'1_stepName': 'cmsRun1', 'MessageType': 'jobRuntime-stepStart', 'jobId': '0d664b54-ba0a-11e5-ba77-001e67abf518-119_0', 'MessageTS': '2016-01-13 21:08:49', 'taskId': u'wmagent_pdmvserv_EGM-RunIISummer15GS-00010_00200_v0__160111_201702_1997', '1_ExeStart': 'cmsRun1'}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:Pre-executing CMSSW step
INFO:root:User files are 
INFO:root:User sandboxes are 
INFO:root:CMSSW configured for 1 cores
INFO:root:Executing CMSSW step
INFO:root:Runing SCRAM
INFO:root:Running PRE scripts
INFO:root:RUNNING SCRAM SCRIPTS
INFO:root:    Invoking command: /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_20/external/slc6_amd64_gcc481/bin/python2.7 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 
CRITICAL:root:Error running command
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc481/external/python/2.6.8-comp9/bin/python2.6 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 

5
 
        Scram Command Diagnostic:
        Command : scramv1
        Architecture: slc6_amd64_gcc481
        Executed: /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_20/external/slc6_amd64_gcc481/bin/python2.7 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 

        Exit Status: 5
        Stdout: None
        Stderr: None 
INFO:root:Steps.Executors.CMSSW.post called
INFO:root:Post Executor Task Change: logArch1
ERROR:root:'1_ExeWCTime'
ERROR:root:Traceback (most recent call last):
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMCore.zip/WMCore/WMRuntime/Monitors/DashboardMonitor.py", line 140, in stepEnd
    stepReport = stepReport)
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMCore.zip/WMCore/WMRuntime/DashboardInterface.py", line 339, in stepEnd
    self.WrapperWCTime += data['%d_ExeWCTime' % self.stepCount]
KeyError: '1_ExeWCTime'

ERROR:root:Encountered error while running ExecuteMaster:
No module named shutil
Traceback (most recent call last):
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 71, in __call__
    executor = StepFactory.getStepExecutor(stepType)
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMCore.zip/WMCore/WMSpec/Steps/StepFactory.py", line 158, in getStepExecutor
    executor =_ExecutorFactory.loadObject(stepType)
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMCore.zip/WMCore/WMFactory.py", line 68, in loadObject
    module = __import__(module, globals(), locals(), [classname])
  File "/wntmp/condor/execute/dir_44811/glide_CxPFyZ/execute/dir_28677/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/LogArchive.py", line 12, in <module>
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/tarfile.py", line 47, in <module>
    import shutil
ImportError: No module named shutil


INFO:root:MonitorThread: JobEnded
INFO:root:About to send UDP package to dashboard: {'JobExitReason': 'Step cmsRun1 failed in the WN', 'ExeEnd': None, 'WrapperCPUTime': 0, 'MessageType': 'jobRuntime-jobEnd', 'jobId': '0d664b54-ba0a-11e5-ba77-001e67abf518-119_0', 'WrapperWCTime': 0, 'MessageTS': '2016-01-13 21:08:50', 'JobExitCode': 60515, 'taskId': u'wmagent_pdmvserv_EGM-RunIISummer15GS-00010_00200_v0__160111_201702_1997', 'NCores': 1}
INFO:root:Using address ['cms-wmagent-job.cern.ch:8884']
INFO:root:MonitorState: Shutdown called
INFO:root:MonitorState: Shutdown called
```

**Comment by juztas** [comment]
if not wrong, problem is here: https://github.com/dmwm/WMCore/blob/6f3570a741779d209f0f720647642d51b64845da/src/python/WMCore/WMRuntime/Tools/Scram.py#L282

**Comment by hufnagel** [comment]
That's not a problem, that's intentional. CMSSW config manipulation code in the WMCore runtime runs with the CMSSW python (has to as it won't work otherwise).

**Comment by hufnagel** [comment]
Looks like that python version broken, which is a CMSSW or cvmfs problem I would say.

**Comment by hufnagel** [comment]
Also, do all jobs for this request fail or do you only see failures at certain sites ?

**Comment by juztas** [comment]
It fails at multiple sites, but not all jobs are failing. Also seems it fails to load diff libraries.
```
Production	jobcooloff	T2_DE_DESY	60515	75	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T1_US_FNAL	60515	70	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_Purdue	60515	48	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_MIT	60515	45	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T1_IT_CNAF	60515	38	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_PL_Swierk	60515	33	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_Caltech	60515	32	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_CH_CERN	60515	30	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_Wisconsin	60515	30	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T1_FR_CCIN2P3	60515	26	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_CH_CERN	60515	23	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T1_DE_KIT	60515	20	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T1_US_FNAL	60515	19	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_Nebraska	60515	19	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_UK_London_IC	60515	18	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_ES_CIEMAT	60515	17	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_FR_GRIF_LLR	60515	16	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_ES_IFCA	60515	14	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_PK_NCP	60515	14	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_MIT	60515	14	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_UCSD	60515	14	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_Wisconsin	60515	14	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_US_Nebraska	60515	13	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T1_UK_RAL	60515	11	ReportManipulatingError,SCRAMScriptFailure	
Production	jobcooloff	T2_PK_NCP	60515	11	ReportManipulatingError,SCRAMScriptFailure
```

**Comment by hufnagel** [comment]
Weird. If it was a general problem with the CMSSW provided python I would expect all jobs to fail (all jobs using that same CMSSW release actually). Maybe worth checking with cvmfs experts if there is a problem distributing these areas, really looks like it randomly fails to load various pieces of code.

**Comment by amaltaro** [comment]
I believe it was an environment problem, since we didn't hear anymore about problems like this (and production has no issues like this). Shall we close this issue?

**Comment by juztas** [comment]
Close. It will be easy to see if this will pop-up
