### ISSUE TITLE
WmAgentScripts/assignProdTaskChain.py

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#6623]
Assignment via script for taskchain failed with the following
Only change to checked out script is:
jen_a@vocms049:~/WmAgentScripts_testbed $ diff assignProdTaskChain.py assignProdTaskChain.py~
166,167c166
< #    url = 'cmsweb.cern.ch'
<     url = 'cmsweb-testbed.cern.ch' 
---
>     url = 'cmsweb.cern.ch'

jen_a@vocms049:~/WmAgentScripts_testbed $ python assignProdTaskChain.py -w sryu_TaskChain_Task_Multicore_reqmgr2_test_160223_223034_4279
Traceback (most recent call last):
  File "assignProdTaskChain.py", line 317, in <module>
    main()
  File "assignProdTaskChain.py", line 270, in main
    datasets = schema["OutputDatasets"]
KeyError: 'OutputDatasets'

**Comment by ticoann** [comment]
@jenimal, Jen, could you run this test again with updated patch.
https://github.com/CMSCompOps/WmAgentScripts/pull/129
I am getting some DBS permission error. I just want to check whether you are getting a same error.

```
/SMS-T2-4bd_mStop-250_mLSP-170to240_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/FAKE-MCRUN2_71_V1-v1/LHE
Traceback (most recent call last):
  File "rejectAndClone.py", line 82, in <module>
    main()
  File "rejectAndClone.py", line 75, in main
    dbs3.setDatasetStatus(ds, 'INVALID', files=True)
  File "/afs/cern.ch/user/s/sryu/WmAgentScripts/dbs3Client.py", line 162, in setDatasetStatus
    dbsapi.updateDatasetType(dataset=dataset, dataset_access_type=newStatus)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 1358, in updateDatasetType
    return self.__callServer("datasets", params=kwargs, callmethod='PUT')
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 193, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 403: You are not allowed to access this resource
```

**Comment by amaltaro** [comment]
@jenimal @vlimant should we close this issue now?
