### ISSUE TITLE
WmAgentScripts/changePriorityWorkflow

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#6704]
Testing changePriorityWorkflow.py (Failed)
Command:
`python changePriorityWorkflow.py jen_a_MonteCarloFromGEN_Jen_reqmgr2_160225_214203_7410 70000`
Result:
```
Traceback (most recent call last):
  File "changePriorityWorkflow.py", line 41, in <module>
    main()
  File "changePriorityWorkflow.py", line 37, in main
    changePriorityWorkflow(url, wf, priority)
  File "changePriorityWorkflow.py", line 12, in changePriorityWorkflow
    if reqMgrClient.isRequestMgr2Request(url, workflow):
  File "/afs/cern.ch/user/p/prozober/WmAgentScripts_testbed/reqMgrClient.py", line 534, in isRequestMgr2Request
    result = getWorkflowInfo(url, workflow)
  File "/afs/cern.ch/user/p/prozober/WmAgentScripts_testbed/reqMgrClient.py", line 530, in getWorkflowInfo
    request = requestManagerGet(url,'/reqmgr2/data/request?name='+workflow)
  File "/afs/cern.ch/user/p/prozober/WmAgentScripts_testbed/reqMgrClient.py", line 339, in requestManagerGet
    r1=conn.request("GET",request, headers=headers)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/httplib.py", line 1112, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/data/srv/wmagent/v1.0.8.patch1/sw.pre/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/socket.py", line 547, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by ticoann** [comment]
Hi Paola, could you print out url before following line. Thanks,

File "changePriorityWorkflow.py", line 37, in main
    changePriorityWorkflow(url, wf, priority)

**Comment by prozober** [comment]
Hi Alan, we can close this issue, changePriorityWorkflow.py has no problem now.

**Comment by amaltaro** [comment]
Thanks!
