### ISSUE TITLE
request search intermitently give error 500

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6764]
https://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved&details=true

 is failing very often

**Comment by ticoann** [comment]
@vlimant,  how often this gets call. I will try to repeated call to reproduced the errors. (By just calling few times, I couldn't reproduce the error)
Could you also point the code to calling this api?
https://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved&details=true

FYI. you don't have to add detail=true (that is default option)

**Comment by vlimant** [comment]
the call is valid, no need to see where it's coming from

https://github.com/CMSCompOps/WmAgentScripts/blob/merging_unified_testbed_reqmgr2/utils.py#L2708

if you put this in a loop, you should start seeing it fail from time to time, and some times very often

**Comment by ticoann** [comment]
It seems the problem is due to python memory management. I will push jemalloc in testbed. And run the test. If that doesn't help, we probably use generator as DBS did.

**Comment by ticoann** [comment]
Unfortunately, jemalloc doesn't seems to fix the problem. I am working on the call to use generator and cache.

**Comment by ticoann** [comment]
This is the error getting in the server side.

04/Apr/2016:17:58:29]  SERVER OTHER ERROR socket.error 48456d1e26c430eb8430c95ec68baac2 (Error contacting: cmsweb-testbed.cern.ch)
[04/Apr/2016:17:58:29]    Traceback (most recent call last):
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 701, in default
[04/Apr/2016:17:58:29]        return self._call(RESTArgs(list(args), kwargs))
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 776, in _call
[04/Apr/2016:17:58:29]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 344, in get
[04/Apr/2016:17:58:29]        request_info.append(self.reqmgr_db_service.getRequestByCouchView("bystatus", option, status))
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 192, in getRequestByCouchView
[04/Apr/2016:17:58:29]        data = self._getCouchView(view, options, keys)
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 48, in _getCouchView
[04/Apr/2016:17:58:29]        return self.couchDB.loadView(self.couchapp, view, options, keys)
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 477, in loadView
[04/Apr/2016:17:58:29]        (self.name, design, view, data), {'keys':keys})
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 117, in post
[04/Apr/2016:17:58:29]        encode, decode, contentType)
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 114, in makeRequest
[04/Apr/2016:17:58:29]        encode, decode,contentType)
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 145, in makeRequest
[04/Apr/2016:17:58:29]        encoder, decoder, contentType)
[04/Apr/2016:17:58:29]      File "/data/srv/beHG1604c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.15.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 265, in makeRequest_httplib
[04/Apr/2016:17:58:29]        % self.getDomainName())
[04/Apr/2016:17:58:29]    error: Error contacting: cmsweb-testbed.cern.ch

**Comment by vlimant** [comment]
Hi,
it is becomeing critical to fix this. /reqmgr2/data/request? is just failing way to often and putting Unified under too many fault conditions

**Comment by vlimant** [comment]
any luck with this ? it's impossible to do operation with this failing every other call

**Comment by ticoann** [comment]
It looks like this gotten worse with the IPv6 change. Since it was happening before. I will add some debugging code in testbed and try to find the problem (still IPv6).  It seems Diego reverted this from production cmsweb. Is it better now or the same?

**Comment by vlimant** [comment]
better with Diego's fix.
still this calls fails way too often for stable operation.

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/reqMgrClient.py#L449
 request = requestManagerGet(url, '/couchdb/reqmgr_workload_cache/'+workflow)
is still failing way too often and needs to be fixed asap.
This is a roadblock to announcing efficiently currently available samples.

**Comment by ticoann** [comment]
Hi Jean-Roch, I looked at the errors in cmsweb log.
It seems there are a few different error messages for 500 error.
The first error looks like server returns wrong data (but subsequent same call returns data). 
I dig a little big it could be httplib2 bugs on caching the data. (But not very confident)
The other seems to be the couch server not handling well volumes of request. (I am not sure whether it is actually couch server or our python client problem)
One thing we can try to change is using pycurl instread of httplib2 library and whether that helps.
However, that would take sometime since we are having trouble on reqmgr1 with pycurl patches.

```
[27/May/2016:17:32:31] vocms0136.cern.ch 128.142.209.42 "GET /reqmgr2/data/request?name=pdmvserv_HIG-RunIISummer15wmLHEGS-00117_00030_v0__160511_081917_814 HTTP/1.1" 500 Internal Server Error [data: 3900 in 723 out 5265622 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms0308.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[27/May/2016:17:32:31]  SERVER OTHER ERROR cjson.DecodeError 47768efa7290fdb2f9892837a177b4ee (empty JSON description)
[27/May/2016:17:32:31]    Traceback (most recent call last):
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 701, in default
[27/May/2016:17:32:31]        return self._call(RESTArgs(list(args), kwargs))
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 776, in _call
[27/May/2016:17:32:31]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 365, in get
[27/May/2016:17:32:31]        request_info.append(self.reqmgr_db_service.getRequestByNames(name))
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 149, in getRequestByNames
[27/May/2016:17:32:31]        data = self._getRequestByNames(requestNames, detail = detail)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 82, in _getRequestByNames
[27/May/2016:17:32:31]        result = self.couchDB.allDocs(options, requestNames)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 533, in allDocs
[27/May/2016:17:32:31]        {'keys':keys})
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 118, in post
[27/May/2016:17:32:31]        encode, decode, contentType)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 114, in makeRequest
[27/May/2016:17:32:31]        encode, decode,contentType)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 146, in makeRequest
[27/May/2016:17:32:31]        encoder, decoder, contentType)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 282, in makeRequest_httplib
[27/May/2016:17:32:31]        result = self.decode(result)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 573, in decode
[27/May/2016:17:32:31]        data =  decoder.decode(data)
[27/May/2016:17:32:31]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Wrappers/JsonWrapper/__init__.py", line 93, in decode
[27/May/2016:17:32:31]        return cjson.decode(idict)
[27/May/2016:17:32:31]    DecodeError: empty JSON description
```

```
[27/May/2016:02:02:08]  SERVER OTHER ERROR WMCore.Database.CMSCouch.CouchError 00d51ffcb60f4868009b8f72acc6d03b (CouchError - reason: None, data: {'keys': [u'pdmvserv_HIG-RunIIWinter15pLHE-00113_00165_v0__160517_162325_42']} result: None)
[27/May/2016:02:02:08]    Traceback (most recent call last):
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 701, in default
[27/May/2016:02:02:08]        return self._call(RESTArgs(list(args), kwargs))
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 776, in _call
[27/May/2016:02:02:08]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 365, in get
[27/May/2016:02:02:08]        request_info.append(self.reqmgr_db_service.getRequestByNames(name))
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 149, in getRequestByNames
[27/May/2016:02:02:08]        data = self._getRequestByNames(requestNames, detail = detail)
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/RequestDB/RequestDBReader.py", line 82, in _getRequestByNames
[27/May/2016:02:02:08]        result = self.couchDB.allDocs(options, requestNames)
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 533, in allDocs
[27/May/2016:02:02:08]        {'keys':keys})
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 118, in post
[27/May/2016:02:02:08]        encode, decode, contentType)
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 117, in makeRequest
[27/May/2016:02:02:08]        getattr(e, "reason", None), data)
[27/May/2016:02:02:08]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/reqmgr2/1.0.16.pre3-comp/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 149, in checkForCouchError
[27/May/2016:02:02:08]        raise CouchError(reason, data, result, status)
[27/May/2016:02:02:08]    CouchError: CouchError - reason: None, data: {'keys': [u'pdmvserv_HIG-RunIIWinter15pLHE-00113_00165_v0__160517_162325_42']} result: None
```

**Comment by ticoann** [comment]
Meanwhile, I would suggest some changes in WmAgentScript side so at least it can be operable more efficiently even with the error. 
Basically, instead of sending individual request it can send bulk requests. (10 requests at a time)
But first, I was wondering how you get the list of requests for announcing. Could you explain or point the code?
Sorry for the extra trouble.

**Comment by vlimant** [comment]
In places, it is not relevant to do bullk calls.
In places, it is the bulk call that fails.
What is the syntax for grouping calls ?
/reqmgr2/data/request?name=<name1>&name=<name2>&name=<name3> 

I added a 10000 sleep(1) retry to get through without breaking cycles and catch up with enormeous backlog of things to acquire

**Comment by ticoann** [comment]
I am not saying bulk call will fix the problem. What I am saying was bulk call will take almost the same time as one call. (in case ~10 request at a time).  So if the failure rate is the same it will be more efficient.
It is a get call so I would bulk it together not more than 15. I added sleep between the call but that doesn't seem to help much. 

> What is the syntax for grouping calls ?
> /reqmgr2/data/request?name=&name=&name=

Yes, syntax is correct.

The reason I asked how you get the workflow list is that there might be a API you can use directly.
i.e. https://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved
Which would take longer per each call but you don't have to query that often. 
Dose this bulk fall fails more often than individual call?

**Comment by vlimant** [comment]
pretty sure this is related 

2016-08-03 14:15:45,940:140666797897472:WARNING:Service:The cachefile /data/srv/wmagent/v1.0.17.patch1/install/wmagent/JobUpdater/.wmcore_cache/.wmcore_cache_31961/requests/cmsweb.cern.ch/15744094587142094_GET_request?name=pdmvserv_task_EXO-RunIISpring16DR80-03859__v1_T_160728_083116_6264 does not exist and the service at https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_task_EXO-RunIISpring16DR80-03859__v1_T_160728_083116_6264 is unavailable - it returned 500 because Internal Server Error


agents are not able to sync workflows. Can we have a retry in the agent code and a wmstats alarm counting those ?
