### ISSUE TITLE
Agent status when DB is down

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7180]
When DB goes down in the agent, is there a mechanism to keep the agent safe?
We were wondering if somehow the agent could enter to a "sleeping status", when the database is down.
E.g. today we had https://hypernews.cern.ch/HyperNews/CMS/get/cernCompAnnounce/1148/2.html, all CERN agents were down, and all the components had to be restarted once the intervention was over.

**Comment by amaltaro** [comment]
I think this can be done. We need to make sure the couch/dashboard/etc is not going to be updated while oracle is down though. For reference, here is a traceback from today's intervention:
```
2016-09-14 10:14:55,996:140641479939840:ERROR:pool:Exception closing connection <cx_Oracle.Connection to CMS_WMBS_PROD4@CMSR>
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/pool.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in do_close
    dbapi_connection.close()
OperationalError: ORA-03114: not connected to ORACLE

2016-09-14 10:14:56,010:140641479939840:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobCreator.JobCreatorPoller.JobCreatorPoller instance at 0x7fe9af0d5a70> (OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 44288
Session ID: 3723 Serial number: 28353
 'SELECT component_id FROM wm_workers\n                WHERE component_id = (SELECT id FROM wm_components\n                                   WHERE name = :component_name)\n                AND name = :worker_name\n             ' {'worker_name': 'JobCreatorPoller', 'component_name': 'JobCreator'}  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/c
ms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 165, in __call__
    myThread.getName(), "Running")
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Agent/HeartbeatAPI.py", line 47, in updateWorkerHeartbeat
    transaction = self.existingTransaction())
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Agent/Database/MySQL/ExistWorker.py", line 37, in execute
    transaction = transaction)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 194, in processData
    returnCursor=returnCursor)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 79, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
```

**Comment by vlimant** [comment]
that'd be great ! just registering myself to the issue.
@scarletnorberg

**Comment by amaltaro** [comment]
Closing it in favor of #7713
