### ISSUE TITLE
ErrorHandler still crashing on CouchConnectionError

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7194]
We still see this component going down from time to time, even though it should not crash on `(CouchConnectionError, HTTPException)` exceptions...

I made a couple of nasty changes to ErrorHandlerPoller.py in vocms0303 :)

BTW, here is an error message/traceback from vocms0303 - running the original code -:

```
2016-09-19 10:18:17,874:140277928490752:INFO:ErrorHandlerPoller:This operation will take some time...
2016-09-19 10:19:29,858:140277928490752:ERROR:ErrorHandlerPoller:Caught unexpected exception in ErrorHandler
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 362, in algorithm
    self.handleErrors()
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 300, in handleErrors
    self.handleRetryDoneJobs(jobList)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 259, in handleRetryDoneJobs
    self.exhaustJobs(jobList)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 126, in exhaustJobs
    self.handleACDC(jobList)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 185, in handleACDC
    self.dataCollection.failedJobs(loadList)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Database/CouchUtils.py", line 53, in wrapper
    return funcRef(x, *args, **opts)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/ACDC/DataCollectionService.py", line 99, in failedJobs
    job.get("owner", "cmsdataops"))
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/ACDC/CouchService.py", line 71, in newOwner
    userInstance = makeUser(group, user, self.url, self.database)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/GroupUser/User.py", line 93, in makeUser
    group.connect()
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/GroupUser/CouchObject.py", line 88, in connect
    raise CouchConnectionError(msg)
CouchConnectionError
2016-09-19 10:19:29,936:140277928490752:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.ErrorHandler.ErrorHandlerPoller.ErrorHandlerPoller instance at 0x7f95085c8950> ErrorHandlerException
Message: Caught unexpected exception in ErrorHandler

    ModuleName : WMComponent.ErrorHandler.ErrorHandlerPoller
    MethodName : algorithm
    ClassInstance : None
    FileName : /data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py
    ClassName : None
    LineNumber : 372
    ErrorNr : 0

Traceback:
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 362, in algorithm
    self.handleErrors()

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 300, in handleErrors
    self.handleRetryDoneJobs(jobList)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 259, in handleRetryDoneJobs
    self.exhaustJobs(jobList)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 126, in exhaustJobs
    self.handleACDC(jobList)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 185, in handleACDC
    self.dataCollection.failedJobs(loadList)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/Database/CouchUtils.py", line 53, in wrapper
    return funcRef(x, *args, **opts)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/ACDC/DataCollectionService.py", line 99, in failedJobs
    job.get("owner", "cmsdataops"))

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/ACDC/CouchService.py", line 71, in newOwner
    userInstance = makeUser(group, user, self.url, self.database)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/GroupUser/User.py", line 93, in makeUser
    group.connect()

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/GroupUser/CouchObject.py", line 88, in connect
    raise CouchConnectionError(msg)

  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 172, in __call__
    self.algorithm(parameters)
  File "/data/srv/wmagent/v1.0.19.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch1/lib/python2.7/site-packages/WMComponent/ErrorHandler/ErrorHandlerPoller.py", line 372, in algorithm
    raise ErrorHandlerException(msg)

2016-09-19 10:19:29,936:140277928490752:INFO:Harness:>>>Terminating worker threads
```

where we can clearly see the exception of type `CouchConnectionError`, which I don't get why it doesn't fall on the first except block
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L363

**Comment by jenimal** [comment]
Since you have restarts on cron job, for the time being should I just inform the Operational Support group to report, but not restart anything with the agents?  Are there components they should restart?  Where do you want them to report these issues to?

Jen

**Comment by amaltaro** [comment]
The automatic restart is set *only* for ErrorHandler (this component was getting stuck with no activity some time ago). So, you can keep restarting anything that crashes (even ErrorHandler, if you want, though it's not needed).

About reporting issues, you can create a GH issue everytime problems arise and a developer needs to look at it, then if it happens again, there is no need to update the issue (unless it's hitting production very badly)

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ErrorHandler still crashing on CouchConnectionError](https://trello.com/c/xhH8rHfk/18-errorhandler-still-crashing-on-couchconnectionerror)

**Comment by amaltaro** [comment]
I haven't seen this issue for quite some time now, so closing it.
