### ISSUE TITLE
Investigate the JobExtractionError error during bootstrap

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7273]
Info from wmstats

```
Job Name: 24fdfab4-81c9-11e6-9565-001e67abef8c-27
    WMBS job id: 1548420
    Workflow: cerminar_Run2016B-v2-BTagCSV-23Sep2016_8020_160923_163236_9822
    Task: /cerminar_Run2016B-v2-BTagCSV-23Sep2016_8020_160923_163236_9822/DataProcessing
    Status: jobcooloff
    Input dataset: /BTagCSV/Run2016B-v2/RAW
    Site: T2_CH_CERN_HLT
    Agent: vocms0311.cern.ch
    ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
    State Transition
    Exit code: 11003
    Retry count: 0
    Errors:
        CRITICAL
            JobExtractionError (Exit Code: 11003)

                Failed to extract Job 1548420
                1548420
```

condor.out

```
...
WMAgent bootstrap : Sat Oct  1 11:27:37 UTC 2016 : WMAgent is now running the job...
Startup.py : 2016-10-01T06:27:37 : loading job definition
WMAgent bootstrap : Sat Oct  1 11:27:37 UTC 2016 : WMAgent finished the job, is copying the pickled report
WMAgent bootstrap : Sat Oct  1 11:27:37 UTC 2016 : WMAgent is finished. The job had an exit code of 1
```

and condor.err

```
Traceback (most recent call last):
  File "Startup.py", line 15, in <module>
    job = Bootstrap.loadJobDefinition()
  File "/storage/local/data1/condor/execute/dir_1529846/glide_PMCpkr/execute/dir_1735873/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 153, in loadJobDefinition
WMCore.WMRuntime.Bootstrap.BootstrapException: BootstrapException
Message: Failed to extract Job 1548420
1548420
        ModuleName : WMCore.WMRuntime.Bootstrap
        MethodName : loadJobDefinition
        ClassInstance : None
        FileName : /storage/local/data1/condor/execute/dir_1529846/glide_PMCpkr/execute/dir_1735873/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py
        ClassName : None
        LineNumber : 153
        ErrorNr : 0

Traceback:
  File "/storage/local/data1/condor/execute/dir_1529846/glide_PMCpkr/execute/dir_1735873/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 148, in loadJobDefinition
    job = package[index]


cp: cannot stat `WMTaskSpace/Report*.pkl': No such file or directory
ls: cannot access WMTaskSpace: No such file or directory
ls: cannot access WMTaskSpace/*: No such file or directory
```

**Comment by jenimal** [comment]
We are seeing these errors in MC workflows now as well, any progress to report on the issue?:
 pdmvserv_HIG-RunIISummer15GS-01733_00443_v0__161013_001620_6350
 	- pdmvserv_HIG-RunIISummer15GS-01724_00443_v0__161013_001316_4934
 	- pdmvserv_BPH-RunIISummer15GS-00080_00448_v0__161019_161345_989
 		- WMStats shows that most failed jobs have the exit code 11003: JobExtractionError
 		- These workflows are running at T2_CH_CERN, T2_CH_CERN_HLT and T2_IT_Pisa

**Comment by vlimant** [comment]
Looking at mcremone_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161215_002821_7569 that all failed with jobextraction @mcremone, finding the jobpackage in the agent, and looking into it does not contains the expected wmbs jobid

/data/srv/wmagent/v1.0.21.patch1/install/wmagent/WorkQueueManager/cache/mcremone_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161215_002821_7569/PackageCollection_0/batch_4894600-0/JobPackage.pkl

>>> pkg.keys()
[4894772, 4894773, 4894774, 4894775, 4894776, 4894777, 4894778, 4894779, 4894780, 4894781, 4894782, 4894783, 4894784, 4894785, 4894786, 4894787, 4894788, 4894789, 4894790, 4894791, 4894792, 4894793, 4894794, 4894795, 4894796, 4894797, 4894798, 4894799, 4894800, 4894801, 4894802, 4894803, 4894804, 4894805, 4894806, 4894807, 4894808, 4894809, 4894810, 4894811, 4894812, 4894813, 4894814, 4894815, 4894816, 4894817, 4894818, 4894819, 4894820, 4894821, 4894822, 4894823, 4894824, 4894825, 4894826, 4894827, 4894828, 4894829, 4894830, 4894831, 4894832, 4894833, 4894834, 4894835, 4894836, 4894837, 4894838, 4894839, 4894840, 4894841, 4894842, 4894843, 4894844, 4894845, 4894846, 4894847, 4894848, 4894849, 4894850, 4894851, 4894852, 4894853, 4894854, 4894855, 4894856, 4894857, 4894858, 4894859, 4894860, 4894861, 4894862, 4894863, 4894864, 4894865, 4894866, 4894867, 4894868, 4894869, 4894870, 4894871, 4894872, 'directory', 4894600, 4894601, 4894602, 4894603, 4894604, 4894605, 4894606, 4894607, 4894608, 4894609, 4894610, 4894611, 4894612, 4894613, 4894614, 4894615, 4894616, 4894617, 4894618, 4894619, 4894620, 4894621, 4894622, 4894623, 4894624, 4894625, 4894626, 4894627, 4894628, 4894629, 4894630, 4894631, 4894632, 4894633, 4894634, 4894635, 4894636, 4894637, 4894638, 4894639, 4894640, 4894641, 4894642, 4894643, 4894644, 4894645, 4894646, 4894647, 4894648, 4894649, 4894650, 4894651, 4894652, 4894653, 4894654, 4894655, 4894656, 4894657, 4894658, 4894659, 4894660, 4894661, 4894662, 4894663, 4894664, 4894665, 4894666, 4894667, 4894668, 4894669, 4894670, 4894671, 4894672, 4894673, 4894674, 4894675, 4894676, 4894677, 4894678, 4894679, 4894680, 4894681, 4894682, 4894683, 4894684, 4894685, 4894686, 4894687, 4894688, 4894689, 4894690, 4894691, 4894692, 4894693, 4894694, 4894695, 4894696, 4894697, 4894698, 4894699, 4894700, 4894701, 4894702, 4894703, 4894704, 4894705, 4894706, 4894707, 4894708, 4894709, 4894710, 4894711, 4894712, 4894713, 4894714, 4894715, 4894716, 4894717, 4894718, 4894719]

>>> pkg[4894723]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 4894723

**Comment by amaltaro** [comment]
And just for the record, I can list this jobid in wmbs_job and I can also load the `job.pkl` file from:
/data/srv/wmagent/v1.0.21.patch1/install/wmagent/JobCreator/JobCache/mcremone_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch0-09Nov2016_8023__161215_002821_7569/DataProcessing/JobCollection_523106_0/job_4894723

**Comment by vlimant** [comment]
is there a plan to not try to get the stageout report when there was no output produced/uploaded. i.e. have the proper error message/code ?

**Comment by amaltaro** [comment]
You probably mixed the subjects :)

**Comment by vlimant** [comment]
Now that we know what was going on : jobpackage not having the actual job, is there anything that can be done to trace how the jobpackage got corrupted ?

**Comment by amaltaro** [comment]
Reopening it since it still happens in agent version 1.1.10.patch1.
I've put a bunch of logs under
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7273/

where one can find the sandbox tarball created by the agent, the JobPackage.pkl transferred to the job (as decribed by TransferIn ad), the job logs from JobArchiver and alan.json is JobPackage unpickled.

These were the parameters the agent submitted via condor:
`Arguments:  amaltaro_MonteCarlo_eff_Agent1110_Validation_180209_120351_9130-Sandbox.tar.bz2 8200`

and we can clearly see that JobPackage has an index gap between 8191 and 8260(???)
I'll get back to this issue once the agent validation is over.

**Comment by vlimant** [comment]
happened also in production team, but there's too much crap going for streamlined reporting

**Comment by amaltaro** [comment]
FMY: While I look at something else in the code, I found it:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L174

it's worth having a deeper look at this code...

**Comment by bbockelm** [comment]
I wonder if it's possible that an exception is thrown before `addJobsToPackage` when handling a new job (causing the transaction to abort), then it's somehow skipped on the second refresh, causing the job to be submitted regardless.

I don't see any code that would cause this -- but seems to be one candidate we should hunt down.

**Comment by amaltaro** [comment]
I can't really see that happening. The only exception that wouldn't rollback the transaction (and is not terminal) happens to jobs that failed to be submitted, thus they weren't actually added to the cache.
Any other exception would trigger a transaction rollback and be terminal to the component.

JobPackage is job driven, by this I mean they get created as we load/parse jobs, which "at the same time"  are also added to the component cache (and linked to the JobPackage by `batchDir`).
There are some minor improvements to this code, but I couldn't spot the root cause yet.

**Comment by prozober** [comment]
Hello,
This error showed up again in one of the Data2016MiniAODv2 Rerecos.
https://cms-unified.web.cern.ch/cms-unified/report/fabozzi_Run2016E-07Aug17-v1-SingleElectron-17Jul2018_949_180717_162519_1873
Here some logs https://cms-unified.web.cern.ch/cms-unified//condorlogs/fabozzi_Run2016E-07Aug17-v1-SingleElectron-17Jul2018_949_180717_162519_1873/11003/DataProcessing/
We are running ACDCs in the meantime.

**Comment by sharad1126** [comment]
Hello,

This error showed in one more workflow.
https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_task_MUO-RunIISummer18wmLHEGS-00001__v1_T_180511_235829_4578#MUO-RunIISummer18wmLHEGS-00001_0
I don't have the job logs for this. 
Not running an ACDC as of now.

**Comment by jenimal** [comment]
Ha apparently this issue shows up in July.  I am seeing it for : 
https://cms-unified.web.cern.ch/cms-unified//report/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00440__v1_T_190605_144033_9840

Not a common problem but shows up periodically.

Jen
