### ISSUE TITLE
ReqMgr2: default assignment value for AutoApproveSubscriptionSites

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7284]
I've just hit an issue on the agent side while going through an ACDC workflow that had subscriptions settings and changed during UI assignment in ReqMgr2. WorkQueue is failing to process it [1]

@ticoann I think the reason it's failing is because we set the default value to empty string:
https://github.com/dmwm/WMCore/pull/7254/files#diff-4129fdb6f4ac8568d6ac3fa9cb51f010R101

in case no sites are selected, which then fails in the lambda function.

Would you have a better than creating a specific default value for this case?

[1]
2016-10-12 10:49:08,593:140631694944000:INFO:WorkQueue:Adding WMBS subscription for amaltaro_ACDC_MonteCarlo_Ext_Agent1021_Validation_161011_133611_1649
2016-10-12 10:49:08,614:140631694944000:INFO:WMBSHelper:Top level subscription created: 1543
2016-10-12 10:49:08,642:140631694944000:INFO:WMBSHelper:Child subscription created: 1544
2016-10-12 10:49:08,721:140631694944000:INFO:WMBSHelper:Child subscription created: 1545
2016-10-12 10:49:08,772:140631694944000:INFO:WMBSHelper:Child subscription created: 1546
2016-10-12 10:49:08,791:140631694944000:INFO:WMBSHelper:Child subscription created: 1547
2016-10-12 10:49:08,811:140631694944000:ERROR:WMBSHelper:Failed to create subscription Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 406, in createSubscriptionAndAddFiles
    sub = self.createSubscription(self.topLevelTask, self.topLevelFileset)
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 264, in createSubscription
    self._createDatasetSubscriptionsInDBSBuffer()
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 497, in _createDatasetSubscriptionsInDBSBuffer
    subInfo = self.wmSpec.getSubscriptionInformation()
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1297, in getSubscriptionInformation
    taskSubInfo = self.getSubscriptionInformation(task)
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1305, in getSubscriptionInformation
    subInfo[dataset]["AutoApproveSites"])
  File "/data/srv/wmagent/v1.0.21.pre6/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1280, in <lambda>
    extendWithoutDups = lambda x, y: x + list(set(y) - set(x))
TypeError: cannot concatenate 'str' and 'list' objects

2016-10-12 10:49:08,812:140631694944000:ERROR:WorkQueue:amaltaro_ACDC_MonteCarlo_Ext_Agent1021_Validation_161011_133611_1649, /acdc/amaltaro_ACDC_MonteCarlo_Ext_Agent1021_Validation_161011_133611_1649/:amaltaro_MonteCarlo_Ext_Agent1021_Validation_161008_105904_7030:Production/0/1: 
creating subscription failed in LQ: 
cannot concatenate 'str' and 'list' objects

**Comment by ticoann** [comment]
Hmm, if it is empty string it should still convert to empty list [] in validation. Let me check the code.

**Comment by amaltaro** [comment]
Yep, I'm not really sure as well. We either:
a) cast the input data to the `type` definined in the spec
b) or we make sure the input data is on the `type` format expected.
What do you think?

**Comment by ticoann** [comment]
we have to cast. we can't enforce it from web interface since everything is string from web.
But we are already casting. (makelist with convert empty string to list)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L993

I am trying to find why this didn't get called.
