### ISSUE TITLE
Agent failing to put some docs into local couch

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7295]
One of the side effects is what was reported in #7291

This issue seems to be hitting the agents since Oct 5 or 6 (it depends on the agent), which causes ErrorHandler to fail to update/inject data into local couch, e.g. from vocms0308
```
2016-10-06 00:16:01,100:139690432091904:INFO:ErrorHandlerPoller:About to process 30 failures
2016-10-06 00:16:01,101:139690432091904:INFO:ErrorHandlerPoller:Processing retries for 30 failed jobs of type jobfailed
2016-10-06 00:16:02,834:139690432091904:ERROR:ChangeState:Error updating job in couch: CouchInternalServerError - reason: Internal Server Error, data: None result: None
2016-10-06 00:16:02,835:139690432091904:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 164, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 293, in recordInCouch
    self.jsumdatabase.makeRequest(uri = updateUri, type = "PUT", decode = False)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 148, in checkForCouchError
    raise CouchInternalServerError(reason, data, result)
CouchInternalServerError: CouchInternalServerError - reason: Internal Server Error, data: None result: None
```

then looking at the other components, JobAccountant also complains when decoding data with 'utf8' code, e.g.
```
2016-10-14 12:35:28,829:140665816086272:INFO:AccountantWorker:Job 1205694 , handle successful job
2016-10-14 12:35:30,737:140665816086272:ERROR:ChangeState:Error updating job in couch: 'utf8' codec can't decode byte 0x8e in position 1627: invalid start byte
2016-10-14 12:35:30,738:140665816086272:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 164, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 340, in recordInCouch
    self.fwjrdatabase.queue(fwjrDocument, timestamp = True, callback = discardConflictingDocument)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 217, in queue
    self.commit(viewlist=viewlist, callback=callback)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 112, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 140, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 220, in makeRequest_httplib
    encoded_data = self.encode(data)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.0.19.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 548, in encode
    return encoder.encode(thunked)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/srv/wmagent/v1.0.19.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 1627: invalid start byte

2016-10-14 12:35:30,738:140665816086272:INFO:DashboardReporter:Handling 84 jobs
```

The real issue seems to be coming from the fact the job summary (updatesummary)
`    self.recordInCouch(jobs, newstate, oldstate, updatesummary)`
contains some bad encoded char. Which is likely related to these fixes:
https://github.com/dmwm/WMCore/pull/7209/files
https://github.com/dmwm/WMCore/pull/7272/files

**Comment by amaltaro** [comment]
I made this fix to BasicAlgos:
https://github.com/amaltaro/WMCore/commit/2c3932964e5a3eb1a267303d544f25439b8a2ef2

just to sanitize data that we're reading from these logs (not sure about 'utf8' or 'ISO-8859-1' as well). I patched vocms0308 but that didn't solve the problem and I still see complaints in JobAccountant. I'm removing this patch for now, though I think in general it'll be good to add it to our code.

BTW, here is one data sample that caused problems (taken from the logs):
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7295/alan
