### ISSUE TITLE
Fail workflow in GQ if dataset does not exist

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7300]
Federica was trying to run a test in testbed and the workflow remained in assigned for a long time.
Looking at the GQ logs, this was the reason

```
2016-10-17 02:05:03,131 INFO     WorkQueueReqMgrInterface: Contacting Request manager for more work
2016-10-17 02:05:04,565 INFO     WorkQueueReqMgrInterface: Processing request fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724 at https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/fanzago_Re
Digi_fede_premix_HN_FF_161013_185453_5724/spec
2016-10-17 02:05:04,565 INFO     WorkQueue: queueWork() begin queueing "https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724/spec"
2016-10-17 02:05:05,215 INFO     WorkQueue: Resume splitting of "fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724"
2016-10-17 02:05:05,437 INFO     WorkQueue: Splitting /fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724/StepOneProc with policy Block params = {'ResubmitBlock': {'args': {}, 'name': 'ResubmitBlock'}, '
MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Block'}}
2016-10-17 02:05:05,820 ERROR    ProdException: DBSReaderError
Message: Dataset /Neutrino_E-10_gun/RunIISpring15PrePremix-PU2016_80X_mcRun2_asymptotic_v14-v2/GEN-SIM-DIGI-RAW doesn't exist in DBS https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/
        ModuleName : WMCore.Services.DBS.DBSErrors
        MethodName : __init__
        ClassInstance : None
        FileName : /data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/Services/DBS/DBSErrors.py
        ClassName : None
        LineNumber : 38
        ErrorNr : 1002

2016-10-17 02:05:05,820 ERROR    WorkQueue: Exception splitting wqe fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724 for fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724: DBSReaderError
Message: Dataset /Neutrino_E-10_gun/RunIISpring15PrePremix-PU2016_80X_mcRun2_asymptotic_v14-v2/GEN-SIM-DIGI-RAW doesn't exist in DBS https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/
        ModuleName : WMCore.Services.DBS.DBSErrors
        MethodName : __init__
        ClassInstance : None
        FileName : /data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/Services/DBS/DBSErrors.py
        ClassName : None
        LineNumber : 38
        ErrorNr : 1002

2016-10-17 02:05:06,266 ERROR    WorkQueueReqMgrInterface: Unknown error processing fanzago_ReDigi_fede_premix_HN_FF_161013_185453_5724
Traceback (most recent call last):
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 104, in queueNewRequests
    units = queue.queueWork(workLoadUrl, request=reqName, team=team)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 630, in queueWork
    work = self.processInboundWork(inbound, throw=True)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1073, in processInboundWork
    continuous=continuous)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1019, in _splitWork
    units, rejectedWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 140, in __call__
    self.pileupData = self.getDatasetLocations(pileupDatasets)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 203, in getDatasetLocations
    locations = dbs.listDatasetLocation(datasetPath)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 808, in listDatasetLocation
    self.checkDatasetPath(datasetName)
  File "/data/srv/beHG1610j/sw/slc6_amd64_gcc493/cms/workqueue/1.0.21.pre6/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 854, in checkDatasetPath
    raise DBSReaderError("Dataset %s doesn't exist in DBS %s" % (pathName, self.dbsURL))
DBSReaderError: DBSReaderError
```

Even better, add a validation during request creation for input and PU dataset. 
Actually, AFAIR we already have it for the input, "just" need to extend it to the PU case.

**Comment by ticoann** [comment]
Alan, did you have to look at the log or is this displayed in WMStats (logDB) if not it should report at logDB as well.

**Comment by amaltaro** [comment]
Good point! I haven't looked at wmstats, so I don't know if the issue was reported in logdb as well.
These logs were taken out of the workqueue logs in cmsweb.

**Comment by amaltaro** [comment]
It's now validated during request creation:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkloadTools.py#L125

Closing
