### ISSUE TITLE
vocms0126 Component down: JobAccountant

### ISSUE THREAD

**Issue by scarletnorberg** [dmwm/WMCore#7334]
Log on WMStats:
Error in worker algorithm (1):
Backtrace:
   JobAccountantPollerException
Message: Hit general exception in JobAccountantPoller while using worker.
'NoneType' object has no attribute 'files'
ModuleName : WMComponent.JobAccountant.JobAccountantPoller
MethodName : algorithm
ClassInstance : None
FileName : /data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py
ClassName : None
LineNumber : 88
ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py", line 73, in algorithm
    self.accountantWorker(jobsSlice)

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/Accountant
pid: 16960

ERROR LOG ON COMPNENT LOG:

0199_v0__161020_121756_4427/Production/JobCollection_26614_0/job_343649/Report.0.pkl
2016-10-27 03:40:43,221:140523847075584:WARNING:AccountantWorker:Job 343649 , bad jobReport, failing job
2016-10-27 03:40:43,227:140523847075584:ERROR:JobAccountantPoller:Hit general exception in JobAccountantPoller while using worker.
'NoneType' object has no attribute 'files'
2016-10-27 03:40:43,311:140523847075584:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobAccountant.JobAccountantPoller.JobAccountantPoller instance at 0x7fce4b787b00> JobAccountantPollerException
Message: Hit general exception in JobAccountantPoller while using worker.
'NoneType' object has no attribute 'files'
ModuleName : WMComponent.JobAccountant.JobAccountantPoller
MethodName : algorithm
ClassInstance : None
FileName : /data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py
ClassName : None
LineNumber : 88
ErrorNr : 0

Traceback:
  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py", line 73, in algorithm
    self.accountantWorker(jobsSlice)

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 243, in **call**
    fwkJobReport = fwkJobReport)

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 584, in handleJob
    self._mapLocation(wmbsJob['fwjr'])

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 450, in _mapLocation
    for file in fwkJobReport.getAllFileRefs():

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMCore/FwkJobReport/Report.py", line 1239, in getAllFileRefs
    tmpRefs = self.getAllFileRefsFromStep(step=step)

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMCore/FwkJobReport/Report.py", line 1073, in getAllFileRefsFromStep
    for i in range(outputModuleRef.files.fileCount):

  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 180, in **call**
    self.algorithm(parameters)
  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py", line 88, in algorithm
    raise JobAccountantPollerException(msg)

**Comment by scarletnorberg** [comment]
Restart because I had not seen any logs and I figured everyone was asleep it went down again.

**Comment by amaltaro** [comment]
Thanks for reporting this issue. The component is going down because this job report:
/data/srv/wmagent/v1.0.21.patch1/install/wmagent/JobCreator/JobCache/pdmvserv_TOP-RunIISummer15wmLHEGS-00125_00199_v0__161020_121756_4427/Production/JobCollection_26614_0/job_343649/Report.0.pkl

doesn't have one of the outputModules section.
```
>>> reportJson = jobReport.__to_json__(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.0.21.patch1/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch1/lib/python2.7/site-packages/WMCore/FwkJobReport/Report.py", line 242, in __to_json__
    reportOutputModule = getattr(reportStep.output, outputModule)
AttributeError: 'ConfigSection' object has no attribute 'RAWSIMoutput'
```

I copied this file to the `current` directory and I'll debug it further. This job was failed and the component is up and running again.

**Comment by vlimant** [comment]
@amaltaro can we protect ourselves from this ?

**Comment by amaltaro** [comment]
This is reallyyy weird... this is why this job report was crashing the component:
```
>>> pprint(vars(reportSection.output))
{'LHEoutput': <WMCore.Configuration.ConfigSection object at 0x7fc58a505890>,
 'RAWSIMoupput': <WMCore.Configuration.ConfigSection object at 0x7fc58a5059d0>,
 '_internal_children': set(['LHEoutput', 'RAWSIMoutput']),
 '_internal_docstrings': {},
 '_internal_documentation': '',
 '_internal_name': 'output',
 '_internal_parent_ref': <WMCore.Configuration.ConfigSection object at 0x7fc58a505250>,
 '_internal_settings': set(['LHEoutput', 'RAWSIMoutput']),
 '_internal_skipChecks': False}
```

so it has the correct output modules. However, one of the ConfigSections has the output module `RAWSIMoupput` instead of `RAWSIMoutput`?!?

I had a look at the ConfigCacheID and the request schema and I see no problems at all. In addition to that, this workflow had 1 single failure out of 47k success jobs so far.

Honestly, I have no idea of what happened here. My best guess would be a messed up CMSSW environment in the worker node or so...

**Comment by amaltaro** [comment]
Yes, of course! But I'd rather not add a patch (read it as another dirty patch - try/except block - in the code) for something like that that comes out of thin air once in life.

**Comment by amaltaro** [comment]
And for any possible future reference, I fixed the jobReport in my local machine and dumped the its content as json:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7334/pdmvserv_TOP-RunIISummer15wmLHEGS-00125_00199_v0__161020_121756_4427-JobID343649.json

**Comment by vlimant** [comment]
agreed that this is rather rare. but maybe protecting from a corrupted <whatever was corrupted> to not have the agent crash. We'd go from "once in life" to "once in 10 lives".

**Comment by amaltaro** [comment]
I don't think it's worth chasing this mysterious problem that happen only once in a lifetime.
Anyways, if we ever see it again, we can always find this issue in GH and reopen it. So closing this issue.
