### ISSUE TITLE
Prevent component crash on Oracle connection error

### ISSUE THREAD

**Issue by scarletnorberg** [dmwm/WMCore#7713]
I think this is the second time this has happened where there has been an oracle issue. Does the WMcore group maintain Oracle? Is this a git issue? Is there a log that I should be sending?

Issues related to it are: #7710 #7589 #7180

**Comment by ticoann** [comment]
@scarletnorberg, Oracle is maintained by CERN IT. Currently if Oracle has major problem, all the agent will crash. It was OK since it happened very rarely and also when it happens we can't process any jobs.  I am sure why this happened a couple of times in a short period. But unless this is transient issue which can happen often. I don't think we should to something to ignore and retried.

**Comment by scarletnorberg** [comment]
I guess this is a closed issue for now and a keep an eye on. Hopefully these were the only two times for the year. Thanks for the information. Is this the site I can use to check if there is oracle issues: https://cern.service-now.com/service-portal/ssb.do?area=IT ?

**Comment by vlimant** [comment]
Hi, regardless of the instability or oracle, we need the agents to not die on it, but report to wmstats that service is unavailable. 
Is it that hard to setup a dbcheck ?

**Comment by ticoann** [comment]
I am not completely sure whether this will be hard to set up. I think there might be a simpler way to catch all DB call make component not crash.  One thing I would I like to avoid is catching too general errors and miss the case we actually need to fix. (i.e. there were duplicate insert due to the uuid collision and we had to manually fix the files)

I think what we can do probably is if there is connection error happens don't crash the component and retry. I will look how hard it will be to implement that.  Reopening the issue

**Comment by hufnagel** [comment]
I think catching all db related errors might be asking too much. The database is such a fundamental part of WMAgent, there is often very little you can do when it goes away. Also, keep going in the presence of database errors exposes you to the serious risk of state inconsistencies. If you want to continue in the presence of database errors you better make very very sure the internal state of your component *CAN* survive database errors and isn't afterwards inconsistent with what is saved in the database, leading to other huge problems down the line. If you continue after a db error, your code absolutely needs to be aware of the db error and handle that correctly. You can't just ignore the error. 

IMO, unless you have specific reasons to retry db operations (which might exists on a case by case basis and should be implemented on a case by case basis), it's better to just stop and force a human to take a look at what's going on.

That being said, crashed components show up in the monitoring, don't they ? So what's the problem ?

**Comment by ticoann** [comment]
Hi Dirk, I think the problem was when it is transient errors. DB connection goes away somehow and fixed in a couple of hours.  Ops has to follow what is going one with DB and restart all the components.
I guess they want to minimize those situation. 
But I completely agree that we can't blindly catch all db exceptions and proceed other task.
I was wondering whether we can do better with specific cases.

**Comment by hufnagel** [comment]
Oh, don't get me wrong. If we can catch specific database operations exceptions and move on while maintaining internal component state consistency, I am all for it. But that is highly component specific. Some db operations you will be able to ignore the error and just retry the next cycle. Some db operations affect the next steps in the current polling cycle. It all depends on the what the component is doing.

**Comment by vlimant** [comment]
I agree that db error should be not just ignored and move on. I was thinking f throwing a db connect error, stopping the component cycle, leaving the component alive and trying to come back to it. The exception should propagated as a warning in wmstats, so that we can monitor why an agent is not making jobs, but the agent would come back to work by itself once the db transient/announced issue is over, whenever that happens, with a view to not have a human involved except for monitoring the rate of such warnings.

**Comment by hufnagel** [comment]
That's not really possible in general. You get db errors for other reasons than non-availability of db resources. For instance, you can get a FK constraint error, in these cases something seriously is screwed up and you want to crash since either you have a query bug or your data is so screwed up that you really don't want to continue.

Not sure if we can reliably detect "database is temporarily unavailable", that would be the only type of error where your proposal is a workable solution.

**Comment by amaltaro** [comment]
Just in case, I placed here the complete logs with the oracle crashes:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_7713/oracle_disconnect.log

It seems to be exactly the same crash in these 4 components: DBS3Upload, JobStatusLite, JobTracker and JobCreator.

The exception is OperationalError, but there are two error messages:
OperationalError: ORA-03114: not connected to ORACLE
(OperationalError) ORA-03135: connection lost contact

and what's seen in the components is ORA-03135.

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent component crash on Oracle connection error](https://trello.com/c/qxSQhtLw/16-prevent-component-crash-on-oracle-connection-error)

**Comment by amaltaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent component crash on Oracle connection error](https://trello.com/c/ecPZbNza/26-prevent-component-crash-on-oracle-connection-error)

**Comment by scarletnorberg** [comment]
Here is the error that was seen last week:

2017-04-26 09:56:46,913:139850001897216:INFO:AnalyticsPoller:Combining data from
Job Couch(14),
FWJR(14),
WorkflowsWithSkippedFile(8),
Batch Job(5),
Finished Tasks(14),
Local Queue(6) ...
2017-04-26 09:56:46,913:139850001897216:INFO:AnalyticsPoller:14 requests Data combined,
uploading request data...
2017-04-26 09:56:47,203:139850001897216:INFO:AnalyticsPoller:Request data upload success
14 request,
sleep for next cycle
2017-04-26 10:22:15,007:139850001897216:ERROR:pool:Exception closing connection <cx_Oracle.Connection to CMS_WMBS_PROD5@CMSR>
Traceback (most recent call last):
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/pool.py", line 244, in _close_connection
self._dialect.do_close(connection)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in do_close
dbapi_connection.close()
OperationalError: ORA-03114: not connected to ORACLE
2017-04-26 10:22:15,051:139850001897216:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
<WMComponent.AnalyticsDataCollector.AnalyticsPoller.AnalyticsPoller instance at 0x7f3165bd8680> (OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 147125
Session ID: 582 Serial number: 26663
'SELECT component_id FROM wm_workers\n WHERE component_id = (SELECT id FROM wm_components\n WHERE name = :component_name)\n AND name = :worker_name\n '
{'worker_name': 'AnalyticsPoller', 'component_name': 'AnalyticsDataCollector'}
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 172, in _call_
myThread.getName(), "Running")
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/Agent/HeartbeatAPI.py", line 47, in updateWorkerHeartbeat
transaction = self.existingTransaction())
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/Agent/Database/MySQL/ExistWorker.py", line 37, in execute
transaction = transaction)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 179, in processData
returnCursor=returnCursor)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 65, in executebinds
resultProxy = connection.execute(s, b)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
return self._execute_text(object, multiparams, params)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
statement, parameters
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
context)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
exc_info
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
context)
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/py2-sqlalchemy/0.9.6-comp3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
cursor.execute(statement, parameters)
2017-04-26 10:22:15,051:139850001897216:INFO:Harness:>>>Terminating worker threads
2017-04-26 10:22:15,204:139850001897216:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.AnalyticsDataCollector.AnalyticsPoller.AnalyticsPoller instance at 0x7f3165bd8680> (OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 147125
Session ID: 582 Serial number: 26663
'SELECT component_id FROM wm_workers\n WHERE component_id = (SELECT id FROM wm_components\n WHERE name = :component_name)\n AND name = :worker_name\n '
{'worker_name': 'AnalyticsPoller', 'component_name': 'AnalyticsDataCollector'}
Backtrace:
File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.0.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 205, in _call_
raise ex
2017-04-26 10:22:15,204:139850001897216:INFO:BaseWorkerThread:Worker thread <WMComponent.AnalyticsDataCollector.AnalyticsPoller.AnalyticsPoller instance at 0x7f3165bd8680> terminated
https://its.cern.ch/jira/projects/CMSCOMPPR/issues/CMSCOMPPR-846?filter=allopenissues

There was never any log on this issue but here is one now and it says oracle connection issue.

Another agent with this issue:
https://its.cern.ch/jira/projects/CMSCOMPPR/issues/CMSCOMPPR-845?filter=allopenissues

**Comment by ticoann** [comment]
duplicate #8402
