### ISSUE TITLE
JobSubmitter dies after failing to retrieve aborted workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7879]
It keeps up for a few cycles and then eventually it dies, process is gone and component is down.
Nothing in stderr/stdout/ComponentLog. Since it happens to vocms0159 every time there is a testbed upgrade, I figured it was time to track it down and fix it.

Just in case, tail of the component log:
```
2017-05-29 19:47:09,905:139713378219776:INFO:JobSubmitterPoller:Determining possible sites for new jobs...
2017-05-29 19:47:09,907:139713378219776:INFO:JobSubmitterPoller:Done pruning killed jobs, moving on to submit.
2017-05-29 19:47:10,053:139713378219776:WARNING:Service:The cachefile /data/srv/wmagent/v1.1.2.patch2/install/wmagent/JobSubmitter/.wmcore_cache/.wmcore_cache_31961/requests/cmsweb-testbed.cern.ch/15744094587142094_GET_request?status=aborted&status=aborted-completed&status=force-complete&detail=False does not exist and the service at https://cmsweb-testbed.cern.ch/reqmgr2/data/request?status=aborted&status=aborted-completed&status=force-complete&detail=False raised a ServerNotFoundError('Unable to find the server at cmsweb-testbed.cern.ch',) when accessed
2017-05-29 19:47:10,102:139713378219776:ERROR:GenericDataCache:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.2.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.2.patch2/lib/python2.7/site-packages/WMCore/Cache/GenericDataCache.py", line 37, in getData
    self.data = self.func(**self.kwargs)
  File "/data/srv/wmagent/v1.1.2.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.2.patch2/lib/python2.7/site-packages/WMCore/Services/ReqMgr/ReqMgr.py", line 113, in getRequestByStatus
    return self._getResult(callname, verb="GET")
  File "/data/srv/wmagent/v1.1.2.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.2.patch2/lib/python2.7/site-packages/WMCore/Services/ReqMgr/ReqMgr.py", line 44, in _getResult
    verb=verb, contentType=contentType)
  File "/data/srv/wmagent/v1.1.2.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.2.patch2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 201, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/wmagent/v1.1.2.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.2.patch2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 309, in getData
    raise he
ServerNotFoundError: Unable to find the server at cmsweb-testbed.cern.ch

2017-05-29 19:47:10,121:139713378219776:INFO:JobSubmitterPoller:Site submission report: {u'T3_CH_Volunteer': Counter({'NoRunningSlot': 1127, 'submitted': 24})}
2017-05-29 19:47:10,121:139713378219776:INFO:JobSubmitterPoller:Priority submission report: {70000.0: Counter({'Total': 1151, 'submitted': 24})}
2017-05-29 19:47:10,121:139713378219776:INFO:JobSubmitterPoller:Have 1 packages to submit.
2017-05-29 19:47:10,121:139713378219776:INFO:JobSubmitterPoller:Have 24 jobs to submit.
2017-05-29 19:47:10,122:139713378219776:INFO:JobSubmitterPoller:Done assigning site locations.
2017-05-29 19:47:10,460:139713378219776:INFO:SimpleCondorPlugin:Done submitting jobs for this cycle in SimpleCondorPlugin
2017-05-29 19:47:10,474:139713378219776:INFO:JobSubmitterPoller:Jobs that succeeded/failed submission: 24/0.
2017-05-29 19:47:10,495:139713378219776:INFO:DashboardReporter:Handling 24 jobs
2017-05-29 19:47:11,316:139713378219776:INFO:JobSubmitterPoller:Transaction cycle successfully completed.
and nothing else
```

**Comment by scarletnorberg** [comment]
vocms0304.cern.ch went down June 9 2017 JobSubmitter down but not reporting to WMStats

**Comment by scarletnorberg** [comment]
cmsgwms-submit2.fnal.gov June15 2017 JobSubmitter down not reporting to WMStats Component JobSubmitter with process id 1350386 is not running

**Comment by ticoann** [comment]
2017-06-15 09:49:52,983:140327621375744:INFO:JobSubmitterPoller:Have 17 packages to submit.
2017-06-15 09:49:52,984:140327621375744:INFO:JobSubmitterPoller:Have 1000 jobs to submit.
2017-06-15 09:49:52,984:140327621375744:INFO:JobSubmitterPoller:Done assigning site locations.

This is the last log before it crashed silently

**Comment by ticoann** [comment]
I am labeling as WMAgent Crash, but closing it. We will reopen if the same error occurs again.
