### ISSUE TITLE
Buggy initialize_clone method

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7909]
I know I wrote this code myself
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/Request.py#L75

but depending on the case it can raise `RuntimeError: dictionary changed size during iteration` :(

An easy fix would be replacing iteritems by items, but then it'll simply postpone this bug for when we migrate to python3.

I decided to make this issue just to draw attention that the same issue might/will happen somewhere else that we do the same dict handling.

BTW, I think it was not caught by the unit tests because I don't have invalid args in the sample dict (and that's why it passed all tests in my VM as well...).

**Comment by amaltaro** [comment]
Following is the traceback
```
amaltaro@vocms049:/data/amaltaro/ReqMgr2_scripts $ python clone.py pdmvserv_task_HIG-PhaseIIFall16LHEGS82-00018__v1_T_170228_170033_676 '{"Task1": {"RequestNumEvents": 10000, "PrepID": "TEST-Task1", "ProcessingVersion": -1}, "Task2": {"PrepID": "TEST-Task2", "KeepOutput": true}, "Task3": {"PrepID": "TEST-Task3"}, "Campaign": "DMWM_Test", "PrepID": "TEST"}'
Cloning request 'pdmvserv_task_HIG-PhaseIIFall16LHEGS82-00018__v1_T_170228_170033_676' with the following override settings: {u'Task1': {u'PrepID': u'TEST-Task1', u'ProcessingVersion': -1, u'RequestNumEvents': 10000}, u'Task2': {u'KeepOutput': True, u'PrepID': u'TEST-Task2'}, u'Task3': {u'PrepID': u'TEST-Task3'}, u'PrepID': u'TEST', u'Campaign': u'DMWM_Test'}
Response status: 400	Response reason: Bad Request
Error message: Invalid spec parameter value: dictionary changed size during iteration

[08/Jun/2017:12:11:27] vocms0131.cern.ch 188.184.135.207 "GET /reqmgr2/data/request?name=amaltaro_TaskChain_Prod_HG1706_Validation_170524_122530_835 HTTP/1.1" 200 OK [data: 3892 in 8672 out 258981 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms040.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[08/Jun/2017:12:11:27]  Error: Traceback (most recent call last):
  File "/data/srv/beHG1706d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.4.pre7/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 179, in validate
    self._validateRequestBase(param, safe, validate_clone_create_args)
  File "/data/srv/beHG1706d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.4.pre7/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 84, in _validateRequestBase
    workload, r_args = valFunc(args, self.config, self.reqmgr_db_service, param)
  File "/data/srv/beHG1706d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.4.pre7/lib/python2.7/site-packages/WMCore/ReqMgr/Utils/Validation.py", line 207, in validate_clone_create_args
    cloned_args = initialize_clone(request_args, originalArgs, createArgs, chainArgs)
  File "/data/srv/beHG1706d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.4.pre7/lib/python2.7/site-packages/WMCore/ReqMgr/DataStructs/Request.py", line 96, in initialize_clone
    for innerKey in topValue:
RuntimeError: dictionary changed size during iteration
```
