### ISSUE TITLE
Execute stage out commands with runCommandWithOutput

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8004]
From #7996, we should execute the stage out commands with runCommandWithOutput instead of the non-output version.

Here is one that keeps only the return code:
```
Traceback (most recent call last):
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 72, in __call__
    executor = StepFactory.getStepExecutor(stepType)
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/WMSpec/Steps/StepFactory.py", line 158, in getStepExecutor
    executor =_ExecutorFactory.loadObject(stepType)
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/WMFactory.py", line 68, in loadObject
    module = __import__(module, globals(), locals(), [classname])
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/StageOut.py", line 18, in <module>
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/Storage/StageOutMgr.py", line 13, in <module>
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/Storage/Backends/__init__.py", line 24, in <module>
  File "/storage/local/data1/condor/execute/dir_2230667/glide_Hx4g9h/execute/dir_2478175/job/WMCore.zip/WMCore/Storage/Backends/RFCPImpl.py", line 13, in <module>
ImportError: cannot import name runCommand
```

**Comment by ticoann** [comment]
Thanks Alan, I will update the code once #7996 is merged (I still need to investigate and fix the unit tests)
