### ISSUE TITLE
JobAccountant crashing with undecoded bytes

### ISSUE THREAD

**Issue by DAMason** [dmwm/WMCore#8056]
Seeing repeat crashes on the JobAccountant on cmssrv237 -- attached (one hopes) is an exerpt of the log and the offending pkl file -- 

[JobAccountant.err.txt](https://github.com/dmwm/WMCore/files/1223271/JobAccountant.err.txt)
[Report.0.pkl.txt](https://github.com/dmwm/WMCore/files/1223273/Report.0.pkl.txt)

Tried removing that file to see if it moved on -- but crashed again...

**Comment by hufnagel** [comment]
@amaltaro @ticoann , is this a known problem ? Copying the relevant error messages from the component log:

2017-08-14 14:43:57,122:140478753007360:ERROR:ChangeState:Error updating job in couch: unsupported operand type(s) for -: 'NoneType' and 'int'

2017-08-14 14:43:57,525:140478753007360:ERROR:ChangeState:A critical error happened! Report it to developers. Error: 'utf8' codec can't decode byte 0x90 in position 400: invalid start byte

**Comment by ticoann** [comment]
I am not sure. I think there were a similar problem before. But whatever it was it should have been fixed. 

According to log Dave posted it seems frwj report doesn't contain stop or/and start time. 

@DAMason, Dave when you removed the Report.0.pkl, what kind of error it gave. The same error in different job. (Somehow I can't access that machine - permission denied)

```
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 181, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 363, in recordInCouch
    updateSummaryDB(self.statsumdatabase, job)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 159, in updateSummaryDB
    sum_doc = fwjr_parser(document)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 74, in fwjr_parser
    wrappedTotalJobTime += val['stop'] - val['start']
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by DAMason** [comment]
user is cmsdataops.

Actually it occurs to me I may have removed the wrong fjr -- it says its going to process 98 jobs, and I took out the last one -- maybe its failing on the first one?  Try logging in -- probably better in more expert hands ;)

**Comment by ticoann** [comment]
It seems fwjr ['stop'] time is None. Not sure how/why that happens, It has the error it might be crashed before it create the stop time?
Anyway, I will investigate more and patch the agent.

**Comment by ticoann** [comment]
That is not the sole error. It seems there is something else causing json encoding fails. I will look at it later in the evening.

```
2017-08-14 16:28:08,067:140455080879872:ERROR:ChangeState:A critical error happened! Report it to developers. Error: 'utf8' codec can't decode byte 0x90 in position 400: invalid start byte
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 181, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 452, in recordInCouch
    self.fwjrdatabase.commit(callback = discardConflictingDocument)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 121, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 149, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 229, in makeRequest_httplib
    encoded_data = self.encode(data)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 563, in encode
    return encoder.encode(thunked)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x90 in position 400: invalid start byte

```

**Comment by ticoann** [comment]
There are 2 problems here. 
1. one is 'stop' time returns None.
2. error message contain "\x90\xf7c failed on write!\nxrdcp-old" which cause json encoding error."\x90"

For the second problem I thought we fixed sometime ago. @amaltaro, Alan don't you remember?
using
```
unicode(some_string, errors='ignore')
```

**Comment by ticoann** [comment]
fix is created #8057 but that is only affect new jobs. So temp fix is created #8058 and applied to cmssrv237. and JobAccount is retarted. I will revert back the patch when jobs go through,

**Comment by ticoann** [comment]
Patch (#8058) is reversed, if there is another case, we can apply that again.

**Comment by amaltaro** [comment]
Error
`TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'`

is sort of common. Though I had the impression Justas fixed it a year ago. In addition to that, that error doesn't crash the component.

About the decode issue, that's new for me and it should have been fixed in
https://github.com/dmwm/WMCore/pull/7298#issuecomment-255377575

... wait, it says we'd re-raise this exception to these components and let them break....

**Comment by DAMason** [comment]
Looks like we done broke it again -- see that it appears to have gone down overnight with the franti running at NERSC

**Comment by ticoann** [comment]
Do you want be to apply patch again? I can leave that patch this time, if you prefer.

**Comment by DAMason** [comment]
I guess that can be up to you -- I can keep making noise whenever this crashes, if it will help identify/fix the underlying problem.

**Comment by ticoann** [comment]
I patched cmssrv237 and restarted agent. I will leave the patch applied this time.

**Comment by amaltaro** [comment]
And this issue strikes again, on vocms0250 now
```
2017-10-31 13:42:03,312:140192483354368:ERROR:DashboardReporter:Output module PREMIXRAWoutput has a file /store/unmerged/RunIISummer16DR80Premix/GGJets_M-60To200_Pt-50_13TeV-sherpa/GEN-SIM-RAW/PUMoriond17_magnetOffBS0T_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/010000/PREMIXRAWoutput.root with incomplete info
2017-10-31 13:42:06,050:140192483354368:ERROR:ChangeState:A critical error happened! Report it to developers. Error: 'utf8' codec can't decode byte 0xd2 in position 46179: invalid continuation byte
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 181, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 452, in recordInCouch
    self.fwjrdatabase.commit(callback = discardConflictingDocument)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 153, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 233, in makeRequest_httplib
    encoded_data = self.encode(data)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 537, in encode
    return encoder.encode(thunked)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd2 in position 46179: invalid continuation byte
2017-10-31 13:42:06,682:140192483354368:ERROR:JobAccountantPoller:Hit general exception in JobAccountantPoller while using worker.

Traceback: 
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py", line 68, in algorithm
    self.accountantWorker(jobsSlice)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 290, in __call__
    self.stateChanger.propagate(self.listOfJobsToFail, "jobfailed", "complete")

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 181, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 452, in recordInCouch
    self.fwjrdatabase.commit(callback = discardConflictingDocument)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 153, in makeRequest
    encoder, decoder, contentType)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 233, in makeRequest_httplib
    encoded_data = self.encode(data)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 537, in encode
    return encoder.encode(thunked)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
```

I'll try to find these problematic files/report before anything. And then I guess we have to apply Seangchan's temp patch.

**Comment by amaltaro** [comment]
I found the problematic FJR file and I placed it here:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_8056/

such that we can cook a proper fix for this issue.

Here's how we can replicate the problem:
```
from WMCore.FwkJobReport.Report import Report

jobReport = Report()
jobReport.load('Report.1.pkl')
jsonFWJR = jobReport.__to_json__(None)
badStr = jsonFWJR["steps"]["stageOut1"]["errors"]

from json import JSONEncoder
from WMCore.Wrappers.JsonWrapper.JSONThunker import JSONThunker
encoder = JSONEncoder()
thunker = JSONThunker()
thunked = thunker.thunk(badStr)
encoder.encode(thunked)
```

for now, I removed this file
/data/srv/wmagent/v1.1.6.patch4/install/wmagent/JobCreator/JobCache/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00271__v1_T_171020_160630_901/TOP-RunIISummer15wmLHEGS-00271_0/TOP-RunIISummer16DR80Premix-00291_0/JobCollection_159640_0/job_1481326/Report.1.pkl

and restarted JobAccountant.
