### ISSUE TITLE
DBSUploader fails to insert block into DBS (vocms0126)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8113]
@yuyiguo could you please have a look at this issue?

I've just noticed vocms0126 is failing to inject this block `/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6` since 2 days ago.

I really see no issues with this block name neither with the metadata sent to DBS, e.g.:
    "processed_ds_name": "RunIIWinter15wmLHE-MCRUN2_71_V1-v2",

The traceback is in [1] and the json dump of the data sent to DBSServer is here [2].

[1]
```
2017-08-31 13:32:00,325:139814527305472:INFO:DBSUploadPoller:About to insert block /W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6
2017-08-31 13:32:00,886:139814851102464:ERROR:DBSUploadPoller:Error trying to process block /W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6 through DBS.
HTTP Error 400: BlockInsert:                   processed_ds_name=acquisition_era_name[-filter_name][-processing_str]-vprocessing_version must be satisified.
2017-08-31 13:32:00,889:139814851102464:ERROR:DBSUploadPoller:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 116, in uploadWorker
    dbsApi.insertBulkBlock(blockDump = block)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/dbs3-client/3.4.4/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 337, in insertBulkBlock
    result =  self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/dbs3-client/3.4.4/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 194, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/dbs3-client/3.4.4/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 400: BlockInsert:                   processed_ds_name=acquisition_era_name[-filter_name][-processing_str]-vprocessing_version must be satisified.

2017-08-31 13:32:00,900:139814527305472:ERROR:DBSUploadPoller:Error found in multiprocess during process of block /W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6
2017-08-31 13:32:00,901:139814527305472:ERROR:DBSUploadPoller:Error trying to process block /W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6 through DBS.
HTTP Error 400: BlockInsert:                   processed_ds_name=acquisition_era_name[-filter_name][-processing_str]-vprocessing_version must be satisified.
```

[2]
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_8113/DBS3Uploader_block.json

**Comment by yuyiguo** [comment]
@amaltaro @ticoann 
There is a big error in the data and DBS caught it. You may want to check how this error happened.
Here is what in the data:
"processed_ds_name": "RunIIWinter15wmLHE-MCRUN2_71_V1-v2", 
 "acquisition_era_name": "RunIIWinter15GenOnly", 
CMS requires: 
processed_ds_name=acquisition_era_name[-filter_name][-processing_str]-vprocessing_version
You can see the acquisition in the given processed ds does not match the given acquisition era.

**Comment by amaltaro** [comment]
Thanks, Yuyi! As we just chatted, Indeed there is an inconsistency in this meta-data and the workflow is actually problematic (issue #8102).

I've just marked that block and its files as closed and in phedex to avoid having the components trying to insert them.

For the record:
```
SQL> select * from dbsbuffer_block where blockname='/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6';

	ID DATASET_ID BLOCKNAME 																														   LOCATION CREATE_TIME STATUS			DELETED
---------- ---------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------- ----------- -------------------- ----------
     17897	 3111 /W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/RunIIWinter15wmLHE-MCRUN2_71_V1-v2/GEN#4c868156-8b36-11e7-9af5-02163e0184a6																	 22  1503845099 Pending 		      0


SQL> select lfn from dbsbuffer_file where BLOCK_ID=17897;

LFN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/569D099D-328B-E711-9EB0-00E081B705C6.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/006E7FDA-318B-E711-AFB6-002590DE6E52.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/C03297D9-318B-E711-9090-002590DE6E52.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/06BFA516-328B-E711-A40A-00259069BCEC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/2812FA5B-328B-E711-B7BC-00E081B705DC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/62C84FD8-338B-E711-B522-D4AE526CD4D9.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/4E3D8BD7-338B-E711-BE46-00259068AD8E.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/70992325-348B-E711-B0D2-D4AE526CE4B0.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/E65176E2-318B-E711-A1F2-0025904B871E.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/02C33AD7-318B-E711-83BC-0025901A9EFC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/663B76E2-318B-E711-B9B8-0025904B871E.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/024B30D7-318B-E711-88F9-0025901A9EFC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/F6BC4CD7-318B-E711-98D6-0025901A9EFC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/FAA023D7-318B-E711-B41B-0025901A9EFC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/045AF518-338B-E711-A621-00E081B705D6.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/8265FFDE-338B-E711-B971-00E081B706B2.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/D6256F28-348B-E711-BF64-00E081B18DBE.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/0C95DCD6-318B-E711-B0E2-0025901A9EFC.root
/store/mc/RunIIWinter15wmLHE/W2jet_WToMuNuJ_powheg_minlo_13TeV_NNPDF31nnlo/GEN/MCRUN2_71_V1-v2/1110000/C67C5DD7-318B-E711-808E-0025901A9EFC.root

19 rows selected.
```
