### ISSUE TITLE
aborting large workflows times out

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8128]
while trying to abort 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_task_EXO-RunIISummer15wmLHEGS-04802__v1_T_170811_181808_305

https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_task_EXO-RunIISummer15wmLHEGS-04800__v1_T_170811_181958_1008

the command takes a while, times out and sends a "server error"

**Comment by amaltaro** [comment]
The first one seems to be hitting the frontend timeout (5min). According to the reqmgr2 logs, there was a (document?) couch conflict [1].

I'm trying to abort both of them, if that doesn't work, then we might need to script it. For the next deployment, I think we should make this operation asynchronous (same for force-complete).

[1]
[06/Sep/2017:13:50:16] vocms0136.cern.ch 131.225.205.13 "GET /reqmgr2/data/request?name=vlimant_ACDC0_Run2016H-v1-SingleElectron-07Aug17_8029_170903_163807_8496 HTTP/1.1" 200 OK [data: 2734 in 5650 out 318309 us ] [auth: OK "/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=Services/CN=wmagent/wmagent.fnal.gov" "" ] [ref: "" "WMCore.Ser
vices.Requests/v001" ]
[06/Sep/2017:13:50:17]  SERVER OTHER ERROR WMCore.Database.CMSCouch.CouchConflictError e368a00b4b787dc0940cad80dd3c0e1c (CouchConflictError - reason: Conflict, data: None result: None)
[06/Sep/2017:13:50:17]    Traceback (most recent call last):
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/REST/Server.py", line 711, in default
[06/Sep/2017:13:50:17]        return self._call(RESTArgs(list(args), kwargs))
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/REST/Server.py", line 787, in _call
[06/Sep/2017:13:50:17]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 477, in put
[06/Sep/2017:13:50:17]        result = self._updateRequest(workload, request_args)
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 462, in _updateRequest
[06/Sep/2017:13:50:17]        report = self._handleOnlyStateTransition(workload, request_args, dn)
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 439, in _handleOnlyStateTransition
[06/Sep/2017:13:50:17]        self.gq_service.cancelWorkflow(workload.name())
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 211, in cancelWorkflow
[06/Sep/2017:13:50:17]        return self.updateElements(*elements, Status='CancelRequested')
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 190, in updateElements
[06/Sep/2017:13:50:17]        self.db.makeRequest(uri=thisuri, type='PUT')
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
[06/Sep/2017:13:50:17]        getattr(e, "reason", None), data)
[06/Sep/2017:13:50:17]      File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/reqmgr2/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 144, in checkForCouchError
[06/Sep/2017:13:50:17]        raise CouchConflictError(reason, data, result)
[06/Sep/2017:13:50:17]    CouchConflictError: CouchConflictError - reason: Conflict, data: None result: None
[06/Sep/2017:13:50:17] vocms0136.cern.ch 128.141.188.116 "PUT /reqmgr2/data/request/mcremone_task_EXO-RunIISummer15wmLHEGS-04802__v1_T_170811_181808_305 HTTP/1.1" 500 Internal Server Error [data: 4948 in 743 out 323452251 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=vlimant/CN=652956/CN=Jean-Roch Vlimant" "" ] [ref: "http
s://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_task_EXO-RunIISummer15wmLHEGS-04802__v1_T_170811_181808_305" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" ]

**Comment by amaltaro** [comment]
Second workflow 
mcremone_task_EXO-RunIISummer15wmLHEGS-04800__v1_T_170811_181958_1008

had been aborted already. It has around 12k wqe docs.

The first one has almost 20k wqe docs.

**Comment by vlimant** [comment]
+1 on asynchroneous, though this will require a new state like "force-abort" or "abort"

**Comment by amaltaro** [comment]
I have a script running right now to mark workqueue elements to CancelRequested for
mcremone_task_EXO-RunIISummer15wmLHEGS-04802__v1_T_170811_181808_305

it's going to take a while though, I'd say it has a rate of 10hz or so. Once that's done, I'll flip that workflow to aborted.

**Comment by amaltaro** [comment]
The other has been aborted as well.

**Comment by ticoann** [comment]
@amaltaro, So the bottleneck here is (WorkQueue) couch db updates?

**Comment by amaltaro** [comment]
Yes, it happens when there are way too many workqueue elements. Same for force-complete that can take several secs or minutes or even timeout.
