### ISSUE TITLE
request in "completed" with 15k jobs pending

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8138]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348
has been toggled down to completed by 
{
      "Status": "acquired", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch", 
      "UpdateTime": 1502994416
    }, 
    {
      "Status": "running-open", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch", 
      "UpdateTime": 1504707187
    }, 
    {
      "Status": "running-closed", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch", 
      "UpdateTime": 1504709809
    }, 
    {
      "Status": "completed", 
      "DN": "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch", 
      "UpdateTime": 1504709810
    }
and still, has 70k CPUs pending

![daily](https://user-images.githubusercontent.com/4989875/30151763-15be6e80-93b1-11e7-8b1c-633e0e36f3a2.png)

**Comment by amaltaro** [comment]
What happened in here...
these were the transitions
```
assignment-approved: 2017-08-17 16:53:27 UTC
assigned: 2017-08-17 18:10:17 UTC
acquired: 2017-08-17 18:26:56 UTC
running-open: 2017-09-06 14:13:07 UTC
running-closed: 2017-09-06 14:56:49 UTC
completed: 2017-09-06 14:56:50 UTC
```
so the running-closed and completed happened right after each other.

==> Now checking the workqueue logs (notice 2h shift, UTC timezone):
```
vocms0140/workqueue/cleanUpTask-20170804.log:2017-09-06 16:08:49,615:ERROR:WorkQueue:Error processing workflow "vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348": 
vocms0140/workqueue/cleanUpTask-20170804.log:2017-09-06 16:23:41,969:INFO:WorkQueue:Canceling work for workflow(s): set([u'vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348'])
vocms0140/workqueue/cleanUpTask-20170804.log:2017-09-06 16:40:00,584:INFO:WorkQueue:Canceling work for workflow(s): set([u'vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348'])
vocms0140/workqueue/cleanUpTask-20170804.log:2017-09-06 16:55:55,055:INFO:WorkQueue:Request vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348 finished ({'Status': 'Canceled', 'PercentSuccess': 0, 'PercentComplete': 6})
```

==> and the ReqMgr log
```
amaltaro@vocms022:/build/srv-logs $ grep vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348 vocms01{36,61,63,65}/reqmgr2/reqmgr2-20170906.log | grep PUT
vocms0163/reqmgr2/reqmgr2-20170906.log:[06/Sep/2017:16:08:43] vocms0163.cern.ch 128.142.143.162 "PUT /reqmgr2/data/request/vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348 HTTP/1.1" 500 Internal Server Error [data: 6488 in 743 out 61745879 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=vlimant/CN=652956/CN=Jean-Roch Vlimant" "" ] [ref: "" "" ]
```

so, global workqueue was trying to cancel those elements while it was still in running-open (16:23:41), it took a couple iterations to cancel all elements.

So, we have to figure out WHY those elements were canceled.

Meanwhile, I'll see how to better cleanup this mess. Likely connecting to every single agent that pulled work and abort everything from there:
agent url: vocms0308.cern.ch,cmsgwms-submit2.fnal.gov,vocms0310.cern.ch,vocms0126.cern.ch,vocms0304.cern.ch

**Comment by vlimant** [comment]
were those cancelled by mistake when trying to abort those big workflows yesterday ?

**Comment by amaltaro** [comment]
Certainly not, my script ran against
`    wf = "mcremone_task_EXO-RunIISummer15wmLHEGS-04802__v1_T_170811_181808_305"`
only

**Comment by amaltaro** [comment]
Ok, jobs for vlimant_task_SMP-RunIISummer15wmLHEGS-00164__v1_T_170817_185312_6348
should have been killed in all agents and local wqe gone.

**Comment by vlimant** [comment]
thanks. it's being rejected in favor of a clone. remains to know what has happened, fingers crossed that it does not spread

**Comment by amaltaro** [comment]
It seems couch was down for a couple of minutes (maybe when Lina was cleaning up aso stuff) and around that time ~4pm I see several errors in the global workqueue logs (different workflow, bug enough to picture it):
```
2017-09-06 16:28:46,659:ERROR:WorkQueue:Error processing workflow "vlimant_task_HIG-RunIISummer15wmLHEGS-01574__v1_T_170818_195012_9533": Can't get policy, no elements or parents
2017-09-06 16:39:13,923:INFO:LogDB:<LogDB(url=https://cmsweb.cern.ch/couchdb/wmstats_logdb, identifier=global_workqueue, agent=1)>
2017-09-06 16:39:21,795:ERROR:WorkQueue:Error deleting wq elements  "CouchNotFoundError - reason: Object Not Found, data: {} result: None": Traceback (most recent call last):
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 980, in performQueueCleanupActions
    self.deleteCompletedWFElements()
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 907, in deleteCompletedWFElements
    return self.backend.deleteWQElementsByWorkflow(deleteRequests)
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueBackend.py", line 588, in deleteWQElementsByWorkflow
    self.db.delete_doc(wf)
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 379, in delete_doc
    doc = self.document(id, rev)
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 303, in document
    return Document(id=id, inputDict=self.get(uri))
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 113, in get
    encode, decode, contentType)
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/beHG1707d/sw/slc6_amd64_gcc493/cms/workqueue/1.1.5.pre5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 140, in checkForCouchError
    raise CouchNotFoundError(reason, data, result)
CouchNotFoundError: CouchNotFoundError - reason: Object Not Found, data: {} result: None
```

**Comment by amaltaro** [comment]
I had a look at the CleanUpTask GQ thread and I can't see any problems with that code.
This workflow would be cancelled only if there was at least one workqueue element in CancelRequested status:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L937

**Comment by amaltaro** [comment]
We have added some extra mechanism to cancel any jobs that shouldn't exist or be submitted when the workflow is not meant to be creating jobs anymore.
I'm not sure it fixes this problem, but since it dates from almost 2 years ago, let me close this issue and we can reopen in case the same problem reoccur.
