### ISSUE TITLE
AgentStatusPoller broken in Tier0 2.0.9

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#8212]
What is the error message trying to tell me ?

2017-10-02 21:42:13,354:140023845025536:INFO:AgentStatusPoller:Getting agent info ...
2017-10-02 21:42:13,777:140023845025536:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: You must include http(s):// in your server's address, ReqMgr2 rest service/data/ doesn't
Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 112, in algorithm
    agentInfo = self.collectAgentInfo()
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 188, in collectAgentInfo
    agentInfo['disk_warning'] = listDiskUsageOverThreshold(self.config, updateDB=True)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 141, in listDiskUsageOverThreshold
    reqMgrAux = ReqMgrAux(config.TaskArchiver.ReqMgr2ServiceURL)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 34, in __init__
    Service.__init__(self, httpDict)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Service.py", line 133, in __init__
    self["requests"] = requests(cfg_dict['endpoint'], cfg_dict)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 526, in __init__
    Requests.__init__(self, url, idict)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 109, in __init__
    check_server_url(self['host'])
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 58, in check_server_url
    raise ValueError(msg)
ValueError: You must include http(s):// in your server's address, ReqMgr2 rest service/data/ doesn't

**Comment by amaltaro** [comment]
I'm not sure which ReqMgr url the T0 agent is supposed to use. But Seangchan will know that.

What I wanted to comment is, please use our WMAgent stable release (1.1.6.patch4). Seangchan is already cooking 3 other patches, so we'll have 1.1.6.patch5 by tomorrow evening.

**Comment by hufnagel** [comment]
We are using 1.1.6.patch4. The rpm was built against 1.1.7.pre3 (no way to specify what I want, it takes the latest and @ticoann updated the spec too quickly). We are overriding all the python code during deployment.

**Comment by amaltaro** [comment]
Hmm, that isn't the best. Is the spec simply pointing to master/HEAD? You should be able to define one specific release in the spec file. It also helps anyone that needs to debug the T0 code.

**Comment by hufnagel** [comment]
I have wmagent as a dependency, which means it picks whatever version is currently defined in wmagent.spec. If someone can give me a way how to override that (without specifying WMCore as a source in the t0.spec and building it myself and including it in the to rpms), I would be using that immediately.

**Comment by hufnagel** [comment]
Ok, I am trying some of that in my personal builds, lets see how it goes...

**Comment by hufnagel** [comment]
Yeah, it doesn't work. Following up in HN.

**Comment by amaltaro** [comment]
Dirk, have a look at the wmarchive spec:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmarchive.spec#L3

it does exactly what you need.

**Comment by hufnagel** [comment]
No, it doesn't. It builds a wmarchive package that includes the WMCore code. I want to build a t0 package that depends on the wmagent package and installs the wmagent package.

**Comment by ticoann** [comment]
Hmm the error looks like a bug. Dirk, was it working before when you test with 1.1.6.patch4?
Anyway, I will create a new patch for that.

**Comment by hufnagel** [comment]
Not sure if this was ever working. It didn't prevent my replays from completing, so this might very well always have been there with the later WMCore versions. Tier0Ops noticed it in their replay and then I checked mine and it was there as well.

**Comment by ticoann** [comment]
Sorry about that I created the patch, #8217, could you apply this patch and run it again you don't have to change tier0 config now. It will take the default value.

**Comment by hufnagel** [comment]
#8217 seems to fix this problem, but then I get the following error (did you change something in the component heartbeat ?):

2017-10-03 02:08:37,302:140548846745344:INFO:AgentStatusPoller:Getting agent info ...
2017-10-03 02:08:37,703:140548846745344:INFO:AgentStatusPoller:CouchDB is running with 2 processes
2017-10-03 02:08:37,704:140548846745344:INFO:AgentStatusPoller:List of agent components down: ['Tier0Feeder']
2017-10-03 02:08:38,615:140548846745344:INFO:AgentStatusPoller:Getting wmbs job info ...
2017-10-03 02:08:38,916:140548846745344:INFO:AgentStatusPoller:WMBS data collected in: 0 secs
2017-10-03 02:08:38,924:140548846745344:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: CouchNotFoundError - reason: Object Not Found, data: {'docs': [{'status': 'down', 'couch_process_warning': 0, 'disk_warning': [], 'agent_team': 'REPLACE_TEAM_NAME', 'down_components': ['Tier0Feeder'], 'timestamp': 1506989318, 'acdc': 'http://localhost:5984/acdcserver/_design/ACDC/collections.html', 'agent': 'WMAgentCommissioning', 'WMBS_INFO': {'wmbsCreatedTypeCount': {}, 'sitePendCountByPrio': {'T2_CH_CERN': {0: 0}, 'T0_CH_CERN': {0: 0}}, 'wmbsCountByState': {}, 'thresholds': {'T2_CH_CERN': {'state': 'Normal', 'running_slots': 0, 'pending_slots': 0}, 'T0_CH_CERN': {'state': 'Normal', 'running_slots': 1600, 'pending_slots': 1600}}, 'total_query_time': 0, 'completeRunJobByStatus': {}, 'wmbsExecutingTypeCount': {}, 'activeRunJobByStatus': {}, 'thresholdsGQ2LQ': {'T2_CH_CERN': 0.0, 'T0_CH_CERN': 1600.0}}, 'down_component_detail': ['Tier0Feeder'], 'drain_mode': False, 'agent_url': 'vocms001.cern.ch', '_id': 'vocms001.cern.ch', 'type': 'agent_info', 'agent_version': '1.1.6.patch4'}]} result: None
Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 128, in algorithm
    self.uploadAgentInfoToCentralWMStats(agentInfo, uploadTime)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 234, in uploadAgentInfoToCentralWMStats
    self.centralWMStatsCouchDB.updateAgentInfo(agentDocs)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsWriter.py", line 140, in updateAgentInfo
    result = self.couchDB.commitOne(agentInfo)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 240, in commitOne
    retval = self.post(uri, data)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/tier0/srv/wmagent/2.0.9/sw/slc6_amd64_gcc493/cms/wmagent/1.1.7.pre3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 140, in checkForCouchError
    raise CouchNotFoundError(reason, data, result)
CouchNotFoundError: CouchNotFoundError - reason: Object Not Found, data: {'docs': [{'status': 'down', 'couch_process_warning': 0, 'disk_warning': [], 'agent_team': 'REPLACE_TEAM_NAME', 'down_components': ['Tier0Feeder'], 'timestamp': 1506989318, 'acdc': 'http://localhost:5984/acdcserver/_design/ACDC/collections.html', 'agent': 'WMAgentCommissioning', 'WMBS_INFO': {'wmbsCreatedTypeCount': {}, 'sitePendCountByPrio': {'T2_CH_CERN': {0: 0}, 'T0_CH_CERN': {0: 0}}, 'wmbsCountByState': {}, 'thresholds': {'T2_CH_CERN': {'state': 'Normal', 'running_slots': 0, 'pending_slots': 0}, 'T0_CH_CERN': {'state': 'Normal', 'running_slots': 1600, 'pending_slots': 1600}}, 'total_query_time': 0, 'completeRunJobByStatus': {}, 'wmbsExecutingTypeCount': {}, 'activeRunJobByStatus': {}, 'thresholdsGQ2LQ': {'T2_CH_CERN': 0.0, 'T0_CH_CERN': 1600.0}}, 'down_component_detail': ['Tier0Feeder'], 'drain_mode': False, 'agent_url': 'vocms001.cern.ch', '_id': 'vocms001.cern.ch', 'type': 'agent_info', 'agent_version': '1.1.6.patch4'}]} result: None

**Comment by hufnagel** [comment]
Tier0Feeder is definitely NOT down.

**Comment by ticoann** [comment]
Dirk, what is following config value?

config.AnalyticsDataCollector.centralWMStatsURL

**Comment by hufnagel** [comment]
I have three of those in the config

config.TaskArchiver.centralWMStatsURL = 'http://admin:couch@localhost:5984/wmstats'
config.AnalyticsDataCollector.centralWMStatsURL = 'http://admin:couch@localhost:5984/wmstats'
config.AgentStatusWatcher.centralWMStatsURL = 'http://admin:couch@localhost:5984/wmstats'

**Comment by hufnagel** [comment]
Which is exactly what's in the secrets file

WMSTATS_URL=http://admin:couch@localhost:5984/wmstats

This is a replay, we do not have a central wmstats instance for that, just the local one.

**Comment by ticoann** [comment]
You should still have different central db as local db fpr the test even if it is using the same db.  ie 
```
http://admin:couch@localhost:5984/wmstats_central
```
But still weird that it cannot find the document. If you restart is do you still get the same error?

**Comment by hufnagel** [comment]
Same error when I restart the AgentStatusWatcher. Seems something is screwed up with my configuration. If you want to take a look:

vocms001:/data/tier0/srv/wmagent/current/config/tier0/config.py

**Comment by ticoann** [comment]
Can I restart AgentStatusWatcher there for debugging?

**Comment by hufnagel** [comment]
Only Couch and AgentStatusWatcher are running right now, feel free to start/stop/restart whatever. Keep the JobSubmitter down if possible though to avoid jobs being run (not the end of the world if they do, but for debugging this issue we don't need them, so I'd rather not run them).

**Comment by ticoann** [comment]
The problem was central WMStats url is pointing to local database but it doesn't exist.
I created the db manually and restarted AgentStatusWatcher. It seems OK now.
We can maybe change config or deploy script for local testing settings to handle this properly.

**Comment by hufnagel** [comment]
Does the deployment assume that the wmstats couch db exists already ? How do you handle this in agent testing ? Are you always using the central wmstats ?

**Comment by ticoann** [comment]
for vm agent testing we set up in separate vm for all other applications reqmgr, workqueue, wmstats.
But I guess that is overkill for Tier0 case. You can also point to cmsweb-testbed wmstats if there is no change in wmstats code in the deployment.

**Comment by hufnagel** [comment]
What happens if two replays publish the exact same workflows to the testbed wmstats instance ? Will likely happen if we have two active replays going on.

**Comment by ticoann** [comment]
Not good. :-) The basic assumption is the workflow names are unique. So it will add up all the data,
However, that is only in central wmstats. local data is intact. If you just set up in local db, you are not really using tier0 wmstats anyway, isn't it?

**Comment by ticoann** [comment]
Anyway, it sounds like we need to set up test specific case to put the central wmstats locally.

**Comment by hufnagel** [comment]
Would that go into the wmagent deploy scripts ? Check if the wmstats db in the secrets files is local and create it if it is ?

**Comment by ticoann** [comment]
I create the patch. It is a little hacky but I think it is simplest
#8226

**Comment by hufnagel** [comment]
With that patch the AgentStatusWatcher works now ! Guess we need both patches in the master branch and also the 1.1.16 branch ?

**Comment by ticoann** [comment]
Yes I will include both.
