### ISSUE TITLE
PhEDExInjectorPoller timing out on a few new agents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8231]
WMStats is reporting errors for both vocms0250 and vocms0251, hearbeat issues like
`Last worker thread heartbeat was 83 min ago`

and actually, this issue is hitting all our agents, but it gets reported only on the new ones.

The timeout comes from the fact that we iterate over datasets and call `injectFilesPhEDExCall`, so one cycle might take a long time.

The error in the component log is for instance
```
2017-10-04 09:40:54,986:139964737386240:INFO:PhEDExInjectorPoller:Starting injectFiles method
2017-10-04 09:40:54,989:139964737386240:INFO:PhEDExInjectorPoller:About to inject 1 files for block /QCD_Pt-1000toInf_MuEnrichedPt5_TuneCP5_13TeV_pythia8/RunIIFall17GS-93X_mc2017_realistic_v3-v1/GEN-SIM#3fedc0a8-a8d7-11e7-884c-02163e01877e
2017-10-04 09:50:55,573:139964737386240:WARNING:Requests:Http request failed, retrying once again..
2017-10-04 10:00:56,931:139964737386240:WARNING:Service:The cachefile /data/srv/wmagent/v1.1.6.patch4/install/wmagent/PhEDExInjector/.wmcore_cache/.wmcore_cache_31961/requests/cmsweb.cern.ch/-4169948280470247288_POST_inject does not exist and the service at https://cmsweb.cern.ch/phedex/datasvc/json/prod/inject raised a SSLError('The read operation timed out',) when accessed
2017-10-04 10:00:56,939:139964737386240:ERROR:PhEDExInjectorPoller:PhEDEx file injection failed with Exception: ('The read operation timed out',)
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py", line 312, in injectFilesPhEDExCall
    injectRes = self.phedex.injectBlocks(location, xmlData)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/PhEDEx/PhEDEx.py", line 76, in injectBlocks
    return self._getResult(callname, args=args, verb="POST")
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/PhEDEx/PhEDEx.py", line 47, in _getResult
    f = self.refreshCache(file, callname, args, verb=verb)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Service.py", line 201, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/wmagent/v1.1.6.patch4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.6.patch4/lib/python2.7/site-packages/WMCore/Services/Service.py", line 309, in getData
    raise he
SSLError: ('The read operation timed out',)
```

and I can't find this block in phedex datasvc
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?block=/QCD_Pt-1000toInf_MuEnrichedPt5_TuneCP5_13TeV_pythia8/RunIIFall17GS-93X_mc2017_realistic_v3-v1/GEN-SIM%233fedc0a8-a8d7-11e7-884c-02163e01877e

Neither I can find something useful in the cmsweb phedex logs.

Last but not least, there are entries like this in the frontend logs:
```
[Wed Oct 04 09:45:55.304294 2017] [proxy_http:error] [pid 22496] (70007)The timeout specified has expired: [client 188.184.86.128:4694] AH01102: error reading status line from remote server vocms0165.cern.ch:7001
[Wed Oct 04 09:45:55.304449 2017] [proxy:error] [pid 22496] [client 188.184.86.128:4694] AH00898: Error reading from remote server returned by /auth/complete/phedex/datasvc/json/prod/inject
```

**Comment by amaltaro** [comment]
File/block has just been injected. Maybe it was some general instabilities on the phedex/cmsweb side(?)
I'll check a few components later today and close this issue if everything is fine.

**Comment by amaltaro** [comment]
18 cmsweb phedex alarms came up in the last hour, so that was it. Closing it

**Comment by vlimant** [comment]
I have had issues with phedex too. I think it is under heavy load, but noone's noticing but us
