### ISSUE TITLE
AgentStatusWatcher failing - sometimes - to update thresholds

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8292]
We should also separate the site state from the slots database updates.

I've just seen this error in one of the agents:
```
2017-11-01 09:46:55,473:139773779375872:WARNING:ResourceControlUpdater:Found slotsCPU thresholds for site T3_US_Omaha which has no state in SSB
2017-11-01 09:46:55,473:139773779375872:WARNING:ResourceControlUpdater:Found slotsCPU thresholds for site T3_US_Colorado which has no state in SSB
2017-11-01 09:46:55,473:139773779375872:WARNING:ResourceControlUpdater:Found slotsIO thresholds for site T3_US_Colorado which has no state in SSB
2017-11-01 09:46:55,474:139773779375872:WARNING:ResourceControlUpdater:Site T2_TH_CUNSTDA does not have thresholds in SSB. Taking no action
2017-11-01 09:46:55,803:139773779375872:ERROR:ResourceControlUpdater:Error occurred, will retry later:
2017-11-01 09:46:55,803:139773779375872:ERROR:ResourceControlUpdater:integer division or modulo by zero
2017-11-01 09:46:55,803:139773779375872:ERROR:ResourceControlUpdater:Trace back: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.4.patch3/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 95, in algorithm
    self.checkSlotsChanges(sitesRC, sitesSSB, self.agentsNumByTeam)
  File "/data/srv/wmagent/v1.1.4.patch3/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 235, in checkSlotsChanges
    sitePending = max(int(CPUBound / agentsCount * self.pendingSlotsSitePercent / 100), minCPUSlots)
ZeroDivisionError: integer division or modulo by zero

2017-11-01 09:46:55,804:139773779375872:INFO:ResourceControlUpdater:Resource control cycle finished updating site state and thresholds.
```

**Comment by amaltaro** [comment]
Looking at the code, I don't think it can happen anymore. There were a few changes in 1.1.6 that got this issue fixed.
