### ISSUE TITLE
Don't crash agent component for some of  Oracle error.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8402]
Component need to be resilient for following errors (Need to send the warning in LogDB though)
```
OperationalError: ORA-03114: not connected to ORACLE
(OperationalError) ORA-03135: connection lost contact
(OperationalError) ORA-03113: end-of-file on communication channel
```

Som examples
```
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in do_close
    dbapi_connection.close()
OperationalError: ORA-03114: not connected to ORACLE

2017-12-30 20:10:56,292:139871493072640:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller object at 0x7f366711c3d0> (OperationalError) ORA-03135: connection lost contact
Process ID: 170015
Session ID: 1941 Serial number: 261

```
```
 <@========== WMException Start ==========@>
Exception Class: StatusPollerException
Message: Unhandled error in statusPoller(OperationalError) ORA-03135: connection lost contact
Process ID: 127944
Session ID: 2739 Serial number: 673
```
```
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.6.patch6/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/data/srv/wmagent/v1.1.6.patch6/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in do_close
    dbapi_connection.close()
OperationalError: ORA-03114: not connected to ORACLE

2017-12-30 20:14:07,723:140342101583616:ERROR:JobCreatorPoller:Failed to execute JobCreator 
(OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 150844
Session ID: 2625 Serial number: 1047
 None None

```

**Comment by ticoann** [comment]
2018-01-12 14:27:52,030:140065516156672:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.AgentStatusWatcher.AgentStatusPoller.AgentStatusPoller object at 0x7f63929c8b90> (OperationalError) ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0
 None None
Backtrace:
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 213, in __call__
    self.sleepThread()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 253, in sleepThread
    self.heartbeatAPI.updateWorkerHeartbeat(self.workerName, "Running")
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Agent/HeartbeatAPI.py", line 63, in updateWorkerHeartbeat
    componentID = self.getComponentID(workerName)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Agent/HeartbeatAPI.py", line 55, in getComponentID
    transaction = self.existingTransaction())
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Agent/Database/MySQL/ExistWorker.py", line 37, in execute
    transaction = transaction)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 134, in processData
    connection = self.connection()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 121, in connection
    return self.engine.connect()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1717, in connect
    return self._connection_cls(self, **kwargs)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 59, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1786, in raw_connection
    return self.pool.unique_connection()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 273, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 630, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 435, in checkout
    dbapi_connection = rec.get_connection()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 518, in get_connection
    self.connection = self.__connect()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 530, in __connect
    connection = self.__pool._creator()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 95, in connect
    connection_invalidated=invalidated
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
    return dialect.connect(*cargs, **cparams)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 376, in connect
    return self.dbapi.connect(*cargs, **cparams)

2018-01-12 14:27:52,030:140065516156672:INFO:BaseWorkerThread:Worker thread <WMComponent.AgentStatusWatcher.AgentStatusPoller.AgentStatusPoller object at 0x7f63929c8b90> terminated

**Comment by ticoann** [comment]
2018-01-12 14:27:23,833:140120038721280:ERROR:pool:Exception closing connection <cx_Oracle.Connection to CMS_WMBS_PROD11@CMSR>
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in do_close
    dbapi_connection.close()
OperationalError: ORA-03114: not connected to ORACLE

2018-01-12 14:27:23,837:140120038721280:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller object at 0x7f70458b53d0> (OperationalError) ORA-03135: connection lost contact
Process ID: 35425
Session ID: 2055 Serial number: 485
 'SELECT component_id FROM wm_workers\n                WHERE component_id = (SELECT id FROM wm_components\n                                   WHERE name = :component_name)\n                AND name = :worker_name\n             ' {'worker_name': 'RetryManagerPoller', 'component_name': 'RetryManager'}
Backtrace:
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 213, in __call__
    self.sleepThread()
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 253, in sleepThread
    self.heartbeatAPI.updateWorkerHeartbeat(self.workerName, "Running")
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Agent/HeartbeatAPI.py", line 63, in updateWorkerHeartbeat
    componentID = self.getComponentID(workerName)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Agent/HeartbeatAPI.py", line 55, in getComponentID
    transaction = self.existingTransaction())
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Agent/Database/MySQL/ExistWorker.py", line 37, in execute
    transaction = transaction)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 179, in processData
    returnCursor=returnCursor)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 65, in executebinds
    resultProxy = connection.execute(s, b)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)

**Comment by ticoann** [comment]
2018-01-12 14:31:15,830:140212895692544:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.JobCreator.JobCreatorPoller.JobCreatorPoller object at 0x7f85dce589d0> <@========== WMException Start ==========@>
Exception Class: JobCreatorException
Message: Failed to execute JobCreator 
(OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 34271
Session ID: 1603 Serial number: 5113
 'SELECT wls.pnn AS pnn, wl.site_name AS psn FROM wmbs_location_pnns wls\n             INNER JOIN wmbs_location wl ON wls.location = wl.id' {}

Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 428, in algorithm
    self.pollSubscriptions()
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 540, in pollSubscriptions
    limit = self.limit)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/SplitterFactory.py", line 34, in __call__
    limit = limit)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/EventAwareLumiBased.py", line 34, in __init__
    super(EventAwareLumiBased, self).__init__(package, subscription, generators, limit)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 56, in __init__
    self.pnn_to_psn = self.daoFactory(classname="Locations.GetPNNtoPSNMapping").execute()
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/WMBS/MySQL/Locations/GetPNNtoPSNMapping.py", line 26, in execute
    results = self.dbi.processData(self.sql, conn = conn, transaction = transaction)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 150, in processData
    returnCursor=returnCursor)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 63, in executebinds
    resultProxy = connection.execute(s)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 34271
Session ID: 1603 Serial number: 5113
 'SELECT wls.pnn AS pnn, wl.site_name AS psn FROM wmbs_location_pnns wls\n             INNER JOIN wmbs_location wl ON wls.location = wl.id' {}

	ModuleName : WMComponent.JobCreator.JobCreatorPoller
	MethodName : algorithm
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py
	ClassName : None
	LineNumber : 448
	ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 428, in algorithm
    self.pollSubscriptions()

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 540, in pollSubscriptions
    limit = self.limit)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/SplitterFactory.py", line 34, in __call__
    limit = limit)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/EventAwareLumiBased.py", line 34, in __init__
    super(EventAwareLumiBased, self).__init__(package, subscription, generators, limit)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 56, in __init__
    self.pnn_to_psn = self.daoFactory(classname="Locations.GetPNNtoPSNMapping").execute()

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/WMBS/MySQL/Locations/GetPNNtoPSNMapping.py", line 26, in execute
    results = self.dbi.processData(self.sql, conn = conn, transaction = transaction)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 150, in processData
    returnCursor=returnCursor)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 63, in executebinds
    resultProxy = connection.execute(s)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)

  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)

<@---------- WMException End ----------@>
Backtrace:
  File "/data/srv/wmagent/v1.1.8.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 211, in __call__
    raise ex

2018-01-12 14:31:15,831:140212895692544:INFO:BaseWorkerThread:Worker thread <WMComponent.JobCreator.JobCreatorPoller.JobCreatorPoller object at 0x7f85dce589d0> terminated
