### ISSUE TITLE
Another unicode encoding failure

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8403]
It is in

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Execute.py#L70

output contains "\x95" which cause encoding error
  
and

'utf8' codec can't decode byte 0xb2 in position 24451

**Comment by amaltaro** [comment]
Seangchan, would you still have the complete traceback for this issue? Since the stdout is loaded in memory, I think we cannot fix it as we did for the condor.* logs

**Comment by ticoann** [comment]
Actually traceback doesn't say exact place I had to add some debugging messages to find out where it fails. Anyway, both error happened in the same place I pointed above. 

Yes, you are right we can't do it the same way since this is in the memory. It will have to be fixed right on that code or as temp patch does. I think right on Execute is better since we don't waist that much resources.

**Comment by amaltaro** [comment]
Sigh... it happened again on the CMS@Home agent (vocms0267), I put the bad job report here for further investigation:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_8403/

traceback is
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 107: invalid start byte
2018-03-13 10:43:16,045:139786948114176:ERROR:JobAccountantPoller:Hit general exception in JobAccountantPoller while using worker.
'utf8' codec can't decode byte 0xc0 in position 107: invalid start byte
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMComponent/JobAccountant/JobAccountantPoller.py", line 71, in algorithm
    self.accountantWorker(jobsSlice)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMComponent/JobAccountant/AccountantWorker.py", line 288, in __call__
    self.stateChanger.propagate(self.listOfJobsToFail, "jobfailed", "complete")
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 181, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 452, in recordInCouch
    self.fwjrdatabase.commit(callback = discardConflictingDocument)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 153, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 233, in makeRequest_httplib
    encoded_data = self.encode(data)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 537, in encode
    return encoder.encode(thunked)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
```

**Comment by ticoann** [comment]
@amaltaro, do you still want to leave this open? Since Brian's uuid4 patch would mostly fix this?

**Comment by amaltaro** [comment]
uuid fixes another issue, not this one :)

**Comment by ticoann** [comment]
Ah, yes you are right. :-)

**Comment by ticoann** [comment]
It seems special character is in the error message. This should be fixed.

2018-03-20 19:59:36,007:140106155919104:ERROR:CMSCouch:{'docs': [{'timestamp': 1521572374, 'archivestatus': 'ready', 'retrycount': 0, 'fwjr': {'task': '/ireid_MonteCarlo_eff2_IDR_CMS_Home_180317_211405_3095/Production', 'PrepID': 'FSQ-ppSpring2014-00007', 'skippedFiles': [], 'Campaign': 'IDR_CMS_Home', 'fallbackFiles': [], 'steps': {'CRITICAL': {'status': 11001, 'logs': {}, 'stop': None, 'site': 'T3_CH_Volunteer', 'input': {}, 'errors': [{'details': "Failed to load JobPackage:/var/lib/condor/execute/dir_8141/job/WMSandbox/JobPackage.pcl\ninvalid load key, **'\xfc'.",** 'type': 'JobPackageError', 'exitCode': 11001}],

**Comment by amaltaro** [comment]
This _wonderful_ issue strikes again on vocms0282. Traceback is:
```
2019-03-19 15:55:19,135:140460613945088:ERROR:DashboardReporter:Output module RAWSIMoutput has a file /store/unmerged/RunIIFall18wmLHEGS/TT_AK8HT650_TuneCP5Down_13TeV-powheg-pythia8/GEN-SIM/102X_upgrade2018_realistic_v11-v1/120022/RAWSIMoutput.root with incomplete info
2019-03-19 15:55:20,160:140460613945088:ERROR:ChangeState:A critical error happened! Report it to developers. Error: 'utf8' codec can't decode byte 0xff in position 349: invalid start byte
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 181, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/JobStateMachine/ChangeState.py", line 454, in recordInCouch
    self.fwjrdatabase.commit(callback = discardConflictingDocument)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 281, in commit
    retval = self.post(uri, data)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 153, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 233, in makeRequest_httplib
    encoded_data = self.encode(data)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 537, in encode
    return encoder.encode(thunked)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 349: invalid start byte
```
