### ISSUE TITLE
JobUpdater crashing with timeout

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8545]
It happened to the CMS@Home agent, we should just skip the cycle (and maybe register it in logdb).

Traceback was
```
2018-04-05 10:50:44,217:140498145695488:WARNING:Requests:Http request failed, retrying once again..
2018-04-05 11:10:44,399:140498145695488:ERROR:JobUpdaterPoller:Caught unexpected exception in JobUpdater: timed out
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 84, in algorithm
    self.synchronizeJobPriority()
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 116, in synchronizeJobPriority
    workflowsToCheck = [x for x in self.workqueue.getAvailableWorkflows()]
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 193, in getAvailableWorkflows
    {'reduce': False, 'stale': 'update_after'})
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 527, in loadView
    (self.name, design, view), encodedOptions)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 117, in get
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 120, in makeRequest
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 153, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 272, in makeRequest_httplib
    response, result = conn.request(uri, method=verb, body=encoded_data, headers=headers)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/py2-httplib2/0.7.1-comp/lib/python2.7/site-packages/httplib2/__init__.py", line 1436, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/py2-httplib2/0.7.1-comp/lib/python2.7/site-packages/httplib2/__init__.py", line 1188, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/py2-httplib2/0.7.1-comp/lib/python2.7/site-packages/httplib2/__init__.py", line 1158, in _conn_request
    response = conn.getresponse()
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/data/srv/wmagent/v1.1.10.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2018-04-05 11:17:10,875:140498145695488:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobUpdater.JobUpdaterPoller.JobUpdaterPoller object at 0x7fc84d6857d0> <@========== WMException Start ==========@>
Exception Class: JobUpdaterException
Message: Caught unexpected exception in JobUpdater: timed out
```

**Comment by amaltaro** [comment]
Since it's on the same component, vocms0250 had this Couch error:
```
2018-04-14 09:23:42,613:139750312437504:INFO:JobUpdaterPoller:Synchronizing priorities with ReqMgr...
2018-04-14 09:24:41,838:139750312437504:ERROR:JobUpdaterPoller:Caught unexpected exception in JobUpdater: CouchError - reason: None, data: {'stale': 'update_after', 'reduce': 'false'} result: None
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 84, in algorithm
    self.synchronizeJobPriority()
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 116, in synchronizeJobPriority
    workflowsToCheck = [x for x in self.workqueue.getAvailableWorkflows()]
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 193, in getAvailableWorkflows
    {'reduce': False, 'stale': 'update_after'})
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 527, in loadView
    (self.name, design, view), encodedOptions)
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 117, in get
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 155, in checkForCouchError
    raise CouchError(reason, data, result, status)
CouchError: CouchError - reason: None, data: {'stale': 'update_after', 'reduce': 'false'} result: None
2018-04-14 09:24:44,009:139750312437504:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.JobUpdater.JobUpdaterPoller.JobUpdaterPoller object at 0x7f1a28660890> <@========== WMException Start ==========@>
Exception Class: JobUpdaterException
Message: Caught unexpected exception in JobUpdater: CouchError - reason: None, data: {'stale': 'update_after', 'reduce': 'false'} result: None

        ModuleName : WMComponent.JobUpdater.JobUpdaterPoller
        MethodName : algorithm
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py
        ClassName : None
        LineNumber : 102
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 84, in algorithm
    self.synchronizeJobPriority()

  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 116, in synchronizeJobPriority
    workflowsToCheck = [x for x in self.workqueue.getAvailableWorkflows()]

  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 193, in getAvailableWorkflows
    {'reduce': False, 'stale': 'update_after'})

  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 527, in loadView
    (self.name, design, view), encodedOptions)

  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 117, in get
    encode, decode, contentType)

  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)

  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 155, in checkForCouchError
    raise CouchError(reason, data, result, status)

<@---------- WMException End ----------@>  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 178, in __call__
    tSpent, results, _ = algorithmWithDBExceptionHandler(parameters)
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/Utils/DecoratorUtils.py", line 22, in wrapper
    return f(*args, **kwargs)
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.1.10.patch5/sw/slc7_amd64_gcc630/cms/wmagent/1.1.10.patch5/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 102, in algorithm
    raise JobUpdaterException(msg)
```

**Comment by ticoann** [comment]
Scarlet reported again this problem on multiple agent again. I check the wq view which causing this problem - elementsDetailByWorkflowAndStatus. Didn't see any reason. (Number of WQ elements are small enough ~1000). 
I think it might be some temporary couch server glitch. Although that doesn't explain many agent has the same problem at the same time.
I will create the patch for retrying in this case.

**Comment by ticoann** [comment]
Doesn't match the time exactly with the JobUpdater error, but below couch error is showing in couch log.
```
[Mon, 30 Apr 2018 16:25:30 GMT] [info] [<0.19736.0>] 127.0.0.1 - - GET /wmagent_jobdump%2Ffwjrs/_design/FWJRDump/_view/errorsByWorkflowName?startkey=%5B%22fabozzi_Run2017C-31Mar2018-v1-IsolatedBunch-31Mar2018_946p1_180417_173814_2469%22%2C+0%2C+0%5D&endkey=%5B%22fabozzi_Run2017C-31Mar2018-v1-IsolatedBunch-31Mar2018_946p1_180417_173814_2469%22%2C+999999999%2C+999999%5D&stale=update_after 200
[Mon, 30 Apr 2018 16:45:20 GMT] [info] [<0.245.0>] OS Process #Port<0.3776> Log :: function raised error: (new TypeError("doc is null", "updates.jobSummaryState", 2)) 
[Mon, 30 Apr 2018 16:45:20 GMT] [error] [<0.18666.0>] OS Process Error <0.245.0> :: {<<"render_error">>,
                                                     <<"function raised error: (new TypeError(\"doc is null\", \"updates.jobSummaryState\", 2)) \nstacktrace: (null,[object Object])@updates.jobSummaryState:2\nrunUpdate(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \"OK\"];},[object Object],[object Array])@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:961\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \"OK\"];},[object Object],[object Array])@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1033\n(\"_design/WMStatsAgent\",[object Array],[object Array])@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1517\n()@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1562\n@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1573\n">>}
[Mon, 30 Apr 2018 16:45:20 GMT] [error] [<0.18666.0>] httpd 500 error response:
 {"error":"render_error","reason":"function raised error: (new TypeError(\"doc is null\", \"updates.jobSummaryState\", 2)) \nstacktrace: (null,[object Object])@updates.jobSummaryState:2\nrunUpdate(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \"OK\"];},[object Object],[object Array])@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:961\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \"OK\"];},[object Object],[object Array])@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1033\n(\"_design/WMStatsAgent\",[object Array],[object Array])@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1517\n()@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1562\n@/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/external/couchdb15/1.6.1-comp/share/couchdb/server/main.js:1573\n"}
[Mon, 30 Apr 2018 17:04:08 GMT] [error] [<0.175.0>] Replicator, request GET to "http://cmst1:*****@localhost:5984/wmagent_summary/_changes?filter=WMStatsAgent%2Frepfilter&feed=continuous&style=all_docs&since=1669821&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 17:04:08 GMT] [error] [<0.232.0>] Replicator, request GET to "http://localhost:5984/workqueue_inbox/_changes?filter=WorkQueue%2FqueueFilter&childUrl=http%3A%2F%2Fvocms0251.cern.ch%3A5984&parentUrl=https%3A%2F%2Fcmsweb.cern.ch%2Fcouchdb%2Fworkqueue&feed=continuous&style=all_docs&since=58098&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 17:04:08 GMT] [error] [<0.212.0>] Replicator, request GET to "https://cmsweb.cern.ch/couchdb/workqueue/_changes?filter=WorkQueue%2FqueueFilter&childUrl=http%3A%2F%2Fvocms0251.cern.ch%3A5984&parentUrl=https%3A%2F%2Fcmsweb.cern.ch%2Fcouchdb%2Fworkqueue&feed=continuous&style=all_docs&since=4940984&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 17:32:58 GMT] [error] [<0.230.0>] Replicator, request GET to "http://localhost:5984/workqueue_inbox/_changes?filter=WorkQueue%2FqueueFilter&childUrl=http%3A%2F%2Fvocms0251.cern.ch%3A5984&parentUrl=https%3A%2F%2Fcmsweb.cern.ch%2Fcouchdb%2Fworkqueue&feed=continuous&style=all_docs&since=58108&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 17:32:58 GMT] [error] [<0.189.0>] Replicator, request GET to "http://cmst1:*****@localhost:5984/wmagent_summary/_changes?filter=WMStatsAgent%2Frepfilter&feed=continuous&style=all_docs&since=1674851&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 18:40:25 GMT] [error] [<0.232.0>] Replicator, request GET to "https://cmsweb.cern.ch/couchdb/workqueue/_changes?filter=WorkQueue%2FqueueFilter&childUrl=http%3A%2F%2Fvocms0251.cern.ch%3A5984&parentUrl=https%3A%2F%2Fcmsweb.cern.ch%2Fcouchdb%2Fworkqueue&feed=continuous&style=all_docs&since=4941221&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 18:40:26 GMT] [error] [<0.192.0>] Replicator, request GET to "http://cmst1:*****@localhost:5984/wmagent_summary/_changes?filter=WMStatsAgent%2Frepfilter&feed=continuous&style=all_docs&since=1675989&heartbeat=10000" failed due to error timeout
[Mon, 30 Apr 2018 18:40:26 GMT] [error] [<0.256.0>] Replicator, request GET to "http://localhost:5984/workqueue_inbox/_changes?filter=WorkQueue%2FqueueFilter&childUrl=http%3A%2F%2Fvocms0251.cern.ch%3A5984&parentUrl=https%3A%2F%2Fcmsweb.cern.ch%2Fcouchdb%2Fworkqueue&feed=continuous&style=all_docs&since=58121&heartbeat=10000" failed due to error timeout
```
