### ISSUE TITLE
Failed to push workqueue couchapps in testbed

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8579]
Every time we need to {re}start couchdb in testbed, it looks at the files under the stagingarea and those are executed to push the couchapps to couch.

It's now failing to import WorkQueueSecrets
```
...
http://localhost:5984/tier0_wmstats/_design/WMStats/index.html
2018-04-23 12:01:55 [INFO] Visit your CouchApp here:
http://localhost:5984/t0_workloadsummary/_design/WorkloadSummary/index.html
Traceback (most recent call last):
  File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/workqueue/1.1.13.pre3/bin/wmagent-couchapp-init", line 288, in <module>
    wmagentConfig = loadConfigurationFile(os.environ["WMAGENT_CONFIG"])
  File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/workqueue/1.1.13.pre3/lib/python2.7/site-packages/WMCore/Configuration.py", line 596, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/tmp/_couchdb/tmpihChlp.py
Due to error:
No module named WorkQueueSecretsTraceback (most recent call last):
  File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/workqueue/1.1.13.pre3/lib/python2.7/site-packages/WMCore/Configuration.py", line 589, in loadConfigurationFile
    modPath[1], modPath[2])
  File "/tmp/_couchdb/tmpihChlp.py", line 37, in <module>
    from WorkQueueSecrets import USER_AMQ, PASS_AMQ, AMQ_TOPIC
ImportError: No module named WorkQueueSecrets
```

PYTHONPATH is correct, so it should be able to find that module. I'm also not able to reproduce it in my VM.

I'm making a deployment patch for it.

**Comment by ticoann** [comment]
Discussed with Alan, 
We will change workqueue deployment (manage script) for pushing couchapp. 
Instead of using wmagent-couchapp-init push the app directly.  (Error is caused by importing config)

**Comment by amaltaro** [comment]
Seangchan, since you already looked at that code, let me reassign this one to you :)

**Comment by amaltaro** [comment]
This one might be easier than I thought...

**Comment by amaltaro** [comment]
We no longer rely on an specific script to push in the WorkQueue couchapps. It's all done through the `couchdb` manage script now, see: https://github.com/dmwm/WMCore/issues/10216

It's going to be deployed to production tomorrow, probably under tag `HG2106g`. Closing this issue.
