### ISSUE TITLE
Fail to load request config in testbed

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8580]
Apparently it's happening to any request created after the last testbed upgrade.
Queries like:
/reqmgr2/config?name=amaltaro_MonteCarlo_eff_HG1805_Validation_180422_144232_6230

return a 500 Internal Server Error.
Logs from the server are:
```
[23/Apr/2018:14:50:50] vocms0731.cern.ch 188.184.93.56 "GET /reqmgr2/data/request?name=amaltaro_ReDigi_LumiMask_Agent1112_Validation_180405_140835_601 HTTP/1.1" 200 OK [data: 3898 in 5916 out 249106 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms040.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
INFO:cherrypy.access:[23/Apr/2018:14:50:50] vocms0731.cern.ch 188.184.93.56 "GET /reqmgr2/data/request?name=amaltaro_ReDigi_LumiMask_Agent1112_Validation_180405_140835_601 HTTP/1.1" 200 OK [data: 3898 in 5916 out 249106 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=wmagent/vocms040.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[23/Apr/2018:14:50:52]  SERVER OTHER ERROR __builtins__.AttributeError 4ca80febad9f7abe7ab2aad88376993a ('dict' object has no attribute 'pythonise_')
INFO:cherrypy.error:[23/Apr/2018:14:50:52]  SERVER OTHER ERROR __builtins__.AttributeError 4ca80febad9f7abe7ab2aad88376993a ('dict' object has no attribute 'pythonise_')
[23/Apr/2018:14:50:52]    Traceback (most recent call last):
INFO:cherrypy.error:[23/Apr/2018:14:50:52]    Traceback (most recent call last):
[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 711, in default
INFO:cherrypy.error:[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 711, in default
[23/Apr/2018:14:50:52]        return self._call(RESTArgs(list(args), kwargs))
INFO:cherrypy.error:[23/Apr/2018:14:50:52]        return self._call(RESTArgs(list(args), kwargs))
[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 787, in _call
INFO:cherrypy.error:[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 787, in _call
[23/Apr/2018:14:50:52]        obj = apiobj['call'](*safe.args, **safe.kwargs)
INFO:cherrypy.error:[23/Apr/2018:14:50:52]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/ReqMgr/Service/RequestAdditionalInfo.py", line 182, in get
INFO:cherrypy.error:[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/ReqMgr/Service/RequestAdditionalInfo.py", line 182, in get
[23/Apr/2018:14:50:52]        return str(helper.data)
INFO:cherrypy.error:[23/Apr/2018:14:50:52]        return str(helper.data)
[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/Configuration.py", line 318, in __str__
INFO:cherrypy.error:[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/Configuration.py", line 318, in __str__
[23/Apr/2018:14:50:52]        for pystring in self.pythonise_():
INFO:cherrypy.error:[23/Apr/2018:14:50:52]        for pystring in self.pythonise_():
[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/Configuration.py", line 236, in pythonise_
INFO:cherrypy.error:[23/Apr/2018:14:50:52]      File "/data/srv/beHG1805b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.13.pre3/lib/python2.7/site-packages/WMCore/Configuration.py", line 236, in pythonise_
[23/Apr/2018:14:50:52]        result.extend(getattr(self, attr).pythonise_(
INFO:cherrypy.error:[23/Apr/2018:14:50:52]        result.extend(getattr(self, attr).pythonise_(
[23/Apr/2018:14:50:52]    AttributeError: 'dict' object has no attribute 'pythonise_'
INFO:cherrypy.error:[23/Apr/2018:14:50:52]    AttributeError: 'dict' object has no attribute 'pythonise_'
[23/Apr/2018:14:50:52] vocms0731.cern.ch 188.184.66.4 "GET /reqmgr2/data/workload_config/amaltaro_MonteCarlo_eff_HG1805_Validation_180422_144232_6230 HTTP/1.1" 500 Internal Server Error [data: 3858 in 743 out 275679 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
```

**Comment by ticoann** [comment]
Sorry Alan, I missed config test. Thanks for fix it.
