### ISSUE TITLE
Fix LogDBBackend error message

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8632]
I've seen this error in a few components. From AgentStatusWatcher
```
2018-05-27 20:35:56,142:140353884305152:INFO:AgentStatusPoller:Getting agent info ...
2018-05-27 20:36:33,738:140353884305152:WARNING:Service:The cachefile /data/srv/wmagent/v1.1.12.patch2/install/wmagent/AgentStatusWatcher/.wmcore_cache/.wmcore_cache_31961/requests/cmsweb.cern.ch/15744094587142094_GET_wmagentconfig_vocms0257.cern.ch does not exist and the service at https://cmsweb.cern.ch/reqmgr2/data/wmagentconfig/vocms0257.cern.ch is unavai
lable - it returned 503 because Service Unavailable
 with result: Unable to find the server at cmsweb.cern.ch

2018-05-27 20:36:33,770:140353884305152:ERROR:GenericDataCache:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMCore/Cache/GenericDataCache.py", line 37, in getData
    self.data = self.func(**self.kwargs)
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 49, in _getResult
    verb=verb, contentType=contentType)
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 201, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 309, in getData
    raise he
HTTPException

2018-05-27 20:36:33,771:140353884305152:WARNING:ReqMgrAux:agent config is not correct: {}
2018-05-27 20:36:33,771:140353884305152:ERROR:AgentStatusPoller:Error occurred, will retry later.
Details: 'DiskUseThreshold'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 113, in algorithm
    agentInfo = self.collectAgentInfo()
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/AgentStatusPoller.py", line 189, in collectAgentInfo
    agentInfo['disk_warning'] = listDiskUsageOverThreshold(self.config, updateDB=True)
  File "/data/srv/wmagent/v1.1.12.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.12.patch2/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 223, in listDiskUsageOverThreshold
    diskUseThreshold = agentConfig["DiskUseThreshold"]
KeyError: 'DiskUseThreshold'
2018-05-27 20:36:33,797:140353884305152:INFO:BaseWorkerThread:AgentStatusPoller took 37.655 secs to execute
```

**Comment by ticoann** [comment]
@amaltaro, Is this still the problem?
