### ISSUE TITLE
Global workqueue crashing to process a document - 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8719]
This is happening now in cmsweb production. Error message in wmstats is:
```
Traceback (most recent call last):
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/REST/CherryPyPeriodicTask.py", line 91, in run
    self.taskFunc(self.config)
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/GlobalWorkQueue/CherryPyThreads/LocationUpdateTask.py", line 24, in updateDataLocation
    globalQ.updateLocationInfo()
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 719, in updateLocationInfo
    result = self.dataLocationMapper()
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/DataLocationMapper.py", line 201, in __call__
    elements = self.backend.getElementsForData(data)
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueBackend.py", line 442, in getElementsForData
    elements = self.db.loadView('WorkQueue', 'elementsByData', {'key': data, 'include_docs': True})
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 527, in loadView
    (self.name, design, view), encodedOptions)
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 117, in get
    encode, decode, contentType)
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 123, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/beHG1807d/sw/slc7_amd64_gcc630/cms/workqueue/1.1.14.pre4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 148, in checkForCouchError
    raise CouchInternalServerError(reason, data, result)
CouchInternalServerError: CouchInternalServerError - reason: Internal Server Error, data: {'key': '"/ttH_M125_mtop1735_TuneCP5_13TeV-powheg-pythia8/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM#c4761ce4-39fa-11e8-8c33-02163e01877e"', 'include_docs': 'true'} result: None
```

**Comment by amaltaro** [comment]
It was just a glitch fetching information for that dataset, I can run exactly the same query multiple times without any issues:
```
    globalWQBackend = WorkQueueBackend(config.WorkloadSummary.couchurl, db_name="workqueue")
    data = "/ttH_M125_mtop1735_TuneCP5_13TeV-powheg-pythia8/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM#c4761ce4-39fa-11e8-8c33-02163e01877e"
    elements = globalWQBackend.db.loadView('WorkQueue', 'elementsByData', {'key': data, 'include_docs': True})
```

Looking at the log in vocms0740, it's updating dataset locations very very slowly, but it's moving..

It's certainly related to the amount of Available GQE, which jumped from 42k to 160k elements within the last 24h. Which seem to be coming all from this workflow
sagarwal_task_SUS-PhaseIISummer17wmLHEGENOnly-00061__v1_T_180727_155350_705

well, it has 50k workqueue elements.

**Comment by amaltaro** [comment]
Let's wait until November and close it if the same issue doesn;t pop up again.
