### ISSUE TITLE
AnalyticsDataCollector failing to query byAgentURL couch view

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8877]
This problem can be seen in the new agent 1.1.18.pre4 . This is the traceback with a couple of debugging added by me
```
2018-10-29 18:08:19,031:140292110464768:INFO:AnalyticsPoller:AMR agent_url: vocms0262.cern.ch
2018-10-29 18:08:19,031:140292110464768:INFO:CMSCouch:AMR uri /wmstats/_design/WMStats/_view/byAgentURL?reduce=false and keys ['vocms0262.cern.ch']
2018-10-29 18:08:19,076:140292110464768:INFO:CMSCouch:AMR message: , reason: Object Not Found, result: {"error":"not_found","reason":"missing_named_view"}
, status: 404
2018-10-29 18:08:19,078:140292110464768:ERROR:AnalyticsPoller:Error occurred, will retry later: CouchNotFoundError - reason: Object Not Found, data: {'keys': ['vocms0262.cern.ch']} result: None
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.18.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.pre4/lib/python2.7/site-packages/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py", line 142, in algorithm
    existingDocs = self.centralWMStatsCouchDB.getAllAgentRequestRevByID(self.agentInfo["agent_url"])
  File "/data/srv/wmagent/v1.1.18.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.pre4/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsReader.py", line 419, in getAllAgentRequestRevByID
    results = self.couchDB.loadView(self.couchapp, "byAgentURL", options=options, keys=[agentURL])
  File "/data/srv/wmagent/v1.1.18.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.pre4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 523, in loadView
    retval = self.post(uri, {'keys': keys})
  File "/data/srv/wmagent/v1.1.18.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.pre4/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 125, in post
    encode, decode, contentType)
  File "/data/srv/wmagent/v1.1.18.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.pre4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 124, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/wmagent/v1.1.18.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.pre4/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 141, in checkForCouchError
    raise CouchNotFoundError(reason, data, result)
CouchNotFoundError: CouchNotFoundError - reason: Object Not Found, data: {'keys': ['vocms0262.cern.ch']} result: None
```

so it seems to be failing to find that view `missing_named_view`.

I compared this WMStatsErl view to other erlang views (like allWorkflows) and everything seems Ok...

**Comment by ticoann** [comment]
@amaltaro, Alan, can you see the view directly from couch db in your vm?

**Comment by ticoann** [comment]
Sorry Alan, it is my mistake. Below should be added in deployment

https://github.com/dmwm/deployment/pull/687

**Comment by amaltaro** [comment]
I get 0 rows in the output of my VM
https://alancc7-cloud1.cern.ch/couchdb/wmstats/_design/WMStatsErl/_view/byAgentURL?keys=[%22vocms0262.cern.ch%22]

however it works fine in testbed:
https://cmsweb-testbed.cern.ch/couchdb/wmstats/_design/WMStatsErl/_view/byAgentURL?keys=[%22cmsgwms-submit2.fnal.gov%22]

**Comment by amaltaro** [comment]
I don't see any improvements with that deployment changes. I applied it to my VM, restarted all services (including httpd) and the error persists in the component logs.

**Comment by ticoann** [comment]
Hi Alan, you might have to redeploy frontend. I don't think it take effect with config update. It must copy that config in real apache configuration file.
