### ISSUE TITLE
Bad ReqMgr2 spec parameter type error message

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8897]
Sharad tried to clone a workflow and got an error, which fell into my hands as a error message like:
```
    <body>
        <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: int() argument must be a string or a number, not 'NoneType'</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
```

which clearly doesn't help much :-) We should add the parameter name into this error message

**Comment by justinasr** [comment]
Hello,
PdmV would also be very grateful if the error message would give some hints on what we do wrong. This morning alone we got this
```
<p>Invalid spec parameter value: int() argument must be a string or a number, not \'NoneType\'</p>
```
five times when submitting ~48 RelVals :( Not to mention that this occasionally pops up when submitting Data or MC.

**Comment by amaltaro** [comment]
Hi @justinasr , I might be able to get it from the logs, but in case you have the exact dictionary posted to ReqMgr2, could you please share it?

**Comment by justinasr** [comment]
No, unfortunately I don't have the _exact_ dictionary that failed (it is not logged on failure), I can only give you _supposedly identical_ one, i.e. same code builds a dict using same data from DB. Would that work? I can also add logging and wait for the next occurrence.
We always "fix" this by just retrying - it never fails twice, so even the exact dictionary might not be sufficient to reproduce this.

**Comment by amaltaro** [comment]
> We always "fix" this by just retrying - it never fails twice, so even the exact dictionary might not be sufficient to reproduce this.

Hmm, that's not very encouraging :-(

I found some useful information in the logs and the traceback is very much unexpected. I don't see why `ProcessingVersion` would be `None`...
For future reference, once I (or someone else) starts investigating this issue, here is the reqmgr2 log around that error:
```
[18/Feb/2021:08:25:03]  Updating request "None" with these user-provided args: {u'Group': u'PPD', u'Requestor': u'pdmvserv', u'ProcessingString': u'113X_mcRun4_realistic_v3_2026D49noPU', u'Multicore': 1, 
u'SizePerEvent': 1.0, u'Memory': 3000, u'PrepID': u'CMSSW_11_3_0_pre3_G4VECGEOM__UPSG_Std_2026D49noPU-MinBias_14TeV-00001', u'DQMUploadUrl': u'https://cmsweb.cern.ch/dqm/relval', u'Task1': {u'KeepOutput':
 True, u'Campaign': u'CMSSW_11_3_0_pre3_G4VECGEOM__UPSG_Std_2026D49noPU-1613632162', u'GlobalTag': u'113X_mcRun4_realistic_v3', u'Seeding': u'AutomaticSeeding', u'SplittingAlgo': u'EventBased', u'Processi
ngString': u'113X_mcRun4_realistic_v3_2026D49noPU', u'ScramArch': u'slc7_amd64_gcc900', u'RequestNumEvents': 90000, u'ConfigCacheID': u'5588c9b190957287619aa60c3721dee1', u'Memory': 12000, u'Multicore': 8
, u'TaskName': u'GenSimFull', u'AcquisitionEra': u'CMSSW_11_3_0_pre3_G4VECGEOM', u'PrimaryDataset': u'RelValMinBias_14TeV', u'EventsPerJob': 100, u'EventsPerLumi': 100, u'CMSSWVersion': u'CMSSW_11_3_0_pre
3_G4VECGEOM'}, u'Task2': {u'KeepOutput': True, u'GlobalTag': u'113X_mcRun4_realistic_v3', u'InputFromOutputModule': u'FEVTDEBUGoutput', u'Memory': 12000, u'ProcessingString': u'113X_mcRun4_realistic_v3_20
26D49noPU', u'SplittingAlgo': u'LumiBased', u'InputTask': u'GenSimFull', u'ScramArch': u'slc7_amd64_gcc900', u'ConfigCacheID': u'5588c9b190957287619aa60c3721ee9d', u'LumisPerJob': 10, u'Multicore': 8, u'T
askName': u'DigiTrigger_2026D49', u'AcquisitionEra': u'CMSSW_11_3_0_pre3_G4VECGEOM', u'Campaign': u'CMSSW_11_3_0_pre3_G4VECGEOM__UPSG_Std_2026D49noPU-1613632162', u'CMSSWVersion': u'CMSSW_11_3_0_pre3_G4VECGEOM'}, u'SubRequestType': u'RelVal', u'RequestType': u'TaskChain', u'TimePerEvent': 1.0, u'AcquisitionEra': u'CMSSW_11_3_0_pre3_G4VECGEOM', u'CMSSWVersion': u'CMSSW_11_3_0_pre3_G4VECGEOM', u'EnableHarvesting': True, u'RequestPriority': 500000, u'ProcessingVersion': 1, u'Task3': {u'KeepOutput': True, u'GlobalTag': u'113X_mcRun4_realistic_v3', u'InputFromOutputModule': u'FEVTDEBUGHLToutput', u'Memory': 12
000, u'ProcessingString': u'113X_mcRun4_realistic_v3_2026D49noPU', u'SplittingAlgo': u'LumiBased', u'InputTask': u'DigiTrigger_2026D49', u'ScramArch': u'slc7_amd64_gcc900', u'ConfigCacheID': u'5588c9b1909
57287619aa60c37221fc4', u'LumisPerJob': 10, u'Multicore': 8, u'TaskName': u'RecoGlobal_2026D49', u'AcquisitionEra': u'CMSSW_11_3_0_pre3_G4VECGEOM', u'Campaign': u'CMSSW_11_3_0_pre3_G4VECGEOM__UPSG_Std_202
6D49noPU-1613632162', u'CMSSWVersion': u'CMSSW_11_3_0_pre3_G4VECGEOM'}, u'DQMConfigCacheID': u'5588c9b190957287619aa60c372241da', u'RequestString': u'RVCMSSW_11_3_0_pre3_G4VECGEOMMinBias_14TeV__2026D49noP
U', u'CouchURL': u'https://cmsweb.cern.ch/couchdb', u'GlobalTag': u'113X_mcRun4_realistic_v3', u'Campaign': u'CMSSW_11_3_0_pre3_G4VECGEOM__UPSG_Std_2026D49noPU-1613632162', u'DbsUrl': u'https://cmsweb.cer
n.ch/dbs/prod/global/DBSReader', u'ScramArch': u'slc7_amd64_gcc900', u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb', u'TaskChain': 3}
...
[18/Feb/2021:08:25:04]  Error: Traceback (most recent call last):
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 194, in validate
    self._validateRequestBase(param, safe, validate_request_create_args)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 89, in _validateRequestBase
    workload, r_args = valFunc(args, self.config, self.reqmgr_db_service, param)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Utils/Validation.py", line 113, in validate_request_create_args
    request_args)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 916, in factoryWorkloadConstruction
    workload = self.__call__(workloadName=workloadName, arguments=arguments)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/TaskChain.py", line 278, in __call__
    self.setupTask(task, taskConf)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/TaskChain.py", line 152, in __call__
    self.func(self.obj, task, taskConf)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/TaskChain.py", line 503, in setupTask
    taskConf=taskConf)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 396, in setupProcessingTask
    procTask.setProcessingVersion(procVer)
  File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMTask.py", line 1329, in setProcessingVersion
    self.data.parameters.processingVersion = int(taskProcVer)
TypeError: int() argument must be a string or a number, not 'NoneType'

[18/Feb/2021:08:25:04]  SERVER REST ERROR WMCore.ReqMgr.DataStructs.RequestError.InvalidSpecParameterValue 0d0b7c0cfa5ae43a4019300f65d399f2 (Invalid spec parameter value: int() argument must be a string or a number, not 'NoneType')
[18/Feb/2021:08:25:04]    Traceback (most recent call last):
[18/Feb/2021:08:25:04]      File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 726, in default
[18/Feb/2021:08:25:04]        return self._call(RESTArgs(list(args), kwargs))
[18/Feb/2021:08:25:04]      File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 803, in _call
[18/Feb/2021:08:25:04]        v(apiobj, request.method, api, param, safe)
[18/Feb/2021:08:25:04]      File "/data/srv/HG2102e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.4.5.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 208, in validate
[18/Feb/2021:08:25:04]        raise InvalidSpecParameterValue(msg)
[18/Feb/2021:08:25:04]    InvalidSpecParameterValue: InvalidSpecParameterValue 0d0b7c0cfa5ae43a4019300f65d399f2 [HTTP 400, APP 1102, MSG "Invalid spec parameter value: int() argument must be a string or a number, not 'NoneType'", INFO None, ERR None]
[18/Feb/2021:08:25:04] reqmgr2-68dbcbbf74-g8sn8 188.185.88.214 "POST /reqmgr2/data/request HTTP/1.1" 400 Bad Request [data: 3735 in 799 out 881188 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=pdmvserv/CN=821111/CN=Robot: PdmV Service" "" ] [ref: "" "" ]
```

**Comment by justinasr** [comment]
I looked around the functions that are in the traceback and indeed don't see why it would _sometimes_ have `None`.
Only one guess/observation (mandatory "I'm not an expert, but...", "As far as I understand", etc.), don't hesitate to ignore:

Method `setupProcessingTask` in `StdBase.py` has a line `procVer = taskConf.get("ProcessingVersion") or self.processingVersion`, so the `or` should protect from `None` in `taskConf` and use `self.processingVersion` where `self` is the whole TaskChain (?). This part looks ok and I would wonder why `self.processingVersion` is `None`.

When TaskChain is creating and setting up tasks, `setupTask` method is wrapped in `ParameterStorage` decorator that does some _things_ with TaskChain's attributes, one of them being `processingVersion`, i.e. `self.processingVersion` (processing version of the whole TaskChain?). I am still clueless and not pointing any fingers, but I would maybe look at what exactly is happening when TaskChain's _parameters_ are _stored_, _altered_, _restored_ and _reset_.
