### ISSUE TITLE
ReqMgr2 fails to import STATES from WorkQueueElement

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8930]
Lina reported that ReqMgr2 crashes in testbed and this is here is the traceback
```
[29/Nov/2018:11:29:47]  WATCHDOG: server exited with exit code 0
[29/Nov/2018:11:55:57]  WATCHDOG: starting server daemon (pid 3770)
[29/Nov/2018:11:55:57]  INFO: instantiating extension statusChangeTasks
[29/Nov/2018:11:56:00]  ERROR: terminating due to error, error trace follows
[29/Nov/2018:11:56:00]  ERROR:   Traceback (most recent call last):
[29/Nov/2018:11:56:00]  ERROR:     File "/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/REST/Main.py", line 415, in start_daemon
[29/Nov/2018:11:56:00]  ERROR:       self.run()
[29/Nov/2018:11:56:00]  ERROR:     File "/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/REST/Main.py", line 472, in run
[29/Nov/2018:11:56:00]  ERROR:       self.install_application()
[29/Nov/2018:11:56:00]  ERROR:     File "/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/REST/Main.py", line 250, in install_application
[29/Nov/2018:11:56:00]  ERROR:       module = __import__(module_name, globals(), locals(), [class_name])
[29/Nov/2018:11:56:00]  ERROR:     File "/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py", line 10, in <module>
[29/Nov/2018:11:56:00]  ERROR:       from WMCore.Services.WorkQueue.WorkQueue import WorkQueue
[29/Nov/2018:11:56:00]  ERROR:     File "/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 5, in <module>
[29/Nov/2018:11:56:00]  ERROR:       from WMCore.WorkQueue.DataStructs.WorkQueueElement import STATES
[29/Nov/2018:11:56:00]  ERROR:   ImportError: No module named WorkQueue.DataStructs.WorkQueueElement
[29/Nov/2018:11:56:00]  WATCHDOG: server exited with exit code 1
```

This bug was introduced with #8923, even though I made the necessary changes to the setup_dependencies script, I think...

**Comment by amaltaro** [comment]
Interesting, we do have this module under reqmgr2 area:
```
[cmsweb@vocms0731 current]$ ls /data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/WorkQueue/DataStructs/WorkQueueElement.py
/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/WorkQueue/DataStructs/WorkQueueElement.py
```

and I do see it in the sys.path / PYTHONPATH
```
>>> pprint(sys.path)
['',
 '/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/xlib/python2.7/site-packages',
 '/data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages',
```

I think the reason it cannot be imported is that we do NOT have a `__init__.py` file under WorkQueue, so it does not know DataStructs is/has a python package.
```
[cmsweb@vocms0731 current]$ ls /data/srv/beHG1812b/sw/slc7_amd64_gcc630/cms/reqmgr2/1.1.19.pre2/lib/python2.7/site-packages/WMCore/WorkQueue/
DataStructs
[cmsweb@vocms0731 current]$ 
```
