### ISSUE TITLE
Internal Server Error in wmstatsserver filtered requests 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8936]
Just found it in cmsweb-testbed with this query:
https://cmsweb-testbed.cern.ch/wmstatsserver/data/filtered_requests?IncludeParents=True&mask=Campaign

which according to the reqmon logs, this is the traceback:
```
[03/Dec/2018:09:50:12] vocms0132.cern.ch 127.0.0.1 "GET /wmstatsserver/data/info HTTP/1.1" 200 OK [data: 343 in 40 out 544 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
[03/Dec/2018:09:50:41]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 81f89bb4b98552c97eb4f9c87abcda3b (Execution error)
[03/Dec/2018:09:50:41]    Traceback (most recent call last):
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/REST/Format.py", line 289, in stream_chunked
[03/Dec/2018:09:50:41]        for obj in stream:
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2367, in rows
[03/Dec/2018:09:50:41]        for row in cursor:
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/WMStats/DataStructs/DataCache.py", line 68, in filterDataByRequest
[03/Dec/2018:09:50:41]        if reqInfo.andFilterCheck(filterDict):
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/ReqMgr/DataStructs/Request.py", line 254, in andFilterCheck
[03/Dec/2018:09:50:41]        if not set(reqValue).intersection(set(value)):
[03/Dec/2018:09:50:41]    TypeError: 'bool' object is not iterable
[03/Dec/2018:09:50:41]  SERVER HTTP ERROR cherrypy._cperror.HTTPError 6cca9ca617c0246bfd21d329469b9e5a ((500, 'Execution error'))
[03/Dec/2018:09:50:41]    Traceback (most recent call last):
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 711, in default
[03/Dec/2018:09:50:41]        return self._call(RESTArgs(list(args), kwargs))
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 822, in _call
[03/Dec/2018:09:50:41]        return stream_maybe_etag(apiobj.get('etag_limit', self.etag_limit), etagger, reply)
[03/Dec/2018:09:50:41]      File "/data/srv/beHG1812c/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre3/lib/python2.7/site-packages/WMCore/REST/Format.py", line 590, in stream_maybe_etag
[03/Dec/2018:09:50:41]        raise cherrypy.HTTPError(int(err), message)
[03/Dec/2018:09:50:41]    HTTPError: (500, 'Execution error')
[03/Dec/2018:09:50:41] vocms0132.cern.ch 194.12.153.215 "GET /wmstatsserver/data/filtered_requests?IncludeParents=True&mask=IncludeParents HTTP/1.1" 500 Internal Server Error [data: 5110 in 746 out 1330866 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues" "" ] [ref: "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" ]
```

**Comment by amaltaro** [comment]
@ticoann Seangchan, bad news, we hit the same problem in testbed, just a bit lower in the if statements :-( Traceback from testbed is:
```
[05/Dec/2018:13:28:24]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 837e596dc1de7ca90d67b5f2a6a4a1cc (Execution error)
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2367, in rows
[05/Dec/2018:13:28:24]    Traceback (most recent call last):
[05/Dec/2018:13:28:24]        for row in cursor:
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/REST/Format.py", line 289, in stream_chunked
[05/Dec/2018:13:28:24]        for obj in stream:
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2367, in rows
[05/Dec/2018:13:28:24]        for row in cursor:
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/WMStats/DataStructs/DataCache.py", line 68, in filterDataByRequest
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/WMStats/DataStructs/DataCache.py", line 68, in filterDataByRequest
[05/Dec/2018:13:28:24]        if reqInfo.andFilterCheck(filterDict):
[05/Dec/2018:13:28:24]        if reqInfo.andFilterCheck(filterDict):
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/DataStructs/Request.py", line 260, in andFilterCheck
[05/Dec/2018:13:28:24]      File "/data/srv/beHG1812d/sw/slc7_amd64_gcc630/cms/reqmon/1.1.19.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/DataStructs/Request.py", line 260, in andFilterCheck
[05/Dec/2018:13:28:24]        elif reqValue not in value:
[05/Dec/2018:13:28:24]    TypeError: argument of type 'bool' is not iterable
```

Could you please have a look at it? I already ping'ed Lina @h4d4 that we have something to fix.
The same query as above should hit this bug. I wonder why it wasn't caught by the unit tests...

**Comment by ticoann** [comment]
Thanks Alan, I will update the patch
