### ISSUE TITLE
Inconsistencies between TMDB/DBS while filling the pileup json config

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8993]
I saw WorkQueueManager failing to process the pileup dataset (which creates the json file) and the reason is that we use first DBS in order to fetch dataset/block/file information, then we use PhEDEx to find block subscriptions:
```
2019-02-04 17:20:44,573:140045524363008:ERROR:WMBSHelper:Failed to create subscription. Error: u'/Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW#b94a8445-24e6-4525-9016-21ffca4c3f8a'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 408, in createSubscriptionAndAddFiles
    sub = self.createSubscription(self.topLevelTask, self.topLevelFileset)
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 257, in createSubscription
    sub = self._createSubscriptionsInWMBS(task, fileset, alternativeFilesetClose)
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 272, in _createSubscriptionsInWMBS
    self.createSandbox()
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WMBSHelper.py", line 208, in createSandbox
    sandboxCreator.makeSandbox(self.cachepath, self.wmSpec)
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WMRuntime/SandboxCreator.py", line 131, in makeSandbox
    fetcher(task)
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 200, in __call__
    self._createPileupConfigFile(helper)
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 178, in _createPileupConfigFile
    configDict = self._queryDbsAndGetPileupConfig(helper, dbsReader)
  File "/data/srv/wmagent/v1.1.20.pre4/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.pre4/lib/python2.7/site-packages/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py", line 76, in _queryDbsAndGetPileupConfig
    blockDict[block]['PhEDExNodeNames'] = list(nodes)
KeyError: u'/Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW#b94a8445-24e6-4525-9016-21ffca4c3f8a'
```

**Comment by jenimal** [comment]
any chance this is related to the ongoing issues with heartbeat issues for WorkqueueManager?
agent: cmsgwms-submit3.fnal.gov (1.1.18.patch2)
agent last updated: 2019/2/4 (Mon) 17:36:26 UTC : 0 h 6 m
data last updated: 0 h 7 m
status: Components or Thread down;
team: production
component errors for: WorkQueueManager
WorkQueueManager
worker thread: WorkQueueManagerCleaner
status: Timeout
last updated: 2019/2/4 (Mon) 14:44:42 UTC
pid: 3272228
error message:
Last worker thread heartbeat was 169 min ago

**Comment by amaltaro** [comment]
Nope, but we already have an issue for that specific component/thread:
https://github.com/dmwm/WMCore/issues/8477
