### ISSUE TITLE
New release eventually failing LogCollect jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9018]
Still to be investigated, but the new release 1.1.20.patch2 fails a LogCollect job here and there. For instance, for this Integration template: ReReco_Parents.json, e.g.:
amaltaro_ReReco_Parents_Agent1120_Validation_190212_153958_8632

and the error is the following:
```
2019-02-12 15:49:04,460:INFO:LogCollect:Using edmCopyUtil: True
2019-02-12 15:49:04,461:INFO:LogCollect:Running scram
2019-02-12 15:49:06,581:INFO:LogCollect:Running edmCopyUtil
2019-02-12 15:49:06,582:INFO:Scram:Creating a subprocess to run the PSet setup.
2019-02-12 15:49:06,582:INFO:Scram:Also recording SCRAM command-line related output.
2019-02-12 15:49:06,588:INFO:Scram:    Invoking command: env X509_USER_PROXY=/srv/myproxy.pem edmCopyUtil /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-5-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-276-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-36-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-277-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-205-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-126-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-38-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-42-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-41-0-logArchive.tar.gz /store/unmerged/logs/prod/2019/2/12/amaltaro_TaskChain_RelVal_Multicore_Agent1120_Validation_190212_154013_9384/HLTD/0000/0/e58c3fec-8142-4db0-9618-acf90d3239ed-104-0-logArchive.tar.gz /srv/job/WMTaskSpace/logCollect1
2019-02-12 15:49:06,700:INFO:Scram:Subprocess stdout was:
env: edmCopyUtil: No such file or directory

2019-02-12 15:49:06,700:INFO:Scram:Subprocess stderr was:
None
2019-02-12 15:49:06,700:ERROR:LogCollect:Unable to copy logArchives to local disk
```

which gets masked by this error in WMStats
```
2019-02-12 15:49:06,701:ERROR:ExecuteMaster:Exception occured when executing step
2019-02-12 15:49:06,701:ERROR:ExecuteMaster:Exception is [Errno 2] No such file or directory: 'scramOutput.log'
2019-02-12 15:49:06,701:ERROR:ExecuteMaster:Traceback:
2019-02-12 15:49:06,702:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 138, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/LogCollect.py", line 195, in execute
    with open('scramOutput.log', 'r') as f:
IOError: [Errno 2] No such file or directory: 'scramOutput.log'

2019-02-12 15:49:06,704:INFO:LogCollect:Steps.Executors.LogCollect.post called
```

this job was supposed to be using CMSSW_7xy, and I do not see it logging
`CMSSW too old or not fully functional...`, which makes me believe it somehow passed the `isCMSSWSupported` method check.... sigh

**Comment by amaltaro** [comment]
Fixed by #9004
