### ISSUE TITLE
Catch ORA-01033: ORACLE initialization or shutdown in progress

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9023]
This oracle exception caused a bunch of components to go down yesterday. From the exception message, I believe it's safe to simply wait until the next cycle of the components instead of crashing the component... @hufnagel do you agree?

Just in case, here is the full traceback of one of the components:
```
2019-02-15 03:11:06,022:140271752836864:INFO:RetryManagerPoller:Found 0 jobs in submitpaused
2019-02-15 03:11:06,025:140271752836864:INFO:BaseWorkerThread:RetryManagerPoller took 0.408 secs to execute
2019-02-15 03:15:45,088:140271752836864:ERROR:pool:Exception closing connection <cx_Oracle.Connection to CMS_WMBS_PROD3@CMSR>
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 244, in _close_connection
    self._dialect.do_close(connection)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in do_close
    dbapi_connection.close()
OperationalError: ORA-03114: not connected to ORACLE

2019-02-15 03:15:45,089:140271752836864:WARNING:HeartbeatAPI:Heartbeat update failed! Wait for the next time...:
(OperationalError) ORA-03113: end-of-file on communication channel
Process ID: 18556
Session ID: 344 Serial number: 91
 'UPDATE wm_workers\n                      SET last_updated = :last_updated\n               , state = :state WHERE name = :worker_name' {'state': 'Running', 'worker_name': 'RetryManagerPoller', 'last_updated': 1550196846}
2019-02-15 03:16:45,211:140271752836864:WARNING:HeartbeatAPI:Heartbeat update failed! Wait for the next time...:
(OperationalError) ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0
 None None
2019-02-15 03:16:45,575:140271752836864:ERROR:RetryManagerPoller:Caught exception in RetryManager
(OperationalError) ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0
 None NoneTraceback (most recent call last):
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 161, in algorithm
    myThread.transaction.begin()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/Transaction.py", line 32, in begin
    self.conn = self.dbi.connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 120, in connection
    return self.engine.connect()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1717, in connect
    return self._connection_cls(self, **kwargs)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 59, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1786, in raw_connection
    return self.pool.unique_connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 273, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 630, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 435, in checkout
    dbapi_connection = rec.get_connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 499, in get_connection
    self.connection = self.__connect()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 530, in __connect
    connection = self.__pool._creator()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 95, in connect
    connection_invalidated=invalidated
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
    return dialect.connect(*cargs, **cparams)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 376, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (OperationalError) ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0
 None None

2019-02-15 03:16:45,616:140271752836864:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller object at 0x7f939c8e5350> Caught exception in RetryManager
(OperationalError) ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0
 None NoneTraceback (most recent call last):
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 161, in algorithm
    myThread.transaction.begin()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/Transaction.py", line 32, in begin
    self.conn = self.dbi.connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/DBCore.py", line 120, in connection
    return self.engine.connect()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1717, in connect
    return self._connection_cls(self, **kwargs)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 59, in __init__
    self.__connection = connection or engine.raw_connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1786, in raw_connection
    return self.pool.unique_connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 273, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 630, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 435, in checkout
    dbapi_connection = rec.get_connection()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 499, in get_connection
    self.connection = self.__connect()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/pool.py", line 530, in __connect
    connection = self.__pool._creator()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 95, in connect
    connection_invalidated=invalidated
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
    return dialect.connect(*cargs, **cparams)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/0.9.6-comp/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 376, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (OperationalError) ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0
 None None

  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 187, in __call__
    tSpent, results, _ = algorithmWithDBExceptionHandler(parameters)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/DBExceptionHandler.py", line 35, in wrapper
    return f(*args, **kwargs)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMComponent/RetryManager/RetryManagerPoller.py", line 181, in algorithm
    raise Exception(msg)

2019-02-15 03:16:45,616:140271752836864:INFO:Harness:>>>Terminating worker threads
2019-02-15 03:16:45,616:140271752836864:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.RetryManager.RetryManagerPoller.RetryManagerPoller object at 0x7f939c8e5350> Caught exception in RetryManager
```

**Comment by vlimant** [comment]
great !
