### ISSUE TITLE
JobUpdater TypeError crash

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9063]
Apparently the component still fetch LQEs as available in the local workqueue, which have a different priority compared to ReqMgr2, then it tries to update those docs in local workqueue but it fails...
Traceback:
```
2019-03-04 09:23:00,077:140398592079616:INFO:JobUpdaterPoller:Synchronizing priorities with ReqMgr...
2019-03-04 09:23:00,522:140398592079616:INFO:JobUpdaterPoller:Found 1 workflows to update in workqueue
2019-03-04 09:23:00,537:140398592079616:ERROR:JobUpdaterPoller:Caught unexpected exception in JobUpdater: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 84, in algorithm
    self.synchronizeJobPriority()
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMComponent/JobUpdater/JobUpdaterPoller.py", line 138, in synchronizeJobPriority
    self.workqueue.updatePriority(workflow, workflowsToUpdate[workflow])
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 230, in updatePriority
    self.updateElements(*elementsToUpdate, Priority=priority)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Services/WorkQueue/WorkQueue.py", line 196, in updateElements
    conflictIDs = self.db.updateBulkDocumentsWithConflictHandle(elementIds, eleParams, maxConflictLimit=20)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 379, in updateBulkDocumentsWithConflictHandle
    conflictDocIDs = self.updateBulkDocuments(doc_ids, updateParams, updateLimits)
  File "/data/srv/wmagent/v1.1.18.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.1.18.patch2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 360, in updateBulkDocuments
    doc.update(j['doc'])
TypeError: 'NoneType' object is not iterable
```

**Comment by amaltaro** [comment]
Local workqueue views were somehow broken. Instead of handling this exception and masking problematic views, I'll just let it be. Closing it.
