### ISSUE TITLE
ReqMgr2 failing with 'AppResponse' object has no attribute 'iter_response'

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9089]
As reported by Lina, today all the ReqMgr2 backends had to be restarted because they were not responding - even though I see records in the logs proving otherwise - the snow ticket where it got reported is:
https://cern.service-now.com/service-portal/view-incident.do?n=INC1938609

and this is the traceback:
```
[12/Mar/2019:15:03:21] vocms0165.cern.ch 131.225.188.33 "GET /reqmgr2/data/request?name=pdmvserv_task_B2G-RunIIFall18wmLHEGS-00575__v1_T_190308_100236_8252 HTTP/1.1" 200 OK [data: 2729 in 10996 out 807233878 us ] [auth: OK "/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=Services/CN=wmagent/wmagent.fnal.gov" "" ] [ref: "" "WMCore.Services.Requests/v001" ]
[12/Mar/2019:15:03:21]  Traceback (most recent call last):
  File "/data/srv/beHG1903c/sw/slc7_amd64_gcc630/external/cherrypy/5.4.0-comp2/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "/data/srv/beHG1903c/sw/slc7_amd64_gcc630/external/cherrypy/5.4.0-comp2/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "/data/srv/beHG1903c/sw/slc7_amd64_gcc630/external/cherrypy/5.4.0-comp2/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 411, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/data/srv/beHG1903c/sw/slc7_amd64_gcc630/external/cherrypy/5.4.0-comp2/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 266, in __init__
    self.close()
  File "/data/srv/beHG1903c/sw/slc7_amd64_gcc630/external/cherrypy/5.4.0-comp2/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 288, in close
    if streaming and is_closable_iterator(self.iter_response):
AttributeError: 'AppResponse' object has no attribute 'iter_response'

[12/Mar/2019:15:03:34] vocms0165.cern.ch 127.0.0.1 "GET /reqmgr2/data/about HTTP/1.1" 200 OK [data: 338 in 807 out 231158369 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
```

**Comment by amaltaro** [comment]
It happened only once, we didn't manage to reproduce and we will likely not work on it, unless it happens again. So I'm going to close it.
