### ISSUE TITLE
DrainStatusPoller KeyError crash in 1.1.18

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9143]
I've just seen this reported in wmstats for vocms0282. Traceback is in [1]

[1]
```
2019-04-06 20:00:16,208:140226378852096:INFO:DrainStatusPoller:Running agent drain algorithm...
2019-04-06 20:00:16,461:140226387244800:WARNING:ResourceControlUpdater:Site T2_TH_CUNSTDA has invalid IO thresholds in SSB. Taking no action
2019-04-06 20:00:16,462:140226387244800:WARNING:ResourceControlUpdater:Site: T3_US_Omaha has incomplete SSB metrics, see {'slotsCPU': 2001}
2019-04-06 20:00:16,462:140226387244800:WARNING:ResourceControlUpdater:Site: T2_TH_CUNSTDA has incomplete SSB metrics, see {'slotsCPU': 67}
2019-04-06 20:00:16,519:140226387244800:ERROR:GenericDataCache:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Cache/GenericDataCache.py", line 37, in getData
    self.data = self.func(**self.kwargs)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 49, in _getResult
    verb=verb, contentType=contentType)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/Service.py", line 211, in refreshCache
    return open(cachefile, 'r')
IOError: [Errno 2] No such file or directory: '/data/srv/wmagent/v1.1.20.patch3/install/wmagent/AgentStatusWatcher/.wmcore_cache/.wmcore_cache_31961/requests/cmsweb.cern.ch:8443/15744094587142094_GET_wmagentconfig_vocms0282.cern.ch'

2019-04-06 20:00:16,520:140226378852096:ERROR:GenericDataCache:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Cache/GenericDataCache.py", line 37, in getData
    self.data = self.func(**self.kwargs)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 49, in _getResult
    verb=verb, contentType=contentType)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/Service.py", line 211, in refreshCache
    return open(cachefile, 'r')
IOError: [Errno 2] No such file or directory: '/data/srv/wmagent/v1.1.20.patch3/install/wmagent/AgentStatusWatcher/.wmcore_cache/.wmcore_cache_31961/requests/cmsweb.cern.ch:8443/15744094587142094_GET_wmagentconfig_vocms0282.cern.ch'

2019-04-06 20:00:16,520:140226387244800:WARNING:ReqMgrAux:agent config is not correct: {}
2019-04-06 20:00:16,520:140226378852096:WARNING:ReqMgrAux:agent config is not correct: {}
2019-04-06 20:00:16,520:140226387244800:ERROR:ResourceControlUpdater:Error occurred, will retry later:
2019-04-06 20:00:16,521:140226387244800:ERROR:ResourceControlUpdater:'UserDrainMode'
2019-04-06 20:00:16,524:140226387244800:ERROR:ResourceControlUpdater:Trace back: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 104, in algorithm
    self.getAgentsByTeam()
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 120, in getAgentsByTeam
    if isDrainMode(self.config):
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 199, in isDrainMode
    return AUXDB_AGENT_CONFIG_CACHE["UserDrainMode"] or AUXDB_AGENT_CONFIG_CACHE["AgentDrainMode"]
KeyError: 'UserDrainMode'

2019-04-06 20:00:16,524:140226387244800:INFO:ResourceControlUpdater:Resource control cycle finished updating site state and thresholds.
2019-04-06 20:00:16,524:140226387244800:INFO:BaseWorkerThread:ResourceControlUpdater took 0.414 secs to execute
2019-04-06 20:00:16,545:140226378852096:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.AgentStatusWatcher.DrainStatusPoller.DrainStatusPoller object at 0x7f89041435d0> 'UserDrainMode'  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 182, in __call__
    tSpent, results, _ = algorithmWithDBExceptionHandler(parameters)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Database/DBExceptionHandler.py", line 35, in wrapper
    return f(*args, **kwargs)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/DrainStatusPoller.py", line 48, in algorithm
    if isDrainMode(self.config):
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/Services/ReqMgrAux/ReqMgrAux.py", line 199, in isDrainMode
    return AUXDB_AGENT_CONFIG_CACHE["UserDrainMode"] or AUXDB_AGENT_CONFIG_CACHE["AgentDrainMode"]

2019-04-06 20:00:16,545:140226378852096:INFO:Harness:>>>Terminating worker threads
2019-04-06 20:00:16,545:140226378852096:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.AgentStatusWatcher.DrainStatusPoller.DrainStatusPoller object at 0x7f89041435d0> 'UserDrainMode'
Backtrace:
  File "/data/srv/wmagent/v1.1.20.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.20.patch3/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 208, in __call__
    raise ex

2019-04-06 20:00:16,607:140226378852096:INFO:BaseWorkerThread:Worker thread <WMComponent.AgentStatusWatcher.DrainStatusPoller.DrainStatusPoller object at 0x7f89041435d0> terminated
```

**Comment by amaltaro** [comment]
Actually let me assign it to Erik, since he already worked on this component.
