### ISSUE TITLE
JobCreator crashing on CERN agents - oracle issue

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9256]
And oracle issues are hitting us again and bringing components down. Right now I see vocms0281 JobCreator down, here is the traceback [1].

It seems those come from the SQLAlchemy update in the latest WMAgent release. It now wraps the exception from the DBAPI, thus the error message is now somehow different and the exception handler is not able to find those anymore:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/DBExceptionHandler.py#L9

[1]
```
2019-06-13 06:54:02,923:139664752584448:INFO:JobCreatorPoller:Found end in iteration over subscription 6180
2019-06-13 06:54:03,019:139664752584448:ERROR:base:Error closing cursor
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1333, in _safe_close_cursor
    cursor.close()
InterfaceError: not connected
2019-06-13 06:54:03,062:139664752584448:ERROR:JobCreatorPoller:Failed to execute JobCreator. Error: (cx_Oracle.InterfaceError) not connected
(Background on this error at: http://sqlalche.me/e/rvf5)
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 414, in algorithm
    self.pollSubscriptions()
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 549, in pollSubscriptions
    wmbsJobGroups = next(jobSplittingFunction)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 87, in runSplitter
    groups = jobFactory(**splitParams)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 94, in __call__
    self.algorithm(*args, **kwargs)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/EventAwareLumiBased.py", line 103, in algorithm
    lDict = self.getFilesSortedByLocation(avgEventsPerJob)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 460, in getFilesSortedByLocation
    lDict = self.sortByLocation()
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 237, in sortByLocation
    fileset = self.loadFiles(size=self.limit)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 339, in loadFiles
    newResults = resultProxy.fetchmany(size=length)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1247, in fetchmany
    e, None, None, self.cursor, self.context
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1241, in fetchmany
    l = self.process_rows(self._fetchmany_impl(size))
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/external/py2-sqlalchemy/1.3.3/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 1157, in _fetchmany_impl
    return self.cursor.fetchmany(size)
InterfaceError: (cx_Oracle.InterfaceError) not connected
(Background on this error at: http://sqlalche.me/e/rvf5)
```

**Comment by jenimal** [comment]
257 was just restared... error was:
Error in worker algorithm (1):
Backtrace:
<WMComponent.JobCreator.JobCreatorPoller.JobCreatorPoller object at 0x7f6511518e50> <@========== WMException Start ==========@>
Exception Class: JobCreatorException
Message: Failed to execute JobCreator. Error: (cx_Oracle.InterfaceError) not connected
(Background on this error at: http://sqlalche.me/e/rvf5)
ModuleName : WMComponent.JobCreator.JobCreatorPoller
MethodName : algorithm
ClassInstance : None
FileName : /data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py
ClassName : None
LineNumber : 435
ErrorNr : 0

Traceback: 
File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 414, in algorithm
self.pollSubscriptions()

File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-package

**Comment by amaltaro** [comment]
Same issue again on vocms0282. I'm creating a fix and will apply it to all production agents.

**Comment by jenimal** [comment]
I had to restart 280 last night, and just restarted 253:
agent: vocms0253.cern.ch (1.2.2.patch2)
agent last updated: 2019/6/18 (Tue) 15:17:51 UTC : 0 h 4 m
data last updated: 0 h 8 m
status: Components or Thread down;
team: production
component errors for: JobCreator
JobCreator
worker thread: JobCreatorPoller
status: Error
last updated: 2019/6/18 (Tue) 06:40:39 UTC
pid: 302592
error message:
Error in worker algorithm (1):
Backtrace:
   <@========== WMException Start ==========@>
Exception Class: JobCreatorException
Message: Failed to execute JobCreator. Error: (cx_Oracle.InterfaceError) not connected
(Background on this error at: http://sqlalche.me/e/rvf5)
	ModuleName : WMComponent.JobCreator.JobCreatorPoller
	MethodName : algorithm
	ClassInstance : None
	FileName : /data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py
	ClassName : None
	LineNumber : 435
	ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/JobCreator/JobCreatorPoller.py", line 414, in algorithm
    self.pollSubscriptions()

  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-package
