### ISSUE TITLE
DBS3Upload fails to insert some StepChain data into DBS

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9259]
As reported in this JIRA ticket: https://its.cern.ch/jira/browse/CMSCOMPPR-6517

vocms0257 is failing to inject the output blocks for this workflow:
cmsunified_task_L1T-PhaseIITDRSpring19GS-00017__v1_T_190605_130259_6694

with this exception in the logs [1]. 

As discussed in the JIRA with Yuyi, the data posted to the blockDump API is not consistent, see:
http://amaltaro.web.cern.ch/amaltaro/forYuyi/dbsuploader_block.json

where
```
dataset
    "processed_ds_name": "PhaseIITDRSpring19DR-PU200_106X_upgrade2023_realistic_v3-v2", 
acquisition_era
    "acquisition_era_name": "PhaseIITDRSpring19GS", 
```

We need to investigate how this information is gathered at the DBS3Upload.

[1]
```
2019-06-13 11:21:10,068:140417954010880:ERROR:DBSUploadPoller:Error trying to process block /Mu_FlatPt2to100-pythia8-gun/PhaseIITDRSpring19DR-PU200_106X_upgrade2023_realistic_v3-v2/GEN-SIM-DIGI-RAW#9dbb8c96-d5d4-4f01-9682-6caf56699596 through DBS. Error: HTTP Error 400: BlockInsert:                   processed_ds_name=acquisition_era_name[-filter_name][-processing_str]-vprocessing_version must be satisified.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 112, in uploadWorker
    dbsApi.insertBulkBlock(blockDump=block)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.7.8/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 342, in insertBulkBlock
    result =  self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.7.8/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 199, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/dbs3-client/3.7.8/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 226, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 400: BlockInsert:                   processed_ds_name=acquisition_era_name[-filter_name][-processing_str]-vprocessing_version must be satisified.
```

**Comment by amaltaro** [comment]
I should have started looking at the job logs instead of the code.
It turns to be a bug in the agent when we have files going straight to the merge area, which then uses the AcqEra/ProcStr/ProcVer from the top level task (Production/Processing), instead of using that info from the Merge task (which has the correct settings).

Here are some parts of the report for a production job `Job_875727`:
```
 'steps': {'cmsRun1': {'analysis': {},
                       'output': {'analysis': []},

           'cmsRun2': {'analysis': {},
                       'output': {'FEVTDEBUGHLToutput': [{'InputPFN': '/srv/job/WMTaskSpace/cmsRun2/FEVTDEBUGHLToutput.root',
                                                          'OutputPFN': 'srm://cmssrm-kit.gridka.de:8443/srm/managerv2\\?SFN=/pnfs/gridka.de/cms/disk-only/store/mc/PhaseIITDRSpring19DR/Mu_FlatPt2to100-pythia8-gun/GEN-SIM-DIGI-RAW/PU200_106X_upgrade2023_realistic_v3-v2/70000/A8A917B3-4980-984A-B64E-4A2EA42222E6.root',
                                                          'StageOutCommand': 'gfal2',
                                                          'acquisitionEra': 'PhaseIITDRSpring19GS',
                                                          'events': 312,
                                                          'size': 19891709460,
                                                          'runs': {'1': {315: 312}},
                                                          'dataset': {'applicationName': 'cmsRun',
                                                                      'applicationVersion': 'CMSSW_10_6_0_patch2',
                                                                      'dataTier': 'GEN-SIM-DIGI-RAW',
                                                                      'primaryDataset': 'Mu_FlatPt2to100-pythia8-gun',
                                                                      'processedDataset': 'PhaseIITDRSpring19DR-PU200_106X_upgrade2023_realistic_v3-v2'},
                                                          'globalTag': '106X_upgrade2023_realistic_v3',
                                                          'lfn': '/store/mc/PhaseIITDRSpring19DR/Mu_FlatPt2to100-pythia8-gun/GEN-SIM-DIGI-RAW/PU200_106X_upgrade2023_realistic_v3-v2/70000/A8A917B3-4980-984A-B64E-4A2EA42222E6.root',
                                                          'location': 'T1_DE_KIT_Disk',
                                                          'merged': True,
                                                          'module_label': 'FEVTDEBUGHLToutput',
                                                          'ouput_module_class': 'PoolOutputModule',

           'cmsRun3': {'analysis': {},
                       'output': {'AODSIMoutput': [{'InputPFN': '/srv/job/WMTaskSpace/cmsRun3/AODSIMoutput.root',
                                                    'OutputPFN': 'srm://cmssrm-kit.gridka.de:8443/srm/managerv2\\?SFN=/pnfs/gridka.de/cms/disk-only/store/mc/PhaseIITDRSpring19DR/Mu_FlatPt2to100-pythia8-gun/AODSIM/PU200_106X_upgrade2023_realistic_v3-v2/70000/D3D565A3-159F-6A4D-B32F-B023B28CA59F.root',
                                                    'StageOutCommand': 'gfal2',
                                                    'acquisitionEra': 'PhaseIITDRSpring19GS',
                                                    'size': 8230417915,
                                                    'runs': {'1': {315: 312}},
                                                    'events': 312,
                                                    'dataset': {'applicationName': 'cmsRun',
                                                                'applicationVersion': 'CMSSW_10_6_0_patch2',
                                                                'dataTier': 'AODSIM',
                                                                'primaryDataset': 'Mu_FlatPt2to100-pythia8-gun',
                                                                'processedDataset': 'PhaseIITDRSpring19DR-PU200_106X_upgrade2023_realistic_v3-v2'},
                                                    'lfn': '/store/mc/PhaseIITDRSpring19DR/Mu_FlatPt2to100-pythia8-gun/AODSIM/PU200_106X_upgrade2023_realistic_v3-v2/70000/D3D565A3-159F-6A4D-B32F-B023B28CA59F.root',
                                                    'merged': True,

           'cmsRun4': {'analysis': {},
                       'output': {'MINIAODSIMoutput': [{'InputPFN': '/srv/job/WMTaskSpace/cmsRun4/MINIAODSIMoutput.root',
                                                        'OutputPFN': 'srm://cmssrm-kit.gridka.de:8443/srm/managerv2\\?SFN=/pnfs/gridka.de/cms/disk-only/store/unmerged/PhaseIITDRSpring19MiniAOD/Mu_FlatPt2to100-pythia8-gun/MINIAODSIM/PU200_106X_upgrade2023_realistic_v3-v2/70000/0F64D569-A662-DC43-A2C9-CF2EA0057DEB.root',
                                                        'StageOutCommand': 'gfal2',
                                                        'acquisitionEra': 'PhaseIITDRSpring19GS',
                                                        'size': 68896181,
                                                        'runs': {'1': {315: 312}},
                                                        'events': 312,
                                                        'dataset': {'applicationName': 'cmsRun',
                                                                    'applicationVersion': 'CMSSW_10_6_0_patch2',
                                                                    'dataTier': 'MINIAODSIM',
                                                                    'primaryDataset': 'Mu_FlatPt2to100-pythia8-gun',
                                                                    'processedDataset': 'PhaseIITDRSpring19MiniAOD-PU200_106X_upgrade2023_realistic_v3-v2'},
                                                        'lfn': '/store/unmerged/PhaseIITDRSpring19MiniAOD/Mu_FlatPt2to100-pythia8-gun/MINIAODSIM/PU200_106X_upgrade2023_realistic_v3-v2/70000/0F64D569-A662-DC43-A2C9-CF2EA0057DEB.root',
                                                        'merged': False,
 'task': '/cmsunified_task_L1T-PhaseIITDRSpring19GS-00017__v1_T_190605_130259_6694/L1T-PhaseIITDRSpring19GS-00017_0'}
```

output of cmsRun2 and cmsRun3 were much bigger than 2GB.

While a report for a merge job looks like (Job_963478):
```
 'steps': {'cmsRun1': {'analysis': {},
                       'output': {'Merged': [{'InputPFN': '/srv/job/WMTaskSpace/cmsRun1/Merged.root',
                                              'acquisitionEra': 'PhaseIITDRSpring19MiniAOD',
                                              'dataset': {'applicationName': 'cmsRun',
                                                          'applicationVersion': 'CMSSW_10_6_0_patch2',
                                                          'dataTier': 'MINIAODSIM',
                                                          'primaryDataset': 'Mu_FlatPt2to100-pythia8-gun',
                                                          'processedDataset': 'PhaseIITDRSpring19MiniAOD-PU200_106X_upgrade2023_realistic_v3-v2'},
                                              'globalTag': '106X_upgrade2023_realistic_v3',
                                              'lfn': '/store/mc/PhaseIITDRSpring19MiniAOD/Mu_FlatPt2to100-pythia8-gun/MINIAODSIM/PU200_106X_upgrade2023_realistic_v3-v2/70000/CB891838-0B97-3043-AB33-FFCDD93CE58F.root',
                                              'location': 'T2_US_Wisconsin',
                                              'merged': False,
                                              'module_label': 'Merged',
                                              'ouput_module_class': 'PoolOutputModule',
                                              'pfn': '/srv/job/WMTaskSpace/cmsRun1/Merged.root',
                                              'prep_id': 'L1T-PhaseIITDRSpring19MiniAOD-00007',
                                              'processingStr': 'PU200_106X_upgrade2023_realistic_v3',
 'task': '/cmsunified_task_L1T-PhaseIITDRSpring19GS-00017__v1_T_190605_130259_6694/L1T-PhaseIITDRSpring19GS-00017_0/L1T-PhaseIITDRSpring19MiniAOD-00007_0MergeMINIAODSIMoutput'}
```

The problem looks simple, but it's gonna take some good thought on how to properly fix it...

**Comment by amaltaro** [comment]
Sigh... and I just noticed the same can happen to the `prep_id` field as well. `globalTag` is likely on the same boat as well, since it's one of the columns of `dbsbuffer_dataset`.
