### ISSUE TITLE
JobSubmitter fails to submit jobs to condor with "Failed to create new cluster"

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9381]
**Impact of the bug**
vocms0252, vocms0253 (new agents).
But Jen also reported submit7 - which is running the old version - and I see it failed the last time on 2019-07-29 15:16:32,18

**Describe the bug**
JobSubmitter is failing to submit part of the jobs it has to submit within a cycle. From this log
```
2019-09-19 16:22:13,541:140413107058432:INFO:JobSubmitterPoller:Have 1000 jobs to submit.
2019-09-19 16:22:13,541:140413107058432:INFO:JobSubmitterPoller:Done assigning site locations.
2019-09-19 16:22:15,381:140413107058432:ERROR:SimpleCondorPlugin:SimpleCondorPlugin job submission failed.
2019-09-19 16:22:15,382:140413107058432:ERROR:SimpleCondorPlugin:Failed to create new cluster.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.6.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.2.6.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 169, in submit
    submitRes = sub.queue_with_itemdata(txn, 1, iter(jobParams))
RuntimeError: Failed to create new cluster.
2019-09-19 16:22:15,382:140413107058432:ERROR:SimpleCondorPlugin:Moving on the the next batch of jobs and/or cycle....
2019-09-19 16:22:15,499:140413107058432:ERROR:SimpleCondorPlugin:SimpleCondorPlugin job submission failed.
2019-09-19 16:22:15,499:140413107058432:ERROR:SimpleCondorPlugin:Failed to create new cluster.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.6.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.2.6.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 169, in submit
    submitRes = sub.queue_with_itemdata(txn, 1, iter(jobParams))
RuntimeError: Failed to create new cluster.
2019-09-19 16:22:15,500:140413107058432:ERROR:SimpleCondorPlugin:Moving on the the next batch of jobs and/or cycle....
2019-09-19 16:22:15,615:140413107058432:ERROR:SimpleCondorPlugin:SimpleCondorPlugin job submission failed.
2019-09-19 16:22:15,616:140413107058432:ERROR:SimpleCondorPlugin:Failed to create new cluster.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.6.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.2.6.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 169, in submit
    submitRes = sub.queue_with_itemdata(txn, 1, iter(jobParams))
RuntimeError: Failed to create new cluster.
2019-09-19 16:22:15,616:140413107058432:ERROR:SimpleCondorPlugin:Moving on the the next batch of jobs and/or cycle....
2019-09-19 16:22:15,719:140413107058432:ERROR:SimpleCondorPlugin:SimpleCondorPlugin job submission failed.
2019-09-19 16:22:15,719:140413107058432:ERROR:SimpleCondorPlugin:Failed to create new cluster.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.6.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.2.6.patch1/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 169, in submit
    submitRes = sub.queue_with_itemdata(txn, 1, iter(jobParams))
RuntimeError: Failed to create new cluster.
2019-09-19 16:22:15,719:140413107058432:ERROR:SimpleCondorPlugin:Moving on the the next batch of jobs and/or cycle....
2019-09-19 16:22:15,720:140413107058432:INFO:SimpleCondorPlugin:Done submitting jobs for this cycle in SimpleCondorPlugin
2019-09-19 16:22:16,009:140413107058432:INFO:JobSubmitterPoller:Jobs that succeeded/failed submission: 200/800.
2019-09-19 16:22:16,481:140413107058432:INFO:DashboardReporter:Handling 200 jobs
2019-09-19 16:23:35,873:140413107058432:INFO:JobSubmitterPoller:Transaction cycle successfully completed.
2019-09-19 16:23:35,896:140413107058432:INFO:BaseWorkerThread:JobSubmitterPoller took 84.796 secs to execute
```

200 jobs out of 1000 were successfully submitted. The others hit that `RuntimeError`...

In addition to that, the schedd doesn't seem to be under heavy usage, see:
```
cmst1@vocms0253:/data/srv/wmagent/current $ condor_status -schedd
Name                     Machine                  RunningJobs   IdleJobs   HeldJobs
vocms0252.cern.ch        vocms0252.cern.ch               3819      71011          0
vocms0253.cern.ch        vocms0253.cern.ch              16138      29430          0
```

**How to reproduce it**
likely hard to do so

**Expected behavior**
Understand why these problems are happening; is it something on the host making the submission? is it something wrong with the SI layer?

Regardless of what the problem is, we might change JobSubmitter to no longer fail jobs that fail to get submitted. Instead, we could:
* report those failures
* and not fail those jobs, just keep them in the JobSubmitter queue and try again in the next cycle
* (bonus) record this failure in LogDB
 
**Additional context and error message**

**Comment by amaltaro** [comment]
@khurtado Kenyi, we know it's not a problem of the newest agent only (or newer HTCondor); but have you ever seen these problems and/or have any clue of why it might fail like that?

We have just reached around 40k failures only from vocms0253, so I have `temporarily stopped JobSubmitter on vocms0253`, before it creates more problems!
https://monit-grafana.cern.ch/d/lhVKAhNik/cms-wmagent-monitoring?orgId=11&refresh=30m&fullscreen&panelId=7

Can you also have a look at vocms0253, to see whether there is anything unusual with that node.
I'll be off for a couple of hours, then I can catch up on your investigation.

**Comment by khurtado** [comment]
@amaltaro 

I see the following in the schedd:
```
09/19/19 23:01:34 (pid:14497) NewProc(): MAX_JOBS_SUBMITTED exceeded, submit failed
```

This option is set to 250K in the schedd:
```
$ condor_config_val MAX_JOBS_SUBMITTED
250000
```

**Comment by amaltaro** [comment]
Thanks, Kenyi.
Given that job submission was still failing this morning, I increased it to its default value
```
cmst1@vocms0253:/data/srv/wmagent/current $ condor_config_val condor_config_val -v -dump MAX_JOBS_SUBMITTED
# Configuration from machine: vocms0253.cern.ch

# Parameters with names that match condor_config_val:

# Parameters with names that match MAX_JOBS_SUBMITTED:
DAGMAN_MAX_JOBS_SUBMITTED = 0
 # at: <Default>
 # expanded: 0
 # default: 0
MAX_JOBS_SUBMITTED = 2147483647
 # at: /etc/condor/config.d/99_local_tweaks.config, line 34
 # expanded: 2147483647
 # default: 2147483647
```
and restarted the component.

Still, this limit doesn't make sense because of:
1) the agent had < 50k jobs in condor, now it has ~70k only
2) JobSubmitter only submits jobs if `MAX_JOBS_PER_OWNER` hasn't been reached (which is set to 100k)

So either `MAX_JOBS_SUBMITTED` has a different meaning, like jobs submitted over a period of time (?) or there is a bug somewhere in HTCondor that we're hitting on this agent.

**Comment by amaltaro** [comment]
@khurtado BTW, do you know how we can evaluate that `MAX_JOBS_SUBMITTED` parameter?
I tried to do the same logic as in here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/PyCondor/PyCondorAPI.py#L81-L84
but the response is empty.

**Comment by amaltaro** [comment]
For the record: https://cms-logbook.cern.ch/elog/GlideInWMS/7107

**Comment by khurtado** [comment]
@amaltaro Yes, the method you pointed out is to get the classads. The schedd configuration values can also be read with the python bindings, but in a slightly different way:

``` 
>>> import htcondor
>>> coll = htcondor.Collector()
>>> scheddAd = coll.locate(htcondor.DaemonTypes.Schedd)
>>> params = htcondor.RemoteParam(scheddAd)
>>> params['MAX_JOBS_SUBMITTED']
'2147483647'
>>> params['MAX_JOBS_PER_OWNER']
'100000'
>>>
```

**Comment by khurtado** [comment]
@amaltaro I think this is a bug in HTCondor indeed. I made some comments in the elog ticket, but what seems suspicious is that before raising the limits from 250K to 350K, the Cpu counts in the schedd were limited to approximately 250K, then to 350K after I raised the limit. However, a small test in another schedd seems to be counting things in a different way I don't understand and that seems wrong.

**Comment by amaltaro** [comment]
Thanks for those hints, Kenyi.
Besides the work we can do on our side here, which is not failing jobs that fail to get submitted, can you please try to get it discussed/reported to the HTCondor at the next developers meeting?

**Comment by khurtado** [comment]
Yes, I will mention this to them.

**Comment by thongonary** [comment]
From operation side, do you think ACDC would work for these failure, or would you like to hear from HTCondor team first?
There are nearly 1000 workflows affected by this, and increasing.

**Comment by thongonary** [comment]
When is the developer meeting? Can we just post it on comp-ops? I don't think meeting is appropriate for highly urgent matter like this.

**Comment by amaltaro** [comment]
@thongonary it was an oversight from my side. I could have changed the condor configuration as we did for vocms0253. I just did the same for vocms0252 and I no longer see failures during job submission.

Anyways, the condor schedd configuration is something that I always tried to leave up to the SI team and, we didn't hear anything back from them on Friday.

**Comment by thongonary** [comment]
So do you think ACDC would work? @amaltaro

**Comment by amaltaro** [comment]
Definitely! However, if the workflow is pretty small (<1k jobs) and/or failure rate is very large, it might be cleaner to run it from scratch.

**Comment by amaltaro** [comment]
Reading this issue again, I think the expected behaviour from WMCore is that job submission failure should not cause jobs to go to failed, but instead retried in the next cycle.

**Comment by khurtado** [comment]
@amaltaro Since all schedds raised the limits:

```
MAX_JOBS_SUBMITTED = 2147483647
```

and there have not been new reports on this issue, should we close this issue?

**Comment by amaltaro** [comment]
Given that it is a 3 years old issue, yes, I am in favor of closing it out. If needed, we can reopen it.

However, note that job submission is based on this check:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitAPI.py#L17

and I think this `MAX_JOBS_PER_OWNER` is what actually gave us issues in the past (or... maybe we didn't have it implemented back then). Just adding this note here, anyhow I am closing it :) Thanks Kenyi!
