### ISSUE TITLE
Cache TagCollector data

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9383]
**Impact of the bug**
ReqMgr2

**Describe the bug**
It looks like we are not using any caching mechanism for the releases XML data (TagCollector) used to validate CMSSW and ScramArchs during request creation (and/or assignment).

**How to reproduce it**
Not easily reproducible

**Expected behavior**
We should either use the Services caching mechanism or MemoryCache and avoid unneeded http queries. Setting the cache to 1h should be enough.

**Additional context and error message**
Traceback from ReqMgr2:
```
[23/Sep/2019:00:39:07]  Updating request "None" with these user-provided args: {u'PrepID': u'task_EXO...
WARNING:root:Http request failed, retrying once again..
WARNING:root:The cachefile <cStringIO.StringO object at 0x7f9725971a08> does not exist and the service at https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML/ raised a error(111, 'Connection refused') when accessed
ERROR:root:About to raise exception <@========== WMException Start ==========@>
Exception Class: WMSpecFactoryException
Message: [Errno 111] Connection refused
        ModuleName : WMCore.WMSpec.WMWorkloadTools
        MethodName : _validateArgFunction
        ClassInstance : None
        FileName : /data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py
        ClassName : None
        LineNumber : 102
        ErrorNr : 0

Traceback: 
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkloadTools.py", line 93, in _validateArgFunction
    if not valFunction(value):

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 1030, in <lambda>
    "ScramArch": {"validate": lambda x: all([y in architectures() for y in x]),

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Tools/cms.py", line 224, in architectures
    return TC.architectures()

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/Services/TagCollector/TagCollector.py", line 88, in architectures
    for row in self.data():

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/Services/TagCollector/TagCollector.py", line 67, in data
    data = self._getResult()

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/Services/TagCollector/TagCollector.py", line 53, in _getResult
    verb=verb, contentType=contentType)

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/Services/Service.py", line 205, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)

  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/Services/Service.py", line 318, in getData
    raise he

<@---------- WMException End ----------@>
[23/Sep/2019:00:39:07]  Error: Traceback (most recent call last):
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 193, in validate
    self._validateRequestBase(param, safe, validate_request_create_args)
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Service/Request.py", line 88, in _validateRequestBase
    workload, r_args = valFunc(args, self.config, self.reqmgr_db_service, param)
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/ReqMgr/Utils/Validation.py", line 101, in validate_request_create_args
    request_args)
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 915, in factoryWorkloadConstruction
    self.masterValidation(schema=arguments)
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 940, in masterValidation
    self.raiseValidationException(str(ex))
  File "/data/srv/beHG1909e/sw/slc7_amd64_gcc630/cms/reqmgr2/1.2.6.pre4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py", line 952, in raiseValidationException
    raise WMSpecFactoryException(message=msg)
WMSpecFactoryException: <@========== WMException Start ==========@>
```

**Comment by amaltaro** [comment]
@khurtado Kenyi, this is also a good candidate for you, especially because you've just implemented the same mechanism for DBS datatiers.
I didn't check, but I think there is a caching already in place by using global variables or so. If possible, let's get rid of of that as well.
