### ISSUE TITLE
Global WorkQueue locationUpdateTask thread crashing with AttributeError

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9391]
**Impact of the bug**
Global WorkQueue

**Describe the bug**
I mixed up the data structs from different places and the code tries to execute `items()` for a set/tuple data type, see traceback from the locationUpdateTask CP thread:
```
2019-10-11 00:57:46,224:INFO:LogDB:<LogDB(url=https://cmsweb.cern.ch/couchdb/wmstats_logdb, identifier=global_workqueue, agent=1)>
2019-10-11 00:57:46,225:INFO:WorkQueue:Executing data location update...
2019-10-11 00:57:48,460:INFO:DataLocationMapper:Fetching location data from PhEDEx with args: {'complete': 'y'}
2019-10-11 00:57:48,521:INFO:DataLocationMapper:Fetching location data from PhEDEx with args: {'complete': 'y'}
2019-10-11 00:58:14,534:INFO:DataLocationMapper:Found 304 unique input data to update location
2019-10-11 00:58:14,545:ERROR:CherryPyPeriodicTask:Periodic Thread ERROR __builtins__.AttributeError 'tuple' object has no attribute 'items'
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask: Traceback (most recent call last):
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1910d/sw/slc7_amd64_gcc630/cms/workqueue/1.2.7.pre3/lib/python2.7/site-packages/WMCore/REST/CherryPyPeriodicTask.py", line 91, in run
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:     self.taskFunc(self.config)
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1910d/sw/slc7_amd64_gcc630/cms/workqueue/1.2.7.pre3/lib/python2.7/site-packages/WMCore/GlobalWorkQueue/CherryPyThreads/LocationUpdateTask.py", line 24, in updateDataLocation
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:     res = globalQ.updateLocationInfo()
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1910d/sw/slc7_amd64_gcc630/cms/workqueue/1.2.7.pre3/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 732, in updateLocationInfo
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:     result = self.dataLocationMapper()
2019-10-11 00:58:14,598:ERROR:CherryPyPeriodicTask:   File "/data/srv/beHG1910d/sw/slc7_amd64_gcc630/cms/workqueue/1.2.7.pre3/lib/python2.7/site-packages/WMCore/WorkQueue/DataLocationMapper.py", line 177, in __call__
2019-10-11 00:58:14,599:ERROR:CherryPyPeriodicTask:     for data, locations in dataMapping.items():
2019-10-11 00:58:14,599:ERROR:CherryPyPeriodicTask: AttributeError: 'tuple' object has no attribute 'items'
```

**How to reproduce it**
You need to have GQE - with some input data - sitting in Available state.

**Expected behavior**
Not crash! Go through the thread code and update data location for GQEs sitting in Available status.

**Additional context and error message**
We will need a CMSWEB hot fix, on top of 1.2.7.pre3.
Master has a different version of data location update and shouldn't have any issues, but I'll x-check that one too.

**Comment by amaltaro** [comment]
Ok, the problem is actually related to some StoreResults that were created yesterday. Those don't use global DBS, thus the data location update is done via DBS instead of PhEDEx.

The method fetching data location from DBS is actually returning a tuple:
https://github.com/dmwm/WMCore/blob/1.2.7.pre3/src/python/WMCore/WorkQueue/DataLocationMapper.py#L142

and this is what breaks that thread.

So my new plan is to fix this bug, update those GQEs via a script, and wait until the next CMSWEB production deployment (HG1911 cycle) to get the real fix in. StoreResults are very rare to show up in the system anyways...
