### ISSUE TITLE
Supporting WMArchive in python3

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9413]
**Impact of the new feature**
WMCore in general, WMArchive and perhaps CRAB/DBS

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
As chatted with Valentin, he's migrating WMArchive to python3 and since it relies on some packages from WMCore, like:
WMCore.REST
WMCore.Configuration
WMCore.WMExceptions

we could start working on those once we manage to put our hands into this python3 migration project.

**Describe alternatives you've considered**
none

**Additional context**
The code has to be compatible with python2.7 and python3 (3.7?)

**Comment by vkuznet** [comment]
I have all dependencies in place now and first attempt to build WMArchive failed which gives you direct pointers what should be fixed in WMCore. Here is a relevant part from the build log:
```
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/Utils/Timers.py:docstring of Utils.Timers.timeFunction:5: WARNING: Unexpected indentation.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.Cache.WMConfigCache.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.Cache.WMConfigCache'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/Cache/WMConfigCache.py", line 14, in <module>
    from future.utils import with_metaclass
ModuleNotFoundError: No module named 'future'
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.Configuration.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.Configuration'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/Configuration.py", line 26, in <module>
    basestring,  # For py2/py3 compatibility, don't let futurize remove PY3 Remove when python 3 transition complete
NameError: name 'basestring' is not defined
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/DataStructs/DASDocument.py:docstring of WMCore.DataStructs.DASDocument:5: WARNING: Unexpected indentation.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.DataStructs.Job.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.DataStructs.Job'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/DataStructs/Job.py", line 14, in <module>
    from WMCore.Configuration import ConfigSection
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/Configuration.py", line 26, in <module>
    basestring,  # For py2/py3 compatibility, don't let futurize remove PY3 Remove when python 3 transition complete
NameError: name 'basestring' is not defined
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.DataStructs.LumiList.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.DataStructs.LumiList'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/DataStructs/LumiList.py", line 20, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/DataStructs/Mask.py:docstring of WMCore.DataStructs.Mask.Mask.addRunAndLumis:5: WARNING: Unexpected indentation.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.Lexicon.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.Lexicon'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/Lexicon.py", line 21, in <module>
    from WMCore.WMException import WMException, WMEXCEPTION_START_STR, WMEXCEPTION_END_STR
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMException.py", line 9, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.REST.HeartbeatMonitorBase.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.REST.HeartbeatMonitorBase'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/REST/HeartbeatMonitorBase.py", line 5, in <module>
    from WMCore.Services.WMStats.WMStatsWriter import WMStatsWriter, convertToServiceCouchDoc
ModuleNotFoundError: No module named 'WMCore.Services'
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.REST.Main.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.REST.Main'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/REST/Main.py", line 19, in <module>
    import thread
ModuleNotFoundError: No module named 'thread'
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.REST.Test.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.REST.Test'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/REST/Test.py", line 3, in <module>
    from WMCore.REST.Main import RESTMain
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/REST/Main.py", line 19, in <module>
    import thread
ModuleNotFoundError: No module named 'thread'
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc/wmc-wmarchive/WMCore.WMException.rst:4: (WARNING/2) autodoc: failed to import module 'WMCore.WMException'; the following exception was raised:
Traceback (most recent call last):
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
  File "/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMException.py", line 9, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions:4: WARNING: Bullet list ends without a blank line; unexpected unindent.
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:9: WARNING: Unexpected indentation.
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:10: WARNING: Block quote ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:10: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:14: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:14: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:17: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:17: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:20: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:20: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:23: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:23: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:26: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:26: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:29: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:29: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:32: WARNING: Definition list ends without a blank line; unexpected unindent.
WARNING: /build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WMEXCEPTION:32: (SEVERE/4) Unexpected section title or transition.

----------------
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WM_JOB_ERROR_CODES:4: WARNING: Unexpected indentation.
/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/build/lib/WMCore/WMExceptions.py:docstring of WMCore.WMExceptions.WM_JOB_ERROR_CODES:7: WARNING: Unexpected indentation.

Exception occurred:
  File "/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/babel/localedata.py", line 62, in locale_identifiers
    os.path.splitext(filename) for filename in os.listdir(_dirname)
FileNotFoundError: [Errno 2] No such file or directory: '/build/vk/w630/slc7_amd64_gcc630/external/py3-sphinx/1.6.3/lib/python3.6/site-packages/babel/locale-data'
The full traceback has been saved in /build/vk/w630/tmp/sphinx-err-eoybkkxr.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
make: Leaving directory `/build/vk/w630/BUILD/slc7_amd64_gcc630/cms/wmarchive/v00.08.21/cms+wmarchive+v00.08.21-1/WMCore_wmarchive/doc'
error: command 'make' failed with exit status 2
error: Bad exit status from /build/vk/w630/tmp/rpm-tmp.e376JW (%build)



```

**Comment by amaltaro** [comment]
@mapellidario Dario, once all the changes to support python3 workflows have been implemented, this is probably the next item in the priority list.

**Comment by amaltaro** [comment]
@vkuznet do I understand it right that prioritising the modules aforementioned is no longer required?
If so, I'd suggest to close this GH issue. We will eventually modernize those modules as well.

**Comment by vkuznet** [comment]
Alan, WMArchive is migrated to Go codebase and from that point of view I no longer need/care about these changes. I'm closing the ticket.
