### ISSUE TITLE
Remove deprecated DashboardMonitor/ApMon from WMCore

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9536]
**Impact of the new feature**
WMCore in general

**Is your feature request related to a problem? Please describe.**
As a follow up of:
https://github.com/dmwm/WMCore/issues/9434

where we no longer add DashboardMonitor plugin to the jobs, we should proceed with the last phase and completely remove those libraries from WMCore

**Describe the solution you'd like**
Remove unused code, such as:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/DashboardMonitor.py
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/DashboardInterface.py
and some code from
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/Services/Dashboard/API

**Describe alternatives you've considered**
Instead of removing this code, we might use the current implementation as a baseline for the upcoming runtime monitor (NATS?).

**Additional context**
none

**Comment by amaltaro** [comment]
Keeping WMCore integrated with the old dashboard is just a waste of computing/time resources; ideally we should get rid of this before the next stable WMAgent release.

**Comment by amaltaro** [comment]
And I just noticed that I planned to have this in in the upcoming stable release. Components would provide a slightly better performance in general.

**Comment by amaltaro** [comment]
And here is another good reason to deprecate it sooner than later, it breaks our PY3 WMAgent (tested with 1.4.9.pre2-comp2, during the deployment):
```
*** Populating resource-control ***
Adding ALL sites to resource-control...
Executing wmagent-resource-control --add-all-sites --plugin=SimpleCondorPlugin --pending-slots=50 --running-slots=50 --down ...
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmagent-resource-control", line 16, in <module>
    from WMCore.ResourceControl.ResourceControl import ResourceControl
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/ResourceControl/ResourceControl.py", line 11, in <module>
    from WMCore.BossAir.BossAirAPI import BossAirAPI
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/BossAir/BossAirAPI.py", line 23, in <module>
    from WMCore.JobStateMachine.ChangeState import ChangeState
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 20, in <module>
    from WMCore.Services.Dashboard.DashboardReporter import DashboardReporter
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/DashboardReporter.py", line 13, in <module>
    from WMCore.Services.Dashboard.DashboardAPI import DashboardAPI
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/DashboardAPI.py", line 12, in <module>
    from WMCore.Services.Dashboard import apmon
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/apmon.py", line 55, in <module>
    from types import LongType
ImportError: cannot import name 'LongType' from 'types' (/data/srv/wmagent/v1.4.9.pre2-comp2/sw/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/types.py)
Done!
```

**Comment by amaltaro** [comment]
@belforte Hi Stefano, since the old dashboard has been ended-of-life for a year or more now, I decided to actually remove all these libraries from the WMCore repository. If it's easy enough, I might have a PR for this today.

Anyhow, I just wanted to make sure it won't cause any unexpected issues with CRAB.

**Comment by belforte** [comment]
thanks @amaltaro . Please go ahead, no problem from my side.
