### ISSUE TITLE
Broken fix in ResourceControlUpdater for the SSB deprecation

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9584]
**Impact of the bug**
WMAgents (including those in production right now)

**Describe the bug**
I have just scanned the AgentStatusWatcher logs and I see it's hitting an exception when parsing the site state in MonIT. It's either coming from a site with missing information in MonIT, or I might have missed something in my fix made here:
https://github.com/dmwm/WMCore/pull/9555

**How to reproduce it**
Can be seen in any agent that gets deployed and has the grafana token.

**Expected behavior**
Properly deal with site status from MonIT, local database and switch their statuses when required.
Which also means, fix that bug/exception.

**Additional context and error message**
Traceback from the agent:
```
2020-03-26 10:02:25,105:140105039865600:INFO:AgentStatusPoller:592 out of 592 documents successfully sent to AMQ
2020-03-26 10:02:25,106:140105039865600:INFO:BaseWorkerThread:AgentStatusPoller took 15.845 secs to execute
2020-03-26 10:05:19,439:140105031472896:INFO:Grafana:Calling API: https://monit-grafana.cern.ch/api/datasources/proxy/9475/_msearch with query: '{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["monit_prod_cmssst_*"]}\n{"size":500,"query":{"bool":{"filter":[{"range":{"metadata.timestamp":{"gte":"now-1d","lte":"now","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"metadata.type: ssbmetric AND metadata.type_prefix:raw AND metadata.path: sts15min"}}]}},"sort":{"metadata.timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"docvalue_fields":["metadata.timestamp"]}\n'
2020-03-26 10:05:19,531:140105031472896:ERROR:ResourceControlUpdater:Unknown status 'unknown' for site T2_IT_Pisa, please check SSB
2020-03-26 10:05:19,531:140105031472896:ERROR:ResourceControlUpdater:Error occurred, will retry later:
2020-03-26 10:05:19,531:140105031472896:ERROR:ResourceControlUpdater:'state'
2020-03-26 10:05:19,531:140105031472896:ERROR:ResourceControlUpdater:Trace back: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/cms/wmagent/1.3.0/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 92, in algorithm
    self.checkStatusChanges(sitesRC, ssbSiteStatus)
  File "/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/cms/wmagent/1.3.0/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 177, in checkStatusChanges
    if infoRC[site]['state'] != infoSSB[site]['state']:
KeyError: 'state'

2020-03-26 10:05:19,532:140105031472896:INFO:ResourceControlUpdater:Resource control cycle finished updating site state and thresholds.
```

**Comment by amaltaro** [comment]
@stlammel Stephan, I actually overlooked this error. This error message is saying it all:
```
Unknown status 'unknown' for site T2_IT_Pisa, please check SSB
```

so that site has an invalid status. The keys in this dictionary is what is actually supported in WMAgent:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py#L275-L278

so we are actually getting an invalid value from upstream. Can you please look into it and get it fixed?

I'm also going to make a WMCore change to protect against such problems.

**Comment by stlammel** [comment]
@amaltaro  Hallo Alan,
"unknown" is not an illegal status: occasionally, there will be insufficient data to determine the production status of a site (new site, failure to fetch data needed to determine the status, etc.) and in that cases it's set to "unknown".
Something odd is currently happening with Pisa. It should have not switched to "unknown". I'll investigate and correct.
- Stephan

**Comment by amaltaro** [comment]
Is it an status that always existed (even in the old SSB)? Are there any other statuses that we need to support and/or that we should expect from MonIT?

I had understood that we had simply changed the data source from SSB to MonIT, if there are other logical changes/values, please let us know before we push this fix in.

**Comment by stlammel** [comment]
@amaltaro Hallo Alan,
unknown status existed in the old SSB metric too BUT was handled differently by not making an entry for the site. It then depended on the metric lifetime setting how things propagated and the metric access method. The values to
expect are unknown | enabled | waiting_room | morgue for LifeStatus, unknown | enabled | drain | disabled | test for ProdStatus, and  unknown | enabled | disabled for CrabStatus.
The MonIT metrics are not just new storage location for the old data but the implementation/evaluation is completely changed. I'll update the documentation to make the "unknown" state more clear.
Sorry for the confusion.
- Stephan

**Comment by amaltaro** [comment]
Thanks for the extra information, Stephan. So it's only this `unknown` bit that was missing.
