### ISSUE TITLE
Error when ssbStatus is unknown

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#9601]
**Impact of the bug**
WMAgent

**Describe the bug**
ResourceControlUpdater scans the list of site status, if a site is in an "unknown" state it tries to pop a item from ssbStatus (a string) instead of ssbState (a dict).

**How to reproduce it**
Start AgentStatusWatcher with PR #9584 

**Expected behavior**
Pop the item from ssbState instead of ssbStatus.
https://github.com/dmwm/WMCore/blob/2a7ebaaaa108859802a84f73abdce014e3b8e280/src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py#L269

**Additional context and error message**
```
2020-04-02 20:36:57,725:139635865409280:WARNING:ResourceControlUpdater:Site T3_US_PuertoRico has an unknown SSB status 'unknown'. Skipping it!
2020-04-02 20:36:57,725:139635865409280:ERROR:ResourceControlUpdater:Error occurred, will retry later:
2020-04-02 20:36:57,725:139635865409280:ERROR:ResourceControlUpdater:'unicode' object has no attribute 'pop'
2020-04-02 20:36:57,726:139635865409280:ERROR:ResourceControlUpdater:Trace back: 
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.0.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.3.0.patch1/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 96, in algorithm
    ssbSiteStatus = self.getSiteStatus()
  File "/data/srv/wmagent/v1.3.0.patch1/sw/slc7_amd64_gcc630/cms/wmagent/1.3.0.patch1/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py", line 271, in getSiteStatus
    ssbStatus.pop(site, None)
AttributeError: 'unicode' object has no attribute 'pop'
```

**Comment by goughes** [comment]
@amaltaro Take a look and see if you agree with me on this. I can do a quick PR to fix this if you would like.

**Comment by amaltaro** [comment]
Haaa, what a silly mistake from my side. Thanks for catching it, Erik.
This exception is likely happening in the production agents as well :(
