### ISSUE TITLE
MSMonitor crashing to parse dataset level subscription requests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9663]
**Impact of the bug**
ReqMgr2MS MSMonitor

**Describe the bug**
It looks like MSMonitor is failing to parse the data transfer output for a dataset subscription. Traceback will be provided below.

**How to reproduce it**
Need to check

**Expected behavior**
Failures need to be contained in a try/except block to avoid crashing the whole cycle.
In addition to that, we of course need to get this issue fixed.

**Additional context and error message**
Traceback:
```
2020-04-25 02:24:53,374:DEBUG:MSMonitor: Checking transfers for: pdmvserv_task_HIG-RunIIAutumn18NanoAODv7-00134__v1_T_200424_044920_3414
2020-04-25 02:24:53,374:DEBUG:MSMonitor: Checking transfers for: nwickram_RVCMSSW_11_1_0_pre6Pyquen_DiJet_pt80to120_2760GeV_PU__200422_193039_9660
2020-04-25 02:24:53,374:DEBUG:Service: Data is from the Service cache
2020-04-25 02:24:53,374:DEBUG:MSMonitor: Subscription result for dataset: /RelValHydjetQ_B12_5020GeV_2018/CMSSW_11_1_0_pre6-110X_upgrade2018_realistic_v9-v1/GEN-SIM and request ID: 2189272 was: {u'phedex': {u'request_date': u'2020-04-25 00:04:14 UTC', u'request_timestamp': 1587773054.37094, u'call_time': 0.01022, u'dataset': [{u'files': 5, u'name': u'/RelValHydjetQ_B12_5020GeV_2018/CMSSW_11_1_0_pre6-110X_upgrade2018_realistic_v9-v1/GEN-SIM', u'bytes': 10420036381, u'is_open': u'y', u'id': u'1519465', u'subscription': [{u'node': u'T1_FR_CCIN2P3_Disk', u'percent_files': 100, u'custodial': u'n', u'suspend_until': None, u'node_files': 5, u'level': u'DATASET', u'time_create': 1587694041.41837, u'move': u'n', u'request': 2189272, u'percent_bytes': 100, u'group': u'DataOps', u'priority': u'low', u'time_update': 1587694041.41837, u'node_id': 1861, u'suspended': u'n', u'time_start': None, u'node_bytes': 10420036381}]}], u'instance': u'prod', u'request_call': u'subscriptions', u'request_url': u'http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/subscriptions', u'request_version': u'2.5.0pre3-comp'}}
2020-04-25 02:24:53,375:ERROR:MSMonitor: ('Unknown exception processing the transfer records. Error: %s', "'block'")
Traceback (most recent call last):
  File "/data/srv/beHG2004f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.2.pre5/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSMonitor.py", line 106, in execute
    self.getTransferInfo(transferRecords)
  File "/data/srv/beHG2004f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.2.pre5/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSMonitor.py", line 144, in getTransferInfo
    completion = self._getTransferstatus(rec['dataset'], rec['transferIDs'])
  File "/data/srv/beHG2004f/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.2.pre5/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSMonitor.py", line 186, in _getTransferstatus
    for blockRow in dsetRow['block']:
KeyError: 'block'
2020-04-25 02:24:53,388:INFO:MSManager: Total monitor execution time: 21 secs
```

**Comment by amaltaro** [comment]
So, we phedex response data structure is slightly different between a dataset and block level request (`subscriptions` API).

When `block` is part of the query string, here is an example of response:
```
{'phedex': {'call_time': 0.00978,
            'dataset': [{'block': [{'bytes': 174820111,
                                    'files': 1,
                                    'id': '11080105',
                                    'is_open': 'n',
                                    'name': '/ADDGravToGG_NegInt-0_LambdaT-5500_M-500To1000_TuneCP2_13TeV-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM#952e7e45-c292-4f03-8d54-32bd7944a192',
                                    'subscription': [{'custodial': 'n',
                                                      'group': 'DataOps',
                                                      'level': 'BLOCK',
                                                      'move': 'n',
                                                      'node': 'T2_AT_Vienna',
                                                      'node_bytes': 0,
                                                      'node_files': 0,
                                                      'node_id': 63,
                                                      'percent_bytes': 0,
                                                      'percent_files': 0,
                                                      'priority': 'low',
                                                      'request': 2192314,
                                                      'suspend_until': None,
                                                      'suspended': 'n',
                                                      'time_create': 1587740718.17585,
                                                      'time_start': None,
                                                      'time_update': 1587740718.17585}]}],
                         'bytes': 4121424595,
                         'files': 7,
                         'id': '1298909',
                         'is_open': 'n',
                         'name': '/ADDGravToGG_NegInt-0_LambdaT-5500_M-500To1000_TuneCP2_13TeV-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM'}],
            'instance': 'prod',
            'request_call': 'subscriptions',
            'request_date': '2020-04-25 00:24:52 UTC',
            'request_timestamp': 1587774292.52293,
            'request_url': 'http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/subscriptions',
            'request_version': '2.5.0pre3-comp'}}
```

while, when providing a `dataset` query string:
```
{'phedex': {'call_time': 0.01022,
            'dataset': [{'bytes': 10420036381,
                         'files': 5,
                         'id': '1519465',
                         'is_open': 'y',
                         'name': '/RelValHydjetQ_B12_5020GeV_2018/CMSSW_11_1_0_pre6-110X_upgrade2018_realistic_v9-v1/GEN-SIM',
                         'subscription': [{'custodial': 'n',
                                           'group': 'DataOps',
                                           'level': 'DATASET',
                                           'move': 'n',
                                           'node': 'T1_FR_CCIN2P3_Disk',
                                           'node_bytes': 10420036381,
                                           'node_files': 5,
                                           'node_id': 1861,
                                           'percent_bytes': 100,
                                           'percent_files': 100,
                                           'priority': 'low',
                                           'request': 2189272,
                                           'suspend_until': None,
                                           'suspended': 'n',
                                           'time_create': 1587694041.41837,
                                           'time_start': None,
                                           'time_update': 1587694041.41837}]}],
            'instance': 'prod',
            'request_call': 'subscriptions',
            'request_date': '2020-04-25 00:04:14 UTC',
            'request_timestamp': 1587773054.37094,
            'request_url': 'http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/subscriptions',
            'request_version': '2.5.0pre3-comp'}}
```

**Comment by amaltaro** [comment]
I have manually moved that workflow to staged - after checking that transfers are completed - such that it doesn't hold the rest of the workflows.
```
Setting nwickram_RVCMSSW_11_1_0_pre6Pyquen_DiJet_pt80to120_2760GeV_PU__200422_193039_9660 status from staging to staged
  OK!
```

**Comment by amaltaro** [comment]
One more workflow spotted. Moved to staged as well
```
amaltaro@vocms0192:/data/amaltaro/April2020_Val $ python ../ReqMgr2_scripts/setrequeststatus.py alan staged
Setting moanwar_RVCMSSW_11_1_0_pre6ZEE_14_PU25ns__2026D49PU200_200423_190037_4261 status from staging to staged
  OK!
```

**Comment by amaltaro** [comment]
one more:
```
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_E_Front_120um_PU25ns__2026D49PU200_200423_215246_4159 status from staging to staged
  OK!
```

**Comment by amaltaro** [comment]
For the record, a few more:
```
Setting moanwar_RVCMSSW_11_1_0_pre6ZpTT_1500_14_PU25ns__2026D49PU200_200423_190051_1215 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6BsToJpsiPhi_mumuKK_14TeV_PU25ns__2026D49PU200_200423_215407_118 status from staging to staged
  OK!
Setting nwickram_RVCMSSW_11_1_0_pre6Pyquen_ZeemumuJets_pt10_2760GeV_PU__200422_193043_8071 status from staging to staged
  OK!
Setting nwickram_RVCMSSW_11_1_0_pre6Pyquen_GammaJet_pt20_2760GeV_PU__200422_193036_6070 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6B0ToKstarMuMu_14TeV_PU25ns__2026D49PU200_200423_215357_6891 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6BsToEleEle_14TeV_PU25ns__2026D49PU200_200423_215400_5603 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6BsToJpsiGamma_14TeV_PU25ns__2026D49PU200_200423_215403_2365 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6BsToMuMu_14TeV_PU25ns__2026D49PU200_200423_215410_2862 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6BsToPhiPhi_KKKK_14TeV_PU25ns__2026D49PU200_200423_215414_2695 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_E_Front_200um_PU25ns__2026D49PU200_200423_215243_75 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_E_Front_300um_PU25ns__2026D49PU200_200423_215239_2013 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_H_Coarse_300um_PU25ns__2026D49PU200_200423_215306_8766 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_H_Coarse_Scint_PU25ns__2026D49PU200_200423_215304_3053 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_H_Fine_120um_PU25ns__2026D49PU200_200423_215301_6363 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_H_Fine_200um_PU25ns__2026D49PU200_200423_215258_9223 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6CloseByPGun_CE_H_Fine_300um_PU25ns__2026D49PU200_200423_215255_4572 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6DisplacedMuPt10To30_PU25ns__2026D49PU200_200423_215350_9488 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6DisplacedMuPt2To10_PU25ns__2026D49PU200_200423_215348_7287 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6DisplacedMuPt30To100_PU25ns__2026D49PU200_200423_215354_3387 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6H125GGgluonfusion_14_PU25ns__2026D49PU200_200423_190047_4539 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6NuGun_PU25ns__2026D49PU200_200423_190025_9124 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6QCD_Pt15To7000_Flat_14_PU25ns__2026D49PU200_200423_190044_6823 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6QCD_Pt20toInfMuEnrichPt15_14_PU25ns__2026D49PU200_200423_215232_9065 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleEFlatPt2To100_PU25ns__2026D49PU200_200423_215310_2248 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleGammaFlatPt8To150_PU25ns__2026D49PU200_200423_215339_865 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleMuFlatPt0p7To10_PU25ns__2026D49PU200_200423_215313_8149 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleMuFlatPt2To100_PU25ns__2026D49PU200_200423_215317_3333 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleMuPt1000_PU25ns__2026D49PU200_200423_215430_1819 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleMuPt100_PU25ns__2026D49PU200_200423_215427_844 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleMuPt10_PU25ns__2026D49PU200_200423_215424_199 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SinglePiFlatPt0p7To10_PU25ns__2026D49PU200_200423_215343_5633 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6SingleTauFlatPt2To150_PU25ns__2026D49PU200_200423_215346_849 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6TTbar_14TeV_PU25ns__2026D49PU200_200423_190028_9440 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6TauToMuMuMu_14TeV_PU25ns__2026D49PU200_200423_215417_2083 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6TenTau_15_500_PU25ns__2026D49PU200_200423_190034_8476 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6TenTau_15_500_PU25ns__2026D49PU200_200423_215235_8505 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6ZMM_14_PU25ns__2026D49PU200_200423_190041_8343 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6ZTT_14TeV_PU25ns__2026D49PU200_200423_190032_2218 status from staging to staged
  OK!
Setting moanwar_RVCMSSW_11_1_0_pre6ZpTT_1500_14_PU25ns__2026D49PU200_200423_215419_5226 status from staging to staged
  OK!

```
