### ISSUE TITLE
ReqMon DataCacheUpdate thread timing out

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9680]
**Impact of the bug**
ReqMon (aka WMStats)

**Describe the bug**
Likely related to the very high load in the system, as explained here: https://github.com/dmwm/WMCore/issues/9668

Over the last days, WMStats became very sluggish and poking around the logs, I see many timeouts in the `DataCacheUpdate` reqmon cherrypy thread. It seems to have become much worse since yesterday.

From the logs, there are cases that it has to transfer ~200MB worth of logs. Given that this is a general purpose, one can multiply that by 5 (1GB of data every 10 to 15min...). It also explains why wmstats sometimes loads and others it remains spinning forever.

**How to reproduce it**
Have 40k workflows in the system with many job failures.

**Expected behavior**
The obvious ones. Cache should always be up-to-date, thus avoiding these requests time out.
These caches were supposed to be "small" as well (<50MB), having such large caches continuously updated in many backends isn't health for the cluster.
We could also calculate the amount of data in the cache and log it (pushing such information to MonIT would be a plus as well).
Anything else that can still be discussed to make this service more robust and resilient to such a high load.
 
**Additional context and error message**
Logs from vocms0766 for today:
```
2020-05-07 02:54:41,440:INFO:DataCacheUpdate:DataCache is updated: 42096
2020-05-07 03:12:55,214:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270001 milliseconds with 115605922 bytes received')
2020-05-07 03:29:13,663:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270001 milliseconds with 53544228 bytes received')
2020-05-07 03:45:05,224:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 68165469 bytes received')
2020-05-07 04:01:29,324:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 225706992 bytes received')
2020-05-07 04:18:01,356:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270008 milliseconds with 121591632 bytes received')
2020-05-07 04:34:01,814:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 23328350 bytes received')
2020-05-07 04:51:40,050:ERROR:DataCacheUpdate:(28, 'Operation timed out after 271232 milliseconds with 22150520 bytes received')
2020-05-07 05:08:50,854:ERROR:DataCacheUpdate:(28, 'Operation timed out after 280071 milliseconds with 20950855 bytes received')
2020-05-07 05:25:37,535:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 54860085 bytes received')
2020-05-07 05:42:15,440:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 62670518 bytes received')
2020-05-07 05:58:33,363:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 122496096 bytes received')
2020-05-07 06:15:27,999:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 63965610 bytes received')
2020-05-07 06:31:27,804:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 213083083 bytes received')
2020-05-07 06:48:05,471:ERROR:DataCacheUpdate:(28, 'Operation timed out after 276537 milliseconds with 215823928 bytes received')
2020-05-07 07:04:44,183:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 25620037 bytes received')
2020-05-07 07:20:36,991:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270000 milliseconds with 99517239 bytes received')
2020-05-07 07:37:25,040:ERROR:DataCacheUpdate:(28, 'Operation timed out after 270001 milliseconds with 113712109 bytes received')
2020-05-07 07:53:46,004:INFO:DataCacheUpdate:DataCache is updated: 42098
```

**Comment by amaltaro** [comment]
Having another look at this issue from a different angle, I'm actually starting to believe that the memory footprint isn't the evil here.

Many of the time outs from the reqmon logs are actually coming from the couchdb views. Couch logs look normal in the wmstats backend (0743)
```
[13/May/2020:08:43:00]  SERVER OTHER ERROR pycurl.error f0cb22e5dbaaee1d8ac424a7e544a9f5 ((28, 'Operation timed out after 270000 milliseconds with 4564275 bytes received'))
[13/May/2020:08:43:00]    Traceback (most recent call last):
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/REST/Server.py", line 723, in default
[13/May/2020:08:43:00]        return self._call(RESTArgs(list(args), kwargs))
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/REST/Server.py", line 804, in _call
[13/May/2020:08:43:00]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/WMStats/Service/RequestInfo.py", line 36, in get
[13/May/2020:08:43:00]        result = self.wmstats.getRequestSummaryWithJobInfo(request_name)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsReader.py", line 337, in getRequestSummaryWithJobInfo
[13/May/2020:08:43:00]        self._updateRequestInfoWithJobInfo(requestInfo)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsReader.py", line 103, in _updateRequestInfoWithJobInfo
[13/May/2020:08:43:00]        jobInfoByRequestAndAgent = self.getLatestJobInfoByRequests(requestInfo.keys())
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsReader.py", line 97, in getLatestJobInfoByRequests
[13/May/2020:08:43:00]        requestAndAgentKey = self._getRequestAndAgent(requestNames)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsReader.py", line 188, in _getRequestAndAgent
[13/May/2020:08:43:00]        result = self._getCouchView("requestAgentUrl", options)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/WMStats/WMStatsReader.py", line 112, in _getCouchView
[13/May/2020:08:43:00]        return self.couchDB.loadView(self.couchapp, view, options, keys)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 537, in loadView
[13/May/2020:08:43:00]        (self.name, design, view), encodedOptions)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 127, in get
[13/May/2020:08:43:00]        encode, decode, contentType)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Database/CMSCouch.py", line 122, in makeRequest
[13/May/2020:08:43:00]        encode, decode, contentType)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 165, in makeRequest
[13/May/2020:08:43:00]        result, response = self.makeRequest_pycurl(uri, data, verb, headers)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 183, in makeRequest_pycurl
[13/May/2020:08:43:00]        ckey=ckey, cert=cert, capath=capath)
[13/May/2020:08:43:00]      File "/data/srv/beHG2006a/sw/slc7_amd64_gcc630/cms/reqmon/1.3.4.pre2/lib/python2.7/site-packages/WMCore/Services/pycurl_manager.py", line 257, in request
[13/May/2020:08:43:00]        curl.perform()
[13/May/2020:08:43:00]    error: (28, 'Operation timed out after 270000 milliseconds with 4564275 bytes received')
[13/May/2020:08:43:00] vocms0766.cern.ch IP_BLAH "GET /wmstatsserver/data/request/pdmvserv_task_HIG-RunIIFall18GS-00069__v1_T_200203_084212_7776 HTTP/1.1" 500 Internal Server Error [data: 6984 in 742 out 270037208 us ] [auth: OK "/DC=BLAH" "" ] [ref: "" "" ]
```
