### ISSUE TITLE
MSOutput fails to create CampaignMap

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9749]
**Impact of the bug**
reqmgr2ms

**Describe the bug**
MSOutput Producer thread cannot create the Campaign Map for some specific types of workflows [1]. It fails with an error of type [2]. The major suspect is this line here [3], which presumes that if it is a `Task` or `Step` Chain, then the key `ChainParentageMap` should always exist. Basically, for a reason not quite clear to me, for workflows like this one here, that condition is not met. It is still:
`"RequestType": "TaskChain"`, but the `ChainParentagemap` key is missing. As a result the `docTransformer` function in the MSOutput module fails to create an MSOutputTemplate object for this workflow. 

A second order effect is that, since we do handle this exception inside the caller function (`docTransformer` [4]), but only for logging purposes and we still try to return from it, then the error is propagated up here [5] (outside the Pipeline) and is actually masked as a reference to a non existing variable (`UnboundLocalError`), where this exact type of exception is not considered as an expected one, but is rather treated as a `General` exception, and the whole cycle is interrupted. 

As a third order effect is the fact that we are facing the risky situation of while there is a Wrokflow like this one in the system and if the `Reqmgr` returns all the workflows in the same order every time, then the cycle will never be able to progress beyond that workflow and the MongoDB will not be reflecting the exact set of workflows that are in the proper state (`completed`, `closed-out`) as they are in `Reqmgr`.   

[3]
https://github.com/dmwm/WMCore/blob/21637c06ee448a59086fd01e33d4cfce38012893/src/python/WMCore/MicroService/DataStructs/MSOutputTemplate.py#L262

[4]
https://github.com/dmwm/WMCore/blob/21637c06ee448a59086fd01e33d4cfce38012893/src/python/WMCore/MicroService/Unified/MSOutput.py#L621-L625

[5]
https://github.com/dmwm/WMCore/blob/21637c06ee448a59086fd01e33d4cfce38012893/src/python/WMCore/MicroService/Unified/MSOutput.py#L599-L604

**How to reproduce it**
1) The reason for the existence of this type of workflows in the system is not known so no clear recipe for reproducing  
2) Artificially fail the creation of MSOutputTemplate object and the current cycle of the Producer thread will be interrupted.

**Expected behavior**
1) Never fail to create a MSOutputTemplate object. Even if we cannot create the CampaignMap we still need to return the proper object since at the time when this internal method (`_setCampMap`) is called [6], we already have a valid object created, but it is only missing that particular field (which for the time being is not used, but will be).

2) Never interrupt the cycle of the Producer Thread because of a single workflow failure

3) Do not allow exceptions to change flavor so that they create subtle and hard to track bugs

4) In order to achieve the former and for better code readability and usability, handle exceptions inside the Pipeline. 

[6]
https://github.com/dmwm/WMCore/blob/21637c06ee448a59086fd01e33d4cfce38012893/src/python/WMCore/MicroService/DataStructs/MSOutputTemplate.py#L118

**Additional context and error message**
[1]
```
https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_task_HIG-PhaseIISummer17wmLHEGENOnly-00029__v1_T_180704_112124_1897

2020-06-16 22:38:13,471:ERROR:MSOutput: ERR: Unable to create MSOutputTemplate for document {u'AcquisitionEra': {u'HIG-PhaseIISummer17wmLHEGENOnly-00029_0': u'PhaseIISummer17wmLHEGENOnly'},
 u'AllowOpportunistic': False,
 u'AutoApproveSubscriptionSites': [],
 u'BlockCloseMaxEvents': 200000000,
 u'BlockCloseMaxFiles': 500,
 u'BlockCloseMaxSize': 5000000000000,
 u'BlockCloseMaxWaitTime': 172800,
 u'CMSSWVersion': u'CMSSW_9_3_9_patch1',
 u'Campaign': u'PhaseIISummer17wmLHEGENOnly',
 u'Comments': u'',
 u'ConfigCacheID': None,
 u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb',
 u'CouchDBName': u'reqmgr_config_cache',
 u'CouchURL': u'https://cmsweb.cern.ch/couchdb',
 u'CouchWorkloadDBName': u'reqmgr_workload_cache',
 u'CustodialGroup': u'DataOps',
 u'CustodialSites': [],
 u'CustodialSubType': u'Replica',
 u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch',
 u'DQMConfigCacheID': None,
 u'DQMHarvestUnit': u'byRun',
 u'DQMSequences': [],
 u'DQMUploadProxy': None,
 u'DQMUploadUrl': u'https://cmsweb.cern.ch/dqm/dev',
 u'Dashboard': u'production',
 u'DashboardHost': u'cms-jobmon.cern.ch',
 u'DashboardPort': 8884,
 u'DbsUrl': u'https://cmsweb.cern.ch/dbs/prod/global/DBSReader/',
 u'DeleteFromSource': False,
 u'EnableHarvesting': False,
 u'EnableNewStageout': False,
 u'EventStreams': None,
 u'FirstEvent': 1,
 u'FirstLumi': 1,
 u'GlobalTag': u'93X_upgrade2023_realistic_v5',
 u'GlobalTagConnect': None,
 u'GracePeriod': 300,
 u'Group': u'DATAOPS',
 u'HardTimeout': 159900,
 u'IgnoredOutputModules': [],
 u'IncludeParents': False,
 u'InitialPriority': 90000,
 u'LumiList': {},
 u'MaxMergeEvents': 20000000,
 u'MaxMergeSize': 4294967296,
 u'MaxWaitTime': 86400,
 u'Memory': 2300,
 u'MergedLFNBase': u'/store/mc',
 u'MinMergeSize': 2147483648,
 u'Multicore': 1,
 u'NonCustodialGroup': u'DataOps',
 u'NonCustodialSites': [],
 u'NonCustodialSubType': u'Replica',
 u'OpenRunningTimeout': 0,
 u'OutputDatasets': [u'/GluGluHToZZTo4L_M125_14TeV_powheg2_JHUgenV702_pythia8/PhaseIISummer17wmLHEGENOnly-93X_upgrade2023_realistic_v5-v3/GEN',
                     u'/GluGluHToZZTo4L_M125_14TeV_powheg2_JHUgenV702_pythia8/PhaseIISummer17wmLHEGENOnly-93X_upgrade2023_realistic_v5-v3/LHE'],
 u'OutputModulesLFNBases': [u'/store/unmerged/PhaseIISummer17wmLHEGENOnly/GluGluHToZZTo4L_M125_14TeV_powheg2_JHUgenV702_pythia8/GEN/93X_upgrade2023_realistic_v5-v3',
                            u'/store/unmerged/PhaseIISummer17wmLHEGENOnly/GluGluHToZZTo4L_M125_14TeV_powheg2_JHUgenV702_pythia8/LHE/93X_upgrade2023_realistic_v5-v3'],
 u'Override': {u'eos-lfn-prefix': u'root://eoscms.cern.ch//eos/cms/store/logs/prod/recent'},
 u'OverrideCatalog': None,
 u'PeriodicHarvestInterval': 0,
 u'PrepID': u'task_HIG-PhaseIISummer17wmLHEGENOnly-00029',
 u'ProcessingString': {u'HIG-PhaseIISummer17wmLHEGENOnly-00029_0': u'93X_upgrade2023_realistic_v5'},
 u'ProcessingVersion': 3,
 u'ReqMgr2Only': True,
 u'RequestDate': [2018, 7, 4, 9, 21, 24],
 u'RequestName': u'prozober_task_HIG-PhaseIISummer17wmLHEGENOnly-00029__v1_T_180704_112124_1897',
 u'RequestPriority': 190000,
 u'RequestStatus': u'completed',
 u'RequestString': u'task_HIG-PhaseIISummer17wmLHEGENOnly-00029__v1_T',
 u'RequestTransition': [{u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal',
                         u'Status': u'new',
                         u'UpdateTime': 1530696084},
                        {u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal',
                         u'Status': u'assignment-approved',
                         u'UpdateTime': 1530696092},
                        {u'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal',
                         u'Status': u'assigned',
                         u'UpdateTime': 1530697009},
                        {u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch',
                         u'Status': u'acquired',
                         u'UpdateTime': 1530697738},
                        {u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch',
                         u'Status': u'running-open',
                         u'UpdateTime': 1530707524},
                        {u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch',
                         u'Status': u'running-closed',
                         u'UpdateTime': 1530707525},
                        {u'DN': u'/DC=ch/DC=cern/OU=computers/CN=dmwm/cmsweb.cern.ch',
                         u'Status': u'completed',
                         u'UpdateTime': 1530746885}],
 u'RequestType': u'TaskChain',
 u'RequestWorkflow': u'https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/prozober_task_HIG-PhaseIISummer17wmLHEGENOnly-00029__v1_T_180704_112124_1897/spec',
 u'Requestor': u'prozober',
 u'RequestorDN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal',
 u'RobustMerge': True,
 u'RunNumber': 0,
 u'ScramArch': [u'slc6_amd64_gcc630'],
 u'SiteBlacklist': [],
 u'SiteWhitelist': [u'T2_CH_CERN'],
 u'SizePerEvent': 91,
 u'SoftTimeout': 159600,
 u'SubRequestType': u'',
 u'SubscriptionPriority': u'Low',
 u'Task1': {u'AcquisitionEra': u'PhaseIISummer17wmLHEGENOnly',
            u'CMSSWVersion': u'CMSSW_9_3_9_patch1',
            u'Campaign': u'PhaseIISummer17wmLHEGENOnly',
            u'ConfigCacheID': u'23f536f0605b681474c4c7760b19068b',
            u'EventsPerJob': 30800,
            u'EventsPerLumi': 100,
            u'FilterEfficiency': 1,
            u'GlobalTag': u'93X_upgrade2023_realistic_v5',
            u'KeepOutput': True,
            u'LheInputFiles': False,
            u'Memory': 2300,
            u'Multicore': 1,
            u'PrepID': u'HIG-PhaseIISummer17wmLHEGENOnly-00029',
            u'PrimaryDataset': u'GluGluHToZZTo4L_M125_14TeV_powheg2_JHUgenV702_pythia8',
            u'ProcessingString': u'93X_upgrade2023_realistic_v5',
            u'ProcessingVersion': 1,
            u'RequestNumEvents': 1000000,
            u'ScramArch': [u'slc6_amd64_gcc630'],
            u'Seeding': u'AutomaticSeeding',
            u'SizePerEvent': 91,
            u'SplittingAlgo': u'EventBased',
            u'TaskName': u'HIG-PhaseIISummer17wmLHEGENOnly-00029_0',
            u'TimePerEvent': 0.9362594562205079},
 u'TaskChain': 1,
 u'Team': u'production',
 u'TimePerEvent': 0.9362594562205079,
 u'TotalEstimatedJobs': 834,
 u'TotalInputEvents': 1000000,
 u'TotalInputFiles': 0,
 u'TotalInputLumis': 10000,
 u'TrustPUSitelists': False,
 u'TrustSitelists': False,
 u'UnmergedLFNBase': u'/store/unmerged',
 u'ValidStatus': u'PRODUCTION',
 u'VoGroup': u'unknown',
 u'VoRole': u'unknown',
 u'_id': u'prozober_task_HIG-PhaseIISummer17wmLHEGENOnly-00029__v1_T_180704_112124_1897'}ERR: 'ChainParentageMap'
```

[2]
```
2020-06-16 22:38:13,472:ERROR:MSOutput: local variable 'msOutDoc' referenced before assignment
Traceback (most recent call last):
  File "/data/srv/beHG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 588, in msOutputProducer
    pipeLine.run(request)
  File "/data/srv/beHG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/Utils/Pipeline.py", line 139, in run
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/beHG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/Utils/Pipeline.py", line 139, in <lambda>
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/beHG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/Utils/Pipeline.py", line 71, in __call__
    return self.run(obj)
  File "/data/srv/beHG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/Utils/Pipeline.py", line 74, in run
    return self.func(obj, *self.args, **self.kwargs)
  File "/data/srv/beHG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 625, in docTransformer
    return msOutDoc
UnboundLocalError: local variable 'msOutDoc' referenced before assignment
```

[2]

**Comment by todor-ivanov** [comment]
Some more info the actual error was suppressed because of this line:

https://github.com/dmwm/WMCore/blob/21637c06ee448a59086fd01e33d4cfce38012893/src/python/WMCore/MicroService/Unified/MSOutput.py#L624

It was not logging the whole exception but only an error. Once I fixed this then the real culprit  became immediately visible. Here [1] is the full error, which is basically a `KeyError`, as one could expect, instead of `UnboundLocalError` as it is now, because of the bad handling. And if this one was raised here, then on the upper level it would have been treated as a missing Key error from here:

https://github.com/dmwm/WMCore/blob/21637c06ee448a59086fd01e33d4cfce38012893/src/python/WMCore/MicroService/Unified/MSOutput.py#L589

and the cycle would not have been interrupted.


[1]
```
ERR: 'ChainParentageMap'
Traceback (most recent call last):
  File "/data/srv/HG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 619, in docTransformer
    msOutDoc = MSOutputTemplate(doc)
  File "/data/srv/HG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/WMCore/MicroService/DataStructs/MSOutputTemplate.py", line 118, in __init__
    self._setCampMap(doc, myDoc)
  File "/data/srv/HG2006h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.5.pre5/lib/python2.7/site-packages/WMCore/MicroService/DataStructs/MSOutputTemplate.py", line 262, in _setCampMap
    for key in reqDoc["ChainParentageMap"]:
KeyError: 'ChainParentageMap'
```

**Comment by amaltaro** [comment]
@todor-ivanov I had already created this issue:
https://github.com/dmwm/WMCore/issues/9726

Please close one of them as a duplicate.

**Comment by amaltaro** [comment]
and here is a fix to the campaign issue: https://github.com/dmwm/WMCore/pull/9751
Perhaps you can cherry-pick that change and we proceed with a single PR to resolve this issue.
