### ISSUE TITLE
Error in workflows getting announced because of [true, "No ParentageResolved"]

### ISSUE THREAD

**Issue by sharad1126** [dmwm/WMCore#9760]
**Impact of the bug**
The wfs are not getting announced. 

**Describe the bug**
```
Delayed announcement of cmsunified_task_PPS-RunIISummer19UL18pLHEGEN-00003__v1_T_200409_174328_8808 due to unresolved Parentage dependencies
Error with cmsunified_task_PPS-RunIISummer19UL18pLHEGEN-00003__v1_T_200409_174328_8808 to be announced
[true, "No ParentageResolved"]
```

**How to reproduce it**
closor module in unified reports this error:
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_PPS-RunIISummer19UL18pLHEGEN-00003

**Expected behavior**
As per @amaltaro this is a bug in WMCore which needs to be solved. 

**Additional context and error message**
@amaltaro as per our discussion on the slack channel, I am providing the GH issue with that particular wf reported by Wajid. Please add the others to this issue from the service logs. Thanks.

**Comment by sharad1126** [comment]
@amaltaro @todor-ivanov  do we have any updates here?

**Comment by amaltaro** [comment]
I had a look at this issue with an standalone script (plus a couple of debugging prints in DBS3Reader):
https://github.com/amaltaro/ProductionTools/blob/master/runStepChainParentageFix.py

and indeed it fails because it cannot find a run/lumi tuple in the parent file. I think it's actually an expected scenario, because StepChain merge runs asynchronously, which means there might be lumi sections in the child that did not manage to get merged in the parent dataset.

Here is the debugging information from the script:
```
2020-07-17 10:22:28,675:INFO:alan:Request: cmsunified_task_TSG-Phase2HLTTDRWinter20GS-00091__v1_T_200219_195740_3852 needs fixing
2020-07-17 10:22:28,676:INFO:alan:Retrieved 2 datasets to fix parentage, in status: normal-archived
2020-07-17 10:22:28,677:INFO:alan:  datasets are: defaultdict(<type 'set'>, {u'/Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-RECO': set([u'cmsunified_task_TSG-Phase2HLTTDRWinter20GS-00091__v1_T_200219_195740_3852']), u'/Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/MINIAODSIM': set([u'cmsunified_task_TSG-Phase2HLTTDRWinter20GS-00091__v1_T_200219_195740_3852'])})
2020-07-17 10:22:28,677:INFO:alan:
Resolving parentage for dataset: /Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-RECO
2020-07-17 10:22:28,732:INFO:DBS3Reader:Parent datasets for /Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-RECO are: [{'this_dataset': '/Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-RECO', 'parent_dataset_id': 14020950, 'parent_dataset': '/Muplus_Pt100-gun/Phase2HLTTDRWinter20DIGI-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-DIGI-RAW'}]
2020-07-17 10:22:28,759:INFO:DBS3Reader:AMR parentFullInfo: [{'560262557': [[1, 3],
                [1, 15],
                [1, 16],
                [1, 21],
                [1, 35],
                [1, 24],
                [1, 30],
                [1, 32],
                [1, 33],
                [1, 22]]},
 {'560262558': [[1, 70],
                [1, 66],
                [1, 65],
                [1, 63],
                [1, 57],
                [1, 36],
                [1, 27]]},
 {'560262559': [[1, 14], [1, 42], [1, 10], [1, 38], [1, 28]]},
 {'560262597': [[1, 43], [1, 34], [1, 26], [1, 20], [1, 17], [1, 9], [1, 41]]},
 {'560262598': [[1, 29]]},
 {'560268397': [[1, 50], [1, 69], [1, 67], [1, 61], [1, 60]]},
 {'560268437': [[1, 13], [1, 45]]},
 {'560268517': [[1, 56]]},
 {'560268518': [[1, 2], [1, 6], [1, 54], [1, 62]]},
 {'560268597': [[1, 48]]},
 {'560268637': [[1, 11]]},
 {'560268677': [[1, 52], [1, 46]]},
 {'560268877': [[1, 47], [1, 68]]},
 {'560268957': [[1, 1], [1, 58], [1, 53], [1, 51], [1, 4]]},
 {'560268997': [[1, 7]]},
 {'560269157': [[1, 5], [1, 49]]},
 {'560272877': [[1, 8], [1, 12]]},
 {'560272917': [[1, 64], [1, 59], [1, 55], [1, 71]]},
 {'561487517': [[1, 25],
                [1, 31],
                [1, 37],
                [1, 39],
                [1, 40],
                [1, 19],
                [1, 18],
                [1, 44],
                [1, 23]]}]
2020-07-17 10:22:28,832:INFO:DBS3Reader:Found 1 blocks without parentage information
2020-07-17 10:22:28,832:INFO:DBS3Reader:Fixing parentage for block: /Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-RECO#592bc4f4-c5b4-4dc9-80f3-12298fa928b0
2020-07-17 10:22:28,854:INFO:DBS3Reader:AMR childBlockData: [{'560499677': [[1, 72]]}]
2020-07-17 10:22:28,854:WARNING:DBS3Reader:Child file id: 560499677, with run/lumi: frozenset([72, 1]), has no match in the parent dataset
2020-07-17 10:22:28,872:ERROR:DBS3Reader:Parentage updated failed for block /Muplus_Pt100-gun/Phase2HLTTDRWinter20RECOMiniAOD-NoPU_110X_mcRun4_realistic_v3-v2/GEN-SIM-RECO#592bc4f4-c5b4-4dc9-80f3-12298fa928b0
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.6.patch3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch3/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 1038, in fixMissingParentageDatasets
    numFiles = self.findAndInsertMissingParentage(blockName, parentFullInfo, insertFlag=insertFlag)
  File "/data/srv/wmagent/v1.3.6.patch3/sw.amaltaro/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch3/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 977, in findAndInsertMissingParentage
    self.dbs.insertFileParents({"block_name": childBlockName, "child_parent_id_list": listChildParent})
  File "/data/srv/wmagent/v1.3.6.patch3/sw.amaltaro/slc7_amd64_gcc630/cms/dbs3-client/3.13.1-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 467, in insertFileParents
    return self.__callServer("fileparents", data=fileParentObj, callmethod='POST' )
  File "/data/srv/wmagent/v1.3.6.patch3/sw.amaltaro/slc7_amd64_gcc630/cms/dbs3-client/3.13.1-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 203, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.3.6.patch3/sw.amaltaro/slc7_amd64_gcc630/cms/dbs3-client/3.13.1-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 230, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 400: DBSFile/insertFileParents: require child block_name and list of child/parent file id pairs
```

**Comment by amaltaro** [comment]
All the workflows have been fixed and a bugfix will be deployed in the next CMSWEB production upgrade.

**Comment by sharad1126** [comment]
Thanks Alan for the updates.
