### ISSUE TITLE
MSOutput crashes initializing Rucio

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9794]
**Impact of the bug**
ReqMgr2MS - MSOutput

**Describe the bug**
Once updated the ms-output configuration to:
```
data.defaultDataManSys = "Rucio"
```

the ms-output service fails to get started. Traceback will be provided below.

**How to reproduce it**
Deploy reqmgr2ms with tag HG2007h and start MSOutput.

**Expected behavior**
The service should start without any problems, nothing else ;)

**Additional context and error message**
Traceback from ms-output logs in vocms0731
```
...
2020-07-03 13:35:32,866:WARNING:MongoDB: Collection '('msOutRelValColl', <pymongo.operations.IndexModel object at 0x7feb0e6674b0>)' Already exists in database 'msOutDB'
2020-07-03 13:35:32,868:WARNING:MongoDB: Collection '('msOutNonRelValColl', <pymongo.operations.IndexModel object at 0x7feb0e6674b0>)' Already exists in database 'msOutDB'
2020-07-03 13:35:32,868:INFO:Rucio: WMCore Rucio initialization with acct: wma_test, host: None, auth: None and these extra parameters: {'auth_type': None, 'account': 'wma_test', 'timeout': 600, 'ca_cert': None, 'rucio_host': None, 'auth_
host': None, 'creds': None, 'user_agent': 'wmcore-client'}
2020-07-03 13:35:32,869:DEBUG:baseclient: no auth_type passed. Trying to get it from the environment variable RUCIO_AUTH_TYPE and config file.
2020-07-03 13:35:32,869:DEBUG:baseclient: no creds passed. Trying to get it from the config file.
2020-07-03 13:35:32,870:DEBUG:baseclient: no ca_cert passed. Trying to get it from the config file.
2020-07-03 13:35:32,870:DEBUG:baseclient: get a new token
2020-07-03 13:35:32,874:DEBUG:connectionpool: Starting new HTTPS connection (1): cmsrucio-auth-int.cern.ch:443
2020-07-03 13:35:32,988:DEBUG:connectionpool: https://cmsrucio-auth-int.cern.ch:443 "GET /auth/x509 HTTP/1.1" 401 126
Traceback (most recent call last):
  File "/data/srv/beHG2007h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre6/bin/wmc-httpd", line 3, in <module>
    main()
  File "/data/srv/beHG2007h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre6/lib/python2.7/site-packages/WMCore/REST/Main.py", line 596, in main
    server.start_daemon()
  File "/data/srv/beHG2007h/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.6.pre6/lib/python2.7/site-packages/WMCore/REST/Main.py", line 426, in start_daemon
    traceback.print_exc(file=trace)
  File "/data/srv/beHG2007h/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/traceback.py", line 233, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/data/srv/beHG2007h/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/data/srv/beHG2007h/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
TypeError: unicode argument expected, got 'str'
[03/Jul/2020:13:35:33]  WATCHDOG: server exited with exit code 1
```

**Comment by todor-ivanov** [comment]
@amaltaro we depend on external configuration file here. We need to have rucio config file in the proper place with the proper contents [1]. 

```
(WMCore.venv) $ echo  $RUCIO_HOME 
/afs/cern.ch/user/t/tivanov/.local/

(WMCore.venv) $ cat  $RUCIO_HOME/etc/rucio.cfg
[common]
[client]
# rucio_host = http://cms-rucio.cern.ch
# auth_host = https://cms-rucio-auth.cern.ch
rucio_host = http://cmsrucio-int.cern.ch
auth_host = https://cmsrucio-auth-int.cern.ch
auth_type = x509
ca_cert = /etc/grid-security/certificates/
client_cert = $X509_USER_CERT
client_key = $X509_USER_KEY
client_x509_proxy = $X509_USER_PROXY
request_retries = 3


```

**Comment by amaltaro** [comment]
The REST/Main issue is getting fixed in 9871.
About the Rucio initialization in the MicroServices, I have just deployed central services with the tag `HG2008b`, and everything is working out of the box. This is the RUCIO_HOME path used by MSOutput:
```
2020-08-18 08:55:51,831:INFO:MSOutput: AMR RUCIO_HOME is: /data/srv/current/config/reqmgr2ms
2020-08-18 08:55:51,831:INFO:Rucio: WMCore Rucio initialization with acct: wma_test, host: None, auth: None and these extra parameters: {'auth_type': None, 'account': 'wma_test', 'timeout': 600, 'ca_cert': None, 'rucio_host': None, 'auth_host': None, 'creds': None, 'user_agent': 'wmcore-client'}
```

However, we pass only the rucio account name to the Rucio module, which means we have no ability to change the host and auth url, but changing the rucio.cfg file. If we want to have that configurable, we could implement something similar to what is in ms-transferor, e.g.:
https://github.com/dmwm/deployment/blob/master/reqmgr2ms/config-transferor.py#L20-L27

Note that a similar logic is already present at the deploy script, even though it's not a configuration at the service level:
https://github.com/dmwm/deployment/blob/master/reqmgr2ms/deploy#L28-L37

@todor-ivanov if you feel like this needs to be changed, can you please take care of this this week? Otherwise, just close it as a not-an-issue.
