### ISSUE TITLE
WMAgent rc 1.3.6.patch1 fails during runtime when importing future

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9817]
**Impact of the bug**
WMAgent

**Describe the bug**
This patch version is the first release candidate for WMAgent stable release 1.3.6
It contains a few of the python3 compatibility changes, and I noticed that those py3 changes cause 100% job failure rate.

The error happens in the worker nodes during runtime, when importing `future`, such as:
```
    from future.utils import viewitems
ImportError: No module named future.utils
```

**How to reproduce it**
Not sure, if I source the agent environment, I can successfuly import from future:
```
cmst1@vocms0192:/data/srv/wmagent/current $ source apps/wmagent/etc/profile.d/init.sh 
cmst1@vocms0192:/data/srv/wmagent/current $ python
Python 2.7.13+ (default, Dec 18 2018, 10:09:09) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from future.utils import viewitems
>>
```

**Expected behavior**
Future should be available with the COMP python environment, which is meant to be load/used during runtime.

**Additional context and error message**
From the testbed campaign `Agent136_Val`:
```
NoJobReport (Exit Code: 99303)

    Could not find jobReport

    ========== condor.14266.32.err ==========
    Adding end of condor.14266.32.err to error message:

    WARNING: container does not have /.singularity.d/actions/exec, calling /srv/.gwms-user-job-wrapper.sh directly
    WARNING  glidein_config not defined () in singularity_lib.sh. Some functions like advertise and error_gen will be limited.
    Traceback (most recent call last):
      File "Startup.py", line 17, in <module>
        import WMCore.WMRuntime.Bootstrap as Bootstrap
      File "/srv/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 23, in <module>
      File "/srv/job/WMCore.zip/WMCore/WMRuntime/TaskSpace.py", line 16, in <module>
      File "/srv/job/WMCore.zip/WMCore/WMSpec/WMWorkload.py", line 10, in <module>
      File "/srv/job/Utils/Utilities.py", line 4, in <module>
        from future.utils import viewitems
    ImportError: No module named future.utils
    + cp 'WMTaskSpace/Report*.pkl' ../
    cp: cannot stat `WMTaskSpace/Report*.pkl': No such file or directory
    + ls -l WMTaskSpace
    ls: cannot access WMTaskSpace: No such file or directory
    + ls -l 'WMTaskSpace/*'
    ls: cannot access WMTaskSpace/*: No such file or directory
    + set +x
```

From the _condor.out (which makes me wonder, why are we still using the old scram arch...)
```
...
======== WMAgent Python boostrap starting at Thu Jul  9 10:06:34 GMT 2020 ========
WMAgent bootstrap: latest python release is: 2.7.13
WMAgent bootstrap: found python2 at..
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/bin/python2
======== WMAgent Python bootstrap finished at Thu Jul  9 10:06:34 GMT 2020 ========
...
  PYTHONPATH=/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.53/el6-x86_64/usr/lib/python2.6/site-packages:/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.4/3.4.53/el6-x86_64/usr/lib64/python2.6/site-packages:/srv/job/WMCore.zip:/srv/job 
```

**Comment by amaltaro** [comment]
Dario, I was thinking about this issue and I guess Kenyi and Erik could be extremely helpful in this debugging.
For instance, I know Kenyi has a procedure to run interactive jobs using the same setup as production (thus, singularity and any other cvmfs dependency). 

Once we manage to test things in a self-container environment, we could then try to send work to Purdue on slc6_* and slc7_* scramArch, and have Erik helping with possible runtime logs that we have no access to :-D

FYI @mapellidario @goughes @khurtado
