### ISSUE TITLE
Deploy the python future package in CVMFS under slc6_amd64_gcc493 arch

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9834]
**Impact of the new feature**
WMCore/WMAgent

**Is your feature request related to a problem? Please describe.**
As noticed this week, with the py2/py3 compatibility changes added to the agent, it means that the future library is also needed during the job runtime. At the moment, the only COMP package deployed (and used) in CVMFS is for our python version, nothing else. That means that the imports will fail, e.g.:
```
Traceback (most recent call last):
  File "Startup.py", line 17, in <module>
    import WMCore.WMRuntime.Bootstrap as Bootstrap
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 23, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/TaskSpace.py", line 16, in <module>
  File "/srv/job/WMCore.zip/WMCore/WMSpec/WMWorkload.py", line 10, in <module>
  File "/srv/job/Utils/Utilities.py", line 4, in <module>
    from future.utils import viewitems
ImportError: No module named future.utils
```

**Describe the solution you'd like**
We need to build the latest py2-future package (0.18.2) against SLC6 architecture. Talk to Shahzad to deploy that in CVMFS under:
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493

and test that the job runtime goes through.

**Describe alternatives you've considered**
Wait for the end of life of SLC6, which is meant to be in a couple of months from now:
https://linux.web.cern.ch/scientific6/

We need to check whether that also means stopping SLC6 workflows in the production system.

**Additional context**

**Comment by amaltaro** [comment]
Imran has recommissioned vocms022 (the SL6 build node), he also re-enabled the cms-bot under slc6_amd64_gcc493, as can be seen in this future package update to version 0.18.2:
https://github.com/cms-sw/cmsdist/pull/6060

Once the RPM is available, we needed to ask Shahzad to deploy it under:
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493

Further information here as well: https://github.com/dmwm/WMCore/pull/9819

Closing this issue.
