### ISSUE TITLE
RucioInjector crashes when a duplicate rule is found

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9843]
**Impact of the bug**
WMAgent (it will likely affect MicroServices too)

**Describe the bug**
When a block/container duplicate rule is hit, a `TypeError` exception happens and it makes the RucioInjector component to crash.

**How to reproduce it**
Force a rule to be duplicate in the RucioInjector component.

**Expected behavior**
The expected bejavior is:
* the component should not crash
* the rule id should be retrieved and returned - in a transparent manner - from the Rucio wrapper to the RucioInjector component.

**Additional context and error message**
Traceback from vocms0192:
```
2020-07-14 22:27:39,378:139624881190656:INFO:RucioInjectorPoller:Preparing to create block rules into Rucio...
2020-07-14 22:27:39,659:139624881190656:INFO:Rucio:A duplicate rule for: 
account: wma_test 
dids: [{'name': '/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall17NanoAOD-RunIIFall17NanoAOD_TaskChain_NanoAOD_Agent136_Val_Alanv9-v11/NANOAODSIM#a663f7fd-0ebd-4a60-bfca-a9e7e2a7a88c',
  'scope': 'cms'}] 
rseExpression: rse=T2_CH_CERN.

2020-07-14 22:27:40,096:139624881190656:ERROR:RucioInjectorPoller:Caught unexpected exception in RucioInjector. Details:
expected string or buffer
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 189, in algorithm
    self.insertBlockRules()
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 278, in insertBlockRules
    rseExpression="rse=%s" % rseName, **kwargs)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 512, in createReplicationRule
    ruleHistory = self.listRuleHistory(didsDup)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 555, in listRuleHistory
    for hist in self.cli.list_replication_rule_full_history(did['scope'], did['name']):
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/client/ruleclient.py", line 213, in list_replication_rule_full_history
    exc_cls, exc_msg = self._get_exception(r.headers, r.status_code)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/client/baseclient.py", line 262, in _get_exception
    data = parse_response(data)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/common/utils.py", line 450, in parse_response
    return json.loads(ret_obj, object_hook=datetime_parser)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
2020-07-14 22:27:40,435:139624881190656:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <WMComponent.RucioInjector.RucioInjectorPoller.RucioInjectorPoller object at 0x7efcfb848610> <@========== WMException Start ==========@>
Exception Class: RucioInjectorException
Message: Caught unexpected exception in RucioInjector. Details:
expected string or buffer
        ModuleName : WMComponent.RucioInjector.RucioInjectorPoller
        MethodName : algorithm
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py
        ClassName : None
        LineNumber : 194
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 189, in algorithm
    self.insertBlockRules()

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 278, in insertBlockRules
    rseExpression="rse=%s" % rseName, **kwargs)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 512, in createReplicationRule
    ruleHistory = self.listRuleHistory(didsDup)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 555, in listRuleHistory
    for hist in self.cli.list_replication_rule_full_history(did['scope'], did['name']):

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/client/ruleclient.py", line 213, in list_replication_rule_full_history
    exc_cls, exc_msg = self._get_exception(r.headers, r.status_code)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/client/baseclient.py", line 262, in _get_exception
    data = parse_response(data)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/common/utils.py", line 450, in parse_response
    return json.loads(ret_obj, object_hook=datetime_parser)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

<@---------- WMException End ----------@>  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 182, in __call__
    tSpent, results, _ = algorithmWithDBExceptionHandler(parameters)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Database/DBExceptionHandler.py", line 39, in wrapper
    return f(*args, **kwargs)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/Utils/Timers.py", line 24, in wrapper
    res = func(*arg, **kw)
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 194, in algorithm
    raise RucioInjectorException(msg)

2020-07-14 22:27:40,435:139624881190656:INFO:Harness:>>>Terminating worker threads
2020-07-14 22:27:40,435:139624881190656:ERROR:BaseWorkerThread:Error in event loop (2): <WMComponent.RucioInjector.RucioInjectorPoller.RucioInjectorPoller object at 0x7efcfb848610> <@========== WMException Start ==========@>
Exception Class: RucioInjectorException
Message: Caught unexpected exception in RucioInjector. Details:
expected string or buffer
        ModuleName : WMComponent.RucioInjector.RucioInjectorPoller
        MethodName : algorithm
        ClassInstance : None
        FileName : /data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py
        ClassName : None
        LineNumber : 194
        ErrorNr : 0

Traceback: 
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 189, in algorithm
    self.insertBlockRules()

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMComponent/RucioInjector/RucioInjectorPoller.py", line 278, in insertBlockRules
    rseExpression="rse=%s" % rseName, **kwargs)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 512, in createReplicationRule
    ruleHistory = self.listRuleHistory(didsDup)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 555, in listRuleHistory
    for hist in self.cli.list_replication_rule_full_history(did['scope'], did['name']):

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/client/ruleclient.py", line 213, in list_replication_rule_full_history
    exc_cls, exc_msg = self._get_exception(r.headers, r.status_code)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/client/baseclient.py", line 262, in _get_exception
    data = parse_response(data)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.22.2/lib/python2.7/site-packages/rucio/common/utils.py", line 450, in parse_response
    return json.loads(ret_obj, object_hook=datetime_parser)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)

  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

<@---------- WMException End ----------@>
Backtrace:
  File "/data/srv/wmagent/v1.3.6.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.3.6.patch2/lib/python2.7/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 208, in __call__
    raise ex

2020-07-14 22:27:40,475:139624881190656:INFO:BaseWorkerThread:Worker thread <WMComponent.RucioInjector.RucioInjectorPoller.RucioInjectorPoller object at 0x7efcfb848610> terminated
```

**Comment by amaltaro** [comment]
Apparently it's an old'ish issue in rucio-clients, which Eric fixed a couple of months ago:
https://github.com/rucio/rucio/pull/3621

From the commit, it seems it went in starting in `1.23.0` tag, while WMCore is using `1.22.2`.
