### ISSUE TITLE
PY3: Jobs cannot import from future with WMAgent 1.3.6.patch4 and WMCore 1.4.0.pre5 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9876]
**Impact of the bug**
WMCore in general

**Describe the bug**
WMCore central services have just been deployed in testbed, with 1.4.0.pre5. Services seem to be running fine so far, but workflows are hitting 100% failure rate. They fail on the worker node when the job wrapper is loading the workload spec file, traceback at the bottom.

**How to reproduce it**
Try to unpickle that object with the agent environment, but without py2-future in the PYTHONPATH.

This works fine within the agent - as expected, because it has the future package in the path.
```
cmst1@vocms0193:/data/srv/wmagent/current $ source apps/wmagent/etc/profile.d/init.sh 
cmst1@vocms0193:/data/srv/wmagent/current $ python
Python 2.7.13+ (default, Dec 18 2018, 10:09:09) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> workloadPcl = "/data/srv/wmagent/v1.3.6.patch4/install/wmagent/WorkQueueManager/cache/amaltaro_TaskChain_NanoAOD_HG2009_Val_200820_105910_758/WMSandbox/WMWorkload.pkl"
>>> with open(workloadPcl, 'r') as handle:
...   wmWorkload = pickle.load(handle)
... 
>>> wmWorkload
<WMCore.WMSpec.WMWorkload.WMWorkload object at 0x7fd0adc18f90>
```

**Expected behavior**
WMAgent 1.3.6.patch4 should be able to run these jobs without any issues, given that that version does not have the futurize stage2 fixers. 
We need to check how exactly the workload spec file changed, and see what are the changes needed on the agents to make it working.

Another very good alternative would be to actually sort out the py2-future dependency on the worker nodes (cvmfs), reported here:
https://github.com/dmwm/WMCore/issues/9817
Once that gets fixed, then all these futurize issues will be solved.

**Additional context and error message**
traceback from wmstats:
```
Job Name: 1c7fdcdf-88ef-4b01-bd27-b5ac6de91c37-0
WMBS job id: 3558
Workflow: amaltaro_TaskChain_NanoAOD_HG2009_Val_200820_105910_758
Task: /amaltaro_TaskChain_NanoAOD_HG2009_Val_200820_105910_758/RunIIFall17NanoAOD
Status: jobfailed
Input dataset: /WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM
Site: T2_CH_CERN
Agent: vocms0193.cern.ch
ACDC URL: https://cmsweb-testbed.cern.ch/couchdb/acdcserver
State Transition
Exit code: 99303
Retry count: 0
Errors:

    NoJobReport
        NoJobReport (Exit Code: 99303)

            Could not find jobReport

            ========== condor.14002.41.err ==========
            Adding end of condor.14002.41.err to error message:

            WARNING  glidein_config not defined () in singularity_lib.sh. Some functions like advertise and error_gen will be limited.
            INFO:root:Process id: 132	Current working directory: /srv/job
            INFO:root:Loading job definition
...
INFO:root:Loading task
Traceback (most recent call last):
  File "Startup.py", line 29, in <module>
    task = Bootstrap.loadTask(job)
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 185, in loadTask
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 172, in loadWorkload
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named future.types.newstr
+ cp 'WMTaskSpace/Report*.pkl' ../
cp: cannot stat `WMTaskSpace/Report*.pkl': No such file or directory
+ ls -l WMTaskSpace
ls: cannot access WMTaskSpace: No such file or directory
+ ls -l 'WMTaskSpace/*'
ls: cannot access WMTaskSpace/*: No such file or directory
+ set +x
```

**Comment by amaltaro** [comment]
Interesting enough, not all the DMWM workflows failed (half of them succeeded). Checking where that `newstr` comes from, it's actually the backport of py3 str to python2, see:
```
In [1]: str
Out[1]: str

In [2]: from builtins import str

In [3]: str
Out[3]: future.types.newstr.newstr
```

and it looks like when reqmgr2 dumps the workload object in a pickle object, we get the `newstr` object in there, as one can see here:
https://cmsweb-testbed.cern.ch/couchdb/reqmgr_workload_cache/amaltaro_TaskChain_NanoAOD_HG2009_Val_200820_105910_758/spec

**Comment by amaltaro** [comment]
As we (Todor/Dario/I) quickly discussed over zoom, we should probably try to solve it by actually getting this PR to work:
https://github.com/dmwm/WMCore/pull/9819

that will be anyways needed sooner or later!

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/9819
