### ISSUE TITLE
WMRuntime PerformanceMonitor cannot find stepSpace

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9883]
**Impact of the bug**
WMAgent

**Describe the bug**
I have a feeling that this is a new bug inserted with the python3 changes. I had never seen this error before, and it started showing up for a very small amount of jobs (<0.5% of the jobs) with CMSWEB services `1.4.0.pre5` and WMAgent `1.3.6.patch4`. The job error code in WMStats is:
```
MissingJobReport (Exit Code: 99997)
``` 
but it shows up as `8028` in the job summary table.

The actual problem is that to bootstrap the runtime monitors, we need to load some job (task/step) information from the workflow spec, and the object attribute is said not to be there (?)

**How to reproduce it**
Does not seem to be reproducible. It happens to random jobs in a workflow, while all the others run fine.

**Expected behavior**
Job bootstrap should go through :) We need to find out what and where the actual problem is and get it fixed.

**Additional context and error message**
Job example (in vocms0192):
WMBS job id: 4357
Workflow: amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571
Task: /amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571/HLTD/RECODreHLT

Whole wmagentJob.log is:
```
2020-08-27 19:12:46,521:INFO:Startup:Process id: 128    Current working directory: /srv/job
2020-08-27 19:12:46,538:INFO:Startup:Loading job definition
2020-08-27 19:12:46,542:INFO:Bootstrap:Job Index = 4357
Job Instance = {'ownerRole': 'unknown', 'agentName': 'vocms0192.cern.ch', 'jobgroup': 760, 'taskType': 'integration', 'owner': 'amaltaro', 'fwjr': None, 'id': 4357, 'jobType': 'Processing', 'estimatedJobTime': 3600, 'estimatedDiskUsage': 1000000, 'state_time': 1598555398, 'state': 'new', 'location': None, 'agentNumber': 0, 'spec': '/data/srv/wmagent/v1.3.6.patch4/install/wmagent/WorkQueueManager/cache/amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571/WMSandbox/WMWorkload.pkl', 'workflow': 'amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571', 'ownerGroup': 'unknown', 'estimatedMemoryUsage': 2400.0, 'fwjr_path': None, 'input_files': [{'runs': set([<WMCore.DataStructs.Run.Run object at 0x2b7d170f2d90>]), 'last_event': 0, 'lfn': '/store/unmerged/CMSSW_7_2_0/JetHT/RAW/HLTD_TaskChain_LumiMask_multiRun_Aug2020_Valv11-v11/00000/D4F26552-97E8-EA11-B92F-FA163E67E5E6.root', 'locations': set([]), 'first_event': 0, 'parents': set([]), 'checksums': {}, 'events': 4, 'merged': True, 'size': 1372720}], 'task': '/amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571/HLTD/RECODreHLT', 'name': '677d689f-bbd5-440b-8c70-ab6f5a21f253-22', 'counter': 23, 'mask': {'LastRun': None, 'FirstRun': None, 'inclusivemask': True, 'runAndLumis': {202205: [[19, 19]]}, 'LastEvent': None, 'FirstEvent': None, 'LastLumi': None, 'FirstLumi': None}, 'numberOfCores': 1, 'ownerDN': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amaltaro/CN=718748/CN=Alan Malta Rodrigues', 'retry_count': 0, 'sandbox': '/data/srv/wmagent/v1.3.6.patch4/install/wmagent/WorkQueueManager/cache/amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571/amaltaro_TaskChain_LumiMask_multiRun_Aug2020_Val_200827_201611_1571-Sandbox.tar.bz2', 'outcome': 'failure'}

2020-08-27 19:12:46,542:INFO:Startup:Loading task
2020-08-27 19:12:47,751:INFO:Startup:Setting up monitoring
2020-08-27 19:12:47,753:INFO:Startup:Building task at directory: /srv/job
2020-08-27 19:12:47,755:INFO:Builder:CMSSW.coreBuild invoked
2020-08-27 19:12:47,756:INFO:BuildTools:create(/srv/job/WMTaskSpace/cmsRun1)
2020-08-27 19:12:47,756:INFO:CMSSW:Builders.CMSSW.build called on cmsRun1
2020-08-27 19:12:47,756:INFO:Builder:StageOut.coreBuild invoked
2020-08-27 19:12:47,756:INFO:BuildTools:create(/srv/job/WMTaskSpace/stageOut1)
2020-08-27 19:12:47,757:INFO:StageOut:Builders.StageOut.build called on stageOut1
2020-08-27 19:12:47,757:INFO:Builder:LogArchive.coreBuild invoked
2020-08-27 19:12:47,757:INFO:BuildTools:create(/srv/job/WMTaskSpace/logArch1)
2020-08-27 19:12:47,758:INFO:LogArchive:Builders.LogArchive.build called on logArch1
2020-08-27 19:12:47,758:INFO:Startup:Executing task at directory: /srv/job
2020-08-27 19:12:47,758:INFO:Watchdog:In Watchdog.setupMonitors
2020-08-27 19:12:47,758:INFO:Watchdog:Set Watchdog interval to 300
2020-08-27 19:12:47,758:INFO:Watchdog:Initializing monitor PerformanceMonitor
2020-08-27 19:12:47,893:INFO:WMTweak:Not resizing job
2020-08-27 19:12:47,894:INFO:Watchdog:Watchdog modified: False. Final settings:
2020-08-27 19:12:47,894:INFO:Watchdog:  cores: 1
2020-08-27 19:12:47,894:INFO:Watchdog:  softTimeout: 129600
2020-08-27 19:12:47,894:INFO:Watchdog:  hardTimeout: 130600
2020-08-27 19:12:47,894:INFO:Watchdog:  maxPSS: 2400
2020-08-27 19:12:47,895:INFO:Watchdog:MonitorThread: JobStarted
2020-08-27 19:12:47,903:INFO:Executor:Steps.Executor logging started
2020-08-27 19:12:48,006:ERROR:Watchdog:Error in periodicUpdate for monitor class WMCore.WMRuntime.Monitors.PerformanceMonitor.PerformanceMonitor in Watchdog:
Error retrieving stepSpace from TaskSpace:
'module' object has no attribute 'taskSpace'Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Watchdog.py", line 299, in run
    monitor.periodicUpdate()
  File "/srv/job/WMCore.zip/WMCore/WMRuntime/Monitors/PerformanceMonitor.py", line 178, in periodicUpdate
    self.currentStepSpace = getStepSpace(self.stepHelper.name())
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executor.py", line 55, in getStepSpace
    raise RuntimeError(msg)
RuntimeError: Error retrieving stepSpace from TaskSpace:
'module' object has no attribute 'taskSpace'
This is a CRITICAL error because this kills the monitoring.
Terminate thread and retry.
```

**Comment by amaltaro** [comment]
I haven't seen this problem and it was reported for an ancient WMAgent version, so I will just close this out.
