### ISSUE TITLE
WMAgent - LookupError: unknown encoding: utf-8 - branch 1.3.6_wmagent

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#9885]
This issue is created starting from a comment that @amaltaro made in #9868  .

**Impact of the bug**
From Alan's message, it affects the `backfill agent (vocms0285)`, in `1.3.6_wmagent` branch of dmwm/WMCore.

**Describe the bug**
From Alan's traceback:

```
  File "/srv/job/WMCore.zip/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')
LookupError: unknown encoding: utf-8
```

It is like the file `lib/python${VER}/encodings/utf_8.py` is not found, or like some package is shadowing it, like in [this pyinstaller issue](https://github.com/pyinstaller/pyinstaller/issues/3146#issuecomment-354913915). 

This is not the usual encoding/decoding error that one encounters when dealing with python strings.

**How to reproduce it**
I am not sure. I have not been able to reproduce in my docker environment and in my VM. I will need to investigate a bit more on this subject.

**Expected behavior**
There should be no exception raised when already dealing with an exception.

**Additional context and error message**
Message from Alan:

> I was looking at the backfill agent (vocms0285), and I've spotted a few jobs failing with errors like (wmagentJob.log):

```text
2020-09-01 23:18:55,930:INFO:PerformanceMonitor:PSS: 133864; RSS: 133860; PCPU: 0.0; PMEM: 0.0
2020-09-01 23:23:44,021:CRITICAL:CMSSW:Error running cmsRun
{'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', u'slc7_amd64_gcc700', 'scramv1', 'CMSSW', 'CMSSW_10_6_9', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
Linux Return code: 135

2020-09-01 23:23:44,021:CRITICAL:CMSSW:Error message: None
2020-09-01 23:23:44,352:ERROR:ExecuteMaster:Exception occured when executing step
2020-09-01 23:23:44,352:ERROR:ExecuteMaster:Exception is unknown encoding: utf-8
2020-09-01 23:23:44,353:ERROR:ExecuteMaster:Traceback:
2020-09-01 23:23:44,354:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 139, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 284, in execute
    raise WMExecutionFailure(returnCode, "CmsRunFailure", msg)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py", line 18, in __init__
    WMException.__init__(self, detail, code)
  File "/srv/job/WMCore.zip/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')
LookupError: unknown encoding: utf-8

2020-09-01 23:23:44,354:CRITICAL:CMSSW:CMSDefaultHandler Diagnostic Handler invoked
2020-09-01 23:23:44,356:ERROR:ExecuteMaster:Encountered error while running ExecuteMaster:
unknown encoding: utf-8
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 73, in __call__
    result = self.doExecution(executor, step, wmbsJob)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 149, in doExecution
    executor.diagnostic(99109, executor, ExceptionInstance=ex)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Diagnostic.py", line 87, in __call__
    handler(errCode, executor, **args)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Diagnostics/CMSSW.py", line 102, in __call__
    self.parse(executor, jobRepXml)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Diagnostic.py", line 42, in parse
    executorInstance.report.parse(jobRepXml, executorInstance.stepName)
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py", line 156, in parse
    raise FwkJobReportException(msg)
  File "/srv/job/WMCore.zip/WMCore/WMException.py", line 33, in __init__
    message = message.decode('utf-8', 'ignore')
LookupError: unknown encoding: utf-8


2020-09-01 23:23:44,357:INFO:Watchdog:MonitorThread: JobEnded
```

> @mapellidario can I ask you to look into this PR and try to backport it to the branch 1.3.6_wmagent? That branch does not have any of these code modernization, so it might not be very straight forward...
Once you have it ready, please make a PR against the 1.3.6_wmagent branch and we can start testing your changes in the backfill agent itself (I'll take care of the testing). Thanks

**Comment by amaltaro** [comment]
I haven't seen this error popping up again (in agents 1.4.1), so I'm closing this issue.
