### ISSUE TITLE
MSOutput: add alert for campaigns that do not exist in CouchDB

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9907]
**Impact of the new feature**
ReqMgr2MS (MSOutput)

**Is your feature request related to a problem? Please describe.**
Apparently there can be a race condition for RelVal workflows, where the batch gets announced and the campaign configuration is deleted right away. We need to make the necessary changes to avoid it (likely on the Unified side).

It does not seem to apply to RelVals only though, I've seen this campaign: `Commissioning2018` with workflows about to be announced (thus, need to be handled by MSOutput).

**Describe the solution you'd like**
We likely need a couple of fixes/features here:
* add a delay on RelVal campaign deletion in Unified. Another option would be to check if the workflow is RelVal, and in that case simply use the same campaign configuration usually provided by Unified (AFAIK they are always the same for RelVals...)
* in case we have a workflow to make the output data placement, and the campaign cannot be found in central Couch, we should have a notification (one that really draws attention) such that people can act on it in a day or two. Email will likely do that and it should have a very low traffic.

**Describe alternatives you've considered**
Alternative provided for the delayed campaign deletion.

**Additional context**
Traceback from my VM:
```
2020-09-12 09:33:12,170:INFO:MSOutput: Producing MongoDB record for workflow: moanwar_RVCMSSW_11_2_0_pre6_ROOT622SingleGammaFlatPt8To150__2026D49noPU_200911_214607_7873
2020-09-12 09:33:12,170:ERROR:MSOutput: MSOutputProducer Pipeline Possibly broken read from ReqMgr2 API or other. Err: u'CMSSW_11_2_0_pre6_ROOT622__UPSG_Std_2026D49noPU-1599853446'. Continue to the next document.
Traceback (most recent call last):
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 523, in msOutputProducer
    msPipeline.run(request)
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 140, in run
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 140, in <lambda>
    return reduce(lambda obj, functor: functor(obj), self.funcLine, obj)
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 72, in __call__
    return self.run(obj)
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/Utils/Pipeline.py", line 75, in run
    return self.func(obj, *self.args, **self.kwargs)
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 593, in docInfoUpdate
    if not self.canDatasetGoToDisk(dataItem):
  File "/data/srv/HG2009h-comp2/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.4.0.pre9/lib/python2.7/site-packages/WMCore/MicroService/Unified/MSOutput.py", line 672, in canDatasetGoToDisk
    if dataTier in self.campaigns[outputMap['Campaign']]["TiersToDM"]:
KeyError: u'CMSSW_11_2_0_pre6_ROOT622__UPSG_Std_2026D49noPU-1599853446'
2020-09-12 09:33:12,171:INFO:MSOutput:
```

**Comment by amaltaro** [comment]
It turns out the standard workflows without any campaign in central CouchDB were actually rogue workflows sitting in closed-out since March 2019. I've just moved them to `announced`. I don't expect such cases to pop up in production, but we better have such notification in place, if needed.
