### ISSUE TITLE
UnicodeDecodeError when uploading harvesting root files to the DQM Gui

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9926]
**Impact of the bug**
WMAgent

**Describe the bug**
Apparently another issue resulting from the  python3 modernization applied to 1.4.0 agent.
The HTTP request fails to post the root file to the DQM Gui with this exception:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 479: ordinal not in range(128)
```

**How to reproduce it**
Still unsure, but agent 1.4.0 does.

**Expected behavior**
Provide the correct (supported) data types to the DQMHarvest upload step. The issue might be actually with the headers that are passed to the opener object.

**Additional context and error message**
WMBS job id: 2072
Workflow: amaltaro_DQMHarvesting_RunWhitelist_Agent140_Val_200917_123220_5925

and here's the traceback from wmagentJob.log
```
2020-09-17 11:01:18,656:INFO:DQMUpload:HTTP POST upload arguments:
  ==> checksum: md5:9c49e4292a83cf3292cc1d3fe503858a
  ==> size: 46568495
...
2020-09-17 11:01:18,671:INFO:HTTPSAuthHandler:  verify_mode : 2
2020-09-17 11:01:18,895:ERROR:DQMUpload:HTTP upload failed! Error:
'ascii' codec can't decode byte 0xec in position 479: ordinal not in range(128)
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 156, in httpPost
    (headers, data) = self.upload(uploadURL, args, filename)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 253, in upload
    result = opener.open(datareq)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/py2-future/0.18.2/lib/python2.7/site-packages/future/backports/urllib/request.py", line 500, in open
    response = self._open(req, data)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/py2-future/0.18.2/lib/python2.7/site-packages/future/backports/urllib/request.py", line 518, in _open
    '_open', req)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/py2-future/0.18.2/lib/python2.7/site-packages/future/backports/urllib/request.py", line 472, in _call_chain
    result = func(*args)
  File "/srv/job/WMCore.zip/WMCore/Services/HTTPS/HTTPSAuthHandler.py", line 58, in https_open
    return self.do_open(self.get_connection, req)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/py2-future/0.18.2/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1290, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 479: ordinal not in range(128)
2020-09-17 11:01:19,670:WARNING:Report:Exit code: 70318 has been already added to the job report
```

**Comment by amaltaro** [comment]
@mapellidario any chance you could have a look at this one and possibly propose a solution before the weekend is over?
My goal is to start redeploying agents on Monday, so having a possible fix tested by Monday morning would be great.

**Comment by mapellidario** [comment]
This is nastier that it seems. It seems that we have a problem similar to [this one described on stackoverflow](https://stackoverflow.com/a/7993378). It is possible that the problem is caused by non-uniform data types among our headers (some are unicode and some are bytes). 

I suppose that before upgrading urllib from py2 version to py3 version with futurize, `urllib.OpenerDirector().open(datareq)` was ok with `datareq` containing headers in bytes strings, while after the migration we may need to have headers as unicode strings. This is only a suggestion since the official doc [does not say much](https://docs.python.org/3.8/library/urllib.request.html) about what the type of the headers should be. Since the doc is written for py3 and we are using a backported version of py3 urllib, I suppose we have to make sure that all the headers are in unicode.

Furthermore, we do not have a unit test for `DMQUpload.py`, so it is a bit hard for me to be sure about anything. I need more time to do some tests in a separate notebook to be able to replicate the error and check what could be causing the error.

**Comment by amaltaro** [comment]
@mapellidario if you haven't yet managed to reproduce this error, how about you provide me with a debugging patch? I can apply it to one of my testbed agents and run a DQMHarvest workflow. Please let me know if there is anything else I can do to help you debugging it.

**Comment by mapellidario** [comment]
I have not been able to replicate this error, despite mixing string types and trying to use the same functions that DQMUpload.py uses to encode the request headers and data. I uploaded my test script [here](https://gist.github.com/mapellidario/761a1a3b7dc6b70c275d2ee8aedb882b). I will open a PR with some logging

**Comment by mapellidario** [comment]
Thanks to the help of @amaltaro I have been able to replicate the error. I have done some bisecting and the problem is caused by #9762 , as was suspected. The backported `urllib.request` that python future provides behaves differently that `urllib2`.

With `urllib2`, the attribute `self._buffer` (which contains the headers and the body of a http request) of httplib contains only `str` (i.e. bytes). With python-future's `urllib.request`, some of the elements of the buffer are `unicode`, so when they are concatenated in `msg` python2 tries to be clever and converts everything to unicode. Then, it also tries to append a ROOT file read in binary format and stored in a `str` to `msg`, but `msg` now is unicode. Since the ROOT  file is generic binary, sooner or later python finds some bytes that make no sense in `ascii` (python uses the default encoding, which in our case is `ascii`) and it crashes. Even if we used `utf-8` we would encounter a problem. The ROOT file is not meant to be encoded, it is meant to be sent as a pure binary str.

Further investigations are required to pin down why some of the headers are appended as unicode to the httplib buffer, which is not trivial since the incriminated headers do not seem to come from WMCore but from httplib itself. News will follow in the coming days.

**Comment by mapellidario** [comment]
I added the "internal dependency" tag because I had another look at #9934 in the last couple of days but it is complicated to come up with a proper solution without a py3 env.

**Comment by amaltaro** [comment]
Unexpectedly, we hit this problem today while testing workflows created with a Python3 ReqMgr2 service. The agent is still in python2 (vocms0193), and it's running the latest stable version `1.4.7.patch3`. Workflow name is:
amaltaro_TaskChain_PUMCRecyc_HG2107_Val_210629_184629_8968

Error message seems to be the same as the one initially reported in this issue, pasted here [2] as well.
I'm going to try to reproduce this failure with the magic recipe provided by Kenyi, here: https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime

If we do not manage to get it fixed by tomorrow afternoon, we cannot really move forward with the central services upgrade because this feature is a must for Release Validation workflows.

@khurtado Kenyi, if it's not too late for you and you could spare an hour or two investigating this, I would be happy to resume your debugging tomorrow morning.

[2]
```
2021-06-30 14:18:37,074:INFO:DQMUpload:Steps.Executors.DQMUpload.pre called
2021-06-30 14:18:37,074:INFO:DQMUpload:Steps.Executors.DQMUpload.execute called
2021-06-30 14:18:37,074:INFO:DQMUpload:Beginning report processing for step cmsRun1
2021-06-30 14:18:37,598:INFO:DQMUpload:HTTP Upload is about to start:
 => URL: https://cmsweb.cern.ch/dqm/dev
 => Filename: /srv/job/WMTaskSpace/cmsRun1/DQM_V0001_R000000001__RelValQCD_Pt_600_800_14__CMSSW_11_2_0_pre8-RecoPU_2024PU_TaskChain_PUMCRecyc_HG2107_Val_Alanv11-v11__DQMIO.root

2021-06-30 14:18:37,599:INFO:DQMUpload:Using proxy file: /srv/myproxy.pem
2021-06-30 14:18:37,599:INFO:DQMUpload:Using CA certificate path: None
2021-06-30 14:18:37,600:INFO:DQMUpload:HTTP POST upload arguments:
  ==> checksum: md5:9e6dedc824d9a149c47039a66ffb62d9
  ==> size: 211509279

2021-06-30 14:18:37,627:INFO:HTTPSAuthHandler:Found 136 default trusted CA certificates.
2021-06-30 14:18:37,627:INFO:HTTPSAuthHandler:SSL context manager created with the following settings:
2021-06-30 14:18:37,627:INFO:HTTPSAuthHandler:  check_hostname : True
2021-06-30 14:18:37,627:INFO:HTTPSAuthHandler:  options : 2197947391
2021-06-30 14:18:37,628:INFO:HTTPSAuthHandler:  protocol : 2
2021-06-30 14:18:37,628:INFO:HTTPSAuthHandler:  verify_flags : 0
2021-06-30 14:18:37,628:INFO:HTTPSAuthHandler:  verify_mode : 2
2021-06-30 14:18:38,331:ERROR:DQMUpload:HTTP upload failed! Error:
'ascii' codec can't decode byte 0xf2 in position 551: ordinal not in range(128)
Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 156, in httpPost
    (headers, data) = self.upload(uploadURL, args, filename)
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 253, in upload
    result = opener.open(datareq)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/srv/job/WMCore.zip/WMCore/Services/HTTPS/HTTPSAuthHandler.py", line 55, in https_open
    return self.do_open(self.get_connection, req)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/httplib.py", line 880, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf2 in position 551: ordinal not in range(128)
2021-06-30 14:18:38,511:WARNING:Report:Exit code: 70318 has been already added to the job report
```
