### ISSUE TITLE
Eventual difference between `http.client` <-> `httplib` and `urllib2` <-> `urllib` interfaces

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9960]
**Impact of the bug**
This is a general bug. Could affect anything that uses `httplib` or `urllib`

**Describe the bug**
The following commit [1] introduces at least one bug caused by a difference between the interfaces of `httplib` and `http.client`. This is one of the changes this commit introduces [2]. The following error [3] was spotted while trying to run the `validate-test-wfs.py` script. The line that is actually breaking the code is L65 in the current commit [4]. 

@mapellidario Could you please take a look! Thanks in advance!

[1]
https://github.com/dmwm/WMCore/commit/67f432bb2fc447c03ef378a319dcd6ac0348dff2?branch=67f432bb2fc447c03ef378a319dcd6ac0348dff2&diff=split

[2]
`import urllib2` -> `import urllib.request, urllib.parse`
`from httplib import HTTPSConnection, HTTPConnection` -> `from http.client import HTTPSConnection, HTTPConnection`

[3]
```
$ python validate-test-wfs.py.preDario -i validation_${vcamp}_tivanov_int.list -v 
Traceback (most recent call last):
  File "validate-test-wfs.py.preDario", line 571, in <module>
    sys.exit(main())
  File "validate-test-wfs.py.preDario", line 537, in main
    reqmgrInputDset, reqmgrOutDsets = handleReqMgr(reqName, reqmgrUrl)
  File "validate-test-wfs.py.preDario", line 318, in handleReqMgr
    reqmgrOut = getReqMgrCache(reqName, reqmgrUrl)
  File "validate-test-wfs.py.preDario", line 102, in getReqMgrCache
    reqmgrOutput = json.loads(getContent(urn))['result'][0][reqName]
  File "validate-test-wfs.py.preDario", line 69, in getContent
    response = opener.open(url, params)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 506, in open

----------------------------------------------------
==> tivanov_DQMHarvesting_HG2010_Val_201001_164052_4195
    response = meth(req, response)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 612, in http_response
    code, msg, hdrs = response.code, response.msg, response.info()
AttributeError: HTTPResponse instance has no attribute 'code'
```
[4]
`opener = urllib2.build_opener(handler)` -> `opener = urllib.request.build_opener(handler)`

**How to reproduce it**
Just run the latest version of the validation script.

**Expected behavior**
Swapping library versions should not change code behavior. In case of an explicit backwards incompatibility, then (unfortunately) all the places of use of the library in question should be dig out and checked.   

**Additional context and error message**
Add any other context about the problem here, like error message and/or traceback. You might want to use triple back ticks to properly format it.

**Comment by amaltaro** [comment]
Pointing out another script affect by this:
```
cmst1@vocms0285:/data/srv/wmagent/current $ python apps/wmagent/bin/adhoc-scripts/workflowCompletion.py -w pdmvserv_task_EXO-RunIIFall18pLHE-00310__v1_T_200331_012410_3873
Traceback (most recent call last):
  File "apps/wmagent/bin/adhoc-scripts/workflowCompletion.py", line 168, in <module>
    sys.exit(main())
  File "apps/wmagent/bin/adhoc-scripts/workflowCompletion.py", line 153, in main
    inputLumis, reqmgrOutDsets = handleReqMgr(reqName, reqmgrUrl)
  File "apps/wmagent/bin/adhoc-scripts/workflowCompletion.py", line 80, in handleReqMgr
    reqmgrOut = json.loads(getContent(urn))['result'][0][reqName]
  File "apps/wmagent/bin/adhoc-scripts/workflowCompletion.py", line 61, in getContent
    response = opener.open(url, params)
  File "/data/srv/wmagent/v1.4.1.patch1/sw/slc7_amd64_gcc630/external/py2-future/0.18.2/lib/python2.7/site-packages/future/backports/urllib/request.py", line 506, in open
    response = meth(req, response)
  File "/data/srv/wmagent/v1.4.1.patch1/sw/slc7_amd64_gcc630/external/py2-future/0.18.2/lib/python2.7/site-packages/future/backports/urllib/request.py", line 612, in http_response
    code, msg, hdrs = response.code, response.msg, response.info()
AttributeError: HTTPResponse instance has no attribute 'code'
```

**Comment by mapellidario** [comment]
This issue is actually part of #10481, have been left out of #10482 and will be addressed in a new PR in the next days.

**Comment by amaltaro** [comment]
I guess I haven't ever looked into that code, so I cannot even say whether it works if a full environment is available.
I suggest we let it be, and if in the future we have need to profile couch again (it could be useful for the CouchDB 3.1 coming up...), then we look into this script and simply move it straight to python3.

@mapellidario IMO, we can close this issue. If you agree, please go ahead.

**Comment by mapellidario** [comment]
Your plan sounds good! I will close this issue with this comment.

If we realize that we need to use `ipy_profile_couch.py` again, then we open a new issue about its modernization.
